import {test,expect,type Page,type Route} from './fixtures.js';

const guildKey='guild_test',csrf='synthetic-admin-csrf';
const candidate=(id:string,extra:Record<string,unknown>={})=>({user_id:id,display_name:`人選 ${id}`,email:`${id}@example.test`,active:true,eligible:true,eligibility_reason:null,is_current:false,joined:true,is_expert:false,expert_version:null,...extra});
type Fixture={candidates:(route:Route)=>Promise<void>;appoint?:(route:Route)=>Promise<void>;members?:(route:Route)=>Promise<void>;expectedVersion?:()=>number;expert?:(route:Route)=>Promise<void>};
async function setup(page:Page,options:Fixture){
  let current:{user_id:string;display_name:string}|null=null,version=7;let generalReads=0;let experts:any[]=[];
  await page.route('**/admin/api/**',async route=>{
    const path=new URL(route.request().url()).pathname.replace('/admin/api','');
    if(path==='/bootstrap')return route.fulfill({json:{admin:{admin_id:'synthetic-admin',display_name:'測試管理員',email:'admin@example.test',role:'super_admin',community_id:'synthetic-community'},csrf_token:csrf,summary:{members:40,active_members:40,pending_guild_applications:0,guilds:1,admins:1},available_skill_books:[],pending_guild_appointments:[]}});
    if(path==='/members'){generalReads++;if(options.members)return options.members(route);return route.fulfill({json:{items:[],next_offset:null}});}
    if(path==='/guilds')return route.fulfill({json:{items:[{guild_key:guildKey,name:'測試活動公會',purpose:'一起安排活動與聚會',guild_master:current,officer_version:version,guild_experts:experts}]}});
    if(path===`/guilds/${guildKey}/master-candidates`)return options.candidates(route);
    if(path===`/guilds/${guildKey}/master`){const body=route.request().postDataJSON();expect(route.request().headers()['x-admin-csrf']).toBe(csrf);expect(route.request().headers()['if-match']).toBe(`"${options.expectedVersion?.()??7}"`);current={user_id:body.user_id,display_name:`人選 ${body.user_id}`};version=8;return options.appoint?options.appoint(route):route.fulfill({json:{user_id:body.user_id,aggregate_version:8}});}
    if(path===`/guilds/${guildKey}/experts`&&options.expert)return options.expert(route);
    return route.fulfill({status:404,json:{detail:'Unexpected synthetic request'}});
  });
  await page.goto('/admin');await page.getByRole('button',{name:'公會管理',exact:true}).click();await page.getByRole('button',{name:'設定公會長',exact:true}).click();
  return {panel:page.getByRole('region',{name:'測試活動公會公會長人選',exact:true}),reads:()=>generalReads,setExperts:(value:any[])=>{experts=value;},setGuild:(nextVersion:number,nextCurrent:{user_id:string;display_name:string}|null)=>{version=nextVersion;current=nextCurrent;}};
}

test('guild candidates paginate independently from the general member list and show a named appointment result',async({page})=>{
  const queries:URLSearchParams[]=[];let saved:any;
  const {panel,reads}=await setup(page,{candidates:route=>{const query=new URL(route.request().url()).searchParams;queries.push(query);return route.fulfill({json:{items:query.get('offset')==='20'?[candidate('last',{joined:false})]:Array.from({length:20},(_,index)=>candidate(`candidate-${index}`)),total:21,next_offset:query.get('offset')==='20'?null:20}});},appoint:route=>{saved=route.request().postDataJSON();return route.fulfill({json:{aggregate_version:8}});}});
  await expect(panel.getByRole('radio')).toHaveCount(20);expect(queries[0].get('scope')).toBe('eligible');expect(reads()).toBe(1);await panel.getByRole('button',{name:'查看更多人選',exact:true}).click();await expect(panel.getByText('任命時加入公會',{exact:true})).toBeVisible();await panel.getByRole('radio',{name:'人選 last · last@example.test',exact:true}).check();await panel.getByLabel('任命理由',{exact:true}).fill('本人同意帶領下一輪活動');await panel.getByRole('button',{name:'確認任命',exact:true}).click();await expect(page.getByText('公會長：人選 last',{exact:true})).toBeVisible();await expect(page.getByText('已任命 人選 last 為測試活動公會會長。',{exact:true})).toBeVisible();expect(saved).toEqual({user_id:'last',reason:'本人同意帶領下一輪活動'});expect(queries.find(query=>query.get('offset')==='20')?.get('scope')).toBe('eligible');
});

test('all-member results explain unavailable people and changing the query clears a selected appointment',async({page})=>{
  const {panel}=await setup(page,{candidates:route=>{const query=new URL(route.request().url()).searchParams;return route.fulfill({json:query.get('scope')==='eligible'?{items:[],total:0,next_offset:null}:{items:[candidate('outsider',{joined:false}),candidate('inactive',{active:false,eligible:false,eligibility_reason:'inactive'}),candidate('current',{is_current:true}),candidate('eligible')],total:4,next_offset:null}});}});
  await expect(panel).toContainText('沒有符合的啟用會員');await panel.getByRole('button',{name:'查看所有平台會員',exact:true}).click();await expect(panel.getByRole('radio',{name:'人選 outsider · outsider@example.test',exact:true})).toBeEnabled();await expect(panel.getByText('任命時加入公會',{exact:true})).toBeVisible();await expect(panel.getByRole('radio',{name:'人選 inactive · inactive@example.test',exact:true})).toBeDisabled();await expect(panel.getByText('帳號已停用',{exact:true})).toBeVisible();await expect(panel.getByRole('radio',{name:'人選 current · current@example.test',exact:true})).toBeDisabled();await expect(panel.getByText('現任公會長',{exact:true})).toBeVisible();
  await panel.getByRole('radio',{name:'人選 eligible · eligible@example.test',exact:true}).check();await panel.getByLabel('任命理由',{exact:true}).fill('本人已同意帶領公會');await expect(panel.getByRole('button',{name:'確認任命',exact:true})).toBeEnabled();await panel.getByRole('searchbox',{name:'搜尋公會長人選',exact:true}).fill('新的搜尋');await expect(panel.getByRole('button',{name:'確認任命',exact:true})).toBeDisabled();await expect(panel.getByLabel('任命理由',{exact:true})).toHaveValue('本人已同意帶領公會');await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('a slower prior candidate request cannot replace the latest search',async({page})=>{
  let release!:()=>void,requested!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve;}),started=new Promise<void>(resolve=>{requested=resolve;});
  const {panel}=await setup(page,{candidates:async route=>{const query=new URL(route.request().url()).searchParams;if(query.get('q')==='Mini')return route.fulfill({json:{items:[candidate('new')],total:1,next_offset:null}});requested();await pending;return route.fulfill({json:{items:[candidate('old')],total:1,next_offset:null}});}});
  await started;await panel.getByRole('searchbox',{name:'搜尋公會長人選',exact:true}).fill('Mini');await panel.getByRole('button',{name:'查詢人選',exact:true}).click();await expect(panel.getByRole('radio',{name:'人選 new · new@example.test',exact:true})).toBeVisible();const delivered=page.waitForResponse(response=>response.url().includes('/master-candidates?')&&new URL(response.url()).searchParams.get('q')==='');release();await delivered;await expect(panel.getByRole('radio',{name:'人選 new · new@example.test',exact:true})).toBeVisible();await expect(panel.getByRole('radio',{name:'人選 old · old@example.test',exact:true})).toHaveCount(0);
});

test('unknown assignment results retain the candidate, reason and idempotency key for an explicit retry',async({page})=>{
  const keys:string[]=[];
  const {panel}=await setup(page,{candidates:route=>route.fulfill({json:{items:[candidate('retry')],total:1,next_offset:null}}),appoint:route=>{keys.push(route.request().headers()['idempotency-key']);return keys.length===1?route.fulfill({status:503,json:{detail:'回應中斷，任命結果尚未確認。'}}):route.fulfill({json:{aggregate_version:8}});}});
  await panel.getByRole('radio',{name:'人選 retry · retry@example.test',exact:true}).check();await panel.getByLabel('任命理由',{exact:true}).fill('本人同意接手公會活動');await panel.getByRole('button',{name:'確認任命',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('尚未確認');await expect(panel.getByRole('radio',{name:'人選 retry · retry@example.test',exact:true})).toBeChecked();await expect(panel.getByLabel('任命理由',{exact:true})).toHaveValue('本人同意接手公會活動');await panel.getByRole('button',{name:'確認任命',exact:true}).click();await expect(page.getByText('已任命 人選 retry 為測試活動公會會長。',{exact:true})).toBeVisible();expect(keys).toHaveLength(2);expect(keys[0]).toBeTruthy();expect(keys[1]).toBe(keys[0]);
});

test('a version conflict offers a read-only refresh before selecting and appointing again',async({page})=>{
  let attempt=0,expectedVersion=7,fixture:Awaited<ReturnType<typeof setup>>;
  fixture=await setup(page,{expectedVersion:()=>expectedVersion,candidates:route=>route.fulfill({json:{items:[candidate('changed')],total:1,next_offset:null}}),appoint:route=>{attempt++;if(attempt===1){fixture.setGuild(8,{user_id:'other',display_name:'另一位會長'});return route.fulfill({status:412,json:{detail:'公會長任命已變更，請重新載入。'}});}return route.fulfill({json:{aggregate_version:9}});}});
  const {panel}=fixture;await panel.getByRole('radio',{name:'人選 changed · changed@example.test',exact:true}).check();await panel.getByLabel('任命理由',{exact:true}).fill('本人同意接續管理工作');await panel.getByRole('button',{name:'確認任命',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('任命已變更');await panel.getByRole('button',{name:'重讀公會與人選',exact:true}).click();await expect(page.getByText('公會長：另一位會長',{exact:true})).toBeVisible();await expect(panel.getByRole('radio',{name:'人選 changed · changed@example.test',exact:true})).not.toBeChecked();await expect(panel.getByLabel('任命理由',{exact:true})).toHaveValue('本人同意接續管理工作');await expect(panel.getByRole('button',{name:'確認任命',exact:true})).toBeDisabled();expect(attempt).toBe(1);expectedVersion=8;await panel.getByRole('radio',{name:'人選 changed · changed@example.test',exact:true}).check();await panel.getByRole('button',{name:'確認任命',exact:true}).click();await expect(page.getByText('已任命 人選 changed 為測試活動公會會長。',{exact:true})).toBeVisible();expect(attempt).toBe(2);
});

test('general member pagination uses the submitted query while a new search is still being typed',async({page})=>{
  const queries:URLSearchParams[]=[];
  await setup(page,{candidates:route=>route.fulfill({json:{items:[],total:0,next_offset:null}}),members:route=>{const query=new URL(route.request().url()).searchParams;queries.push(query);const offset=Number(query.get('offset')),term=query.get('q');return route.fulfill({json:{items:[{user_id:`${term||'initial'}-${offset}`,display_name:`${term||'原始'}會員 ${offset}`,email:`sample-${offset}@example.test`,active:true,onboarding_required:false,onboarding_completed_at:null,aggregate_version:1,guilds:[]}],next_offset:offset||term?null:25}});}});
  await page.getByRole('button',{name:'會員管理',exact:true}).click();await page.getByLabel('搜尋會員',{exact:true}).fill('新查詢');await page.getByRole('button',{name:'查看更多會員',exact:true}).click();await expect(page.getByRole('heading',{name:'原始會員 25',exact:true})).toBeVisible();expect(queries.at(-1)!.get('q')).toBe('');expect(queries.at(-1)!.get('offset')).toBe('25');await page.getByRole('button',{name:'搜尋',exact:true}).click();await expect(page.getByRole('heading',{name:'新查詢會員 0',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'原始會員 25',exact:true})).toHaveCount(0);expect(queries.at(-1)!.get('q')).toBe('新查詢');expect(queries.at(-1)!.get('offset')).toBe('0');
});


test('multiple guild experts can include the master, autojoin outsiders and be individually removed or reappointed with their version',async({page})=>{
  const records=new Map<string,{active:boolean;version:number}>();const writes:{body:any;version:string|undefined}[]=[];let fixture:Awaited<ReturnType<typeof setup>>;
  fixture=await setup(page,{candidates:route=>route.fulfill({json:{items:['outsider','master'].map(id=>candidate(id,{joined:records.has(id),is_current:id==='master',is_expert:records.get(id)?.active??false,expert_version:records.get(id)?.version??null})),total:2,next_offset:null}}),expert:route=>{
    const body=route.request().postDataJSON(),previous=records.get(body.user_id),version=route.request().headers()['if-match'];writes.push({body,version});expect(version).toBe(previous?`"${previous.version}"`:undefined);expect(route.request().headers()['x-admin-csrf']).toBe(csrf);
    records.set(body.user_id,{active:body.active,version:(previous?.version??0)+1});fixture.setExperts([...records].filter(([,value])=>value.active).map(([id,value])=>({user_id:id,display_name:`人選 ${id}`,active:true,member_active:true,aggregate_version:value.version})));
    return route.fulfill({json:{guild_key:guildKey,user_id:body.user_id,active:body.active,aggregate_version:records.get(body.user_id)!.version,membership_joined:!previous}});
  }});
  async function appoint(id:string){await page.getByRole('button',{name:'新增公會專家',exact:true}).click();const picker=page.getByRole('region',{name:'測試活動公會公會專家人選',exact:true});await picker.getByRole('radio',{name:`人選 ${id} · ${id}@example.test`,exact:true}).check();await picker.getByLabel('任命理由',{exact:true}).fill('本人同意協助公會專業交流');await picker.getByRole('button',{name:'確認任命',exact:true}).click();await expect(page.getByText(`已任命 人選 ${id} 為測試活動公會專家。`,{exact:true})).toBeVisible();}
  await appoint('outsider');await appoint('master');const experts=page.getByRole('region',{name:'測試活動公會公會專家',exact:true});await expect(experts.getByRole('listitem')).toHaveCount(2);
  await page.getByRole('button',{name:'新增公會專家',exact:true}).click();await expect(page.getByRole('radio',{name:'人選 outsider · outsider@example.test',exact:true})).toBeDisabled();await expect(page.getByRole('radio',{name:'人選 master · master@example.test',exact:true})).toBeDisabled();await page.getByRole('button',{name:'取消',exact:true}).click();
  await experts.getByRole('button',{name:'移除專家 人選 outsider',exact:true}).click();await page.getByLabel('移除理由',{exact:true}).fill('本人希望先專注其他領域');await page.getByRole('button',{name:'確認移除專家',exact:true}).click();await expect(experts.getByRole('listitem')).toHaveCount(1);await expect(experts).toContainText('人選 master');
  await appoint('outsider');await expect(experts.getByRole('listitem')).toHaveCount(2);expect(writes.map(write=>[write.body.user_id,write.body.active,write.version])).toEqual([['outsider',true,undefined],['master',true,undefined],['outsider',false,'"1"'],['outsider',true,'"2"']]);
  await page.setViewportSize({width:1440,height:960});await experts.scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/admin-guild-experts-desktop.png'});
  await page.setViewportSize({width:320,height:844});await experts.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/admin-guild-experts-phone.png'});
});

test('expert removal retains its reason through a version conflict and uses the refreshed expert version',async({page})=>{
  let fixture:Awaited<ReturnType<typeof setup>>,attempts=0;const writes:string[]=[];
  const expert=(version:number)=>({user_id:'disabled-expert',display_name:'停用中的專家',active:true,member_active:false,aggregate_version:version});
  fixture=await setup(page,{candidates:route=>route.fulfill({json:{items:[],total:0,next_offset:null}}),expert:route=>{attempts++;writes.push(route.request().headers()['if-match']);expect(route.request().postDataJSON()).toEqual({user_id:'disabled-expert',active:false,reason:'清理已停用的專家身分'});if(attempts===1){fixture.setExperts([expert(4)]);return route.fulfill({status:412,json:{detail:'專家任命版本已變更，請重新載入。'}});}fixture.setExperts([]);return route.fulfill({json:{active:false,aggregate_version:5}});}});
  fixture.setExperts([expert(3)]);await page.getByRole('button',{name:'重讀公會',exact:true}).click();await page.getByRole('button',{name:'移除專家 停用中的專家',exact:true}).click();await page.getByLabel('移除理由',{exact:true}).fill('清理已停用的專家身分');await page.getByRole('button',{name:'確認移除專家',exact:true}).click();await expect(page.getByRole('alert')).toContainText('版本已變更');await page.getByRole('button',{name:'重讀公會與人選',exact:true}).click();await expect(page.getByLabel('移除理由',{exact:true})).toHaveValue('清理已停用的專家身分');expect(attempts).toBe(1);await page.getByRole('button',{name:'確認移除專家',exact:true}).click();await expect(page.getByText('已移除 停用中的專家 的測試活動公會專家身分。',{exact:true})).toBeVisible();expect(writes).toEqual(['"3"','"4"']);
});


test('three active expert appointments fill the limit while removal remains available and frees a slot',async({page})=>{
  const experts=Array.from({length:3},(_,index)=>({user_id:`expert-${index}`,display_name:`專家 ${index}`,active:true,member_active:index!==2,aggregate_version:1}));const writes:any[]=[];let fixture:Awaited<ReturnType<typeof setup>>;
  fixture=await setup(page,{candidates:route=>route.fulfill({json:{items:[candidate('fourth')],total:1,next_offset:null}}),expert:route=>{const body=route.request().postDataJSON();writes.push(body);if(body.active)experts.push({user_id:body.user_id,display_name:'第四位人選',active:true,member_active:true,aggregate_version:1});else{expect(route.request().headers()['if-match']).toBe('"1"');experts.splice(experts.findIndex(expert=>expert.user_id===body.user_id),1);}fixture.setExperts([...experts]);return route.fulfill({json:{active:body.active,aggregate_version:body.active?1:2}});}});
  fixture.setExperts([...experts]);await page.getByRole('button',{name:'重讀公會',exact:true}).click();const section=page.getByRole('region',{name:'測試活動公會公會專家',exact:true});await expect(section.getByRole('heading')).toHaveText('公會專家 3/3');await expect(section).toContainText('已滿3位，請先移除一位');await expect(page.getByRole('button',{name:'新增公會專家',exact:true})).toBeDisabled();await expect(section.getByRole('button',{name:'移除專家 專家 2',exact:true})).toBeEnabled();
  await page.setViewportSize({width:320,height:844});await section.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/admin-guild-expert-limit-phone.png'});
  await section.getByRole('button',{name:'移除專家 專家 2',exact:true}).click();await page.getByLabel('移除理由',{exact:true}).fill('調整公會專家名額');await page.getByRole('button',{name:'確認移除專家',exact:true}).click();await expect(section.getByRole('heading')).toHaveText('公會專家 2/3');await page.getByRole('button',{name:'新增公會專家',exact:true}).click();await page.getByRole('radio',{name:'人選 fourth · fourth@example.test',exact:true}).check();await page.getByLabel('任命理由',{exact:true}).fill('補上新領域的專業協助');await page.getByRole('button',{name:'確認任命',exact:true}).click();await expect(section.getByRole('heading')).toHaveText('公會專家 3/3');await expect(page.getByRole('button',{name:'新增公會專家',exact:true})).toBeDisabled();expect(writes.map(body=>[body.user_id,body.active])).toEqual([['expert-2',false],['fourth',true]]);
});

test('a concurrent expert limit conflict can reload current appointments without hiding removals or losing the reason',async({page})=>{
  const experts=Array.from({length:3},(_,index)=>({user_id:`expert-${index}`,display_name:`專家 ${index}`,active:true,member_active:true,aggregate_version:1}));let fixture:Awaited<ReturnType<typeof setup>>,writes=0;
  fixture=await setup(page,{candidates:route=>route.fulfill({json:{items:[candidate('fourth')],total:1,next_offset:null}}),expert:route=>{writes++;fixture.setExperts(experts);return route.fulfill({status:409,json:{code:'guild_expert_limit_reached',detail:'每個公會最多 3 位公會專家，請先移除一位再任命。'}});}});
  fixture.setExperts(experts.slice(0,2));await page.getByRole('button',{name:'重讀公會',exact:true}).click();await page.getByRole('button',{name:'新增公會專家',exact:true}).click();const picker=page.getByRole('region',{name:'測試活動公會公會專家人選',exact:true});await picker.getByRole('radio',{name:'人選 fourth · fourth@example.test',exact:true}).check();await picker.getByLabel('任命理由',{exact:true}).fill('本人同意協助下一次共創');await picker.getByRole('button',{name:'確認任命',exact:true}).click();await expect(picker.getByRole('alert')).toContainText('最多 3 位');await picker.getByRole('button',{name:'重讀公會與人選',exact:true}).click();await expect(page.getByRole('heading',{name:'公會專家 3/3',exact:true})).toBeVisible();await expect(picker.getByLabel('任命理由',{exact:true})).toHaveValue('本人同意協助下一次共創');await expect(picker.getByRole('button',{name:'確認任命',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'新增公會專家',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'移除專家 專家 0',exact:true})).toBeEnabled();expect(writes).toBe(1);
});
