import {test,expect} from './fixtures.js';
import {navigate} from './navigation.js';
import {randomUUID} from 'node:crypto';

test('導覽訊息給出用途、下一步連結，並把時間放在內容後方',async({page})=>{
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  const next=page.locator('.game-console-entry[data-next-step="true"]').last();
  await expect(next).toBeVisible();
  await expect(next.locator('.game-console-channel-tag')).toHaveText('網頁導覽');
  await expect(next.locator('strong')).toHaveText('下一步');
  const link=next.getByRole('link',{name:'帶我到下一步'});
  expect(await link.evaluate(element=>getComputedStyle(element).fontSize)).toBe(await next.locator('.game-console-content p').evaluate(element=>getComputedStyle(element).fontSize));
  await expect(link).toHaveCSS('display','inline');
  await expect(link).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
  const href=await link.getAttribute('href');
  expect(['/#guilds','/#skills']).toContain(href);
  expect(await next.locator(':scope > :last-child').evaluate(element=>element.tagName)).toBe('TIME');
  await link.click();
  await expect(page.getByRole('heading',{name:href==='/#guilds'?'職業公會':'技能書架',level:1,exact:true})).toBeVisible();
  await navigate(page,'我的定位');
  const positioning=page.locator('.game-console-entry[data-channel="guide"]').filter({hasText:'已進入「我的定位」'}).last();
  await expect(positioning).toContainText('透過情境題整理你的能力與想走的方向');
  await expect(positioning.locator('.game-console-channel-tag')).toHaveText('網頁導覽');
  await expect(positioning.locator('strong')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('訊息控制台 stays visible during required positioning without reading gated messages',async({page})=>{
  const feedReads:string[]=[];
  page.on('request',request=>{if(request.url().includes('/api/v1/me/guild-announcements'))feedReads.push(request.url());});
  await page.goto('/');
  await page.getByRole('button',{name:'建立帳號',exact:true}).click();
  await page.getByLabel('社群顯示名稱',{exact:true}).fill('控制台定位測試');
  await page.getByLabel('電子郵件',{exact:true}).fill(`console-${randomUUID()}@example.test`);
  await page.getByLabel('密碼',{exact:true}).fill('freedom-console-test-2026');
  await page.getByRole('button',{name:'建立帳號，先逛工坊',exact:true}).click();
  await page.getByRole('button',{name:'開始／繼續定位 →',exact:true}).click();
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toBeVisible();
  await expect(page.getByRole('button',{name:'展開訊息控制台'})).toBeVisible();
  expect((await page.locator('.game-console-ticker').boundingBox())?.x).toBeLessThan(20);
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await expect(page.getByRole('heading',{name:'自由工坊 - 即時訊息控制台',level:2})).toBeVisible();
  expect(feedReads).toHaveLength(0);
  await page.locator('.preview-profile-menu > summary').click();
  await page.getByRole('button',{name:'登出',exact:true}).click();
  await expect(page.getByRole('button',{name:'展開訊息控制台'})).toHaveCount(0);
});

test('global 訊息控制台 persists across modules and synchronizes with its pop-out window',async({page})=>{
  test.setTimeout(90000);
  await page.goto('/?game-console=popout&scope=unauthorized-window-scope');
  await expect(page.getByText('登入已結束。')).toBeVisible();
  await expect(page.getByRole('heading',{name:'自由工坊 - 即時訊息控制台'})).toHaveCount(0);
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1,exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'設定',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'設定',exact:true}).click();
  await expect(page.getByRole('menu',{name:'個人檔案'}).getByRole('menuitem',{name:'我的訊息'})).toHaveCount(0);
  await page.getByRole('button',{name:'設定',exact:true}).click();
  await expect(page.getByRole('navigation',{name:'主要工作區'}).getByRole('button',{name:'我的訊息'})).toHaveCount(0);
  await page.getByRole('button',{name:/^通知/}).click();
  await expect(page.getByRole('button',{name:'查看所有通知與訊息'})).toBeVisible();
  await page.getByRole('button',{name:/^通知/}).click();
  await expect(page.getByRole('heading',{name:'最新動態',level:2})).toHaveCount(0);
  await page.screenshot({path:'test-results/game-console-home-desktop.png'});
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await page.getByRole('tab',{name:/私人聊天/}).click();
  await expect(page.getByRole('tab',{name:/私人聊天/})).toBeFocused();
  await page.getByRole('button',{name:'收合訊息控制台'}).click();

  await expect(page.getByRole('button',{name:'展開訊息控制台'})).toBeVisible();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  const consolePanel=page.locator('.game-console-expanded');
  await expect(consolePanel).toBeVisible();
  await expect(consolePanel.getByRole('heading',{name:'自由工坊 - 即時訊息控制台',level:2})).toBeVisible();
  await expect(consolePanel.getByRole('tab',{name:/私人聊天/})).toHaveAttribute('aria-selected','true');
  await consolePanel.getByRole('tab',{name:'總頻道'}).click();
  await expect(consolePanel.getByText('選擇聊天頻道：')).toHaveCount(0);
  const allMessage=`總頻道發送世界訊息 ${randomUUID()}`;
  await consolePanel.getByRole('textbox',{name:'世界聊天訊息'}).fill(allMessage);
  await consolePanel.getByRole('button',{name:'傳送'}).click();
  await expect(consolePanel.getByRole('log')).toContainText(allMessage);
  await expect(consolePanel.locator('.game-console-entry[data-channel="world_chat"]').last()).toHaveCSS('border-left-color','rgb(23, 97, 133)');
  await consolePanel.getByRole('tab',{name:/系統公告/}).click();
  await expect(consolePanel.getByRole('log')).toContainText('訊息控制台已連線');
  await consolePanel.getByRole('tab',{name:/私人聊天/}).click();
  await expect(consolePanel.getByLabel('私訊對象')).toBeVisible();
  await consolePanel.getByLabel('搜尋會員').fill('示範需求者');
  await expect(consolePanel.getByLabel('私訊對象').locator('option')).toContainText(['請選擇會員','示範需求者 · 20000000']);
  await consolePanel.getByLabel('私訊對象').selectOption('20000000-0000-4000-8000-000000000002');
  const directMessage=`控制台私訊 ${randomUUID()}`;
  await consolePanel.getByLabel('私人訊息').fill(directMessage);
  await consolePanel.getByRole('button',{name:'傳送'}).click();
  await expect(consolePanel.getByRole('log')).toContainText(directMessage);
  await expect(consolePanel.locator('.game-console-entry[data-channel="direct"]')).toHaveCSS('border-left-color','rgb(104, 75, 151)');
  await consolePanel.getByRole('tab',{name:'公會聊天'}).click();
  await expect(consolePanel.getByLabel('公會頻道')).toBeVisible();
  await consolePanel.getByRole('tab',{name:'小隊聊天'}).click();
  await expect(consolePanel.getByLabel('小隊頻道')).toBeVisible();
  await consolePanel.locator('.game-console-visibility summary').click();
  await consolePanel.getByLabel('AI 指令',{exact:true}).uncheck();
  await expect(consolePanel.getByRole('tab',{name:'AI 指令'})).toHaveCount(0);
  await consolePanel.locator('.game-console-visibility summary').click();
  await consolePanel.getByRole('tab',{name:'世界聊天'}).click();
  await consolePanel.getByRole('textbox',{name:'世界聊天訊息'}).fill('世界聊天室測試');
  await consolePanel.getByRole('button',{name:'傳送'}).click();
  await expect(consolePanel.getByRole('log')).toContainText('世界聊天室測試');
  await expect(consolePanel.getByLabel('輸入 Console 訊息')).toHaveCount(0);
  await consolePanel.screenshot({path:'test-results/game-console-expanded-desktop.png'});

  await consolePanel.getByRole('button',{name:'收合訊息控制台'}).click();
  await navigate(page,'技能書架');
  await expect(page.getByRole('heading',{name:'技能書架',level:1,exact:true})).toBeVisible();
  await page.keyboard.press('Backquote');
  await expect(consolePanel).toBeVisible();
  await consolePanel.getByRole('tab',{name:/系統導覽/}).click();
  await expect(consolePanel.getByRole('log')).toContainText('已進入「技能書架」');

  const popupPromise=page.waitForEvent('popup');
  await consolePanel.getByRole('button',{name:'在獨立視窗開啟訊息控制台'}).click();
  const popup=await popupPromise;
  await expect(popup.getByRole('heading',{name:'自由工坊 - 即時訊息控制台',level:1})).toBeVisible();
  await popup.getByRole('tab',{name:'世界聊天'}).click();
  await popup.getByRole('textbox',{name:'世界聊天訊息'}).fill('彈出視窗世界訊息');
  await popup.getByRole('button',{name:'傳送'}).click();
  await expect(popup.getByRole('log')).toContainText('彈出視窗世界訊息');
  await consolePanel.getByRole('tab',{name:'世界聊天'}).click();
  await expect(consolePanel.getByRole('log')).toContainText('彈出視窗世界訊息');
  await expect(popup.getByRole('tab',{name:'AI 指令'})).toHaveCount(0);
  await popup.locator('.game-console-visibility summary').click();
  await popup.getByLabel('AI 指令',{exact:true}).check();
  await expect(consolePanel.getByRole('tab',{name:'AI 指令'})).toBeVisible();
  await popup.getByRole('tab',{name:'系統導覽'}).click();
  await expect(popup.getByRole('log')).toContainText('已進入「技能書架」');
  await navigate(page,'職業公會');
  await expect(popup.getByRole('log')).toContainText('已進入「職業公會」');
  await popup.getByRole('tab',{name:/私人聊天/}).click();
  await expect(popup.getByLabel('私訊對象')).toBeVisible();

  await consolePanel.getByRole('button',{name:'收合訊息控制台'}).click();
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'展開訊息控制台'})).toBeVisible();
  await page.screenshot({path:'test-results/game-console-ticker-mobile.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await consolePanel.getByRole('tab',{name:'總頻道'}).click();
  const compactTitle=consolePanel.getByRole('heading',{name:'自由工坊 - 即時訊息控制台'});
  expect((await compactTitle.boundingBox())?.height).toBeLessThan(24);
  await page.setViewportSize({width:320,height:720});
  expect((await compactTitle.boundingBox())?.height).toBeLessThan(24);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:390,height:844});
  await expect(consolePanel.getByRole('textbox',{name:'世界聊天訊息'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await consolePanel.screenshot({path:'test-results/game-console-mobile-expanded.png'});
  await consolePanel.getByRole('button',{name:'收合訊息控制台'}).click();
  await page.getByRole('button',{name:'登出',exact:true}).click();
  await expect(popup.getByText('登入已結束')).toBeVisible();
  await popup.close();
});

test('pop-out keeps receiving room messages after its original page closes',async({page})=>{
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  const popupPromise=page.waitForEvent('popup');
  await page.getByRole('button',{name:'在獨立視窗開啟訊息控制台'}).click();
  const popup=await popupPromise;
  await expect(popup.getByRole('heading',{name:'自由工坊 - 即時訊息控制台'})).toBeVisible();
  await page.close();

  const sender=await popup.context().newPage();
  await sender.goto('/');
  await sender.getByRole('button',{name:'展開訊息控制台'}).click();
  await sender.getByRole('tab',{name:'世界聊天'}).click();
  const message=`獨立視窗繼續接收 ${randomUUID()}`;
  await sender.getByRole('textbox',{name:'世界聊天訊息'}).fill(message);
  await sender.getByRole('button',{name:'傳送'}).click();
  await expect(sender.getByRole('log')).toContainText(message);
  await popup.bringToFront();
  await expect.poll(()=>popup.evaluate(()=>document.visibilityState)).toBe('visible');
  await popup.getByRole('tab',{name:'世界聊天'}).click();
  await expect(popup.getByRole('log')).toContainText(message,{timeout:15000});
  await sender.close();
  await popup.close();
});

test('sent private messages return to the console after signing in again',async({page})=>{
  const message=`重登入仍在的私訊 ${randomUUID()}`;
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await page.getByRole('tab',{name:/私人聊天/}).click();
  await page.getByLabel('搜尋會員').fill('示範需求者');
  await expect(page.getByLabel('私訊對象').locator('option')).toContainText(['請選擇會員','示範需求者 · 20000000']);
  await page.getByLabel('私訊對象').selectOption('20000000-0000-4000-8000-000000000002');
  await page.getByLabel('私人訊息').fill(message);
  await page.getByRole('button',{name:'傳送'}).click();
  await expect(page.getByRole('log')).toContainText(message);
  await page.getByRole('button',{name:'登出',exact:true}).click();
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await page.getByRole('tab',{name:'總頻道'}).click();
  await expect(page.getByRole('log')).toContainText(message);
  await page.getByRole('tab',{name:/私人聊天/}).click();
  await expect(page.getByRole('log')).toContainText(message);
});
