import { randomUUID } from 'node:crypto';
import { test,expect } from './fixtures.js';
import { navigate } from './navigation.js';

test('new member explores before positioning and can switch the bright theme',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.screenshot({path:'test-results/member-login-light.png',fullPage:true});
  await page.getByRole('button',{name:'建立帳號',exact:true}).click();
  await page.getByLabel('社群顯示名稱',{exact:true}).fill('共創新夥伴');
  await page.getByLabel('電子郵件',{exact:true}).fill(`experience-${randomUUID()}@example.test`);
  await page.getByLabel('密碼',{exact:true}).fill('freedom-member-experience-2026');
  await page.getByRole('button',{name:'建立帳號，先逛工坊',exact:true}).click();
  await expect(page.getByRole('heading',{name:'共創新夥伴，歡迎來到自由工坊。'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'近期活動'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'可參與的工作'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'免費技能書'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-preview-light.png',fullPage:true});
  await page.getByRole('button',{name:'切換至深色介面'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.getByRole('button',{name:'切換至明亮介面'}).click();
  await page.getByRole('button',{name:'開始／繼續定位 →',exact:true}).click();
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toBeVisible();
  await page.getByRole('button',{name:'先逛逛社群'}).click();
  await expect(page.getByRole('heading',{name:'共創新夥伴，歡迎來到自由工坊。'})).toBeVisible();
});

test('completed member publishes an event and sees the task board with real points policy',async({page})=>{
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible();
  await page.screenshot({path:'test-results/member-home-light.png',fullPage:true});
  await navigate(page,'社群活動');
  await expect(page.getByRole('heading',{name:'社群活動',level:1})).toBeVisible();
  await page.getByRole('button',{name:'＋ 發佈活動'}).click();
  const title=`共創活動 ${randomUUID().slice(0,8)}`;
  await page.getByLabel('活動名稱').fill(title);
  await page.getByLabel('活動說明').fill('一起分享一個可以完成的小作品。');
  const start=new Date(Date.now()+48*3600000),end=new Date(start.getTime()+3600000);
  const local=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
  await page.getByLabel('開始時間').fill(local(start));
  await page.getByLabel('結束時間').fill(local(end));
  await page.getByLabel('地點或參與連結').fill('https://example.org/meeting');
  await page.getByRole('button',{name:'確認發佈'}).click();
  await expect(page.getByRole('heading',{name:title})).toBeVisible();
  await expect(page.getByRole('link',{name:'開啟參與連結'})).toHaveAttribute('href','https://example.org/meeting');
  await page.screenshot({path:'test-results/member-events-light.png',fullPage:true});
  await navigate(page,'社群任務榜');
  await expect(page.getByRole('heading',{name:'社群任務榜',level:1})).toBeVisible();
  await expect(page.getByText('每件經獨立驗收的工坊工作 +10。')).toBeVisible();
  await page.getByLabel('選擇共創專案').selectOption({index:1});
  await expect(page.getByRole('heading',{name:'GitHub 共創 Issue'})).toBeVisible();
  await page.screenshot({path:'test-results/member-tasks-light.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
