import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import sharp from 'sharp';
import { DEMO_COMMUNITY } from '../../packages/testing/seed.js';
import { test,expect } from './fixtures.js';
import { navigate, openHomeGuide } from './navigation.js';

const leaderboardFixtureUsers: string[] = [];
test.afterEach(async ({ e2eAuthPool }) => {
  if (!leaderboardFixtureUsers.length) return;
  const ids = leaderboardFixtureUsers.splice(0);
  await e2eAuthPool.query('DELETE FROM github_social_connections WHERE user_id = ANY($1::uuid[])', [ids]);
  await e2eAuthPool.query('DELETE FROM users WHERE user_id = ANY($1::uuid[])', [ids]);
});

async function bindLeaderboardLogins(pool: Pool) {
  const memberId = randomUUID(), contributorId = randomUUID();
  leaderboardFixtureUsers.push(memberId, contributorId);
  await pool.query(`INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref,onboarding_required)
    SELECT $1,community_id,$2,'排行綁定甲',password_hash,$3,false FROM users WHERE email='maker@local.test'`, [memberId, `leaderboard-bind-${memberId}@example.test`, randomUUID()]);
  await pool.query(`INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref,onboarding_required)
    SELECT $1,community_id,$2,'排行綁定乙',password_hash,$3,false FROM users WHERE email='maker@local.test'`, [contributorId, `leaderboard-bind-${contributorId}@example.test`, randomUUID()]);
  await pool.query(`INSERT INTO github_social_connections(user_id,community_id,github_user_id,github_login,encrypted_tokens)
    VALUES ($1,$3,'9100100201','member-demo','e2e-not-a-token'),($2,$3,'9100100202','contributor-demo','e2e-not-a-token')`, [memberId, contributorId, DEMO_COMMUNITY]);
}

test('new member explores, submits an event and selects each theme',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.screenshot({path:'test-results/member-login-light.png',fullPage:true});
  await page.getByRole('button',{name:'建立帳號',exact:true}).click();
  await page.getByLabel('社群顯示名稱',{exact:true}).fill('共創新夥伴');
  await page.getByLabel('電子郵件',{exact:true}).fill(`experience-${randomUUID()}@example.test`);
  await page.getByLabel('密碼',{exact:true}).fill('freedom-member-experience-2026');
  await page.getByRole('button',{name:'建立帳號，先逛工坊',exact:true}).click();
  await expect(page.getByRole('heading',{name:'共創新夥伴，歡迎來到自由工坊。'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'近期活動'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'可參與的工作'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'免費技能書'})).toBeVisible();
  await expect(page.locator('.welcome-preview-grid').getByRole('link',{name:'開啟原作 ↗'}).first()).toHaveAttribute('href','https://github.com/arumwu/local-workspace-mcp');
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-preview-light.png',fullPage:true});
  await page.setViewportSize({width:320,height:720});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-preview-light-320.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('.welcome-optional > summary').click();
  await page.getByRole('button',{name:'提交公開活動'}).click();
  await page.getByLabel('活動名稱').fill('新會員一起畫工坊');
  await page.getByLabel('活動說明').fill('一起畫出下一次活動的原創小插圖。');
  await page.getByLabel('線上場地').fill('Discord 讀書會場地');
  await page.getByRole('button',{name:'送出審核'}).click();
  await expect(page.getByText('活動已送出審核；核准後才會開放報名。')).toBeVisible();
  await expect(page.getByText('新會員一起畫工坊')).toBeVisible();
  await page.locator('.preview-profile-menu > summary').click();
  await expect(page.locator('.preview-profile-menu').getByRole('radio')).toHaveCount(5);
  await page.getByRole('radio',{name:'新手導覽－龍娘',exact:true}).check();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await expect(page.locator('html')).toHaveAttribute('data-experience-profile','guide-dragon');
  await expect(page.locator('.page-spirit-widget')).toHaveCount(0);
  await page.getByRole('radio',{name:'新手導覽－AI Sister',exact:true}).check();
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await expect(page.locator('html')).toHaveAttribute('data-experience-profile','guide-ai-sister');
  await expect(page.locator('.page-spirit-widget')).toHaveCount(0);
  await expect(page.getByText('夜航（深色）')).toHaveCount(0);
  await page.getByRole('radio',{name:'自由工坊－敘生'}).check();
  await expect(page.locator('html')).toHaveAttribute('data-theme','versefolk');
  await page.screenshot({path:'test-results/member-preview-versefolk.png',fullPage:true});
  await page.getByRole('radio',{name:'自由工坊－夜航'}).check();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.locator('.preview-profile-menu > summary').click();
  await page.getByRole('radio',{name:'自由工坊－明亮'}).check();
  await page.locator('.welcome-optional > summary').click();
  await page.getByRole('button',{name:'開始／繼續定位 →',exact:true}).click();
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'你喜歡怎麼做事？'})).toBeVisible();
  await page.locator('.preview-profile-menu > summary').click();
  await page.getByRole('button',{name:'先逛逛社群'}).click();
  await expect(page.getByRole('heading',{name:'共創新夥伴，歡迎來到自由工坊。'})).toBeVisible();
});

test('completed member submits an event and sees accepted-work facts without provisional points',async({page,e2eAuthPool})=>{
  test.setTimeout(90_000);
  await bindLeaderboardLogins(e2eAuthPool);
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible();
  await expect(page.locator('.community-header').getByRole('button',{name:/^通知/})).toBeVisible();
  await page.locator('.page-tools-menu > summary').click();
  for(const name of ['提出想法','頁面說明','參與編修'])await expect(page.locator('.topbar').getByRole('button',{name,exact:true})).toBeVisible();
  await page.locator('.page-tools-menu > summary').click();
  await expect(page.locator('.game-console')).toHaveCount(0);
  await expect(page.locator('.development-context')).toHaveCount(0);
  expect(await page.evaluate(()=>getComputedStyle(document.querySelector('.floating-messages')!).backgroundColor)).toBe('rgb(255, 255, 255)');
  await page.screenshot({path:'test-results/member-home-light.png',fullPage:true});
  await navigate(page,'社群活動');
  await expect(page.getByRole('heading',{name:'社群活動',level:1})).toBeVisible();
  await expect(page.getByRole('heading',{name:'活動行事曆'})).toBeVisible();
  await page.getByRole('button',{name:'＋ 提交活動'}).click();
  const title=`共創活動 ${randomUUID().slice(0,8)}`;
  await page.getByLabel('活動名稱').fill(title);
  await page.getByLabel('活動說明').fill('一起分享一個可以完成的小作品。');
  const start=new Date(Date.now()+48*3600000),end=new Date(start.getTime()+3600000);
  const local=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
  await page.getByLabel('開始時間').fill(local(start));
  await page.getByLabel('結束時間').fill(local(end));
  await page.getByLabel('活動類型').selectOption('reading_group');
  await page.getByLabel('讀書會主題').fill('共同創作入門');
  await page.getByLabel('線上場地').fill('Discord 讀書會場地');
  await page.getByLabel('線上參與連結').fill('https://example.org/meeting');
  const banner=await sharp({create:{width:120,height:63,channels:3,background:'#366177'}}).png().toBuffer();
  await page.getByLabel('活動海報（選填）').setInputFiles({name:'event-banner.png',mimeType:'image/png',buffer:banner});
  await page.getByRole('button',{name:'送出審核'}).click();
  await expect(page.getByRole('heading',{name:title})).toBeVisible();
  await expect(page.getByRole('heading',{name:'待審核活動'})).toBeVisible();
  await expect(page.locator('.experience-card').filter({has:page.getByRole('heading',{name:title})}).locator('.experience-banner-image')).toBeVisible();
  await page.screenshot({path:'test-results/member-events-light.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-events-light-phone.png',fullPage:true});
  await page.setViewportSize({width:768,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-events-light-tablet.png',fullPage:true});
  await page.setViewportSize({width:1440,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-events-light-desktop.png',fullPage:true});
  await page.setViewportSize({width:1280,height:720});
  await navigate(page,'社群任務');
  await expect(page.getByRole('heading',{name:'社群任務',level:1})).toBeVisible();
  await expect(page.getByText('GitHub 排行分數不計入這裡的驗收件數。',{exact:false})).toBeVisible();
  await expect(page.getByRole('heading',{name:'使用者排行榜與歷史紀錄'})).toBeVisible();
  await expect(page.getByText('已在平台連結 GitHub')).toBeVisible();
  await expect(page.getByText('這些分數只顯示在本頁，不計入會員經驗、獎勵或驗收。')).toBeVisible();
  await page.getByRole('button',{name:'歷史想法'}).click();
  await expect(page.getByRole('button',{name:/平台結構/})).toHaveAttribute('aria-pressed','true');
  await expect(page.getByRole('link',{name:'讓會員首頁的文字更清楚'})).toBeVisible();
  const outsider=page.locator('.community-history-list li').filter({hasText:'外部協作者的紀錄'});
  await expect(outsider.getByRole('link',{name:'外部協作者的紀錄'})).toBeVisible();
  await expect(outsider).toContainText('outsider-demo');
  await expect(page.locator('.community-history-list li').filter({hasText:'自動檢查未採納'}).locator('.community-history-state')).toHaveText('已解決');
  await expect(page.locator('.community-history-list img')).toHaveCount(0);
  await expect(page.getByText('<img src=x onerror=alert(1)>')).toBeVisible();
  await page.locator('.community-history').getByRole('combobox',{name:'狀態',exact:true}).selectOption('done');
  await expect(page.getByRole('link',{name:'補上社群導覽'})).toHaveCount(0);
  await expect(page.getByRole('link',{name:'自動檢查未採納'})).toBeVisible();
  await page.getByRole('button',{name:'歷史更新'}).click();
  await expect(page.getByRole('link',{name:'改善手機導覽'})).toBeVisible();
  const merged=page.locator('.community-history-list li').filter({hasText:'改善手機導覽'});
  await expect(merged.locator('.community-history-state')).toHaveText('已更新');
  await expect(merged).toContainText('建立');
  await expect(merged).toContainText('更新');
  const unmerged=page.locator('.community-history-list li').filter({hasText:'關閉未合併的說明'});
  await expect(unmerged.locator('.community-history-state')).toHaveText('未更新');
  await expect(unmerged).toContainText('未合併關閉');
  await page.locator('.community-history').getByRole('combobox',{name:'狀態',exact:true}).selectOption('pending');
  await expect(page.getByRole('link',{name:'改善手機導覽'})).toHaveCount(0);
  await expect(page.getByRole('link',{name:'關閉未合併的說明'})).toBeVisible();
  await expect(page.getByRole('link',{name:'更新技能書說明'})).toBeVisible();
  await page.getByRole('button',{name:/私人技能/}).click();
  await expect(page.getByText('此分類目前沒有符合條件的紀錄。')).toBeVisible();
  await page.getByRole('button',{name:'使用者排行榜'}).click();
  await expect(page.getByRole('heading',{name:'貢獻排行榜'})).toBeVisible({timeout:30000});
  await expect(page.getByRole('heading',{name:'想法排行榜'})).toBeVisible();
  const ideas=page.locator('section.community-leaderboard').filter({has:page.getByRole('heading',{name:'想法排行榜'})});
  await expect(ideas).toContainText('member-demo');
  await expect(ideas).toContainText('2 Issue');
  await expect(ideas).not.toContainText('dependabot');
  await expect(ideas).not.toContainText('github-actions');
  await expect(ideas).not.toContainText('outsider-demo');
  const edits=page.locator('section.community-leaderboard').filter({has:page.getByRole('heading',{name:'編修排行榜'})});
  await expect(edits).toContainText('contributor-demo');
  await expect(edits).toContainText('2 PR');
  await expect(edits).toContainText('1 PR');
  await expect(edits.locator('li').filter({hasText:'2 PR'}).locator('.community-rank')).toHaveText('第 1 名');
  await expect(edits.locator('li').filter({hasText:'1 PR'}).locator('.community-rank')).toHaveText('第 2 名');
  const points=page.locator('section.community-leaderboard').filter({has:page.getByRole('heading',{name:'貢獻排行榜'})});
  await expect(points).toContainText('每個 Issue 5 分，每個 PR 20 分（Issue × 5 + PR × 20）');
  await expect(points).toContainText('40 分');
  await expect(points).toContainText('30 分');
  await expect(points).not.toContainText('dependabot');
  await expect(edits).not.toContainText('outsider-demo');
  await expect(points).not.toContainText('outsider-demo');
  await page.getByLabel('選擇共創專案').selectOption({index:1});
  await expect(page.getByRole('heading',{name:'GitHub 共創 Issue'})).toBeVisible();
  await page.screenshot({path:'test-results/member-tasks-light.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:768,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-tasks-light-phone.png',fullPage:true});
  await page.setViewportSize({width:320,height:720});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:820,height:1100});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('community history keeps rankings while repositories are still syncing or unreadable',async({page})=>{
  test.setTimeout(90_000);
  const synced='2026-09-28T00:00:00.000Z';
  await page.route('**/api/v1/community/github-history/leaderboards',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({
    ideas:[{login:'member-demo',count:2}],edits:[{login:'contributor-demo',count:2}],
    contributions:[{login:'contributor-demo',count:40},{login:'member-demo',count:30}],
    complete:false,oldest_synced_at:synced,syncing:['FreeTWAI-AI/freedom-agent-kit'],unreadable:['FreeTWAI-AI/freedom-storefront'],
  })}));
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await navigate(page,'社群任務');
  await expect(page.getByText('部分儲存庫仍在同步中，排行榜會自動補齊。')).toBeVisible();
  await expect(page.getByText('沒有權限讀取這個儲存庫（可能已設為私有或已刪除）')).toBeVisible();
  await expect(page.getByText('FreeTWAI-AI/freedom-storefront')).toBeVisible();
  await expect(page.getByText('FreeTWAI-AI/freedom-agent-kit')).toBeVisible();
  await expect(page.getByText(/資料更新於/)).toBeVisible();
  await expect(page.getByRole('heading',{name:'想法排行榜'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'編修排行榜'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'貢獻排行榜'})).toBeVisible();
  await page.setViewportSize({width:320,height:720});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.route('**/api/v1/community/github-history/repositories**',async route=>{
    const response=await route.fetch();
    const body=await response.json();
    for(const item of body.items??[]){
      if(item.name==='FreeTWAI-AI/freedom-agent-kit')item.sync={status:'syncing',last_synced_at:null};
      if(item.name==='FreeTWAI-AI/freedom-storefront')item.sync={status:'unreadable',last_synced_at:synced};
    }
    await route.fulfill({response,json:body});
  });
  await page.getByRole('button',{name:'重新讀取'}).click();
  await page.getByRole('button',{name:'歷史想法'}).click();
  await expect(page.getByRole('link',{name:'讓會員首頁的文字更清楚'})).toBeVisible();
  await expect(page.getByText('部分儲存庫仍在同步中，排行榜會自動補齊。')).toBeVisible();
  await expect(page.getByText('沒有權限讀取這個儲存庫（可能已設為私有或已刪除）')).toBeVisible();
  await page.unroute('**/api/v1/community/github-history/leaderboards');
  await page.unroute('**/api/v1/community/github-history/repositories**');
  await page.getByRole('button',{name:'重新讀取'}).click();
  await expect(page.getByText('部分儲存庫仍在同步中，排行榜會自動補齊。')).toHaveCount(0);
  await page.getByRole('button',{name:'使用者排行榜'}).click();
  await expect(page.getByRole('heading',{name:'想法排行榜'})).toBeVisible();
  await expect(page.getByText('部分儲存庫仍在同步中，排行榜會自動補齊。')).toHaveCount(0);
  await page.setViewportSize({width:820,height:1100});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('task board explains unavailable and stale GitHub reads without claiming there are no issues',async({page})=>{
  let stale=false;
  await page.route('**/api/v1/co-creation/projects/workshop-video-autopilot/activity',route=>route.fulfill(stale
    ?{status:200,contentType:'application/json',body:JSON.stringify({repository_url:'https://github.com/FreeTWAI-AI/video-autopilot-kit',checked_at:'2026-09-27T12:00:00Z',issues:[],contributions:[],truncated:false,stale_reason:'github_rate_limited'})}
    :{status:200,contentType:'application/json',body:JSON.stringify({repository_url:'https://github.com/FreeTWAI-AI/video-autopilot-kit',checked_at:'2026-09-28T00:00:00Z',issues:[],contributions:[],truncated:false,unavailable_reason:'github_sync_pending'})}));
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await navigate(page,'社群任務');
  const picker=page.getByLabel('選擇共創專案');
  await picker.selectOption('workshop-video-autopilot');
  await expect(page.getByRole('status').filter({hasText:'GitHub 資料同步中'})).toContainText('還無法確認任務清單');
  await expect(page.getByText('這個專案目前沒有符合搜尋的開放 Issue。')).toHaveCount(0);
  await expect(page.locator('.game-console')).toHaveCount(0);
  const repo=page.getByRole('link',{name:'查看完整 GitHub 專案 ↗'});
  await expect(repo).toHaveAttribute('href','https://github.com/FreeTWAI-AI/video-autopilot-kit');
  await page.screenshot({path:'test-results/task-board-github-rate-limit-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/task-board-github-rate-limit-mobile.png',fullPage:true});
  stale=true;
  await picker.selectOption('');
  await picker.selectOption('workshop-video-autopilot');
  await expect(page.getByRole('status').filter({hasText:'GitHub 暫時限制查詢'})).toContainText('以下是');
  await expect(repo).toHaveAttribute('href','https://github.com/FreeTWAI-AI/video-autopilot-kit');
});

test('story theme keeps the workshop controls and cute artwork usable on a narrow phone',async({page})=>{
  await page.setViewportSize({width:320,height:720});await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await page.getByRole('button',{name:'設定',exact:true}).click();
  await page.getByRole('menuitemradio',{name:'自由工坊－敘生'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','versefolk');
  await expect(page.getByRole('menuitemradio',{name:'自由工坊－敘生'})).toHaveAttribute('aria-checked','true');
  await page.getByRole('button',{name:'設定',exact:true}).click();
  // 頁面說明 uses the theme's soft green, the same tint family as the filled 提出想法.
  await expect.poll(()=>page.evaluate(()=>{const tool=document.querySelector('.page-tool-button--help')!,probe=document.createElement('span');probe.style.background=getComputedStyle(document.documentElement).getPropertyValue('--green-soft').trim();document.body.append(probe);const soft=getComputedStyle(probe).backgroundColor;probe.remove();return getComputedStyle(tool).backgroundColor===soft})).toBe(true);
  await openHomeGuide(page);
  await page.locator('.home-module-section > summary').click();
  await expect(page.locator('.home-module-supplier .home-module-cover')).toHaveCSS('background-image',/versefolk-market\.webp/);
  await page.locator('.home-module-section > summary').click();
  await page.locator('.page-tools-menu > summary').click();
  for(const name of ['提出想法','頁面說明','參與編修'])await expect(page.locator('.topbar').getByRole('button',{name:new RegExp(name)})).toBeVisible();
  await page.locator('.page-tools-menu > summary').click();
  await expect(page.locator('.game-console')).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/member-home-versefolk-320.png',fullPage:true});
});
