import {test,expect} from './fixtures.js';
import {navigate} from './navigation.js';

test('every workspace page exposes contextual tools, filtered issues and agent guidance',async({page})=>{
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as typeof window&{copiedClaim?:string}).copiedClaim=text}}}));
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible({timeout:20000});
  await page.route('**/api/v1/me/github',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:true,connected:true,github_user:{id:'123',login:'maker'}})}));
  await page.getByRole('button',{name:'提出想法'}).click();
  const idea=page.getByRole('dialog',{name:'會員首頁：提出想法'});
  await expect(idea).toBeVisible();
  await expect(idea.getByRole('link',{name:/#14/})).toBeVisible();
  await expect(idea.getByRole('link',{name:/#13/})).toHaveCount(0);
  await idea.getByRole('button',{name:'回覆這則 Issue'}).click();
  await expect(idea.getByRole('textbox',{name:'設計認領留言'})).toBeVisible();
  await idea.getByRole('button',{name:'交給 Agent 送出'}).click();
  await expect(idea.getByRole('button',{name:'已複製 Agent 指令'})).toBeVisible();
  expect(await page.evaluate(()=>(window as typeof window&{copiedClaim?:string}).copiedClaim)).toContain('<!-- freedom-design-claim -->');
  await idea.getByRole('textbox',{name:'標題'}).fill('首頁想法');
  await idea.getByRole('textbox',{name:'想法與期待'}).fill('太短');
  const direct=idea.getByRole('button',{name:'用我的 GitHub 發布'});
  await expect(direct).toBeEnabled();
  await direct.click();
  await expect(idea.getByRole('alert')).toContainText('至少 3 字的標題與 10 字');
  await expect(direct).toBeEnabled();
  await idea.getByRole('textbox',{name:'想法與期待'}).fill('讓會員首頁的入口更清楚容易理解。');
  await expect(idea.locator('pre')).toContainText('<!-- freedom-page:home -->');
  await page.evaluate(()=>{(window as typeof window&{issuedGitHubUrl?:string}).open=(url)=>{(window as typeof window&{issuedGitHubUrl?:string}).issuedGitHubUrl=String(url);return null}});
  await idea.getByRole('button',{name:'到 GitHub 檢查並送出'}).click();
  const issueUrl=new URL(await page.evaluate(()=>(window as typeof window&{issuedGitHubUrl?:string}).issuedGitHubUrl??''));
  expect(issueUrl.origin).toBe('https://github.com');
  expect(issueUrl.searchParams.get('body')).toContain('<!-- freedom-page:home -->');
  await page.screenshot({path:'test-results/page-tools-idea-desktop.png'});
  await idea.getByRole('button',{name:'關閉'}).click();
  await navigate(page,'我的定位');
  await page.getByRole('button',{name:'頁面說明'}).click();
  const help=page.getByRole('dialog',{name:'我的定位：頁面說明'});
  await expect(help.getByText('「我的定位」顯示你最後確認的方向與合作偏好')).toBeVisible();
  await expect(help.getByText('重新填寫草稿不會立刻覆蓋原本確認的定位。')).toBeVisible();
  await expect(help.locator('pre')).toContainText('常見問題');
  await help.getByRole('button',{name:'關閉'}).click();
  await page.getByRole('button',{name:'參與編修'}).click();
  const edit=page.getByRole('dialog',{name:'我的定位：參與編修'});
  await expect(edit).toContainText('Fork 平台 Repo');
  await expect(edit.locator('pre')).toContainText('page:positioning');
  await edit.getByRole('button',{name:'關閉'}).click();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await page.getByRole('tab',{name:/系統公告/}).click();
  await expect(page.getByRole('log')).toContainText('member-demo 提出 Issue');
  await expect(page.getByRole('log')).toContainText('contributor-demo 提交 PR');
  await expect(page.getByRole('log')).toContainText('maintainer-demo 核准 PR');
  await expect(page.getByRole('log')).toContainText('designer-demo 表示願意接手 Issue 設計');
  await page.screenshot({path:'test-results/page-tools-desktop.png'});
});

test('phone keeps world chat in an in-page drawer and admin keeps a dock',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('button',{name:'提出想法'})).toBeVisible();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await expect(page.getByRole('button',{name:'在獨立視窗開啟訊息控制台'})).toBeHidden();
  await expect(page.getByRole('textbox',{name:'世界聊天訊息'})).toBeVisible();
  await page.screenshot({path:'test-results/page-tools-mobile-chat.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'收合訊息控制台'}).click();
  await page.getByRole('button',{name:'提出想法'}).click();
  await page.screenshot({path:'test-results/page-tools-idea-mobile.png'});
  await page.getByRole('dialog',{name:'會員首頁：提出想法'}).getByRole('button',{name:'關閉'}).click();
  await page.goto('/admin');
  await expect(page.getByRole('button',{name:'展開訊息控制台'})).toBeVisible();
  await expect(page.getByRole('button',{name:'提出想法'})).toBeVisible();
});

test('unlinked member gets GitHub guidance and screenshot handoff',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as typeof window&{copiedInstruction?:string}).copiedInstruction=text}}}));
  await page.route('**/api/v1/me/github',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:true,connected:false})}));
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible({timeout:20000});
  await page.getByRole('button',{name:'提出想法'}).click();
  const idea=page.getByRole('dialog',{name:'會員首頁：提出想法'});
  await expect(idea.getByText('站內發布前，先連結 GitHub')).toBeVisible();
  await idea.getByRole('button',{name:'複製給 AI 的連結指引'}).click();
  expect(await page.evaluate(()=>(window as typeof window&{copiedInstruction?:string}).copiedInstruction)).toContain('GitHub');
  await idea.getByRole('textbox',{name:'標題'}).fill('首頁截圖建議');
  await idea.getByRole('textbox',{name:'想法與期待'}).fill('希望首頁的入口更容易閱讀，截圖標示了目前的問題。');
  await idea.getByLabel('截圖（選填）').setInputFiles({name:'example.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==','base64')});
  await expect(idea.getByRole('img',{name:'待附上的 Issue 截圖預覽'})).toBeVisible();
  await expect(idea.getByRole('button',{name:'用我的 GitHub 發布'})).toHaveCount(0);
  await page.evaluate(()=>{(window as typeof window&{issuedGitHubUrl?:string}).open=(url)=>{(window as typeof window&{issuedGitHubUrl?:string}).issuedGitHubUrl=String(url);return null}});
  await idea.getByRole('button',{name:'到 GitHub 貼上截圖並送出'}).click();
  expect(await page.evaluate(()=>(window as typeof window&{issuedGitHubUrl?:string}).issuedGitHubUrl)).toContain('/issues/new?');
  await expect(idea.getByRole('status')).toContainText('再次貼上截圖');
  await page.screenshot({path:'test-results/page-tools-screenshot-mobile.png'});
  await idea.getByRole('button',{name:'移除截圖'}).click();
  await expect(idea.getByRole('button',{name:'到 GitHub 檢查並送出'})).toBeVisible();
});
