import {test,expect} from './fixtures.js';
import {navigate} from './navigation.js';

test('every workspace page exposes contextual tools, filtered issues and agent guidance',async({page})=>{
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as typeof window&{copiedClaim?:string}).copiedClaim=text}}}));
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'會員首頁',level:1})).toBeVisible();
  await page.getByRole('button',{name:'提出想法'}).click();
  const idea=page.getByRole('dialog',{name:'會員首頁：提出想法'});
  await expect(idea).toBeVisible();
  await expect(idea.getByRole('link',{name:/#12/})).toBeVisible();
  await expect(idea.getByRole('link',{name:/#13/})).toHaveCount(0);
  await idea.getByRole('button',{name:'複製設計認領留言'}).click();
  await expect(idea.getByRole('button',{name:'已複製認領留言'})).toBeVisible();
  expect(await page.evaluate(()=>(window as typeof window&{copiedClaim?:string}).copiedClaim)).toContain('<!-- freedom-design-claim -->');
  await idea.getByRole('textbox',{name:'標題'}).fill('首頁想法');
  await idea.getByRole('textbox',{name:'想法與期待'}).fill('讓入口更清楚。');
  await expect(idea.locator('pre')).toContainText('<!-- freedom-page:home -->');
  await page.evaluate(()=>{(window as typeof window&{issuedGitHubUrl?:string}).open=(url)=>{(window as typeof window&{issuedGitHubUrl?:string}).issuedGitHubUrl=String(url);return null}});
  await idea.getByRole('button',{name:'到 GitHub 檢查並送出'}).click();
  const issueUrl=new URL(await page.evaluate(()=>(window as typeof window&{issuedGitHubUrl?:string}).issuedGitHubUrl??''));
  expect(issueUrl.origin).toBe('https://github.com');
  expect(issueUrl.searchParams.get('body')).toContain('<!-- freedom-page:home -->');
  await page.screenshot({path:'test-results/page-tools-idea-desktop.png'});
  await idea.getByRole('button',{name:'關閉'}).click();
  await navigate(page,'我的定位');
  await page.getByRole('button',{name:'頁面說明'}).click();
  const help=page.getByRole('dialog',{name:'我的定位：頁面說明'});
  await expect(help).toContainText('檢視與調整方向');
  await expect(help.locator('pre')).toContainText('常見問題');
  await help.getByRole('button',{name:'關閉'}).click();
  await page.getByRole('button',{name:'參與編修'}).click();
  const edit=page.getByRole('dialog',{name:'我的定位：參與編修'});
  await expect(edit).toContainText('Fork 平台 Repo');
  await expect(edit.locator('pre')).toContainText('page:positioning');
  await edit.getByRole('button',{name:'關閉'}).click();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await page.getByRole('tab',{name:'世界聊天'}).click();
  await expect(page.getByRole('log')).toContainText('member-demo 提出 Issue');
  await expect(page.getByRole('log')).toContainText('contributor-demo 提交 PR');
  await expect(page.getByRole('log')).toContainText('maintainer-demo 核准 PR');
  await expect(page.getByRole('log')).toContainText('designer-demo 表示願意接手 Issue 設計');
  await page.screenshot({path:'test-results/page-tools-desktop.png'});
});

test('phone keeps world chat in an in-page drawer and admin keeps a dock',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await page.getByLabel('電子郵件',{exact:true}).fill('maker@local.test');
  await page.getByLabel('密碼',{exact:true}).fill('freedom-local-demo');
  await page.getByRole('button',{name:'登入',exact:true}).click();
  await expect(page.getByRole('button',{name:'提出想法'})).toBeVisible();
  await page.getByRole('button',{name:'展開訊息控制台'}).click();
  await expect(page.getByRole('button',{name:'在獨立視窗開啟訊息控制台'})).toBeHidden();
  await expect(page.getByRole('textbox',{name:'世界聊天訊息'})).toBeVisible();
  await page.screenshot({path:'test-results/page-tools-mobile-chat.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'收合訊息控制台'}).click();
  await page.getByRole('button',{name:'提出想法'}).click();
  await page.screenshot({path:'test-results/page-tools-idea-mobile.png'});
  await page.getByRole('dialog',{name:'會員首頁：提出想法'}).getByRole('button',{name:'關閉'}).click();
  await page.goto('/admin');
  await expect(page.getByRole('button',{name:'展開訊息控制台'})).toBeVisible();
  await expect(page.getByRole('button',{name:'提出想法'})).toBeVisible();
});
