-- Finite original upload-grant skill illustration adapter. No activation/backfill.
ALTER TABLE skill_submissions ADD COLUMN storage_source text NOT NULL DEFAULT 'legacy' CHECK(storage_source IN ('legacy','asset'));
ALTER TABLE skill_submissions ADD CONSTRAINT skill_image_domain_identity UNIQUE(submission_id,community_id,owner_ref);
CREATE TABLE skill_submission_image_asset_targets (
 submission_id uuid PRIMARY KEY REFERENCES skill_submissions(submission_id),community_id uuid NOT NULL,
 scope_id uuid NOT NULL,scope_kind text GENERATED ALWAYS AS ('personal'::text) STORED,
 owner_principal_id uuid NOT NULL,owner_user_id uuid NOT NULL,
 asset_id uuid,linked_at_version bigint CHECK(linked_at_version>0),CHECK((asset_id IS NULL)=(linked_at_version IS NULL)),
 purpose text GENERATED ALWAYS AS ('skill.submission-image'::text) STORED,asset_state text GENERATED ALWAYS AS ('ready'::text) STORED,
 FOREIGN KEY(submission_id,community_id,owner_user_id) REFERENCES skill_submissions(submission_id,community_id,owner_ref),
 FOREIGN KEY(scope_id,scope_kind,owner_principal_id) REFERENCES resource_scopes(scope_id,kind,owner_principal_id),
 FOREIGN KEY(owner_principal_id,owner_user_id) REFERENCES principals(principal_id,user_ref),
 FOREIGN KEY(asset_id,scope_id,owner_principal_id,owner_user_id,purpose,asset_state) REFERENCES assets(asset_id,scope_id,owner_principal_id,owner_user_id,purpose,state),
 UNIQUE(submission_id,scope_id,owner_principal_id,owner_user_id),UNIQUE(asset_id)
);
ALTER TABLE asset_upload_intents ADD COLUMN target_submission_id uuid;
ALTER TABLE asset_upload_intents ADD CONSTRAINT upload_skill_target FOREIGN KEY(target_submission_id,scope_id,owner_principal_id,target_user_id) REFERENCES skill_submission_image_asset_targets(submission_id,scope_id,owner_principal_id,owner_user_id);
ALTER TABLE assets DROP CONSTRAINT assets_purpose_check;
ALTER TABLE assets ADD CONSTRAINT assets_purpose_check CHECK(purpose IN ('member.avatar','work.private-draft','member.service-cover','community.event-banner','community.event-video','community.social-thumbnail','skill.submission-image'));
ALTER TABLE assets DROP CONSTRAINT asset_scope_purpose;
ALTER TABLE assets ADD CONSTRAINT asset_scope_purpose CHECK((scope_kind='personal' AND community_ref IS NULL AND purpose IN ('member.avatar','work.private-draft','member.service-cover','skill.submission-image')) OR (scope_kind='community' AND community_ref IS NOT NULL AND purpose IN ('community.event-banner','community.event-video','community.social-thumbnail')));
ALTER TABLE asset_upload_intents DROP CONSTRAINT upload_profile_shape;
ALTER TABLE asset_upload_intents ADD CONSTRAINT upload_profile_shape CHECK((target_submission_id IS NULL AND ((target_post_id IS NULL AND (

 (target_video_event_id IS NULL AND (

 (target_event_id IS NULL AND target_community_id IS NULL AND source_orientation IS NULL AND purpose='member.avatar' AND target_kind='member.avatar' AND target_work_id IS NULL AND target_service_id IS NULL AND source_content_type IN ('image/png','image/jpeg','image/webp') AND source_byte_size BETWEEN 1 AND 2097152 AND reserved_bytes=131072)
 OR (target_event_id IS NULL AND target_community_id IS NULL AND source_orientation IS NULL AND purpose='work.private-draft' AND target_kind='work.private-result' AND target_work_id IS NOT NULL AND target_service_id IS NULL AND source_content_type IN ('text/plain','text/markdown') AND source_byte_size BETWEEN 1 AND 262144 AND reserved_bytes=262144)
 OR (target_event_id IS NULL AND target_community_id IS NULL AND source_orientation IS NULL AND purpose='work.private-draft' AND target_kind='work.model-result' AND target_work_id IS NOT NULL AND target_service_id IS NULL AND source_content_type='text/plain' AND source_byte_size BETWEEN 1 AND 16384 AND reserved_bytes=16384)
 OR (target_event_id IS NULL AND target_community_id IS NULL AND source_orientation IS NULL AND purpose='member.service-cover' AND target_kind='member.service-cover' AND target_service_id IS NOT NULL AND target_work_id IS NULL AND source_content_type IN ('image/png','image/jpeg','image/webp') AND source_byte_size BETWEEN 1 AND 4194304 AND reserved_bytes=524288)
 OR (purpose='community.event-banner' AND target_kind='community.event-banner' AND target_event_id IS NOT NULL AND target_community_id IS NOT NULL AND target_work_id IS NULL AND target_service_id IS NULL AND source_orientation IS NOT NULL AND source_orientation IN ('landscape','portrait') AND source_content_type IN ('image/png','image/jpeg','image/webp') AND source_byte_size BETWEEN 1 AND 524288 AND reserved_bytes=524288))) OR (purpose='community.event-video' AND target_kind='community.event-video' AND target_video_event_id IS NOT NULL AND target_event_id IS NULL AND target_community_id IS NOT NULL AND target_work_id IS NULL AND target_service_id IS NULL AND source_orientation IS NULL AND source_content_type IN ('video/mp4','video/webm') AND source_byte_size BETWEEN 1 AND 20971520 AND reserved_bytes=20971520))) OR (purpose='community.social-thumbnail' AND target_kind='community.social-thumbnail' AND target_post_id IS NOT NULL AND target_community_id IS NOT NULL AND target_event_id IS NULL AND target_video_event_id IS NULL AND target_work_id IS NULL AND target_service_id IS NULL AND source_orientation IS NULL AND source_content_type IN ('image/png','image/jpeg','image/webp') AND source_byte_size BETWEEN 1 AND 524288 AND reserved_bytes=524288))) OR (purpose='skill.submission-image' AND target_kind='skill.submission-image' AND target_submission_id IS NOT NULL AND target_work_id IS NULL AND target_service_id IS NULL AND target_event_id IS NULL AND target_video_event_id IS NULL AND target_post_id IS NULL AND target_community_id IS NULL AND source_orientation IS NULL AND source_content_type='image/webp' AND source_byte_size BETWEEN 1 AND 524288 AND reserved_bytes=524288));
ALTER TABLE asset_objects DROP CONSTRAINT asset_object_profile_id_shape;
ALTER TABLE asset_objects ADD CONSTRAINT asset_object_profile_id_shape CHECK((purpose IN ('member.service-cover','community.event-banner','community.event-video','community.social-thumbnail','skill.submission-image') AND profile_id IS NOT NULL AND profile_id=purpose) OR (purpose NOT IN ('member.service-cover','community.event-banner','community.event-video','community.social-thumbnail','skill.submission-image') AND profile_id IS NULL));
ALTER TABLE asset_objects DROP CONSTRAINT asset_object_profile_shape;
ALTER TABLE asset_objects ADD CONSTRAINT asset_object_profile_shape CHECK((


 (purpose='member.avatar' AND variant='avatar' AND content_type='image/webp' AND byte_size BETWEEN 1 AND 131072 AND transform_version='avatar.webp.v1')
 OR (purpose='work.private-draft' AND variant='draft' AND content_type IN ('text/plain','text/markdown') AND byte_size BETWEEN 1 AND 262144 AND transform_version='private-text.utf8.v1')
 OR (purpose='member.service-cover' AND variant='cover' AND content_type='image/webp' AND byte_size BETWEEN 1 AND 524288 AND transform_version='member.service-cover.legacy-bytes.v1')
 OR (purpose='community.event-banner' AND variant='banner' AND content_type='image/webp' AND byte_size BETWEEN 1 AND 524288 AND transform_version='community.event-banner.legacy-bytes.v1') OR (purpose='community.event-video' AND variant='video' AND content_type IN ('video/mp4','video/webm') AND byte_size BETWEEN 1 AND 20971520 AND transform_version='community.event-video.legacy-bytes.v1') OR (purpose='community.social-thumbnail' AND variant='thumbnail' AND content_type='image/webp' AND byte_size BETWEEN 1 AND 524288 AND transform_version='community.social-thumbnail.legacy-bytes.v1')) OR (purpose='skill.submission-image' AND variant='illustration' AND content_type='image/webp' AND byte_size BETWEEN 1 AND 524288 AND transform_version='skill.submission-image.legacy-bytes.v1'));
CREATE OR REPLACE FUNCTION preserve_upload_typed_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF ROW(NEW.target_kind,NEW.target_work_id,NEW.target_service_id,NEW.target_event_id,NEW.target_video_event_id,NEW.target_submission_id,NEW.target_post_id,NEW.target_community_id,NEW.source_orientation) IS DISTINCT FROM ROW(OLD.target_kind,OLD.target_work_id,OLD.target_service_id,OLD.target_event_id,OLD.target_video_event_id,OLD.target_submission_id,OLD.target_post_id,OLD.target_community_id,OLD.source_orientation) THEN RAISE EXCEPTION 'Upload typed target is immutable' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE OR REPLACE FUNCTION preserve_domain_media_floor() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' OR NEW.purpose IS DISTINCT FROM OLD.purpose OR (OLD.mode<>'legacy' AND NEW.mode='legacy') THEN RAISE EXCEPTION 'Media storage floor cannot rewind' USING ERRCODE='23514';END IF;
 IF NEW.purpose NOT IN ('member.service-cover','community.event-banner','community.event-video','community.social-thumbnail','skill.submission-image') AND NEW.mode<>'legacy' THEN RAISE EXCEPTION 'Domain media adapter is not installed' USING ERRCODE='23514';END IF;
 IF NEW.purpose='community.social-thumbnail' AND NEW.mode='r2_only' THEN RAISE EXCEPTION 'Automatic social preview writer remains legacy' USING ERRCODE='23514';END IF;
 IF NEW.mode='r2_only' AND ((NEW.purpose='skill.submission-image' AND EXISTS(SELECT 1 FROM skill_submissions WHERE image_bytes IS NOT NULL)) OR (NEW.purpose='community.event-banner' AND EXISTS(SELECT 1 FROM community_event_banners WHERE storage_source='legacy' OR image_bytes IS NOT NULL)) OR (NEW.purpose='member.service-cover' AND EXISTS(SELECT 1 FROM member_service_covers WHERE storage_source='legacy' OR image_bytes IS NOT NULL)) OR (NEW.purpose='community.event-video' AND EXISTS(SELECT 1 FROM community_event_videos WHERE storage_source='legacy' OR media_bytes IS NOT NULL))) THEN RAISE EXCEPTION 'Legacy media sources remain' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE FUNCTION fence_skill_image_writer() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE mode_value text;BEGIN
 SELECT mode INTO STRICT mode_value FROM domain_media_storage_policy WHERE purpose='skill.submission-image' FOR SHARE;
 IF NEW.storage_source='asset' AND (mode_value='legacy' OR NEW.image_bytes IS NOT NULL) THEN RAISE EXCEPTION 'Asset skill image is not enabled or contains legacy bytes' USING ERRCODE='23514';END IF;
 IF NEW.image_bytes IS NOT NULL AND mode_value='r2_only' THEN RAISE EXCEPTION 'Legacy skill writer is fenced' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND OLD.storage_source='asset' AND (NEW.storage_source<>'asset' OR NEW.image_bytes IS DISTINCT FROM OLD.image_bytes) THEN RAISE EXCEPTION 'Asset skill images cannot fall back' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER fence_skill_image_writer BEFORE INSERT OR UPDATE ON skill_submissions FOR EACH ROW EXECUTE FUNCTION fence_skill_image_writer();
CREATE FUNCTION require_skill_image_pointer() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF EXISTS(SELECT 1 FROM skill_submissions s WHERE s.submission_id=COALESCE(NEW.submission_id,OLD.submission_id) AND s.storage_source='asset' AND NOT EXISTS(SELECT 1 FROM skill_submission_image_asset_targets t JOIN asset_objects o ON o.asset_id=t.asset_id AND o.purpose='skill.submission-image' WHERE t.submission_id=s.submission_id AND t.asset_id IS NOT NULL AND t.linked_at_version<=s.aggregate_version)) THEN RAISE EXCEPTION 'Skill image requires typed current pointer' USING ERRCODE='23514';END IF;RETURN COALESCE(NEW,OLD);END $$;
CREATE CONSTRAINT TRIGGER require_skill_image_pointer AFTER INSERT OR UPDATE ON skill_submissions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION require_skill_image_pointer();
CREATE CONSTRAINT TRIGGER require_skill_image_target AFTER INSERT OR UPDATE OR DELETE ON skill_submission_image_asset_targets DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION require_skill_image_pointer();
CREATE TRIGGER reject_fenced_asset_reference BEFORE INSERT OR UPDATE ON skill_submission_image_asset_targets FOR EACH ROW EXECUTE FUNCTION reject_fenced_asset_reference();
CREATE FUNCTION preserve_skill_image_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' OR ROW(NEW.submission_id,NEW.community_id,NEW.scope_id,NEW.owner_principal_id,NEW.owner_user_id) IS DISTINCT FROM ROW(OLD.submission_id,OLD.community_id,OLD.scope_id,OLD.owner_principal_id,OLD.owner_user_id) THEN RAISE EXCEPTION 'Skill image target cannot be rebound' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER preserve_skill_image_target BEFORE UPDATE OR DELETE ON skill_submission_image_asset_targets FOR EACH ROW EXECUTE FUNCTION preserve_skill_image_target();
