-- Automatic preview reservations are not public posts; publication binds the original domain identity.
ALTER TABLE community_social_thumbnail_asset_targets ADD COLUMN create_key text CHECK(create_key ~ '^[0-9a-f]{64}$'),ADD COLUMN create_digest text CHECK(create_digest ~ '^[0-9a-f]{64}$'),ADD COLUMN create_draft jsonb,ADD COLUMN create_source text CHECK(create_source IN ('youtube','page')),ADD COLUMN create_at timestamptz;
ALTER TABLE community_social_thumbnail_asset_targets ADD CONSTRAINT social_create_shape CHECK((create_key IS NULL AND create_digest IS NULL AND create_draft IS NULL AND create_source IS NULL AND create_at IS NULL) OR (create_key IS NOT NULL AND create_digest IS NOT NULL AND create_draft IS NOT NULL AND create_source IS NOT NULL AND create_at IS NOT NULL));
ALTER TABLE community_social_thumbnail_asset_targets ADD CONSTRAINT social_create_key UNIQUE(owner_user_id,create_key);
DO $$ DECLARE c record;BEGIN FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='community_social_thumbnail_asset_targets'::regclass AND confrelid='community_social_posts'::regclass AND contype='f' LOOP EXECUTE format('ALTER TABLE community_social_thumbnail_asset_targets DROP CONSTRAINT %I',c.conname);END LOOP;END $$;
ALTER TABLE community_social_thumbnail_asset_targets ADD COLUMN domain_post_id uuid GENERATED ALWAYS AS (CASE WHEN create_key IS NULL OR asset_id IS NOT NULL THEN post_id END) STORED;
ALTER TABLE community_social_thumbnail_asset_targets ADD CONSTRAINT social_published_domain FOREIGN KEY(domain_post_id,community_id,owner_user_id) REFERENCES community_social_posts(post_id,community_id,author_user_id);
CREATE FUNCTION preserve_social_create_reservation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF ROW(NEW.post_id,NEW.community_id,NEW.scope_id,NEW.owner_principal_id,NEW.owner_user_id,NEW.create_key,NEW.create_digest,NEW.create_draft,NEW.create_source,NEW.create_at) IS DISTINCT FROM ROW(OLD.post_id,OLD.community_id,OLD.scope_id,OLD.owner_principal_id,OLD.owner_user_id,OLD.create_key,OLD.create_digest,OLD.create_draft,OLD.create_source,OLD.create_at) THEN RAISE EXCEPTION 'Social creation source cannot be rebound' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER preserve_social_create_reservation BEFORE UPDATE ON community_social_thumbnail_asset_targets FOR EACH ROW EXECUTE FUNCTION preserve_social_create_reservation();
CREATE OR REPLACE FUNCTION preserve_domain_media_floor() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' OR NEW.purpose IS DISTINCT FROM OLD.purpose OR (OLD.mode<>'legacy' AND NEW.mode='legacy') THEN RAISE EXCEPTION 'Media storage floor cannot rewind' USING ERRCODE='23514';END IF;
 IF NEW.purpose NOT IN ('member.service-cover','community.event-banner','community.event-video','community.social-thumbnail','skill.submission-image','community.event-highlight') AND NEW.mode<>'legacy' THEN RAISE EXCEPTION 'Domain media adapter is not installed' USING ERRCODE='23514';END IF;
 IF NEW.mode='r2_only' AND ((NEW.purpose='community.social-thumbnail' AND EXISTS(SELECT 1 FROM community_social_post_thumbnails WHERE storage_source='legacy' OR image_bytes IS NOT NULL)) OR (NEW.purpose='community.event-highlight' AND EXISTS(SELECT 1 FROM community_event_highlights h JOIN community_event_highlight_images i USING(media_id) WHERE h.storage_source='legacy' OR i.bytes IS NOT NULL)) OR (NEW.purpose='skill.submission-image' AND EXISTS(SELECT 1 FROM skill_submissions WHERE image_bytes IS NOT NULL)) OR (NEW.purpose='community.event-banner' AND EXISTS(SELECT 1 FROM community_event_banners WHERE storage_source='legacy' OR image_bytes IS NOT NULL)) OR (NEW.purpose='member.service-cover' AND EXISTS(SELECT 1 FROM member_service_covers WHERE storage_source='legacy' OR image_bytes IS NOT NULL)) OR (NEW.purpose='community.event-video' AND EXISTS(SELECT 1 FROM community_event_videos WHERE storage_source='legacy' OR media_bytes IS NOT NULL))) THEN RAISE EXCEPTION 'Legacy media sources remain' USING ERRCODE='23514';END IF;RETURN NEW;END $$;

CREATE OR REPLACE FUNCTION fence_social_thumbnail_writer() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE mode_value text;BEGIN
 SELECT mode INTO STRICT mode_value FROM domain_media_storage_policy WHERE purpose='community.social-thumbnail' FOR SHARE;
 IF NEW.storage_source='asset' AND mode_value='legacy' OR NEW.storage_source='legacy' AND mode_value='r2_only' THEN RAISE EXCEPTION 'Thumbnail writer violates the storage floor' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND OLD.storage_source='asset' AND (NEW.storage_source<>'asset' OR NEW.image_bytes IS DISTINCT FROM OLD.image_bytes) THEN RAISE EXCEPTION 'Legacy thumbnail writer is fenced' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
