import { deepFreeze, type TenantDataCatalog } from './catalog-check.js';

/** Tenant purposes come only from pg_get_constraintdef of asset_scope_purpose,
 * the scope_kind = 'tenant' branch. Today that purpose is work.tenant-result.
 * Column lists are the installed attnum order. FORCE is not used (OPEN-14).
 */
export const TENANT_DATA_CATALOG: TenantDataCatalog = deepFreeze({
  catalog_version: "1",
  row_security_force: {
    state: "not_used" as const,
    decision_refs: [
      "OPEN-14",
    ],
    reason: "ENABLE without FORCE. The runtime role is not the table owner, so row security already applies to it. FORCE would also subject the migrator, the reviewed definer functions, and owner-run evidence.",
  },
  exemptions: [
    {
      table: "users",
      dataset_ref: "DC-01",
      reason_code: "platform_native",
      reason: "Platform member account. Not tenant data, and not deleted when a module moves.",
    },
    {
      table: "sessions",
      dataset_ref: "DC-01",
      reason_code: "platform_native",
      reason: "Platform session. Not tenant data. Module export must not read it.",
    },
    {
      table: "principals",
      dataset_ref: "DC-01",
      reason_code: "platform_native",
      reason: "Platform principal mapping. Not tenant data. A tenant package may store only a principal reference.",
    },
    {
      table: "assets",
      dataset_ref: "DC-13",
      reason_code: "asset_maintenance_visible",
      reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
    },
    {
      table: "asset_upload_intents",
      dataset_ref: "DC-13",
      reason_code: "asset_maintenance_visible",
      reason: "Upload intents are read by asset maintenance. Row security would hide live intents from GC and backup. Tenant intent rows are still constrained by target_tenant_id and purpose.",
    },
    {
      table: "asset_objects",
      dataset_ref: "DC-13",
      reason_code: "asset_maintenance_visible",
      reason: "Object inventory must see every byte pointer. An RLS-filtered inventory could delete a live object. Tenant objects are isolated by purpose work.tenant-result and the parent asset scope.",
    },
    {
      table: "resource_scopes",
      dataset_ref: "DC-04",
      reason_code: "scope_identity",
      reason: "Scope identity only. Operator backfill reads every scope row and refuses a row-security-filtered inventory. Tenant payload is not stored here.",
    },
  ],
  datasets: [
    {
      dataset_key: "DC-04",
      catalog_version: "1",
      physical_locations: [
        {
          kind: "table" as const,
          table: "agent_connections",
          columns: [
            "connection_id",
            "runtime_device_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "scope_kind",
            "environment",
            "client_id",
            "state",
            "aggregate_version",
            "issued_at",
            "expires_at",
            "revoked_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "application_installations",
          columns: [
            "installation_id",
            "tenant_id",
            "workspace_id",
            "application_key",
            "release_ref",
            "configuration",
            "configuration_digest",
            "configuration_revision",
            "status",
            "version",
            "created_by_principal_id",
            "created_by_principal_kind",
            "origin_guild_key",
            "provision_operation_id",
            "retained_instance_ids",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "application_installations_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "application_module_links",
          columns: [
            "installation_id",
            "requirement_key",
            "tenant_id",
            "instance_id",
            "binding_selection",
            "version",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "application_module_links_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "bootstrap_nonces",
          columns: [
            "nonce_id",
            "connection_id",
            "runtime_device_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "scope_kind",
            "environment",
            "client_id",
            "connection_version",
            "challenge_key",
            "nonce",
            "issued_at",
            "expires_at",
            "consumed_at",
            "proof_jti",
            "token_jti",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "bootstrap_refresh_families",
          columns: [
            "family_id",
            "connection_id",
            "issued_at",
            "expires_at",
            "current_generation",
            "state",
            "revoked_at",
            "revocation_reason",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "bootstrap_refresh_generations",
          columns: [
            "family_id",
            "generation",
            "parent_generation",
            "handle_hash",
            "handle_wire_hash",
            "issued_at",
            "consumed_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "bootstrap_refresh_families",
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "bootstrap_session_proofs",
          columns: [
            "connection_id",
            "runtime_device_id",
            "operation",
            "proof_jti",
            "accepted_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "broker_credential_vault",
          columns: [
            "credential_id",
            "envelope",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "broker_model_credentials",
              "model_connections",
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "broker_model_credentials",
          columns: [
            "credential_id",
            "model_connection_id",
            "model_version",
            "generation",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "runtime_device_id",
            "connection_id",
            "family_id",
            "environment",
            "client_id",
            "selection",
            "recovery_generation",
            "binding",
            "issued_at",
            "expires_at",
            "state",
            "aggregate_version",
            "terminal_at",
            "replacement_credential_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "model_connections",
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "capacity_ledger",
          columns: [
            "entry_id",
            "tenant_id",
            "operation_id",
            "dimension",
            "delta",
            "kind",
            "source_ref",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "capacity_ledger_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "capacity_reservations",
          columns: [
            "reservation_id",
            "tenant_id",
            "operation_id",
            "dimension",
            "units",
            "policy_revision",
            "state",
            "expires_at",
            "version",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "capacity_reservations_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "credential_ingest_authorizations",
          columns: [
            "authorization_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "original_session_hash",
            "environment",
            "client_id",
            "operation",
            "command_key",
            "command",
            "command_digest",
            "nonce_hash",
            "assertion",
            "model_connection_id",
            "model_version",
            "model_metadata",
            "old_credential_id",
            "old_credential_version",
            "old_credential_generation",
            "old_model_connection_id",
            "old_model_version",
            "recovery_generation",
            "issued_at",
            "expires_at",
            "bootstrap_claimed_at",
            "setup_cookie_hash",
            "setup_csrf_hash",
            "setup_expires_at",
            "submission_claimed_at",
            "write_expires_at",
            "submitted_credential_id",
            "submitted_binding",
            "committed_at",
            "committed_credential_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "credential_ingest_preparations",
          columns: [
            "authorization_id",
            "prepared_at",
            "expires_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "credential_ingest_authorizations",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "deployment_bindings",
          columns: [
            "binding_id",
            "tenant_id",
            "instance_id",
            "mode",
            "environment",
            "endpoint_ref",
            "service_principal_id",
            "contract_ref",
            "state",
            "authority_epoch",
            "version",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "deployment_bindings_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "device_authorizations",
          columns: [
            "authorization_id",
            "environment",
            "client_id",
            "client_display_name",
            "runtime_kind",
            "public_jwk",
            "key_thumbprint",
            "begin_jti",
            "device_code_hash",
            "device_code_wire_hash",
            "user_code_hash",
            "nonce",
            "request_digest",
            "issued_at",
            "expires_at",
            "state",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "scope_kind",
            "challenge_id",
            "decided_at",
            "consumed_at",
            "connection_id",
            "bootstrap_nonce_id",
            "token_jti",
            "poll_interval",
            "last_poll_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "device_poll_proofs",
          columns: [
            "authorization_id",
            "proof_jti",
            "accepted_at",
            "exchange_challenge_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "device_authorizations",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_machine_authorizations",
          columns: [
            "authorization_id",
            "challenge_id",
            "step_id",
            "attempt_id",
            "run_id",
            "grant_id",
            "approval_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "environment",
            "client_id",
            "runtime_device_id",
            "runtime_version",
            "connection_id",
            "connection_version",
            "family_id",
            "key_thumbprint",
            "grant_version",
            "approval_version",
            "binding_sha256",
            "recovery_generation",
            "execute_jti",
            "evidence_jti",
            "issued_at",
            "expires_at",
            "evidence_expires_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_machine_broker_authorizations",
          columns: [
            "authorization_id",
            "machine_authorization_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "environment",
            "client_id",
            "runtime_device_id",
            "connection_id",
            "family_id",
            "grant_id",
            "approval_id",
            "step_id",
            "attempt_id",
            "credential_id",
            "credential_generation",
            "model_connection_id",
            "model_version",
            "recovery_generation",
            "command_key",
            "command",
            "command_digest",
            "proof_digest",
            "access_token_digest",
            "expected_version",
            "nonce_hash",
            "assertion",
            "issued_at",
            "expires_at",
            "consumed_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_machine_challenges",
          columns: [
            "challenge_id",
            "runtime_device_id",
            "connection_id",
            "family_id",
            "nonce_hash",
            "request_sha256",
            "issued_at",
            "expires_at",
            "consumed_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_machine_dispatch_evidence",
          columns: [
            "authorization_id",
            "profile",
            "outcome",
            "reason",
            "evidence_sha256",
            "received_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "execution_machine_authorizations",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_machine_model_pins",
          columns: [
            "authorization_id",
            "profile",
            "evidence_origin",
            "credential_id",
            "credential_generation",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "execution_machine_authorizations",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_machine_proofs",
          columns: [
            "runtime_device_id",
            "connection_id",
            "family_id",
            "proof_jti",
            "operation",
            "challenge_id",
            "authorization_id",
            "request_sha256",
            "accepted_at",
            "valid_until",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "model_connections",
          columns: [
            "model_connection_id",
            "runtime_device_id",
            "connection_id",
            "family_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "environment",
            "client_id",
            "selection",
            "creation_key",
            "state",
            "aggregate_version",
            "created_at",
            "revoked_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "agent_connections",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "model_export_approvals",
          columns: [
            "approval_id",
            "grant_id",
            "run_id",
            "work_item_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "environment",
            "client_id",
            "selection",
            "input_work_version",
            "grant_version",
            "base_run_version",
            "policy_id",
            "export_policy_revision",
            "persistence_policy_revision",
            "context_sha256",
            "input_byte_size",
            "max_output_tokens",
            "consent",
            "state",
            "aggregate_version",
            "creation_key",
            "issued_at",
            "expires_at",
            "revoked_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "model_inference_export_policy",
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "model_inference_export_policy",
          columns: [
            "policy_id",
            "scope_id",
            "owner_principal_id",
            "scope_kind",
            "purpose",
            "environment",
            "client_id",
            "selection",
            "revision",
            "export_allowed",
            "max_prompt_bytes",
            "max_output_tokens",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "module_dependencies",
          columns: [
            "dependency_id",
            "tenant_id",
            "caller_instance_id",
            "requirement_key",
            "capability",
            "provider_instance_id",
            "sharing_policy_ref",
            "version",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "module_dependencies_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "module_instances",
          columns: [
            "instance_id",
            "tenant_id",
            "module_key",
            "application_release_ref",
            "data_schema_version",
            "contract_ref",
            "status",
            "binding_id",
            "authority_epoch",
            "version",
            "configuration_revision",
            "provision_operation_id",
            "created_by_principal_id",
            "created_by_principal_kind",
            "origin_guild_key",
            "created_at",
            "module_release_ref",
            "suspension_operation_id",
            "archive_operation_id",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "module_instances_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "module_launch_plan_consumptions",
          columns: [
            "tenant_id",
            "plan_id",
            "operation_id",
            "consumed_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "module_launch_plan_consumptions_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "module_launch_plans",
          columns: [
            "plan_id",
            "tenant_id",
            "actor_principal_id",
            "actor_principal_kind",
            "guild_key",
            "application_key",
            "release_ref",
            "workspace_id",
            "installation_choice",
            "existing_installation_id",
            "configuration",
            "configuration_digest",
            "selection_digest",
            "dependency_versions",
            "warnings",
            "capacity_delta",
            "policy_revision",
            "expires_at",
            "version",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "module_launch_plans_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "private_work_persistence_policy",
          columns: [
            "scope_id",
            "purpose",
            "owner_principal_id",
            "scope_kind",
            "revision",
            "persistence_allowed",
            "retained_byte_limit",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "resource_scopes",
          columns: [
            "scope_id",
            "kind",
            "owner_principal_id",
            "owner_principal_kind",
            "community_ref",
            "status",
            "created_at",
            "site_shop_ref",
            "service_principal_id",
            "service_principal_kind",
            "tenant_ref",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_ref",
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "scope_identity",
            reason: "Scope identity only. Operator backfill reads every scope row and refuses a row-security-filtered inventory. Tenant payload is not stored here.",
          },
        },
        {
          kind: "table" as const,
          table: "runtime_registration_challenges",
          columns: [
            "challenge_id",
            "runtime_device_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "scope_kind",
            "environment",
            "begin_key",
            "public_jwk",
            "key_thumbprint",
            "nonce",
            "issued_at",
            "expires_at",
            "consumed_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "runtime_registrations",
          columns: [
            "runtime_device_id",
            "challenge_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "scope_kind",
            "environment",
            "public_jwk",
            "key_thumbprint",
            "state",
            "aggregate_version",
            "enrolled_at",
            "revoked_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "resource_scopes",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "fk_chain_not_tenant_private",
            reason: "Detected only because a foreign key reaches a tenant-bearing or mixed table. The row is not tenant-private. Row security stays off so platform, personal and machine flows are not filtered.",
          },
        },
        {
          kind: "table" as const,
          table: "tenant_authority_audit",
          columns: [
            "event_id",
            "tenant_id",
            "actor_principal_id",
            "actor_principal_kind",
            "action",
            "target_principal_id",
            "old_revision",
            "new_revision",
            "reason_code",
            "proof_ref",
            "occurred_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_authority_audit_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_capacity_policies",
          columns: [
            "policy_id",
            "revision",
            "tenant_id",
            "plan_ref",
            "max_active_instances",
            "max_instances_per_module",
            "max_concurrent_provisions",
            "max_work_items",
            "max_retained_bytes",
            "max_concurrent_jobs",
            "max_model_budget",
            "status",
            "policy_lock",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_capacity_policies_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_high_risk_verifications",
          columns: [
            "verification_id",
            "user_id",
            "principal_id",
            "principal_kind",
            "session_hash",
            "tenant_id",
            "purpose",
            "verified_at",
            "expires_at",
            "consumed_at",
            "consumed_by",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_high_risk_verifications_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_invitations",
          columns: [
            "invitation_id",
            "tenant_id",
            "invitee_principal_id",
            "invitee_principal_kind",
            "role",
            "instance_capabilities",
            "expires_at",
            "state",
            "version",
            "created_by_principal_id",
            "created_by_principal_kind",
            "revoked_reason",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_invitations_invitee_expire",
              "tenant_invitations_invitee_read",
              "tenant_invitations_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_memberships",
          columns: [
            "tenant_id",
            "principal_id",
            "principal_kind",
            "role",
            "status",
            "version",
            "accepted_at",
            "revoked_at",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_memberships_principal_read",
              "tenant_memberships_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_ownership_transfers",
          columns: [
            "transfer_id",
            "tenant_id",
            "from_principal_id",
            "from_principal_kind",
            "to_principal_id",
            "to_principal_kind",
            "from_role_after",
            "state",
            "expires_at",
            "tenant_authorization_revision",
            "version",
            "reason",
            "created_at",
            "decided_at",
            "accepted_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_ownership_transfers_principal_invalidate",
              "tenant_ownership_transfers_recipient_expire",
              "tenant_ownership_transfers_recipient_read",
              "tenant_ownership_transfers_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_recovery_cases",
          columns: [
            "case_id",
            "tenant_id",
            "state",
            "proposed_owner_principal_id",
            "proposed_owner_principal_kind",
            "approved_scope",
            "expires_at",
            "version",
            "audit_ref",
            "reason",
            "evidence_ref",
            "opened_by_admin_id",
            "approved_by_admin_id",
            "executed_by_admin_id",
            "recipient_accepted_at",
            "closed_reason",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_recovery_cases_platform_admin_read",
              "tenant_recovery_cases_proposed_owner_read",
              "tenant_recovery_cases_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenants",
          columns: [
            "tenant_id",
            "community_id",
            "display_name",
            "public_slug",
            "status",
            "version",
            "authorization_revision",
            "created_by_principal_id",
            "created_by_principal_kind",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenants_counterparty_read",
              "tenants_principal_read",
              "tenants_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "workspace_module_bindings",
          columns: [
            "tenant_id",
            "workspace_id",
            "entry_capability",
            "instance_id",
            "version",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "workspace_module_bindings_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "workspaces",
          columns: [
            "workspace_id",
            "tenant_id",
            "name",
            "status",
            "version",
            "is_default",
            "created_at",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "workspaces_principal_read",
              "workspaces_tenant",
            ],
          },
        },
      ],
      classification: "tenant-control-plane",
      authoritative_module: "tenant-workspaces",
      tenant_resolution: "direct tenant_id on tenant, membership, invitation, workspace, audit, instance, binding, capacity, verification, ownership-transfer, recovery, installation, module-link, dependency, launch-plan, plan-consumption, capacity-reservation and capacity-ledger rows; resource_scopes uses tenant_ref",
      identity_keys: [
        "tenant_id",
        "workspace_id",
        "instance_id",
        "principal_id",
        "scope_id",
      ],
      readable_by: [
        "active tenant member for rows of that tenant",
        "invitee for own invitation and the named tenant before membership",
        "transfer recipient for own transfer rows and that tenant display name when no tenant is bound",
        "proposed recovery owner for own recovery rows and that tenant display name when no tenant is bound",
        "platform admin with an unrevoked recovery capability for recovery cases while no tenant is bound and freedom.platform_admin_id is set",
      ],
      writable_by: [
        "tenant owner for authority changes",
        "module-registry for instance, binding, installation, link, dependency, launch-plan, plan-consumption and capacity rows",
        "invitee for accept or decline of own invitation",
        "transfer recipient for expiry of own overdue pending transfer when no tenant is bound",
        "the bound principal for invalidation of own pending transfers when no tenant is bound",
        "platform admin recovery commands after that case tenant is bound",
      ],
      export_scope: "Stable tenant and instance ids, schema and contract versions, and dependency configuration. Platform authorization is descriptive. Import must not revive a grant.",
      dependency_refs: [
        "module-registry",
        "resource-scopes",
      ],
      sensitivity: "tenant-private control plane; resource_scopes also holds personal, community and site scope identity",
      sharing_purpose: "Name the tenant, its workspace, its module binding and its authority revision to the members who may see them.",
      field_allowlist: {
        state: "undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      central_retention: {
        state: "policy_undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      derived_copies: [],
      copies_note: "No cache, search index, summary, embedding or notification copy of tenant data is registered. Scoped journal and outbox rows are DC-14 locations, not derived copies of another dataset.",
      deletion_and_restore: "Deletion, restore, tombstones and backup expiry are policy_undecided (OPEN-07). This slice does not delete tenant rows and does not promise that every copy disappears.",
      verification_refs: [
        "T-021",
        "T-024",
      ],
    },
    {
      dataset_key: "DC-06",
      catalog_version: "1",
      physical_locations: [
        {
          kind: "table" as const,
          table: "contributions",
          columns: [
            "contribution_id",
            "claim_id",
            "user_id",
            "community_id",
            "work_item_id",
            "decision_id",
            "title",
            "summary",
            "artifact_ref",
            "official",
            "accepted_at",
            "work_mode",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_attempts",
          columns: [
            "attempt_id",
            "run_id",
            "work_item_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "grant_id",
            "attempt_number",
            "grant_snapshot",
            "state",
            "blockers",
            "created_at",
            "activation_binding",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "execution_grants",
              "execution_runs",
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_grants",
          columns: [
            "grant_id",
            "run_id",
            "work_item_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "runtime_device_id",
            "runtime_version",
            "connection_id",
            "connection_version",
            "family_id",
            "environment",
            "client_id",
            "model_connection_id",
            "model_version",
            "selection",
            "input_work_version",
            "run_version",
            "task_lease_epoch",
            "control_epoch",
            "persistence_policy_revision",
            "purpose",
            "consent",
            "creation_key",
            "state",
            "aggregate_version",
            "created_at",
            "expires_at",
            "revoked_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "execution_runs",
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "execution_runs",
          columns: [
            "run_id",
            "work_item_id",
            "work_mode",
            "scope_id",
            "owner_principal_id",
            "owner_user_id",
            "input_work_version",
            "persistence_policy_revision",
            "state",
            "aggregate_version",
            "task_lease_epoch",
            "control_epoch",
            "created_at",
            "current_attempt_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "model_broker_authorizations",
          columns: [
            "authorization_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "original_session_hash",
            "environment",
            "client_id",
            "operation",
            "command_key",
            "command",
            "command_digest",
            "nonce_hash",
            "assertion",
            "approval_id",
            "step_id",
            "expected_primary_version",
            "expected_run_version",
            "run_id",
            "work_item_id",
            "grant_id",
            "credential_id",
            "credential_generation",
            "model_connection_id",
            "model_version",
            "recovery_generation",
            "issued_at",
            "expires_at",
            "accepted_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "model_text_steps",
          columns: [
            "step_id",
            "attempt_id",
            "intent_id",
            "approval_id",
            "run_id",
            "work_item_id",
            "owner_user_id",
            "owner_principal_id",
            "scope_id",
            "environment",
            "client_id",
            "binding",
            "verified_binding",
            "evidence_origin",
            "activated_run_version",
            "task_lease_epoch",
            "control_epoch",
            "context_sha256",
            "input_byte_size",
            "max_output_tokens",
            "state",
            "aggregate_version",
            "usage_status",
            "reservation_held",
            "creation_key",
            "created_at",
            "lease_expires_at",
            "permit_expires_at",
            "dispatched_at",
            "observation",
            "observed_at",
            "result_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "private_model_work_results",
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "private_model_work_results",
          columns: [
            "result_id",
            "intent_id",
            "step_id",
            "work_item_id",
            "work_mode",
            "scope_id",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "representation_id",
            "policy_revision",
            "purpose",
            "provenance",
            "revision",
            "work_version",
            "attempt_id",
            "dispatch_intent_id",
            "model_binding",
            "observation",
            "evidence_origin",
            "created_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "private_work_result_index",
          columns: [
            "result_id",
            "provenance",
            "work_item_id",
            "scope_id",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "work_version",
            "revision",
            "human_result_id",
            "model_result_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "private_model_work_results",
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "private_work_result_targets",
          columns: [
            "work_item_id",
            "work_mode",
            "scope_id",
            "owner_principal_id",
            "owner_user_id",
            "result_id",
            "asset_id",
            "linked_at_work_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "private_work_results",
          columns: [
            "result_id",
            "intent_id",
            "work_item_id",
            "work_mode",
            "scope_id",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "representation_id",
            "policy_revision",
            "purpose",
            "provenance",
            "revision",
            "work_version",
            "created_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "submissions",
          columns: [
            "submission_id",
            "claim_id",
            "revision",
            "summary",
            "artifact_ref",
            "sha256",
            "created_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_claims",
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "tenant_work_result_targets",
          columns: [
            "work_item_id",
            "work_mode",
            "scope_id",
            "tenant_id",
            "instance_id",
            "owner_principal_id",
            "owner_user_id",
            "result_id",
            "asset_id",
            "linked_at_work_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_work_result_targets_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "tenant_work_results",
          columns: [
            "result_id",
            "intent_id",
            "work_item_id",
            "work_mode",
            "scope_id",
            "tenant_id",
            "instance_id",
            "workspace_id",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "representation_id",
            "policy_revision",
            "purpose",
            "provenance",
            "display_name",
            "content_type",
            "byte_size",
            "content_sha256",
            "revision",
            "work_version",
            "created_by_principal_id",
            "created_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "tenant_work_results_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "work_benefit_observations",
          columns: [
            "observation_id",
            "community_id",
            "work_item_ref",
            "reporter_principal_ref",
            "work_claim_ref",
            "role",
            "observation_revision",
            "supersedes_observation_ref",
            "report",
            "recorded_at",
            "work_mode",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "work_claims",
          columns: [
            "claim_id",
            "work_item_id",
            "claimant_ref",
            "acting_profession_membership_ref",
            "state",
            "aggregate_version",
            "terms_revision",
            "terms_sha256",
            "terms_snapshot",
            "feedback",
            "created_at",
            "work_mode",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "work_decisions",
          columns: [
            "decision_id",
            "claim_id",
            "submission_id",
            "reviewer_ref",
            "decision",
            "feedback",
            "submission_sha256",
            "official",
            "created_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_claims",
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
        {
          kind: "table" as const,
          table: "work_items",
          columns: [
            "work_item_id",
            "community_id",
            "owner_ref",
            "title",
            "objective",
            "acceptance_criteria",
            "gain",
            "state",
            "aggregate_version",
            "participation_terms",
            "participation_terms_revision",
            "participation_terms_sha256",
            "claim_window_expires_at",
            "due_at",
            "created_at",
            "work_mode",
            "scope_id",
            "owner_principal_id",
            "scope_kind",
            "tenant_id",
            "instance_id",
            "workspace_id",
            "created_by_principal_id",
            "created_by_principal_kind",
            "progress",
            "updated_at",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "work_items_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "work_review_routes",
          columns: [
            "work_item_id",
            "reviewer_ref",
            "accepted_at",
            "valid_until",
            "revoked_at",
            "work_mode",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "work_items",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "mixed_work_child",
            reason: "Personal and community work share this table, or the row only references work. work_items already hides tenant rows when no tenant is bound. This table is outside the enabled set.",
          },
        },
      ],
      classification: "mixed-work",
      authoritative_module: "work",
      tenant_resolution: "direct tenant_id on tenant work, results and targets; personal and community rows keep tenant_id NULL; other tables resolve by foreign key to work_items",
      identity_keys: [
        "work_item_id",
        "result_id",
        "tenant_id",
      ],
      readable_by: [
        "work ACL plus the tenant capability",
        "no guild-leader private privilege",
      ],
      writable_by: [
        "work domain for the bound tenant or the personal owner",
      ],
      export_scope: "Work title, objective, progress, historical results, and attachment refs. Community claim, review and contribution rows are references, not a second copy of private text.",
      dependency_refs: [
        "tenant-workspaces",
        "module-registry",
        "asset-lifecycle",
        "private-results",
      ],
      sensitivity: "tenant-private work text when tenant_id is set; personal and community rows in the same tables are not tenant data",
      sharing_purpose: "Show a member the work and result they are allowed to open inside one tenant.",
      field_allowlist: {
        state: "undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      central_retention: {
        state: "policy_undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      derived_copies: [],
      copies_note: "No cache, search index, summary, embedding or notification copy of tenant data is registered. Scoped journal and outbox rows are DC-14 locations, not derived copies of another dataset.",
      deletion_and_restore: "Deletion, restore, tombstones and backup expiry are policy_undecided (OPEN-07). This slice does not delete tenant rows and does not promise that every copy disappears.",
      verification_refs: [
        "T-021",
        "T-024",
      ],
    },
    {
      dataset_key: "DC-13",
      catalog_version: "1",
      physical_locations: [
        {
          kind: "table" as const,
          table: "asset_backup_pins",
          columns: [
            "capture_id",
            "asset_id",
            "scope_id",
            "representation_id",
            "policy_revision",
            "byte_size",
            "content_sha256",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "asset_deletion_tombstones",
          columns: [
            "asset_id",
            "policy_revision",
            "fenced_at",
            "attempt",
            "lease_token",
            "lease_expires_at",
            "observation",
            "observed_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "asset_object_write_effects",
          columns: [
            "effect_id",
            "intent_id",
            "asset_id",
            "intent_fence",
            "settlement_nonce",
            "state",
            "begun_at",
            "finished_at",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "asset_upload_intents",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "asset_objects",
          columns: [
            "asset_id",
            "scope_id",
            "representation_id",
            "variant",
            "logical_store",
            "object_key",
            "content_type",
            "byte_size",
            "content_sha256",
            "transform_version",
            "policy_revision",
            "verified_at",
            "purpose",
            "profile_id",
          ],
          tenant_resolution: {
            kind: "asset_purpose" as const,
            purposes: [
              "work.tenant-result",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "asset_upload_intents",
          columns: [
            "intent_id",
            "asset_id",
            "representation_id",
            "scope_id",
            "owner_principal_id",
            "target_user_id",
            "purpose",
            "policy_revision",
            "prepare_key",
            "request_digest",
            "source_content_type",
            "source_byte_size",
            "source_sha256",
            "expected_version",
            "reserved_bytes",
            "state",
            "fence",
            "lease_token",
            "lease_expires_at",
            "expires_at",
            "created_at",
            "finalized_at",
            "target_kind",
            "target_work_id",
            "avatar_target_user_id",
            "work_mode",
            "target_service_id",
            "target_event_id",
            "target_community_id",
            "source_orientation",
            "target_video_event_id",
            "target_post_id",
            "target_submission_id",
            "target_highlight_media_id",
            "target_tenant_id",
            "display_name",
            "tenant_work_mode",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "target_tenant_id",
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "assets",
          columns: [
            "asset_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "purpose",
            "policy_revision",
            "representation_id",
            "state",
            "created_at",
            "ready_at",
            "retired_at",
            "deletion_fence",
            "community_ref",
            "personal_owner_principal_id",
            "write_effect_coverage",
            "tenant_ref",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_ref",
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "community_event_banner_asset_targets",
          columns: [
            "event_id",
            "community_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "linked_at_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "table" as const,
          table: "community_event_highlight_asset_targets",
          columns: [
            "media_id",
            "event_id",
            "community_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "source_digest",
            "image_asset_id",
            "thumb_asset_id",
            "published_at",
            "published_media_id",
            "purpose",
            "asset_state",
            "image_variant",
            "thumb_variant",
            "image_profile",
            "thumb_profile",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "table" as const,
          table: "community_event_video_asset_targets",
          columns: [
            "event_id",
            "community_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "linked_at_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "table" as const,
          table: "community_social_thumbnail_asset_targets",
          columns: [
            "post_id",
            "community_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "linked_at_version",
            "purpose",
            "asset_state",
            "create_key",
            "create_digest",
            "create_draft",
            "create_source",
            "create_at",
            "domain_post_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "table" as const,
          table: "media_backfill_items",
          columns: [
            "job_id",
            "service_id",
            "intent_id",
            "asset_id",
            "source_version",
            "source_size",
            "source_sha256",
            "source_binding_sha256",
            "outcome",
            "created_at",
            "finished_at",
            "event_id",
            "source_content_type",
            "target_id",
            "purpose",
            "banner_event_id",
            "post_id",
            "submission_id",
            "highlight_media_id",
            "variant",
            "avatar_user_id",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "asset_upload_intents",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "asset_maintenance_visible",
            reason: "Maintenance, backup and deletion inventory must see every asset row. Tenant bytes stay on scoped queries, composite foreign keys, asset_scope_purpose, and the purpose allow-list that never GC-claims work.tenant-result.",
          },
        },
        {
          kind: "table" as const,
          table: "member_avatar_asset_targets",
          columns: [
            "user_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "asset_id",
            "linked_at_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "table" as const,
          table: "member_service_cover_asset_targets",
          columns: [
            "service_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "linked_at_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "table" as const,
          table: "skill_submission_image_asset_targets",
          columns: [
            "submission_id",
            "community_id",
            "scope_id",
            "scope_kind",
            "owner_principal_id",
            "owner_user_id",
            "asset_id",
            "linked_at_version",
            "purpose",
            "asset_state",
          ],
          tenant_resolution: {
            kind: "fk_chain" as const,
            via: [
              "assets",
            ],
          },
          isolation: {
            rls: "exempt" as const,
            reason_code: "non_tenant_sidecar",
            reason: "Personal or community asset sidecar with no tenant column. It is listed because a foreign key reaches an asset or scope row. Row security stays off so those flows still see every row.",
          },
        },
        {
          kind: "object" as const,
          purpose: "work.tenant-result",
          target_kind: "work.tenant-result",
          variants: [
            "draft",
          ],
        },
      ],
      classification: "attachment",
      authoritative_module: "asset-lifecycle",
      tenant_resolution: "assets.tenant_ref, asset_upload_intents.target_tenant_id, and asset purpose work.tenant-result on asset_objects; other asset rows resolve by foreign key to assets",
      identity_keys: [
        "asset_id",
        "intent_id",
        "representation_id",
      ],
      readable_by: [
        "domain and tenant check on download, variant and export",
        "maintenance sees every asset row because row security is off",
      ],
      writable_by: [
        "asset lifecycle engine for the owning scope",
      ],
      export_scope: "Logical asset id, immutable representation, sha256, byte size, content type, source revision, and the bytes. A pointer delete is not a byte delete.",
      dependency_refs: [
        "work",
        "tenant-workspaces",
      ],
      sensitivity: "tenant-private bytes for purpose work.tenant-result; other purposes are personal or community",
      sharing_purpose: "Deliver one tenant result attachment to a member who can read that work.",
      field_allowlist: {
        state: "undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      central_retention: {
        state: "policy_undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      derived_copies: [],
      copies_note: "No cache, search index, summary, embedding or notification copy of tenant data is registered. Scoped journal and outbox rows are DC-14 locations, not derived copies of another dataset.",
      deletion_and_restore: "Deletion, restore, tombstones and backup expiry are policy_undecided (OPEN-07). This slice does not delete tenant rows and does not promise that every copy disappears.",
      verification_refs: [
        "T-021",
        "T-024",
      ],
    },
    {
      dataset_key: "DC-14",
      catalog_version: "1",
      physical_locations: [
        {
          kind: "table" as const,
          table: "module_provision_operations",
          columns: [
            "operation_id",
            "tenant_id",
            "installation_id",
            "actor_principal_id",
            "actor_principal_kind",
            "operation_kind",
            "state",
            "request_digest",
            "plan_id",
            "authorization_revision",
            "policy_revision",
            "version",
            "accepted_at",
            "updated_at",
            "cancel_requested_at",
            "terminal_problem",
            "instance_id",
            "reason",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "module_provision_operations_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "module_provision_steps",
          columns: [
            "operation_id",
            "step_key",
            "ordinal",
            "instance_id",
            "tenant_id",
            "provider_effect_key",
            "state",
            "attempt_count",
            "next_attempt_at",
            "lease_fence",
            "lease_expires_at",
            "evidence_ref",
            "result_digest",
            "expected_authority_epoch",
            "problem",
          ],
          tenant_resolution: {
            kind: "direct" as const,
            column: "tenant_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "module_provision_steps_tenant",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "scoped_command_receipts",
          columns: [
            "principal_id",
            "principal_kind",
            "authn_kind",
            "scope_id",
            "scope_kind",
            "personal_owner_principal_id",
            "operation",
            "idempotency_key",
            "target_kind",
            "target_id",
            "request_sha256",
            "response",
            "created_at",
            "execution_authorization_id",
            "execution_attempt_id",
            "execution_grant_id",
            "execution_runtime_device_id",
            "execution_connection_id",
            "site_service_principal_id",
          ],
          tenant_resolution: {
            kind: "scope" as const,
            scope_kind_column: "scope_kind",
            scope_id_column: "scope_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "scoped_command_receipts_tenant_scope",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "scoped_outbox",
          columns: [
            "event_id",
            "transition_id",
            "scope_id",
            "scope_kind",
            "event_type",
            "payload",
            "created_at",
          ],
          tenant_resolution: {
            kind: "scope" as const,
            scope_kind_column: "scope_kind",
            scope_id_column: "scope_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "scoped_outbox_tenant_scope",
            ],
          },
        },
        {
          kind: "table" as const,
          table: "scoped_transition_journal",
          columns: [
            "transition_id",
            "scope_id",
            "scope_kind",
            "principal_id",
            "principal_kind",
            "personal_owner_principal_id",
            "authn_kind",
            "aggregate_type",
            "aggregate_id",
            "aggregate_version",
            "operation",
            "data",
            "created_at",
            "execution_authorization_id",
            "execution_attempt_id",
            "execution_grant_id",
            "execution_runtime_device_id",
            "execution_connection_id",
            "site_service_principal_id",
          ],
          tenant_resolution: {
            kind: "scope" as const,
            scope_kind_column: "scope_kind",
            scope_id_column: "scope_id",
          },
          isolation: {
            rls: "enabled" as const,
            policies: [
              "scoped_transition_journal_tenant_scope",
            ],
          },
        },
      ],
      classification: "operation-record",
      authoritative_module: "scoped-commands",
      tenant_resolution: "direct tenant_id on module provision operations and steps; scope_kind tenant plus scope_id on receipts, journal and outbox; personal, community and site rows stay visible",
      identity_keys: [
        "principal_id",
        "authn_kind",
        "scope_id",
        "operation",
        "idempotency_key",
        "transition_id",
        "operation_id",
      ],
      readable_by: [
        "the same target read right that applied when the operation was admitted",
        "a tenant member with module.operation.read for that tenant's provision operations and steps",
      ],
      writable_by: [
        "the scoped command adapter inside the admitting transaction",
        "the module-registry executor for provision operations and steps of the bound tenant",
      ],
      export_scope: "Admitted operation and receipt summary, plus unsent outbox continuation. The idempotency key is not a login credential.",
      dependency_refs: [
        "tenant-workspaces",
        "work",
        "command-core",
        "module-registry",
      ],
      sensitivity: "tenant-private when scope_kind is tenant; provision operations and steps are tenant-private; other scope kinds are not tenant data",
      sharing_purpose: "Replay an admitted command, continue an unsent event for the same scope, and settle an admitted module provision.",
      field_allowlist: {
        state: "undecided" as const,
        decision_refs: [
          "OPEN-07",
        ],
      },
      central_retention: {
        state: "policy_undecided" as const,
        decision_refs: [
          "OPEN-07",
          "OPEN-05",
        ],
      },
      derived_copies: [],
      copies_note: "No cache, search index, summary, embedding or notification copy of tenant data is registered. Scoped journal and outbox rows are DC-14 locations, not derived copies of another dataset.",
      deletion_and_restore: "Receipt body cleanup and the dedup marker are separate. Retention is policy_undecided (OPEN-07, OPEN-05). A minimum replay guard lasts until the namespace is retired. This slice does not delete receipt bodies.",
      verification_refs: [
        "T-021",
        "T-024",
      ],
    },
  ],
});
