export type DevelopmentPage={id:string;title:string;purpose:string;source_paths:string[];related_repositories:string[];first_task:string;checks:string[];boundaries:string[]};
const page=(id:string,title:string,purpose:string,source_paths:string[],related_repositories:string[],first_task:string,checks:string[],boundaries:string[]=[]):DevelopmentPage=>({id,title,purpose,source_paths,related_repositories,first_task,checks:checks.some(command=>command.includes('playwright'))&&!checks.includes('npm run build')?['npm run build',...checks]:checks,boundaries});
export const developmentPages:DevelopmentPage[]=[
 page('home','會員首頁','呈現會員目前方向、主要公會與下一個可自行選擇的行動。',['apps/portal-web/src/modules/MemberHome.tsx','modules/opportunity-project-work/work.ts'],[],'改善一項首頁提示，保留目前定位及工作事實的來源。',['npm run typecheck','npx playwright test tests/e2e/journeys.spec.ts'],['不把接受工作數當成收入、總分或已證明的實益。']),
 page('registration','註冊與登入','一個登入信箱、密碼、暱稱；聯絡可見範圍在會員資料設定。',['apps/portal-web/src/App.tsx','modules/identity-membership/members.ts','modules/identity-membership/service.ts'],[],'針對登入或新手流程重現一個問題，新增會失敗的行為測試後修正。',['npx tsx --test tests/runtime/identity-member.test.ts','npx playwright test tests/e2e/onboarding-members.spec.ts'],['一般註冊不因 email 文字相符而獲得管理權。','不要把登入、定位改成更多必填關卡。']),
 page('onboarding','新人定位','先偏好與情境，再選能力與裝備；本人確認主力公會，領取技能書。',['apps/portal-web/src/modules/Onboarding.tsx','apps/portal-web/src/modules/CapabilityTree.tsx','modules/positioning/assessment.ts','modules/positioning/onboarding.ts'],[],'改善一題說明或一項分類，檢查手機收合、既有草稿與三項精選能力。',['npx tsx --test tests/runtime/onboarding.test.ts','npx playwright test tests/e2e/onboarding-members.spec.ts'],['新會員完成定位前維持伺服器存取限制。','能力與裝備可略過；私人補充不得公開或暗中加分。']),
 page('account','我的名片','精簡呈現定位與主力公會，獨立管理每筆聯絡方式、社群帳號和頻道。',['apps/portal-web/src/modules/Membership.tsx','apps/portal-web/src/modules/MemberSocialLinks.tsx','apps/platform-api/src/routes/members.ts','modules/identity-membership/members.ts','modules/identity-membership/social-links.ts','docs/development/member-social-links.md'],[],'改善一筆社群連結的編輯；核對同平台多筆、版本衝突、好友／公會／小隊可見範圍及撤銷。',['npx tsx --test tests/runtime/identity-member.test.ts tests/runtime/social-links.test.ts','npx playwright test tests/e2e/social-links.spec.ts'],['不得把 login email、私人聯絡方式或社群連結加入公開開發索引。','每筆連結獨立寫入，不整包覆寫；自填網址不是帳號擁有權證明。']),
 page('members','工坊夥伴','依暱稱、定位與公會尋找夥伴，使用精簡名片與伺服器分頁。',['apps/portal-web/src/modules/Membership.tsx','apps/portal-web/src/modules/MemberSocialLinks.tsx','apps/platform-api/src/routes/members.ts','modules/identity-membership/members.ts','modules/identity-membership/social-links.ts','docs/development/member-social-links.md'],[],'改善一項名冊搜尋或篩選；社群連結需先依當下關係篩選再分頁，不從隱藏聯絡方式反查會員。',['npx tsx --test tests/runtime/identity-member.test.ts tests/runtime/member-directory.test.ts tests/runtime/social-links.test.ts','npx playwright test tests/e2e/member-directory.spec.ts tests/e2e/social-links.spec.ts'],['名聲由可追溯貢獻構成，不指定案子給某人或產生萬用排名。','會員名片與社群連結仍需會員權限；公開 Agent 文件不包含真人資料。']),
 page('positioning','我的定位','檢視與調整方向；重新填寫草稿不覆蓋最後確認的公開定位。',['apps/portal-web/src/modules/PositioningPanels.tsx','modules/positioning/onboarding.ts','modules/positioning/service.ts'],[],'改善一段定位回饋，保留本人選擇公會及已完成者的存取。',['npx tsx --test tests/runtime/onboarding.test.ts tests/runtime/positioning.test.ts']),
 page('guilds','職業公會與技能庫','主力、次要、未加入公會依序呈現；會長在上、最多三位專家各占一列，下接技能庫與成員名冊。',['apps/portal-web/src/modules/PositioningPanels.tsx','apps/portal-web/src/modules/GuildLeadership.tsx','apps/portal-web/src/modules/GuildMembers.tsx','apps/portal-web/src/modules/Membership.tsx','modules/positioning/onboarding.ts','modules/identity-membership/members.ts','modules/community/catalog.ts'],['freedom-skill-registry'],'改善一個公會的成員或技能入口；成員搜尋與分頁須固定 guild_key，會長及專家只按正式會員識別碼標示。',['npx tsx --test tests/runtime/onboarding.test.ts tests/runtime/member-directory.test.ts','npx playwright test tests/e2e/guild-members.spec.ts tests/e2e/onboarding-members.spec.ts'],['會長是職務，專家是獨立標章；各人獨立成列，最多三位專家，不增加能力等級或管理權限。','查看公會成員不自動加入公會，也不擴大聯絡方式和社群連結的可見範圍。']),
 page('squads','小隊集合','跨公會的專案小隊與共同目標互助小隊，成員自主申請與接受。',['apps/portal-web/src/modules/Squads.tsx','modules/identity-membership/members.ts'],['freedom-project-template'],'為一個明確共同目標改善小隊流程，先說清現況與完成條件。',['npx tsx --test tests/runtime/identity-member.test.ts'],['不得自動替人加入、指定案源或保證報酬。']),
 page('supplier','供貨中心','商品與供貨條件在中央平台保存，由供應商核對每次供貨回覆。',['apps/portal-web/src/modules/CommercePanels.tsx','modules/catalog-commerce/service.ts','modules/client-connections/service.ts'],['freedom-supplier-client'],'網站表單改本 repo；自己的供應端 client 改 freedom-supplier-client。',['npx tsx --test tests/runtime/commerce.test.ts tests/runtime/client-connections.test.ts','npx playwright test tests/e2e/commerce-modules.spec.ts'],['客戶端讀取憑證不能作為會員 session，也不能直接改中央 DB。']),
 page('retail','開店與銷售','店主選品、保存條件快照與向供應商確認，商店模板另行 Fork。',['apps/portal-web/src/modules/CommercePanels.tsx','modules/catalog-commerce/service.ts'],['freedom-storefront','pos-pro'],'要改個人商店先 Fork freedom-storefront；要改平台選品規則則提中央 PR。',['npx tsx --test tests/runtime/commerce.test.ts','npx playwright test tests/e2e/commerce-modules.spec.ts'],['平台不保管資金；POS 的功能不代表中央平台已接上結帳或儲值。']),
 page('opensource','開源作品','登錄公開 GitHub 專案、固定來源版本與授權觀察，保留作者及上游。',['apps/portal-web/src/modules/OpenSourcePanels.tsx','modules/opensource-marketing/service.ts','modules/opensource-marketing/github.ts'],['freedom-skill-registry','freedom-project-page'],'改作品入口在中央；改技能宣告在 registry；改專案介紹模板在 project-page。',['npx tsx --test tests/runtime/opensource-marketing.test.ts','npx playwright test tests/e2e/opensource-modules.spec.ts'],['公開、被 Fork、CI 通過都不等同 official、授權已核准或擁有者已驗證。']),
 page('cocreation','一起開發','從共同目標到 GitHub Issue、Agent 工作說明與實際合併 PR 的貢獻來源。',['apps/portal-web/src/modules/CoCreationPanel.tsx','modules/co-creation/service.ts','modules/co-creation/github.ts'],['video-autopilot-kit','freedom-project-template','freedom-agent-kit'],'改善剪輯工具請 Fork video-autopilot-kit；改善共創入口才改 freedom-platform。',['npx tsx --test tests/runtime/co-creation.test.ts','npx playwright test tests/e2e/co-creation.spec.ts'],['GitHub Issues 是任務來源；平台不另建一套虛假認領狀態。','PR 作者帳號不可自動配對成未驗證的會員 slug。']),
 page('marketing','行銷工作室','依可追溯作品或供貨版本寫草稿，保存本人回報的分享紀錄。',['apps/portal-web/src/modules/OpenSourcePanels.tsx','modules/opensource-marketing/service.ts'],['freedom-growth-automation','claude-skill-social-post','typo-studio'],'改文案或渠道模板從 growth repo 開始；來源授權與寫入規則留在中央。',['npx tsx --test tests/runtime/opensource-marketing.test.ts','npx playwright test tests/e2e/opensource-modules.spec.ts'],['草稿和手動分享回報不是 provider 已發布證據；不自動對外發文。']),
 page('workbench','我的工作','自願認領、提交、補件、獨立驗收與實際工作紀錄。',['apps/portal-web/src/App.tsx','modules/opportunity-project-work/work.ts'],['freedom-agent-kit','freedom-project-template'],'重現一個工作狀態轉換，從精確版本與可重試操作測試開始。',['npx tsx --test tests/runtime/flows.test.ts','npx playwright test tests/e2e/journeys.spec.ts'],['沒有可用 reviewer 時不以承諾真人補位維持假綠燈。']),
 page('showcase','一般作品與需求','讓作品、真需求與合作機會可見，會員自主建立合作。',['apps/portal-web/src/App.tsx','modules/opportunity-project-work/business.ts'],['freedom-project-page'],'改善一項作品或需求的表達，維持本人同意與版本可追溯。',['npx tsx --test tests/runtime/flows.test.ts','npx playwright test tests/e2e/journeys.spec.ts']),
 page('engagement','合作紀錄','雙方約定、交付、接受與外部收款的分別回報。',['apps/portal-web/src/App.tsx','modules/opportunity-project-work/business.ts'],[],'改善一項雙方確認步驟，保留對方權限、已確認條款與來源。',['npx tsx --test tests/runtime/flows.test.ts','npx playwright test tests/e2e/journeys.spec.ts'],['自述收款、雙方確認、銀行實收核實分開；平台不代收代付。']),
 page('community','自由工坊社群','品牌、乾淨的社群連結與帶來源時間的公開概況。',['apps/portal-web/src/modules/Community.tsx','modules/community/catalog.ts'],['.github','FreeTWAI-AI.github.io'],'修改社群資料時附來源與日期；社群開放資料的原始來源是 https://github.com/Hao0321/freeworkshop-open-data 。',['npm run typecheck','npm run build'],['社群人數是有日期的概況，不假裝即時或去重統計。']),
 page('admin','平台管理','指定管理員驗證、會員狀態、公會審核、會長與專家任命及操作紀錄。',['apps/portal-web/src/modules/AdminPanel.tsx','apps/portal-web/src/modules/AdminGuildManagement.tsx','modules/platform-admin/access.ts','modules/platform-admin/service.ts','modules/platform-admin/guild-appointment-membership.ts','modules/platform-admin/guild-experts.ts','modules/platform-admin/leadership.ts','docs/development/platform-admin-api.md'],[],'使用隔離資料庫與測試簽章核對一項任命；自動入會、領書與職務必須同交易保存；專家最多三位，並行任命也不能超額，舊操作重播不得重新加入。',['npx tsx --test tests/runtime/admin-access.test.ts tests/runtime/platform-admin.test.ts tests/runtime/admin-guild-candidates.test.ts tests/runtime/guild-experts.test.ts','npx playwright test tests/e2e/admin.spec.ts tests/e2e/admin-guilds.spec.ts'],['不提交管理員私有信箱名單、JWT、OTP、密碼或正式資料。','一般會員登入不能取代管理員信箱驗證。']),
 page('guild-workspace','公會工作室','公會公告、技能書維護與幹部協作；由有權限的會員更新公開計畫。',['apps/portal-web/src/modules/GuildWorkspace.tsx','apps/platform-api/src/routes/guild-workspace.ts','modules/guild-workspace/service.ts'],['freedom-skill-registry'],'改善一項公告或技能書編輯流程，保留指派權限與版本衝突提示。',['npm run typecheck','npm run build','npx tsx --test tests/runtime/guild-workspace.test.ts'],['公會職務不自動授予平台管理或 GitHub repo 寫入權；專家標章不增加公告、討論區或技能編輯權限。','站內計畫狀態不取代 GitHub Issue／PR 的認領與合併證據。']),
 page('skillbooks','技能書介紹','先讀用途、前置條件與實作起點，再到具體專案閱讀或 Fork。',['apps/portal-web/src/modules/SkillBookIntro.tsx','modules/community/catalog.ts','modules/community/skill-book-guides.ts'],['freedom-skill-registry','freedom-project-page'],'每本書按實際 Repo 寫清第一個可驗收成果，改善程式請到該書對應 Repo。',['npm run typecheck','npx tsx --test tests/runtime/skill-book-guides.test.ts'],['不把來源 README 宣稱的功能寫成平台已測過或已部署的服務。'])
];
