import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { BootstrapRefreshSchema, BootstrapRefreshInputSchema, BootstrapSessionNonceInputSchema,
  BootstrapRefreshProofResultSchema, BootstrapNonceProofResultSchema } from '../../contracts/execution/v1/bootstrap-session.js';
import { DeviceAuthorizationPollResultSchema } from '../../contracts/execution/v1/device-pairing.js';
// @ts-expect-error Existing host-only clean environment helper is an ESM JavaScript module.
import { verificationEnvironment } from '../../packages/contribution-tools/process-env.mjs';

const id = '12345678-1234-4234-8234-123456789012', bytes = 'A'.repeat(43);
test('bootstrap session structural contracts match generated bytes', () => {
  const result = spawnSync(process.execPath, ['--import', 'tsx', 'modules/agent-control/generate-bootstrap-session.ts', '--check'], {
    cwd: fileURLToPath(new URL('../../', import.meta.url)), env: verificationEnvironment(),
    encoding: 'utf8', timeout: 30000, maxBuffer: 128 * 1024,
  });
  assert.equal(result.status, 0, result.stdout + result.stderr);
});
test('refresh output is strict canonical secret and decimal generation shape, never a validity proof', () => {
  const value = { familyId: id, generation: '1', handle: bytes, expiresAt: '2026-10-03T00:00:00.000Z' };
  assert(BootstrapRefreshSchema.safeParse(value).success);
  for (const generation of ['0', '01', '+1', '1\n', 1]) assert(!BootstrapRefreshSchema.safeParse({ ...value, generation }).success);
  for (const handle of [bytes + '=', 'A'.repeat(42) + 'B', bytes + '\n']) assert(!BootstrapRefreshSchema.safeParse({ ...value, handle }).success);
  assert(!BootstrapRefreshSchema.safeParse({ ...value, ownerUserId: id }).success);
});
test('refresh and nonce inputs cannot carry actor, scope, clock or previous status nonce', () => {
  const refresh = { familyId: id, refreshHandle: bytes, proof: 'synthetic-shape-only' };
  const nonce = { connectionId: id, accessToken: 'synthetic-shape-only', proof: 'synthetic-shape-only' };
  assert(BootstrapRefreshInputSchema.safeParse(refresh).success);
  assert(BootstrapSessionNonceInputSchema.safeParse(nonce).success);
  for (const override of [{ actor: {} }, { nowMs: 0 }, { scope: 'work.read' }, { nonce: bytes }]) {
    assert(!BootstrapRefreshInputSchema.safeParse({ ...refresh, ...override }).success);
    assert(!BootstrapSessionNonceInputSchema.safeParse({ ...nonce, ...override }).success);
  }
});
test('pure session proof output cannot inflate assurance or operational authority', () => {
  const value = { proofId: 'A'.repeat(16), validFromMs: 0, validUntilMs: 1000, assurance: 'cryptographic_only', operational_authority: false };
  for (const [schema, base] of [[BootstrapRefreshProofResultSchema, value], [BootstrapNonceProofResultSchema, { ...value, tokenId: 'B'.repeat(16) }]] as const) {
    assert(schema.safeParse(base).success);
    assert(!schema.safeParse({ ...base, operational_authority: true }).success);
    assert(!schema.safeParse({ ...base, assurance: 'verified' }).success);
  }
});
test('fresh pairing issued DTO now requires its actual initial refresh, with no optional legacy issuance', () => {
  const value = { status: 'issued', accessToken: 'synthetic-shape-only', tokenType: 'DPoP', expiresAt: '2026-10-03T00:00:00.000Z',
    connectionId: id, runtimeDeviceId: id, nonce: { nonceId: id, nonce: bytes, connectionId: id,
      issuedAt: '2026-10-02T00:00:00.000Z', expiresAt: '2026-10-02T00:01:00.000Z', operational_authority: false },
    refreshSupported: true, refresh: { familyId: id, generation: '1', handle: bytes, expiresAt: '2026-10-03T00:00:00.000Z' }, operational_authority: false };
  assert(DeviceAuthorizationPollResultSchema.safeParse(value).success);
  const { refresh: _refresh, ...missing } = value;
  assert(!DeviceAuthorizationPollResultSchema.safeParse(missing).success);
  assert(!DeviceAuthorizationPollResultSchema.safeParse({ ...value, refreshSupported: false }).success);
});
