import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
// @ts-expect-error Shared dependency-free verifier environment is implemented in JS.
import { verificationEnvironment } from '../../packages/contribution-tools/process-env.mjs';
import { BootstrapHttpTokenSchema, BootstrapHttpNonceSchema } from '../../contracts/execution/v1/bootstrap-http.js';

test('bootstrap HTTP structural schemas match generated bytes', () => {
  const result = spawnSync(process.execPath, ['--import','tsx','modules/agent-control/generate-bootstrap-http.ts','--check'], {
    cwd: fileURLToPath(new URL('../../',import.meta.url)), env: verificationEnvironment(), encoding:'utf8', timeout:30000,
  });
  assert.equal(result.status,0,result.stdout+result.stderr);
});
test('token purposes cannot mix bodies or supply host authority or header credentials', () => {
  const id = '12345678-1234-4234-8234-123456789012', secret = 'A'.repeat(43);
  const pairing = {grantType:'device_code',authorizationId:id,deviceCode:secret};
  const refresh = {grantType:'refresh_token',familyId:id,refreshHandle:secret};
  for (const value of [pairing,refresh]) {
    assert(BootstrapHttpTokenSchema.safeParse(value).success);
    for (const extra of [{proof:'a.b.c'},{actor:{}},{nowMs:0},{scope:'work.read'},{accessToken:'a.b.c'}])
      assert(!BootstrapHttpTokenSchema.safeParse({...value,...extra}).success);
  }
  assert(!BootstrapHttpTokenSchema.safeParse({...pairing,...refresh}).success);
  assert(!BootstrapHttpTokenSchema.safeParse({...refresh,grantType:'device_code'}).success);
  assert(BootstrapHttpNonceSchema.safeParse({connectionId:id}).success);
  assert(!BootstrapHttpNonceSchema.safeParse({connectionId:id,nonce:secret}).success);
});
