import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { DeviceUserCodeSchema, DeviceAuthorizationPollResultSchema, DeviceAuthorizationDecisionInputSchema,
  DevicePairingProofResultSchema } from '../../contracts/execution/v1/device-pairing.js';
// @ts-expect-error Existing host-only clean environment helper is an ESM JavaScript module.
import { verificationEnvironment } from '../../packages/contribution-tools/process-env.mjs';

test('device pairing structural contracts match central generated bytes', () => {
  const result = spawnSync(process.execPath, ['--import', 'tsx', 'modules/agent-control/generate-device-pairing.ts', '--check'], {
    cwd: fileURLToPath(new URL('../../', import.meta.url)), env: verificationEnvironment(),
    encoding: 'utf8', timeout: 30000, maxBuffer: 128 * 1024,
  });
  assert.equal(result.status, 0, result.stdout + result.stderr);
});
test('short codes are exact Crockford spelling, never implicit normalization', () => {
  assert(DeviceUserCodeSchema.safeParse('01234-XYZAB').success);
  for (const code of ['01234-XYZAB\n', '01234-xyzab', '01234XYZAB', '01234-XYZAI', '01234-XYZAL', '01234-XYZAO', '01234-XYZAU']) {
    assert(!DeviceUserCodeSchema.safeParse(code).success);
  }
});
test('poll protocol schemas enforce bounded intervals and refuse authority inflation', () => {
  for (const status of ['authorization_pending', 'slow_down'] as const) {
    const value = { status, interval: 5, operational_authority: false };
    assert(DeviceAuthorizationPollResultSchema.safeParse(value).success);
    for (const interval of [0, 4, 326, 5.5, Number.MAX_SAFE_INTEGER]) assert(!DeviceAuthorizationPollResultSchema.safeParse({ ...value, interval }).success);
    assert(!DeviceAuthorizationPollResultSchema.safeParse({ ...value, operational_authority: true }).success);
    assert(!DeviceAuthorizationPollResultSchema.safeParse({ ...value, refreshToken: 'not-implemented' }).success);
  }
});
test('member decision and proof-result shapes reject extra owner/authority fields', () => {
  const decision = { key: 'review_key', userCode: '01234-XYZAB', authorizationId: '12345678-1234-4234-8234-123456789012',
    requestDigest: 'A'.repeat(43), decision: 'approve' };
  assert(DeviceAuthorizationDecisionInputSchema.safeParse(decision).success);
  assert(!DeviceAuthorizationDecisionInputSchema.safeParse({ ...decision, ownerUserId: decision.authorizationId }).success);
  const proof = { keyThumbprint: 'A'.repeat(43), proofId: 'A'.repeat(16), issuedAt: 100,
    validFromMs: 95000, validUntilMs: 161000, assurance: 'cryptographic_only', operational_authority: false };
  assert(DevicePairingProofResultSchema.safeParse(proof).success);
  assert(!DevicePairingProofResultSchema.safeParse({ ...proof, assurance: 'verified' }).success);
  assert(!DevicePairingProofResultSchema.safeParse({ ...proof, operational_authority: true }).success);
});
