import assert from 'node:assert/strict';
import { before,after,test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { Pool,type PoolClient } from 'pg';
import { migrate } from '../../scripts/database.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('Explicit isolated TEST_DATABASE_URL required');
const schema=`fp_media_acl_${process.pid}_${Date.now()}`,migrator=`${schema}_owner`,runtime=`${schema}_app`,parent=`${schema}_parent`;
const admin=new Pool({connectionString:url}),owner=new Pool({connectionString:url,options:`-c role=${migrator} -c search_path=${schema} -c statement_timeout=10000`});let created=false,query:string,readback:string;
before(async()=>{const verify=await readFile(new URL('../../deploy/cloudflare/sql/30-verify-readonly.psql',import.meta.url),'utf8');readback=verify.split('-- BEGIN DOMAIN MEDIA POLICY READBACK\n')[1].split('\n-- END DOMAIN MEDIA POLICY READBACK')[0].replaceAll(":'runtime'",`'${runtime}'`).replace("n.nspname='public'",`n.nspname='${schema}'`);const template=await readFile(new URL('../../deploy/cloudflare/sql/20-runtime-grants.psql',import.meta.url),'utf8');query=template.split('-- BEGIN DOMAIN MEDIA POLICY GRANTS\n')[1].split('\n\\gexec')[0].replaceAll(":'runtime'",`'${runtime}'`).replace("n.nspname='public'",`n.nspname='${schema}'`);await admin.query(`CREATE ROLE ${migrator} NOLOGIN;CREATE ROLE ${runtime} NOLOGIN;CREATE ROLE ${parent} NOLOGIN;CREATE SCHEMA ${schema} AUTHORIZATION ${migrator};GRANT USAGE ON SCHEMA ${schema} TO ${runtime}`);created=true;await migrate(owner);});
after(async()=>{await owner.end();if(created)await admin.query(`DROP SCHEMA ${schema} CASCADE;DROP ROLE ${runtime},${parent},${migrator}`);await admin.end();});
async function grant(q:PoolClient){const rows=(await q.query(query)).rows;assert.equal(rows.length,1);for(const row of rows)await q.query(Object.values(row)[0] as string);}
async function transaction(run:(q:PoolClient)=>Promise<void>){const q=await owner.connect();try{await q.query('BEGIN');await run(q);}finally{await q.query('ROLLBACK');q.release();}}
const denied=(e:unknown)=>(e as {code?:string}).code==='42501';const unsafe=(e:unknown)=>(e as Error).message==='Unsafe runtime domain media policy privileges';
test('actual grants remove broad and stale column privileges while allowing policy row locks',async()=>{await transaction(async q=>{await q.query(`GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ${schema} TO ${runtime};GRANT UPDATE(persistence_allowed),INSERT(purpose) ON domain_media_storage_policy TO ${runtime} WITH GRANT OPTION`);assert.deepEqual((await q.query(readback)).rows,[{media_policy_read:true,media_policy_lock:true,media_policy_unsafe:true}]);await q.query('SAVEPOINT before_fence');await q.query(`SET LOCAL ROLE ${runtime}`);await q.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='member.service-cover'");await q.query('ROLLBACK TO SAVEPOINT before_fence');await grant(q);await grant(q);assert.deepEqual((await q.query(readback)).rows,[{media_policy_read:true,media_policy_lock:true,media_policy_unsafe:false}]);await q.query(`SET LOCAL ROLE ${runtime}`);await q.query('SELECT policy_revision,persistence_allowed,retained_byte_limit FROM domain_media_storage_policy FOR SHARE');await q.query('UPDATE domain_media_storage_policy SET policy_lock=DEFAULT');for(const sql of ["UPDATE domain_media_storage_policy SET persistence_allowed=true","UPDATE domain_media_storage_policy SET mode='bridge'","UPDATE domain_media_storage_policy SET policy_revision='forged'","UPDATE domain_media_storage_policy SET retained_byte_limit=99999999","UPDATE domain_media_storage_policy SET policy_lock=DEFAULT,persistence_allowed=true","INSERT INTO domain_media_storage_policy(purpose) VALUES('member.service-cover')","DELETE FROM domain_media_storage_policy","TRUNCATE domain_media_storage_policy"]){await q.query('SAVEPOINT denied');await assert.rejects(q.query(sql),denied);await q.query('ROLLBACK TO SAVEPOINT denied');}});});
test('PUBLIC policy-column grant is rejected rather than inferred safe',async()=>{await transaction(async q=>{await q.query('GRANT UPDATE(persistence_allowed) ON domain_media_storage_policy TO PUBLIC');await assert.rejects(grant(q),unsafe);});});
test('a mutable lock column cannot masquerade as the harmless generated constant',async()=>{await transaction(async q=>{await q.query('ALTER TABLE domain_media_storage_policy ALTER COLUMN policy_lock DROP EXPRESSION');await assert.rejects(grant(q),unsafe);});});
test('runtime role memberships are rejected even when no policy privilege is inherited',async()=>{await admin.query(`GRANT ${parent} TO ${runtime}`);try{await transaction(async q=>{await assert.rejects(grant(q),unsafe);});}finally{await admin.query(`REVOKE ${parent} FROM ${runtime}`);}});
