import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {setTimeout as delay} from 'node:timers/promises';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrate} from '../../scripts/database.js';
import {tokenHash,type Actor} from '../../modules/identity-membership/service.js';
import {createEventBannerAssetService,resolveEventBannerUploadPolicy} from '../../modules/assets/event-banner.js';
import {createAssetMaintenance} from '../../modules/assets/maintenance.js';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import {sha256,objectKey,type ObjectStore} from '../../packages/asset-storage/index.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw Error('Explicit synthetic TEST_DATABASE_URL required');
const schema=`fp_domain_gc_${process.pid}_${Date.now()}`,admin=new Pool({connectionString:url}),pool=new Pool({connectionString:url,options:`-c search_path=${schema} -c statement_timeout=10000`});
const community=randomUUID();let png:Buffer,mf:Miniflare,store:ObjectStore,created=false;
before(async()=>{await admin.query(`CREATE SCHEMA ${schema}`);created=true;await migrate(pool);png=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).png().toBuffer();mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'fp-domain-gc',modules:true,script:'export default {fetch(){return new Response("synthetic");}}',compatibilityDate:'2026-09-21',r2Buckets:['MEDIA']}]}));await mf.ready;store=createR2ObjectStore(await mf.getR2Bucket('MEDIA') as unknown as AssetR2Binding,{allowDelete:true});});
after(async()=>{await mf?.dispose();await pool.end();if(created)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
beforeEach(async()=>{await pool.query('TRUNCATE communities,asset_backup_captures CASCADE');await pool.query("INSERT INTO communities VALUES($1,'Synthetic GC')",[community]);await pool.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-banner-policy',persistence_allowed=true,retained_byte_limit=10485760 WHERE purpose='community.event-banner'");await pool.query("UPDATE asset_maintenance_policy SET enabled=true,domain_media_enabled=true,revision='synthetic-gc',orphan_retention_seconds=1,retired_retention_seconds=1,delete_lease_seconds=30,capture_seconds=30,pin_seconds=30,max_capture_objects=10");});
const code=(expected:string)=>(e:unknown)=>(e as {code?:string})?.code===expected;
const body=()=>new ReadableStream<Uint8Array>({start(c){c.enqueue(png);c.close();}});
function gate(){let release!:()=>void;return {promise:new Promise<void>(r=>{release=r;}),release:()=>release()};}
async function fixture(io=store){const userId=randomUUID(),hash=tokenHash(randomBytes(32).toString('base64url'));const user=(await pool.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,'Synthetic owner','not-a-login-hash',$4) RETURNING *",[userId,community,userId+'@gc.local.test',randomUUID()])).rows[0];await pool.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[hash,userId]);const actor={...user,session_hash:hash,csrf_token:'synthetic'} as Actor,id=randomUUID();await pool.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic','Synthetic',clock_timestamp()+interval '2 days',clock_timestamp()+interval '3 days','online','Synthetic','pending','open','other')",[id,community,userId]);const api=createEventBannerAssetService(pool,{store:io,resolvePolicy:resolveEventBannerUploadPolicy});const prepared=await api.prepare(actor,{key:randomUUID(),targetEventId:id,expectedVersion:'1',contentType:'image/png',byteSize:png.length,sha256:await sha256(png),orientation:'landscape'});const claimed=await api.claim(actor,{key:randomUUID(),intentId:prepared.intentId});const lease={intentId:claimed.intentId,fence:claimed.fence,leaseToken:claimed.leaseToken};return {actor,id,api,prepared,lease};}
async function publish(f:Awaited<ReturnType<typeof fixture>>){await f.api.write(f.actor,{key:randomUUID(),...f.lease},body());await f.api.finalize(f.actor,{key:randomUUID(),...f.lease});}
async function retire(f:Awaited<ReturnType<typeof fixture>>){await pool.query('DELETE FROM community_event_banners WHERE event_id=$1',[f.id]);assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[f.prepared.assetId])).rows[0].state,'retired');await delay(1100);}
const maintenance=(enabled=true)=>createAssetMaintenance(pool,{store,enabled:true,domainMediaEnabled:enabled});
async function key(assetId:string){const row=(await pool.query('SELECT scope_id,representation_id FROM assets WHERE asset_id=$1',[assetId])).rows[0];return objectKey({scopeId:row.scope_id,assetId,representationId:row.representation_id});}

test('DOMAIN-GC-01 actual banner publication/removal, both opt-ins, and native R2 deletion preserve permanent identity',async()=>{const f=await fixture();await publish(f);const asset=f.prepared.assetId;assert.equal((await pool.query('SELECT write_effect_coverage FROM assets WHERE asset_id=$1',[asset])).rows[0].write_effect_coverage,true);assert.equal((await pool.query('SELECT state FROM asset_object_write_effects')).rows[0].state,'fulfilled');await assert.rejects(maintenance().claimDelete(asset),code('23514'));await assert.rejects(pool.query("UPDATE assets SET state='retired',retired_at=clock_timestamp()-interval '1 hour' WHERE asset_id=$1",[asset]));await retire(f);await assert.rejects(maintenance(false).claimDelete(asset),code('asset_domain_maintenance_disabled'));await pool.query('UPDATE asset_maintenance_policy SET domain_media_enabled=false');await assert.rejects(maintenance().claimDelete(asset),code('asset_domain_maintenance_disabled'));await pool.query('UPDATE asset_maintenance_policy SET domain_media_enabled=true');const lease=await maintenance().claimDelete(asset);assert.equal((await maintenance().deleteObject(lease)).observation,'missing');assert.equal(await store.head(await key(asset)),null);assert.equal((await pool.query('SELECT count(*)::int n FROM asset_objects WHERE asset_id=$1',[asset])).rows[0].n,1);await assert.rejects(pool.query('UPDATE assets SET deletion_fence=0 WHERE asset_id=$1',[asset]),code('23514'));});

test('DOMAIN-GC-02 delayed original PUT blocks GC after a newer lease publishes; only actual same promise fulfillment settles',async()=>{const entered=gate(),release=gate();let calls=0;const io:ObjectStore={...store,async putImmutable(k,v){if(++calls===1){entered.release();await release.promise;}return store.putImmutable(k,v);}};const f=await fixture(io),first=f.api.write(f.actor,{key:randomUUID(),...f.lease},body()).then(()=>({ok:true}),error=>({ok:false,error}));await entered.promise;try{await pool.query('UPDATE asset_upload_intents SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE intent_id=$1',[f.prepared.intentId]);const next=await f.api.claim(f.actor,{key:randomUUID(),intentId:f.prepared.intentId});f.lease={intentId:next.intentId,fence:next.fence,leaseToken:next.leaseToken};await publish(f);await retire(f);assert.deepEqual((await pool.query('SELECT state FROM asset_object_write_effects ORDER BY begun_at')).rows.map(r=>r.state),['started','fulfilled']);await assert.rejects(maintenance().claimDelete(f.prepared.assetId),code('23514'));assert.ok(await store.head(await key(f.prepared.assetId)));}finally{release.release();}const old=await first;assert.equal(old.ok,false);assert.deepEqual((await pool.query('SELECT state FROM asset_object_write_effects ORDER BY begun_at')).rows.map(r=>r.state),['fulfilled','fulfilled']);const lease=await maintenance().claimDelete(f.prepared.assetId);assert.equal((await maintenance().deleteObject(lease)).observation,'missing');});

test('DOMAIN-GC-03 committed-but-rejected PUT stays unknown despite successful full readback and elapsed clocks',async()=>{const io:ObjectStore={...store,async putImmutable(k,v){await store.putImmutable(k,v);throw Error('PRIVATE_UPSTREAM_DIAGNOSTIC');}};const f=await fixture(io);await publish(f);await retire(f);assert.equal((await pool.query('SELECT state FROM asset_object_write_effects')).rows[0].state,'unknown');assert.ok(await store.head(await key(f.prepared.assetId)));await assert.rejects(maintenance().claimDelete(f.prepared.assetId),code('23514'));await assert.rejects(pool.query("UPDATE asset_object_write_effects SET state='fulfilled',finished_at=clock_timestamp()"),code('23514'));await assert.rejects(pool.query('DELETE FROM asset_object_write_effects'),code('23514'));assert.equal((await pool.query('SELECT deletion_fence FROM assets')).rows[0].deletion_fence,'0');});

test('DOMAIN-GC-04 capturing and expired-but-unreleased backup pins block retired-domain deletion',async()=>{const f=await fixture();await publish(f);await retire(f);const api=maintenance(),capture=await api.beginCapture({sourceRelease:'a'.repeat(40),sourceSchema:'108-synthetic'});await assert.rejects(api.claimDelete(f.prepared.assetId),code('23514'));await api.captureReferences(capture.captureId);assert.equal((await pool.query('SELECT count(*)::int n FROM asset_backup_pins')).rows[0].n,1);await pool.query("UPDATE asset_backup_captures SET pin_expires_at=clock_timestamp()-interval '1 second' WHERE capture_id=$1",[capture.captureId]);await assert.rejects(api.claimDelete(f.prepared.assetId),code('23514'));await api.releaseProtection(capture.captureId,'release');await api.claimDelete(f.prepared.assetId);});

test('DOMAIN-GC-05 RLS cannot turn hidden unresolved effects into clean deletion evidence',async()=>{const f=await fixture();await publish(f);await retire(f);await pool.query('ALTER TABLE asset_object_write_effects ENABLE ROW LEVEL SECURITY');try{await assert.rejects(maintenance().claimDelete(f.prepared.assetId),code('23514'));assert.equal((await pool.query('SELECT deletion_fence FROM assets')).rows[0].deletion_fence,'0');}finally{await pool.query('ALTER TABLE asset_object_write_effects DISABLE ROW LEVEL SECURITY');}});

test('DOMAIN-GC-06 historical coverage cannot be silently adopted by UPDATE',async()=>{const f=await fixture();await assert.rejects(pool.query('UPDATE assets SET write_effect_coverage=false WHERE asset_id=$1',[f.prepared.assetId]),code('23514'));const columns=(await pool.query("SELECT column_default FROM information_schema.columns WHERE table_schema=$1 AND table_name='assets' AND column_name='write_effect_coverage'",[schema])).rows[0];assert.equal(columns.column_default,'false');await assert.rejects(maintenance().claimDelete(f.prepared.assetId),code('23514'));});

for(const boundary of ['database-delete','host-delete','database-takeover'] as const)test(`DOMAIN-GC live opt-in ${boundary} revocation blocks object I/O and lease takeover`,async()=>{const f=await fixture();await publish(f);await retire(f);let deletes=0;const watched:ObjectStore={...store,async delete(k){deletes++;return store.delete(k);}};const api=createAssetMaintenance(pool,{store:watched,enabled:true,domainMediaEnabled:true}),lease=await api.claimDelete(f.prepared.assetId);if(boundary==='host-delete'){await assert.rejects(createAssetMaintenance(pool,{store:watched,enabled:true}).deleteObject(lease),code('asset_domain_maintenance_disabled'));}else{await pool.query('UPDATE asset_maintenance_policy SET domain_media_enabled=false');if(boundary==='database-delete')await assert.rejects(api.deleteObject(lease),code('asset_domain_maintenance_disabled'));else{await pool.query('UPDATE asset_deletion_tombstones SET lease_expires_at=clock_timestamp() WHERE asset_id=$1',[f.prepared.assetId]);await assert.rejects(api.claimDelete(f.prepared.assetId),code('asset_domain_maintenance_disabled'));await assert.rejects(pool.query("UPDATE asset_deletion_tombstones SET attempt=attempt+1,lease_token=$2,lease_expires_at=clock_timestamp()+interval '5 seconds' WHERE asset_id=$1",[f.prepared.assetId,randomUUID()]),code('23514'));}}assert.equal(deletes,0);assert.ok(await store.head(await key(f.prepared.assetId)));});
