import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import sharp from 'sharp';
import {migrate} from '../../scripts/database.js';
import {tokenHash,type Actor} from '../../modules/identity-membership/service.js';
import {createEventBannerAssetService,resolveEventBannerUploadPolicy} from '../../modules/assets/event-banner.js';
import {saveEventBanner,readEventBanner,publicEventBanner} from '../../modules/community/events.js';
import {FakeObjectStore} from '../../packages/asset-storage/fake-store.js';
import {sha256} from '../../packages/asset-storage/index.js';
import {createApp} from '../../apps/platform-api/src/app.js';
import {Problem} from '../../packages/shared/problem.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('Explicit isolated TEST_DATABASE_URL required');
const schema=`fp_banner_${process.pid}_${Date.now()}`,admin=new Pool({connectionString:url}),pool=new Pool({connectionString:url,options:`-c search_path=${schema} -c statement_timeout=10000`});
const community=randomUUID();let png:Buffer,initialized=false;
before(async()=>{await admin.query(`CREATE SCHEMA ${schema}`);initialized=true;await migrate(pool);png=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).png().toBuffer();});
after(async()=>{await pool.end();if(initialized)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
beforeEach(async()=>{await pool.query('TRUNCATE communities CASCADE');await pool.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-banner-policy',persistence_allowed=true,retained_byte_limit=10485760 WHERE purpose='community.event-banner'");await pool.query('INSERT INTO communities VALUES($1,$2)',[community,'Synthetic banner']);});
async function member(){const id=randomUUID(),token=randomBytes(32).toString('base64url'),hash=tokenHash(token);const row=(await pool.query('INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,community,id+'@banner.local.test','Synthetic owner','not-a-login-hash',randomUUID()])).rows[0];await pool.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[hash,id]);return {...row,session_hash:hash,csrf_token:'synthetic',synthetic_token:token} as Actor;}
async function setup(){const owner=await member(),id=randomUUID();await pool.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic','Synthetic',clock_timestamp()+interval '2 days',clock_timestamp()+interval '3 days','online','Synthetic','pending','open','other')",[id,community,owner.user_id]);const store=new FakeObjectStore(),api=createEventBannerAssetService(pool,{store,resolvePolicy:resolveEventBannerUploadPolicy});return {owner,id,store,api};}
async function upload(s:Awaited<ReturnType<typeof setup>>,version='1'){const prepared=await s.api.prepare(s.owner,{key:randomUUID(),targetEventId:s.id,expectedVersion:version,contentType:'image/png',byteSize:png.length,sha256:await sha256(png),orientation:'portrait'});const claim=await s.api.claim(s.owner,{key:randomUUID(),intentId:prepared.intentId});const lease={intentId:claim.intentId,fence:claim.fence,leaseToken:claim.leaseToken};await s.api.write(s.owner,{key:randomUUID(),...lease},new ReadableStream({start(c){c.enqueue(png);c.close();}}));return {...prepared,lease};}
const code=(c:string)=>(e:unknown)=>e instanceof Problem&&e.code===c;
test('genuine community scope publishes normalized banner only at commit and retains organizer read ACL',async()=>{const s=await setup(),u=await upload(s);assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_banners')).rows[0].n,0);const result=await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});assert.equal(result.aggregateVersion,'2');const row=(await pool.query('SELECT a.scope_kind,a.community_ref,r.owner_principal_id,b.image_bytes,b.orientation,o.profile_id FROM assets a JOIN resource_scopes r ON r.scope_id=a.scope_id JOIN community_event_banner_asset_targets t USING(asset_id) JOIN community_event_banners b USING(event_id) JOIN asset_objects o USING(asset_id)')).rows[0];assert.equal(row.scope_kind,'community');assert.equal(row.community_ref,community);assert.equal(row.owner_principal_id,null);assert.equal(row.image_bytes,null);assert.equal(row.orientation,'portrait');assert.equal(row.profile_id,'community.event-banner');const bytes=await readEventBanner(pool,s.owner,s.id,s.store);assert.equal((await sharp(bytes).metadata()).format,'webp');await assert.rejects(readEventBanner(pool,await member(),s.id,s.store),code('media_not_found'));await assert.rejects(readEventBanner(pool,s.owner,s.id),code('media_unavailable'));});
test('original command receipt replays DTO exactly; removal retires object pointer and never advances twice',async()=>{const s=await setup(),key=randomUUID(),command={actor:s.owner,operation:`POST /api/v1/events/${s.id}/banner`,key,expected:'1',body:null};const file={bytes:png,mime:'image/png',orientation:'landscape' as const};const first=await saveEventBanner(pool,command,s.id,file,s.api);assert.equal(first.aggregate_version,'2');assert.ok(first.banner_url);assert.deepEqual(await saveEventBanner(pool,command,s.id,file,s.api),first);assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,1);const removed=await saveEventBanner(pool,{...command,key:randomUUID(),operation:`POST /api/v1/events/${s.id}/banner/remove`,expected:'2'},s.id,null);assert.equal(removed.banner_url,null);assert.equal(removed.aggregate_version,'3');assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'retired');assert.equal((await pool.query('SELECT asset_id FROM community_event_banner_asset_targets')).rows[0].asset_id,null);});
test('canonical policy prohibition, stale CAS and nonorganizer fail before publication',async()=>{const s=await setup(),peer=await member();await assert.rejects(s.api.prepare(peer,{key:randomUUID(),targetEventId:s.id,expectedVersion:'1',contentType:'image/png',byteSize:png.length,sha256:await sha256(png),orientation:'landscape'}),code('organizer_required'));const u=await upload(s);await pool.query('UPDATE community_events SET aggregate_version=2 WHERE event_id=$1',[s.id]);await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('version_conflict'));await pool.query('UPDATE community_events SET aggregate_version=1 WHERE event_id=$1',[s.id]);await pool.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.event-banner'");await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('media_upload_unavailable'));assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_banners')).rows[0].n,0);});
test('public reads keep original published visibility and recheck ACL after object IO',async()=>{const s=await setup(),u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});await assert.rejects(publicEventBanner(pool,s.id,s.store),code('media_not_found'));await pool.query("UPDATE community_events SET state='published',aggregate_version=3 WHERE event_id=$1",[s.id]);assert.ok((await publicEventBanner(pool,s.id,s.store)).length);const get=s.store.get.bind(s.store);s.store.get=async(...args)=>{const value=await get(...args);await pool.query("UPDATE community_events SET state='cancelled' WHERE event_id=$1",[s.id]);return value;};await assert.rejects(publicEventBanner(pool,s.id,s.store),code('media_not_found'));});
test('SQL rejects personal banner authority and scope identity mutation; unknown purposes remain rejected',async()=>{const s=await setup(),u=await upload(s);await assert.rejects(pool.query("UPDATE assets SET scope_kind='personal',community_ref=NULL WHERE asset_id=$1",[u.assetId]),(e:any)=>e.code==='23514');await assert.rejects(pool.query("INSERT INTO domain_media_storage_policy(purpose) VALUES('future.unknown')"),(e:any)=>e.code==='23514');await assert.rejects(pool.query("INSERT INTO community_event_banners(event_id,image_bytes,storage_source) VALUES($1,NULL,'asset')",[s.id]),(e:any)=>e.code==='23514');});

test('actual installed HTTP banner route preserves ETag, private response and safe DTO without storage identity',async()=>{const s=await setup(),origin='http://127.0.0.1:4310',app=createApp(pool,origin,'local',{eventBannerAssets:s.api,eventBannerAssetStore:s.store}),headers={Origin:origin,Cookie:`freedom_local_session=${(s.owner as Actor&{synthetic_token:string}).synthetic_token}`,'X-CSRF-Token':'synthetic','Content-Type':'image/png','Idempotency-Key':randomUUID(),'If-Match':'"1"','X-Poster-Orientation':'portrait'};const response=await app.request(origin+`/api/v1/events/${s.id}/banner`,{method:'POST',headers,body:new Uint8Array(png)});const dto=await response.json() as any;assert.equal(response.status,200,JSON.stringify(dto));assert.equal(response.headers.get('etag'),'"2"');assert.equal(dto.banner_orientation,'portrait');assert.equal(dto.banner_url,`/api/v1/events/${s.id}/banner?v=2`);assert.equal('asset_id' in dto,false);assert.equal('scope_id' in dto,false);const read=await app.request(origin+dto.banner_url,{headers:{Cookie:headers.Cookie}});assert.equal(read.status,200);assert.equal(read.headers.get('cache-control'),'private, no-store');assert.equal(read.headers.get('content-type'),'image/webp');});

test('original active guild intern prohibition and expiry remain binding on every lifecycle phase',async()=>{const s=await setup();await pool.query("UPDATE community_events SET event_kind='guild_skill_exchange',guild_key='guild_security' WHERE event_id=$1",[s.id]);await pool.query("INSERT INTO positioning_profession_memberships(membership_id,community_id,user_id,guild_key,state,member_tier) VALUES($1,$2,$3,'guild_security','active','intern')",[randomUUID(),community,s.owner.user_id]);await assert.rejects(upload(s),code('guild_full_member_required'));await pool.query("UPDATE positioning_profession_memberships SET member_tier='full' WHERE user_id=$1",[s.owner.user_id]);const u=await upload(s);await pool.query("UPDATE community_events SET starts_at=clock_timestamp()-interval '1 minute' WHERE event_id=$1",[s.id]);await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('event_closed'));assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_banners')).rows[0].n,0);});
test('bridge replacement retains historical SQL WebP but missing immutable object never falls back',async()=>{const s=await setup(),legacy=await sharp(png).webp().toBuffer();await pool.query('INSERT INTO community_event_banners(event_id,image_bytes,orientation) VALUES($1,$2,$3)',[s.id,legacy,'landscape']);assert.deepEqual(await readEventBanner(pool,s.owner,s.id),legacy);const a=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...a.lease});assert.deepEqual((await pool.query('SELECT image_bytes FROM community_event_banners')).rows[0].image_bytes,legacy);await assert.rejects(readEventBanner(pool,s.owner,s.id),code('media_unavailable'));const b=await upload(s,'2');await s.api.finalize(s.owner,{key:randomUUID(),...b.lease});assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[a.assetId])).rows[0].state,'retired');assert.ok((await readEventBanner(pool,s.owner,s.id,s.store)).length);await assert.rejects(pool.query("UPDATE domain_media_storage_policy SET mode='r2_only' WHERE purpose='community.event-banner'"),(e:any)=>e.code==='23514');});

test('closed banner manifest rejects oversize and arbitrary scope before object writes',async()=>{const s=await setup(),input={key:randomUUID(),targetEventId:s.id,expectedVersion:'1',contentType:'image/png' as const,byteSize:png.length,sha256:await sha256(png),orientation:'landscape' as const};let puts=0;const put=s.store.putImmutable.bind(s.store);s.store.putImmutable=async(...args)=>{puts++;return put(...args);};await assert.rejects(s.api.prepare(s.owner,{...input,byteSize:524289}));await assert.rejects(s.api.prepare(s.owner,{...input,scopeId:randomUUID()} as any));assert.equal(puts,0);assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);});
