import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import {migrate} from '../../scripts/database.js';
import {tokenHash,type Actor} from '../../modules/identity-membership/service.js';
import {createEventHighlightAssetService,resolveEventHighlightUploadPolicy} from '../../modules/assets/event-highlight.js';
import {addHighlightImage,normalizeHighlightImage,highlightImageDigest,highlightImageBytes,removeHighlight} from '../../modules/community/event-highlights.js';
import {FakeObjectStore} from '../../packages/asset-storage/fake-store.js';
import {sha256,objectKey} from '../../packages/asset-storage/index.js';
import {createApp} from '../../apps/platform-api/src/app.js';
import {Problem} from '../../packages/shared/problem.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('Explicit isolated TEST_DATABASE_URL required');
const schema=`fp_highlight_media_${process.pid}_${Date.now()}`,role=`${schema}_app`,admin=new Pool({connectionString:url}),fixture=new Pool({connectionString:url,options:`-c search_path=${schema} -c statement_timeout=10000`}),pool=new Pool({connectionString:url,options:`-c role=${role} -c search_path=${schema} -c statement_timeout=10000`});
const community=randomUUID();let png:Buffer,initialized=false,mf:Miniflare,bucket:AssetR2Binding;
before(async()=>{await admin.query(`CREATE ROLE ${role} NOLOGIN;CREATE SCHEMA ${schema};GRANT USAGE ON SCHEMA ${schema} TO ${role}`);initialized=true;await migrate(fixture);await fixture.query(`GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ${schema} TO ${role};GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA ${schema} TO ${role}`);const grants=await readFile(new URL('../../deploy/cloudflare/sql/20-runtime-grants.psql',import.meta.url),'utf8');for(const match of grants.matchAll(/-- BEGIN [A-Z ]+\n([\s\S]*?)\n\\gexec/g)){const sql=match[1].replaceAll(":'runtime'",`'${role}'`).replaceAll("n.nspname='public'",`n.nspname='${schema}'`);for(const row of (await fixture.query(sql)).rows)await fixture.query(Object.values(row)[0] as string);}png=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).png().toBuffer();mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'fp-social-domain-test',modules:true,script:'export default {fetch(){return new Response("synthetic");}}',compatibilityDate:'2026-09-21',r2Buckets:['MEDIA']}]}));await mf.ready;bucket=await mf.getR2Bucket('MEDIA') as unknown as AssetR2Binding;});
after(async()=>{await mf?.dispose();await pool.end();await fixture.end();if(initialized)await admin.query(`DROP SCHEMA ${schema} CASCADE;DROP ROLE ${role}`);await admin.end();});
beforeEach(async()=>{await fixture.query('TRUNCATE communities CASCADE');await fixture.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-social-policy',persistence_allowed=true,retained_byte_limit=10485760 WHERE purpose='community.event-highlight'");await fixture.query('INSERT INTO communities VALUES($1,$2)',[community,'Synthetic social']);});
async function member(communityId=community){const id=randomUUID(),token=randomBytes(32).toString('base64url'),hash=tokenHash(token);const row=(await fixture.query('INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,communityId,id+'@social.local.test','Synthetic owner','not-a-login-hash',randomUUID()])).rows[0];await fixture.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[hash,id]);return {...row,session_hash:hash,csrf_token:'synthetic',synthetic_token:token} as Actor;}

async function setup(native=false){const organizer=await member(),owner=await member(),id=randomUUID();await fixture.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic ended','Synthetic',clock_timestamp()-interval '2 days',clock_timestamp()-interval '1 day','online','Synthetic','published','open','other')",[id,community,organizer.user_id]);const store=native?{...createR2ObjectStore(bucket)}:new FakeObjectStore(),api=createEventHighlightAssetService(pool,{store,resolvePolicy:resolveEventHighlightUploadPolicy});const variants=await normalizeHighlightImage(png,'image/png','landscape');const command={actor:owner,operation:`POST /api/v1/event-highlights/${id}/photos`,key:randomUUID(),body:highlightImageDigest(png,'landscape','Synthetic title')};return {organizer,owner,id,store,api,variants,command};}
async function upload(s:Awaited<ReturnType<typeof setup>>){return addHighlightImage(pool,s.command,s.id,'photo',s.variants.image,s.variants.thumb,'landscape','Synthetic title',s.api);}
const code=(c:string)=>(e:unknown)=>e instanceof Problem&&e.code===c;
test('restricted ordinary member publishes native R2 pair with original DTO and one receipt',async()=>{const s=await setup(true),result=await upload(s);const rows=(await pool.query('SELECT a.state,o.variant,o.profile_id FROM assets a JOIN asset_objects o USING(asset_id) ORDER BY o.variant')).rows;assert.equal(rows.length,2);assert.ok(rows.every(r=>r.state==='ready'));assert.deepEqual(rows.map(r=>r.profile_id),['community.event-highlight','community.event-highlight.thumbnail']);const image=await highlightImageBytes(pool,result.media_id,'image',s.store),thumb=await highlightImageBytes(pool,result.media_id,'thumb',s.store);assert.deepEqual(image,s.variants.image);assert.deepEqual(thumb,s.variants.thumb);assert.equal((await sharp(thumb).metadata()).width,480);assert.equal(result.image_url,`/api/v1/public/event-highlights/media/${result.media_id}/image`);assert.deepEqual(await upload(s),result);assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,2);assert.equal((await pool.query("SELECT count(*)::int n FROM community_event_highlights")).rows[0].n,1);await assert.rejects(pool.query('UPDATE domain_media_storage_policy SET persistence_allowed=false'),(e:any)=>e.code==='42501');});
test('failed second PUT leaves neither variant visible and same key resumes the same pair',async()=>{const s=await setup(),put=s.store.putImmutable.bind(s.store);let calls=0;s.store.putImmutable=async(...args)=>{calls++;if(calls===2)throw new (await import('../../packages/asset-storage/index.js')).AssetStorageError('object_unavailable');return put(...args);};await assert.rejects(upload(s));assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0);assert.ok((await pool.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));const result=await upload(s);assert.equal(calls,3);assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,2);assert.ok((await highlightImageBytes(pool,result.media_id,'thumb',s.store)).length);});
test('commit after unknown PUT is reconciled without duplicate objects',async()=>{const s=await setup();(s.store as FakeObjectStore).failNext('put-after');const result=await upload(s);assert.ok(result.media_id);assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,2);});
test('deferred pair constraints reject individual deletion and swapped pointers',async()=>{const s=await setup(),result=await upload(s);await assert.rejects(pool.query("DELETE FROM community_event_highlight_images WHERE media_id=$1 AND variant='thumb'",[result.media_id]),(e:any)=>e.code==='23514');await assert.rejects(pool.query('UPDATE community_event_highlight_asset_targets SET image_asset_id=thumb_asset_id,thumb_asset_id=image_asset_id WHERE media_id=$1',[result.media_id]),(e:any)=>['23503','23514'].includes(e.code));assert.deepEqual(await highlightImageBytes(pool,result.media_id,'thumb',s.store),s.variants.thumb);});
test('combined quota is reserved before object IO and canonical prohibition never publishes half a pair',async()=>{const s=await setup();await fixture.query("UPDATE domain_media_storage_policy SET retained_byte_limit=1253376 WHERE purpose='community.event-highlight'");await upload(s);const next={...s,command:{...s.command,key:randomUUID()}};await assert.rejects(upload(next),code('asset_retained_quota'));assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,1);});
test('policy revoked during verification rolls back both publications',async()=>{const s=await setup(),get=s.store.get.bind(s.store);let revoked=false;s.store.get=async(...args)=>{const value=await get(...args);if(!revoked){revoked=true;await fixture.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.event-highlight'");}return value;};await assert.rejects(upload(s));assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0);assert.ok((await pool.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));});
test('current public ACL after object IO rejects bytes and uploader removal retires both pointers',async()=>{const s=await setup(),result=await upload(s),get=s.store.get.bind(s.store);s.store.get=async(...args)=>{const value=await get(...args);await fixture.query("UPDATE community_events SET state='cancelled',aggregate_version=aggregate_version+1 WHERE event_id=$1",[s.id]);return value;};await assert.rejects(highlightImageBytes(pool,result.media_id,'image',s.store),code('not_found'));s.store.get=get;await fixture.query("UPDATE community_events SET state='published',aggregate_version=aggregate_version+1 WHERE event_id=$1",[s.id]);await removeHighlight(pool,{actor:s.owner,operation:`DELETE /api/v1/event-highlights/media/${result.media_id}`,key:randomUUID(),body:{}},result.media_id);assert.ok((await pool.query('SELECT state FROM assets')).rows.every(r=>r.state==='retired'));const pair=(await pool.query('SELECT image_asset_id,thumb_asset_id FROM community_event_highlight_asset_targets')).rows[0];assert.deepEqual(pair,{image_asset_id:null,thumb_asset_id:null});await assert.rejects(highlightImageBytes(pool,result.media_id,'thumb',s.store),code('not_found'));});
test('original HTTP no new CAS, raw normalization, CSRF, cache, replay and missing store fail closed',async()=>{const s=await setup(),origin='http://127.0.0.1:4310',app=createApp(pool,origin,'local',{eventHighlightAssets:s.api,eventHighlightAssetStore:s.store}),path=`/api/v1/event-highlights/${s.id}/photos`,headers={Origin:origin,Cookie:`freedom_local_session=${(s.owner as Actor&{synthetic_token:string}).synthetic_token}`,'X-CSRF-Token':'synthetic','Content-Type':'image/png','Idempotency-Key':randomUUID(),'X-Photo-Orientation':'landscape','X-Media-Title':'Synthetic title'},send=()=>app.request(origin+path,{method:'POST',headers,body:new Uint8Array(png)});const response=await send(),result=await response.json() as any;assert.equal(response.status,201,JSON.stringify(result));assert.deepEqual(await(await send()).json(),result);const read=await app.request(origin+result.image_url);assert.equal(read.status,200);assert.equal(read.headers.get('cache-control'),'public, max-age=300');await assert.rejects(highlightImageBytes(pool,result.media_id,'image'),code('media_unavailable'));const denied=await app.request(origin+path,{method:'POST',headers:{...headers,'Idempotency-Key':randomUUID(),'X-CSRF-Token':'wrong'},body:new Uint8Array(png)});assert.equal(denied.status,403);});

test('session decision clock after final event lock rejects expired pair without a receipt',async()=>{
 const s=await setup(),get=s.store.get.bind(s.store),locker=await fixture.connect();let gets=0,signal!:()=>void;const blocked=new Promise<void>(r=>signal=r);
 s.store.get=async(...args)=>{const value=await get(...args);if(++gets===4){await locker.query('BEGIN');await locker.query('SELECT event_id FROM community_events WHERE event_id=$1 FOR UPDATE',[s.id]);await fixture.query("UPDATE sessions SET expires_at=clock_timestamp()+interval '600 milliseconds' WHERE token_hash=$1",[s.owner.session_hash]);signal();}return value;};
 const pending=upload(s);const outcome=pending.then(value=>({value}),error=>({error}));try{await blocked;let waiting=false;for(let i=0;i<80;i++){waiting=(await fixture.query("SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE usename=current_user AND query LIKE '%FROM community_events%' AND wait_event_type='Lock' AND pid<>pg_backend_pid()) AS waiting")).rows[0].waiting;if(waiting)break;await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'final publication must actually wait on the event lock');await fixture.query('SELECT pg_sleep(0.7)');await locker.query('COMMIT');const result=await outcome;assert.ok('error' in result);assert.equal((result as {error:Problem}).error.code,'session_expired');assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0);assert.ok((await pool.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));}finally{await locker.query('ROLLBACK');locker.release();await outcome;}
});
test('organizer and verified platform admin remove pairs while ordinary peer cannot',async()=>{for(const authority of ['organizer','admin'] as const){const s=await setup(),result=await upload(s),peer=await member();const cmd=(actor:Actor)=>({actor,operation:`POST /api/v1/event-highlights/media/${result.media_id}/remove`,key:randomUUID(),body:{}});await assert.rejects(removeHighlight(pool,cmd(peer),result.media_id),code('highlight_remove_forbidden'));if(authority==='admin'){await fixture.query('UPDATE users SET email_verified_at=clock_timestamp() WHERE user_id=$1',[peer.user_id]);await fixture.query('INSERT INTO platform_admins(admin_id,community_id,email,display_name,active) VALUES($1,$2,$3,$4,true)',[randomUUID(),community,peer.email,peer.display_name]);}await removeHighlight(pool,cmd(authority==='admin'?peer:s.organizer),result.media_id);assert.equal((await pool.query("SELECT count(*)::int n FROM community_event_highlight_asset_targets WHERE media_id=$1 AND image_asset_id IS NULL AND thumb_asset_id IS NULL",[result.media_id])).rows[0].n,1);}assert.ok((await pool.query('SELECT state FROM assets')).rows.every(r=>r.state==='retired'));});
test('two concurrent same-key creators converge on one atomic receipt and pair',async()=>{const s=await setup(),results=await Promise.all([upload(s),upload(s)]);assert.deepEqual(results[0],results[1]);assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,2);assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,1);assert.equal((await pool.query("SELECT count(*)::int n FROM scoped_transition_journal WHERE aggregate_type='community_event_highlight'")).rows[0].n,1);});
test('same receipt key with changed normalized source cannot rebind pair or issue further PUT',async()=>{const s=await setup(),put=s.store.putImmutable.bind(s.store);let calls=0;s.store.putImmutable=async(...args)=>{calls++;if(calls===2)throw new (await import('../../packages/asset-storage/index.js')).AssetStorageError('object_unavailable');return put(...args);};await assert.rejects(upload(s));const changed=await sharp({create:{width:40,height:20,channels:3,background:'blue'}}).png().toBuffer(),variants=await normalizeHighlightImage(changed,'image/png','landscape');await assert.rejects(upload({...s,variants}),code('asset_source_mismatch'));assert.equal(calls,2);assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0);});
test('missing native object cannot expose old bytes or only one ready representation',async()=>{const s=await setup(true),result=await upload(s),row=(await pool.query("SELECT o.asset_id,o.scope_id,o.representation_id FROM asset_objects o WHERE variant='thumb'")).rows[0];await bucket.delete(objectKey({assetId:row.asset_id,scopeId:row.scope_id,representationId:row.representation_id}));await assert.rejects(highlightImageBytes(pool,result.media_id,'thumb',s.store),code('media_unavailable'));assert.deepEqual(await highlightImageBytes(pool,result.media_id,'image',s.store),s.variants.image);});

test('canonical policy prohibition and pinned revision change after the last object read reject both variants',async()=>{for(const mutation of ['prohibition','revision'] as const){const s=await setup(),get=s.store.get.bind(s.store),locker=await fixture.connect();let gets=0,signal!:()=>void;const blocked=new Promise<void>(r=>signal=r);s.store.get=async(...args)=>{const value=await get(...args);if(++gets===4){await locker.query('BEGIN');await locker.query("SELECT purpose FROM domain_media_storage_policy WHERE purpose='community.event-highlight' FOR UPDATE");signal();}return value;};const pending=upload(s),outcome=pending.then(value=>({value}),error=>({error}));try{await blocked;let waiting=false;for(let i=0;i<80;i++){waiting=(await fixture.query("SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE query LIKE '%SELECT%domain_media_storage_policy%' AND wait_event_type='Lock' AND pid<>pg_backend_pid()) AS waiting")).rows[0].waiting;if(waiting)break;await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'publication must really wait on the canonical policy row');await locker.query(mutation==='revision'?"UPDATE domain_media_storage_policy SET policy_revision='synthetic-revoked-revision' WHERE purpose='community.event-highlight'":"UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.event-highlight'");await locker.query('COMMIT');const result=await outcome;assert.ok('error' in result);assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0);assert.ok((await pool.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));}finally{await locker.query('ROLLBACK');locker.release();await outcome;}await fixture.query("UPDATE domain_media_storage_policy SET policy_revision='synthetic-social-policy',persistence_allowed=true WHERE purpose='community.event-highlight'");}});
