import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import {migrate} from '../../scripts/database.js';
import {tokenHash,type Actor} from '../../modules/identity-membership/service.js';
import {createEventVideoAssetService,resolveEventVideoUploadPolicy} from '../../modules/assets/event-video.js';
import {saveEventVideo,readEventVideo,publicEventVideo,eventVideoHttp} from '../../modules/community/events.js';
import {FakeObjectStore} from '../../packages/asset-storage/fake-store.js';
import {sha256} from '../../packages/asset-storage/index.js';
import {createApp} from '../../apps/platform-api/src/app.js';
import {Problem} from '../../packages/shared/problem.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('Explicit isolated TEST_DATABASE_URL required');
const schema=`fp_video_${process.pid}_${Date.now()}`,admin=new Pool({connectionString:url}),pool=new Pool({connectionString:url,options:`-c search_path=${schema} -c statement_timeout=10000`});
const community=randomUUID();let initialized=false,mf:Miniflare,bucket:AssetR2Binding;
before(async()=>{await admin.query(`CREATE SCHEMA ${schema}`);initialized=true;await migrate(pool);mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'fp-video-domain-test',modules:true,script:'export default {fetch(){return new Response("synthetic");}}',compatibilityDate:'2026-09-21',r2Buckets:['MEDIA']}]}));await mf.ready;bucket=await mf.getR2Bucket('MEDIA') as unknown as AssetR2Binding;});
after(async()=>{await mf?.dispose();await pool.end();if(initialized)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
beforeEach(async()=>{await pool.query('TRUNCATE communities CASCADE');await pool.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-video-policy',persistence_allowed=true,retained_byte_limit=104857600 WHERE purpose='community.event-video'");await pool.query('INSERT INTO communities VALUES($1,$2)',[community,'Synthetic video']);});
async function member(){const id=randomUUID(),token=randomBytes(32).toString('base64url'),hash=tokenHash(token);const row=(await pool.query('INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,community,id+'@video.local.test','Synthetic owner','not-a-login-hash',randomUUID()])).rows[0];await pool.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[hash,id]);return {...row,session_hash:hash,csrf_token:'synthetic',synthetic_token:token} as Actor;}
async function setup(native=false){const owner=await member(),id=randomUUID();await pool.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic','Synthetic',clock_timestamp()+interval '2 days',clock_timestamp()+interval '3 days','online','Synthetic','pending','open','other')",[id,community,owner.user_id]);const store=native?{...createR2ObjectStore(bucket)}:new FakeObjectStore(),api=createEventVideoAssetService(pool,{store,resolvePolicy:resolveEventVideoUploadPolicy});return {owner,id,store,api};}
function mp4(size=64){const bytes=Buffer.alloc(size,7);bytes.write('ftyp',4,'ascii');return bytes;}
function webm(){return Buffer.from([0x1a,0x45,0xdf,0xa3,1,2,3,4]);}
async function upload(s:Awaited<ReturnType<typeof setup>>,bytes=mp4(),mime:'video/mp4'|'video/webm'='video/mp4',version='1'){const prepared=await s.api.prepare(s.owner,{key:randomUUID(),targetEventId:s.id,expectedVersion:version,contentType:mime,byteSize:bytes.length,sha256:await sha256(bytes)});const claim=await s.api.claim(s.owner,{key:randomUUID(),intentId:prepared.intentId});const lease={intentId:claim.intentId,fence:claim.fence,leaseToken:claim.leaseToken};await s.api.write(s.owner,{key:randomUUID(),...lease},new ReadableStream({start(c){c.enqueue(bytes);c.close();}}));return {...prepared,lease};}
const code=(c:string)=>(e:unknown)=>e instanceof Problem&&e.code===c;
test('20MiB native R2 publication and full SHA readback; conditional HTTP range never downloads full object',async()=>{const s=await setup(true),bytes=mp4(20*1024*1024),u=await upload(s,bytes);assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_videos')).rows[0].n,0);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});assert.equal((await pool.query('SELECT scope_kind FROM assets')).rows[0].scope_kind,'community');assert.deepEqual((await readEventVideo(pool,s.owner,s.id,s.store)).bytes,bytes);const get=s.store.get.bind(s.store),ranges:any[]=[];s.store.get=async(key,range)=>{ranges.push(range);return get(key,range);};const head=await eventVideoHttp(pool,s.id,{method:'HEAD',rangeHeader:'bytes=0-9'},s.store,s.owner);assert.equal(head.plan.status,200);assert.equal(head.body,null);assert.equal(head.plan.headers['content-length'],String(bytes.length));assert.equal(ranges.length,0);const ranged=await eventVideoHttp(pool,s.id,{method:'GET',rangeHeader:'bytes=12-1048587',ifRangeHeader:head.plan.headers.etag},s.store,s.owner);assert.equal(ranged.plan.status,206);assert.equal(ranged.wholeDigestVerified,false);assert.deepEqual(ranges,[{offset:12,length:1048576}]);const stream=ranged.body as ReadableStream<Uint8Array>,reader=stream.getReader();const first=await reader.read();assert.ok(first.value?.length);await reader.cancel();reader.releaseLock();const unsat=await eventVideoHttp(pool,s.id,{method:'GET',rangeHeader:`bytes=${bytes.length}-`},s.store,s.owner);assert.equal(unsat.plan.status,416);assert.equal(unsat.body,null);assert.equal(ranges.length,1);const full=await eventVideoHttp(pool,s.id,{method:'GET',rangeHeader:'bytes=0-9',ifRangeHeader:'"wrong"'},s.store,s.owner);assert.equal(full.plan.status,200);assert.equal(full.wholeDigestVerified,true);assert.deepEqual(full.body,new Uint8Array(bytes));assert.equal(ranges.length,2);assert.equal(ranges[1],undefined);});
test('original video HTTP receipt/URL/ETag and replay/removal semantics survive Asset publication',async()=>{const s=await setup(),origin='http://127.0.0.1:4310',app=createApp(pool,origin,'local',{eventVideoAssets:s.api,eventVideoAssetStore:s.store}),key=randomUUID(),headers={Origin:origin,Cookie:`freedom_local_session=${(s.owner as Actor&{synthetic_token:string}).synthetic_token}`,'X-CSRF-Token':'synthetic','Content-Type':'video/webm','Idempotency-Key':key,'If-Match':'"1"'},path=`/api/v1/events/${s.id}/video`;const send=()=>app.request(origin+path,{method:'POST',headers,body:new Uint8Array(webm())});const response=await send(),dto=await response.json() as any;assert.equal(response.status,200,JSON.stringify(dto));assert.equal(response.headers.get('etag'),'"2"');assert.equal(dto.video_url,path+'?v=2');assert.equal(dto.video_mime,'video/webm');assert.deepEqual(await (await send()).json(),dto);const read=await app.request(origin+path,{headers:{Cookie:headers.Cookie,Range:'bytes=0-3'}});assert.equal(read.status,206);assert.deepEqual(new Uint8Array(await read.arrayBuffer()),new Uint8Array(webm().subarray(0,4)));const removed=await saveEventVideo(pool,{actor:s.owner,operation:`POST ${path}/remove`,key:randomUUID(),expected:'2',body:null},s.id,null);assert.equal(removed.video_url,null);assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'retired');await assert.rejects(readEventVideo(pool,s.owner,s.id,s.store),code('media_not_found'));});
test('raw video header/size bounds and closed caller input fail before immutable PUT',async()=>{const s=await setup();let writes=0;const put=s.store.putImmutable.bind(s.store);s.store.putImmutable=async(...args)=>{writes++;return put(...args);};const input={key:randomUUID(),targetEventId:s.id,expectedVersion:'1',contentType:'video/mp4' as const,byteSize:64,sha256:await sha256(mp4())};await assert.rejects(s.api.prepare(s.owner,{...input,byteSize:20971521}));await assert.rejects(s.api.prepare(s.owner,{...input,scopeId:randomUUID()} as any));await assert.rejects(upload(s,Buffer.alloc(64)),(e:any)=>e.code==='invalid_content');assert.equal(writes,0);assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_videos')).rows[0].n,0);});
test('canonical denial, foreign organizer, stale CAS and future clock never publish',async()=>{const s=await setup(),peer=await member(),input={key:randomUUID(),targetEventId:s.id,expectedVersion:'1',contentType:'video/mp4' as const,byteSize:64,sha256:await sha256(mp4())};await assert.rejects(s.api.prepare(peer,input),code('organizer_required'));const u=await upload(s);await pool.query('UPDATE community_events SET aggregate_version=2 WHERE event_id=$1',[s.id]);await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('version_conflict'));await pool.query('UPDATE community_events SET aggregate_version=1 WHERE event_id=$1',[s.id]);await pool.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.event-video'");await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('media_upload_unavailable'));assert.equal((await pool.query('SELECT count(*)::int n FROM community_event_videos')).rows[0].n,0);await pool.query("UPDATE domain_media_storage_policy SET persistence_allowed=true WHERE purpose='community.event-video'");await pool.query("UPDATE community_events SET starts_at=clock_timestamp()-interval '1 minute' WHERE event_id=$1",[s.id]);await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('event_closed'));});
test('public ACL recheck cancels obtained partial stream before returning denied content',async()=>{const s=await setup(),u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});await assert.rejects(publicEventVideo(pool,s.id,s.store),code('media_not_found'));await pool.query("UPDATE community_events SET state='published',aggregate_version=3 WHERE event_id=$1",[s.id]);let cancelled=false,pulls=0;const get=s.store.get.bind(s.store);s.store.get=async(key,range)=>{const real=await get(key,range);await pool.query("UPDATE community_events SET state='cancelled' WHERE event_id=$1",[s.id]);return {...real!,body:new ReadableStream<Uint8Array>({pull(){pulls++;},cancel(){cancelled=true;}},{highWaterMark:0})};};await assert.rejects(eventVideoHttp(pool,s.id,{method:'GET',rangeHeader:'bytes=0-3'},s.store),code('media_not_found'));assert.equal(cancelled,true);assert.equal(pulls,0);});
test('bridge preserves legacy bytes, replacement retires prior object and no transport never falls back',async()=>{const s=await setup(),bytes=mp4();await pool.query("INSERT INTO community_event_videos(event_id,media_bytes,mime_type) VALUES($1,$2,'video/mp4')",[s.id,bytes]);assert.deepEqual((await readEventVideo(pool,s.owner,s.id)).bytes,bytes);const a=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...a.lease});assert.deepEqual((await pool.query('SELECT media_bytes FROM community_event_videos')).rows[0].media_bytes,bytes);await assert.rejects(eventVideoHttp(pool,s.id,{method:'HEAD'},undefined,s.owner),code('media_unavailable'));const b=await upload(s,webm(),'video/webm','2');await s.api.finalize(s.owner,{key:randomUUID(),...b.lease});assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[a.assetId])).rows[0].state,'retired');await assert.rejects(pool.query("UPDATE domain_media_storage_policy SET mode='r2_only' WHERE purpose='community.event-video'"),(e:any)=>e.code==='23514');});

test('active guild interns cannot prepare video, and SQL rejects ready pointer forgery',async()=>{const s=await setup();await pool.query("UPDATE community_events SET event_kind='guild_skill_exchange',guild_key='guild_security' WHERE event_id=$1",[s.id]);await pool.query("INSERT INTO positioning_profession_memberships(membership_id,community_id,user_id,guild_key,state,member_tier) VALUES($1,$2,$3,'guild_security','active','intern')",[randomUUID(),community,s.owner.user_id]);await assert.rejects(upload(s),code('guild_full_member_required'));await assert.rejects(pool.query("INSERT INTO community_event_videos(event_id,media_bytes,mime_type,storage_source) VALUES($1,NULL,'video/mp4','asset')",[s.id]),(e:any)=>e.code==='23514');await assert.rejects(pool.query("UPDATE domain_media_storage_policy SET mode='bridge' WHERE purpose='community.event-highlight'"),(e:any)=>e.code==='23514');});
