import { test,before,after,beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import sharp from 'sharp';
import { migrate } from '../../scripts/database.js';
import { tokenHash,type Actor } from '../../modules/identity-membership/service.js';
import { createServiceCoverAssetService,resolveServiceCoverUploadPolicy } from '../../modules/assets/media-domain.js';
import { FakeObjectStore } from '../../packages/asset-storage/fake-store.js';
import { sha256 } from '../../packages/asset-storage/index.js';
import { backfillServiceCover,readDomainMedia,type DomainMediaSnapshot } from '../../packages/media-migration/domain-bridge.js';
import { Problem } from '../../packages/shared/problem.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('Explicit isolated TEST_DATABASE_URL required');
const schema=`fp_media_bridge_${process.pid}_${Date.now()}`,admin=new Pool({connectionString:url}),pool=new Pool({connectionString:url,options:`-c search_path=${schema} -c statement_timeout=10000`});
const community=randomUUID();let png:Buffer,initialized=false,initialPolicy:Record<string,unknown>;
before(async()=>{await admin.query(`CREATE SCHEMA ${schema}`);initialized=true;await migrate(pool);initialPolicy=(await pool.query("SELECT mode,policy_revision,persistence_allowed,retained_byte_limit FROM domain_media_storage_policy WHERE purpose='member.service-cover'")).rows[0];png=await sharp({create:{width:30,height:20,channels:3,background:'green'}}).png().toBuffer();});
after(async()=>{await pool.end();if(initialized)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
beforeEach(async()=>{await pool.query('TRUNCATE communities CASCADE');await pool.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-v1',persistence_allowed=true,retained_byte_limit=10485760 WHERE purpose='member.service-cover'");await pool.query('INSERT INTO communities VALUES($1,$2)',[community,'Synthetic media']);});
async function member(){const id=randomUUID(),hash=tokenHash(randomUUID());const row=(await pool.query('INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,community,id+'@media.local.test','Synthetic owner','not-a-login-hash',randomUUID()])).rows[0];await pool.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[hash,id]);return {...row,session_hash:hash,csrf_token:'synthetic'} as Actor;}
async function setup(){const owner=await member(),id=randomUUID();await pool.query("INSERT INTO member_services(service_id,community_id,owner_user_id,title,category,summary,service_mode,contacts,state) VALUES($1,$2,$3,'Synthetic','other','Synthetic','online','[{}]','active')",[id,community,owner.user_id]);const store=new FakeObjectStore(),api=createServiceCoverAssetService(pool,{store,resolvePolicy:async()=>({revision:'synthetic-v1',platformPersistenceAllowed:true,retainedByteLimit:'10485760'})});return {owner,id,store,api};}
async function upload(s:Awaited<ReturnType<typeof setup>>,version='1'){const prepared=await s.api.prepare(s.owner,{key:randomUUID(),targetServiceId:s.id,expectedVersion:version,contentType:'image/png',byteSize:png.length,sha256:await sha256(png)});const claim=await s.api.claim(s.owner,{key:randomUUID(),intentId:prepared.intentId});const lease={intentId:claim.intentId,fence:claim.fence,leaseToken:claim.leaseToken};await s.api.write(s.owner,{key:randomUUID(),...lease},new ReadableStream({start(c){c.enqueue(png);c.close();}}));return {...prepared,lease};}
const code=(c:string)=>(e:unknown)=>e instanceof Problem&&e.code===c;
test('service cover publication preserves absence until commit and typed metadata survives readback',async()=>{const s=await setup(),u=await upload(s);assert.equal((await pool.query('SELECT count(*)::int AS n FROM member_service_covers')).rows[0].n,0);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});const row=(await pool.query('SELECT c.storage_source,c.image_bytes,t.asset_id,o.profile_id FROM member_service_covers c JOIN member_service_cover_asset_targets t USING(service_id) JOIN asset_objects o USING(asset_id)')).rows[0];assert.equal(row.storage_source,'asset');assert.equal(row.image_bytes,null);assert.equal(row.asset_id,u.assetId);assert.equal(row.profile_id,'member.service-cover');});
test('replacement retires previous asset; original cover deletion clears pointer and retires replacement',async()=>{const s=await setup(),a=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...a.lease});const b=await upload(s,'2');await s.api.finalize(s.owner,{key:randomUUID(),...b.lease});assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[a.assetId])).rows[0].state,'retired');await pool.query('DELETE FROM member_service_covers WHERE service_id=$1',[s.id]);assert.equal((await pool.query('SELECT asset_id FROM member_service_cover_asset_targets WHERE service_id=$1',[s.id])).rows[0].asset_id,null);assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[b.assetId])).rows[0].state,'retired');});
test('foreign owner cannot route a cover intent and stale domain CAS cannot publish',async()=>{const s=await setup(),other=await member();await assert.rejects(s.api.prepare(other,{key:randomUUID(),targetServiceId:s.id,expectedVersion:'1',contentType:'image/png',byteSize:png.length,sha256:await sha256(png)}),code('asset_target_not_found'));const u=await upload(s);await pool.query('UPDATE member_services SET aggregate_version=aggregate_version+1 WHERE service_id=$1',[s.id]);await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('version_conflict'));assert.equal((await pool.query('SELECT count(*)::int AS n FROM member_service_covers')).rows[0].n,0);});
test('database rejects an asset cover without its typed ready pointer',async()=>{const s=await setup();await assert.rejects(pool.query("INSERT INTO member_service_covers(service_id,image_bytes,storage_source) VALUES($1,NULL,'asset')",[s.id]),(e:any)=>e.code==='23514');});
test('legacy read detects source mutation even without aggregate version change',async()=>{let n=0;const row:DomainMediaSnapshot={purpose:'member.service-cover',targetId:randomUUID(),variant:'cover',domainVersion:'1',source:'legacy',authorizationVersion:'owner-active',legacyBytes:Buffer.from('old'),assetId:null,scopeId:null,representationId:null,metadata:null};await assert.rejects(readDomainMedia(async()=>({...row,legacyBytes:Buffer.from(n++?'new':'old')}),{purpose:row.purpose,targetId:row.targetId,variant:'cover'}),code('media_not_found'));});
test('asset attachment without object transport cannot fall back to retained database bytes',async()=>{const row:DomainMediaSnapshot={purpose:'member.service-cover',targetId:randomUUID(),variant:'cover',domainVersion:'1',source:'asset',authorizationVersion:'active',legacyBytes:Buffer.from('retained'),assetId:randomUUID(),scopeId:randomUUID(),representationId:randomUUID(),metadata:null};await assert.rejects(readDomainMedia(async()=>row,{purpose:row.purpose,targetId:row.targetId,variant:'cover'}),code('media_unavailable'));});
async function coverSnapshot(s:Awaited<ReturnType<typeof setup>>):Promise<DomainMediaSnapshot|undefined>{
 const r=(await pool.query(`SELECT s.aggregate_version,c.storage_source,c.image_bytes,t.asset_id,t.scope_id,o.representation_id,o.content_type,o.byte_size,o.content_sha256,o.transform_version,o.policy_revision,o.profile_id FROM member_services s JOIN member_service_covers c USING(service_id) LEFT JOIN member_service_cover_asset_targets t USING(service_id) LEFT JOIN asset_objects o ON o.asset_id=t.asset_id WHERE s.service_id=$1 AND s.owner_user_id=$2 AND s.state IN ('active','paused')`,[s.id,s.owner.user_id])).rows[0];
 if(!r)return;return {purpose:'member.service-cover',targetId:s.id,variant:'cover',domainVersion:r.aggregate_version,source:r.storage_source,authorizationVersion:'owner-active',legacyBytes:r.image_bytes,assetId:r.asset_id,scopeId:r.scope_id,representationId:r.representation_id,metadata:r.profile_id?{profileId:r.profile_id,contentType:r.content_type,byteSize:r.byte_size,sha256:r.content_sha256,transformVersion:r.transform_version,policyRevision:r.policy_revision}:null};
}
test('verified asset read returns original WebP and rechecks SQL ACL after object IO',async()=>{const s=await setup(),u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});const expected={purpose:'member.service-cover' as const,targetId:s.id,variant:'cover' as const};const read=await readDomainMedia(()=>coverSnapshot(s),expected,s.store);assert.equal(read.contentType,'image/webp');assert.equal((await sharp(read.bytes).metadata()).format,'webp');const get=s.store.get.bind(s.store);s.store.get=async(...args)=>{const object=await get(...args);await pool.query("UPDATE member_services SET state='hidden',aggregate_version=aggregate_version+1 WHERE service_id=$1",[s.id]);return object;};await assert.rejects(readDomainMedia(()=>coverSnapshot(s),expected,s.store),code('media_not_found'));});
test('bridge retains historical bytes yet asset reads refuse cross-purpose metadata',async()=>{const s=await setup();await pool.query('INSERT INTO member_service_covers(service_id,image_bytes) VALUES($1,$2)',[s.id,png]);const u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});assert.deepEqual((await pool.query('SELECT image_bytes FROM member_service_covers WHERE service_id=$1',[s.id])).rows[0].image_bytes,png);await assert.rejects(pool.query("UPDATE domain_media_storage_policy SET mode='r2_only' WHERE purpose='member.service-cover'"),(e:any)=>e.code==='23514');const row=(await coverSnapshot(s))!;await assert.rejects(readDomainMedia(async()=>({...row,metadata:{...row.metadata!,profileId:'community.social-thumbnail'}}),{purpose:'member.service-cover',targetId:s.id,variant:'cover'},s.store),code('media_unavailable'));});
test('typed pointer cannot disappear while the asset attachment remains published',async()=>{const s=await setup(),u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});await assert.rejects(pool.query('UPDATE member_service_cover_asset_targets SET asset_id=NULL WHERE service_id=$1',[s.id]),(e:any)=>e.code==='23514');assert.equal((await coverSnapshot(s))!.assetId,u.assetId);});
test('other domain modes default to legacy and unknown purposes cannot enter the finite registry',async()=>{const rows=(await pool.query("SELECT purpose,mode FROM domain_media_storage_policy WHERE purpose<>'member.service-cover'")).rows;assert.equal(rows.length,6);assert.ok(rows.every(r=>r.mode==='legacy'));await assert.rejects(pool.query("INSERT INTO domain_media_storage_policy(purpose) VALUES('future.unknown')"),(e:any)=>e.code==='23514');});

async function legacyCover(s:Awaited<ReturnType<typeof setup>>){const bytes=await sharp(png).resize(1200,675).webp({quality:80}).toBuffer();await pool.query('INSERT INTO member_service_covers(service_id,image_bytes) VALUES($1,$2)',[s.id,bytes]);return bytes;}
function backfillDeps(s:Awaited<ReturnType<typeof setup>>){return {store:s.store,resolvePolicy:async()=>({revision:'synthetic-v1',platformPersistenceAllowed:true,retainedByteLimit:'10485760'})};}
test('authenticated backfill preserves exact original bytes and same-key replay creates no second publication',async()=>{const s=await setup(),bytes=await legacyCover(s),input={key:randomUUID(),serviceId:s.id,expectedVersion:'1'};const result=await backfillServiceCover(pool,backfillDeps(s),s.owner,input);assert.equal(result.aggregateVersion,'2');const read=await readDomainMedia(()=>coverSnapshot(s),{purpose:'member.service-cover',targetId:s.id,variant:'cover'},s.store);assert.deepEqual(read.bytes,bytes);assert.deepEqual(await backfillServiceCover(pool,backfillDeps(s),s.owner,input),result);assert.equal((await pool.query('SELECT count(*)::int AS n FROM assets')).rows[0].n,1);assert.deepEqual((await pool.query('SELECT image_bytes FROM member_service_covers WHERE service_id=$1',[s.id])).rows[0].image_bytes,bytes);});
test('lost PUT response is recovered by verified readback and replay keeps the same intent',async()=>{const s=await setup(),bytes=await legacyCover(s),input={key:randomUUID(),serviceId:s.id,expectedVersion:'1'};s.store.failNext('put-after');const result=await backfillServiceCover(pool,backfillDeps(s),s.owner,input);assert.deepEqual(await backfillServiceCover(pool,backfillDeps(s),s.owner,input),result);assert.equal(result.aggregateVersion,'2');assert.equal((await pool.query('SELECT count(*)::int AS n FROM asset_upload_intents')).rows[0].n,1);assert.deepEqual((await pool.query('SELECT image_bytes FROM member_service_covers WHERE service_id=$1',[s.id])).rows[0].image_bytes,bytes);});
test('legacy bytes changed during immutable PUT cannot publish even if domain version was not advanced',async()=>{const s=await setup();await legacyCover(s);const put=s.store.putImmutable.bind(s.store);s.store.putImmutable=async(...args)=>{const result=await put(...args);await pool.query('UPDATE member_service_covers SET image_bytes=$2 WHERE service_id=$1',[s.id,png]);return result;};await assert.rejects(backfillServiceCover(pool,backfillDeps(s),s.owner,{key:randomUUID(),serviceId:s.id,expectedVersion:'1'}),code('media_source_changed'));const row=(await pool.query('SELECT storage_source FROM member_service_covers WHERE service_id=$1',[s.id])).rows[0];assert.equal(row.storage_source,'legacy');assert.equal((await pool.query('SELECT aggregate_version FROM member_services WHERE service_id=$1',[s.id])).rows[0].aggregate_version,'1');assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'pending');});
test('new backfill key cannot republish retained historical bytes of an already-asset cover',async()=>{const s=await setup();await legacyCover(s);await backfillServiceCover(pool,backfillDeps(s),s.owner,{key:randomUUID(),serviceId:s.id,expectedVersion:'1'});await assert.rejects(backfillServiceCover(pool,backfillDeps(s),s.owner,{key:randomUUID(),serviceId:s.id,expectedVersion:'2'}),code('media_source_changed'));assert.equal((await pool.query('SELECT count(*)::int AS n FROM assets')).rows[0].n,1);});
test('backfill requires current member session and owner before source bytes or object IO',async()=>{const s=await setup();await legacyCover(s);const peer=await member();let puts=0;const put=s.store.putImmutable.bind(s.store);s.store.putImmutable=async(...args)=>{puts++;return put(...args);};await assert.rejects(backfillServiceCover(pool,backfillDeps(s),peer,{key:randomUUID(),serviceId:s.id,expectedVersion:'1'}),code('asset_target_not_found'));await pool.query('UPDATE sessions SET revoked_at=clock_timestamp() WHERE token_hash=$1',[s.owner.session_hash]);await assert.rejects(backfillServiceCover(pool,backfillDeps(s),s.owner,{key:randomUUID(),serviceId:s.id,expectedVersion:'1'}));assert.equal(puts,0);assert.equal((await pool.query('SELECT count(*)::int AS n FROM assets')).rows[0].n,0);});

test('unavailable PUT resumes existing pending intent after transport recovers',async()=>{const s=await setup();await legacyCover(s);const input={key:randomUUID(),serviceId:s.id,expectedVersion:'1'};s.store.failNext('put-before');await assert.rejects(backfillServiceCover(pool,backfillDeps(s),s.owner,input));assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'pending');const result=await backfillServiceCover(pool,backfillDeps(s),s.owner,input);assert.equal(result.aggregateVersion,'2');assert.equal((await pool.query('SELECT count(*)::int AS n FROM asset_upload_intents')).rows[0].n,1);});
test('mode alone and a true installed callback cannot grant canonical persistence',async()=>{const s=await setup();await pool.query("UPDATE domain_media_storage_policy SET persistence_allowed=false,policy_revision=NULL,retained_byte_limit=NULL WHERE purpose='member.service-cover'");await assert.rejects(upload(s),code('media_upload_unavailable'));assert.equal((await pool.query('SELECT count(*)::int AS n FROM assets')).rows[0].n,0);});
test('revoked canonical persistence after stored IO forbids publication',async()=>{const s=await setup(),u=await upload(s);await pool.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='member.service-cover'");await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('media_upload_unavailable'));assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[u.assetId])).rows[0].state,'pending');});
test('changed canonical revision and lowered canonical quota cannot be overridden by installed settings',async()=>{const s=await setup(),u=await upload(s);await pool.query("UPDATE domain_media_storage_policy SET policy_revision='synthetic-v2' WHERE purpose='member.service-cover'");await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('media_upload_unavailable'));await pool.query("UPDATE domain_media_storage_policy SET policy_revision='synthetic-v1',retained_byte_limit=524288 WHERE purpose='member.service-cover'");await assert.rejects(s.api.prepare(s.owner,{key:randomUUID(),targetServiceId:s.id,expectedVersion:'1',contentType:'image/png',byteSize:png.length,sha256:await sha256(png)}),code('asset_retained_quota'));});
test('policy prohibition committed while publication waits is observed before ready pointer publication',async()=>{const s=await setup(),u=await upload(s),blocker=await pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='member.service-cover'");let settled=false;const pending=s.api.finalize(s.owner,{key:randomUUID(),...u.lease}).finally(()=>{settled=true;});const rejected=assert.rejects(pending,code('media_upload_unavailable'));try{const pid=(await blocker.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;let blocked=false;for(let n=0;n<100;n++){blocked=(await pool.query('SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND $1=ANY(pg_blocking_pids(pid))) AS blocked',[pid])).rows[0].blocked;if(blocked)break;await new Promise(r=>setTimeout(r,10));}assert.equal(blocked,true,'actual PostgreSQL policy lock wait must be observed');assert.equal(settled,false);await blocker.query('COMMIT');}finally{await blocker.query('ROLLBACK');blocker.release();}await rejected;assert.equal((await pool.query('SELECT count(*)::int AS n FROM member_service_covers')).rows[0].n,0);});

test('fresh additive migration leaves canonical cover persistence prohibited with no invented settings',()=>{assert.deepEqual(initialPolicy,{mode:'legacy',policy_revision:null,persistence_allowed:false,retained_byte_limit:null});});

test('canonical installed resolver still rejects an intent pinned to a changed database revision',async()=>{const original=await setup(),s={...original,api:createServiceCoverAssetService(pool,{store:original.store,resolvePolicy:resolveServiceCoverUploadPolicy})},u=await upload(s);await pool.query("UPDATE domain_media_storage_policy SET policy_revision='synthetic-v2' WHERE purpose='member.service-cover'");await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('asset_policy_changed'));});
