import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { z } from 'zod';
import type { Pool } from 'pg';
// @ts-expect-error Existing host-only clean environment helper is an ESM JavaScript module.
import { verificationEnvironment } from '../../packages/contribution-tools/process-env.mjs';
import {
  MemberExecutionHttpRunCreateSchema, MemberExecutionHttpEmptySchema, MemberExecutionHttpModelCreateSchema,
  MemberExecutionHttpGrantCreateSchema, MemberExecutionHttpAttemptCreateSchema, MemberExecutionHttpRunMetadataSchema,
} from '../../contracts/execution/v1/member-execution-http.js';
import { createMemberExecutionHttpTransport } from '../../apps/platform-api/src/routes/member-execution-http.js';
import { readBoundedHttpJson } from '../../packages/execution-state/http-body.js';

const root = fileURLToPath(new URL('../../', import.meta.url));
const id = '12345678-1234-4234-8234-123456789abc';
const selection = { providerRef: 'synthetic-provider', modelRef: 'synthetic-model', processingLocation: 'provider_remote',
  artifactCustody: 'platform_asset', credentialCustody: 'official_cli', engineLocation: 'runtime_local', billingSource: 'user_cli' };
interface Case { name: string; value: unknown; valid: boolean }
interface Profile { name: string; schema: z.ZodType; value: Record<string, unknown> }
const profiles: Profile[] = [
  { name: 'member-execution-http-run-create', schema: MemberExecutionHttpRunCreateSchema, value: { workId: id } },
  { name: 'member-execution-http-empty', schema: MemberExecutionHttpEmptySchema, value: {} },
  { name: 'member-execution-http-model-create', schema: MemberExecutionHttpModelCreateSchema, value: { connectionId: id, selection } },
  { name: 'member-execution-http-grant-create', schema: MemberExecutionHttpGrantCreateSchema,
    value: { expectedWorkVersion: '1', connectionId: id, expectedConnectionVersion: '1', modelConnectionId: id, expectedModelVersion: '1', consent: true } },
  { name: 'member-execution-http-attempt-create', schema: MemberExecutionHttpAttemptCreateSchema, value: { grantId: id, expectedGrantVersion: '1' } },
  { name: 'member-execution-http-run-metadata', schema: MemberExecutionHttpRunMetadataSchema,
    value: { runId: id, workId: id, inputWorkVersion: '1', aggregateVersion: '1', state: 'created', taskLeaseEpoch: '1', controlEpoch: '1', operational_authority: false } },
];
function parity(profile: Profile, cases: Case[]) {
  for (const item of cases) assert.equal(profile.schema.safeParse(item.value).success, item.valid, `${profile.name}: ${item.name}`);
  const schema = JSON.parse(readFileSync(new URL(`../../contracts/execution/v1/${profile.name}.schema.json`, import.meta.url), 'utf8'));
  const script = `import json,sys
from jsonschema import Draft202012Validator,FormatChecker
payload=json.load(sys.stdin)
Draft202012Validator.check_schema(payload['schema'])
validator=Draft202012Validator(payload['schema'],format_checker=FormatChecker())
for case in payload['cases']:
    assert validator.is_valid(case['value']) == case['valid'], case['name']
print('conformant')`;
  const result = spawnSync('python3', ['-c', script], { cwd: root, env: verificationEnvironment(), encoding: 'utf8',
    input: JSON.stringify({ schema, cases }), timeout: 30000, maxBuffer: 128 * 1024 });
  assert.equal(result.status, 0, `${profile.name}\n${result.stdout}${result.stderr}`);
  assert.equal(result.stdout.trim(), 'conformant');
}

test('member execution HTTP contracts regenerate deterministically and match generated bytes', () => {
  const result = spawnSync(process.execPath, ['--import', 'tsx', 'modules/agent-execution/generate-member-execution-http.ts', '--check'], {
    cwd: root, env: verificationEnvironment(), encoding: 'utf8', timeout: 30000, maxBuffer: 128 * 1024,
  });
  assert.equal(result.status, 0, result.stdout + result.stderr);
});

test('all generated HTTP schemas and Zod reject caller authority and require exact bodies', () => {
  for (const profile of profiles) {
    const cases: Case[] = [{ name: 'valid minimal shape', value: profile.value, valid: true }];
    for (const value of [null, [], '', true, 1]) cases.push({ name: `non-object ${JSON.stringify(value)}`, value, valid: false });
    for (const field of Object.keys(profile.value)) {
      const incomplete = { ...profile.value }; delete incomplete[field];
      cases.push({ name: `missing ${field}`, value: incomplete, valid: false });
      cases.push({ name: `null ${field}`, value: { ...profile.value, [field]: null }, valid: false });
    }
    for (const field of ['key', 'actor', 'Actor', 'owner', 'ownerUserId', 'ownerPrincipalId', 'scopeId', 'expectedVersion',
      'expectedRunVersion', 'ttl', 'expiresAt', 'modelReady', 'model_ready', 'inferenceRef', 'token', 'accessToken',
      'providerEndpoint', 'secretRef', 'recoveryGeneration', 'operationalAuthority']) {
      cases.push({ name: `unknown authority ${field}`, value: { ...profile.value, [field]: 'synthetic' }, valid: false });
    }
    if (profile.name !== 'member-execution-http-run-metadata') {
      cases.push({ name: 'body cannot assert false authority', value: { ...profile.value, operational_authority: false }, valid: false });
    } else {
      cases.push({ name: 'response cannot grant authority', value: { ...profile.value, operational_authority: true }, valid: false });
    }
    for (const field of Object.keys(profile.value).filter(name => name.endsWith('Id'))) {
      for (const value of ['not-a-uuid', id.toUpperCase(), id + '\n', '12345678-1234-0234-8234-123456789abc',
        '12345678-1234-4234-1234-123456789abc', id.replaceAll('-', ''), 1]) {
        cases.push({ name: `invalid UUID ${field}: ${JSON.stringify(value)}`, value: { ...profile.value, [field]: value }, valid: false });
      }
    }
    parity(profile, cases);
  }
});

test('required secondary CAS and Run metadata versions preserve exact signed64 JSON parity', () => {
  for (const profile of profiles.filter(item => ['member-execution-http-grant-create', 'member-execution-http-attempt-create',
    'member-execution-http-run-metadata'].includes(item.name))) {
    const fields = Object.keys(profile.value).filter(name => name.endsWith('Version') || name.endsWith('Epoch'));
    const cases: Case[] = [];
    for (const field of fields) {
      for (const value of ['1', '999999999999999999', '1000000000000000000', '9223372036854775806', '9223372036854775807']) {
        cases.push({ name: `valid signed64 ${field}: ${value}`, value: { ...profile.value, [field]: value }, valid: true });
      }
      for (const value of ['0', '01', '-1', '+1', '1.0', '1e1', '1\n', '1\r', ' 1', '1 ', '１',
        '9223372036854775808', '9999999999999999999', '10000000000000000000', 1, 9007199254740991, null, false]) {
        cases.push({ name: `invalid signed64 ${field}: ${JSON.stringify(value)}`, value: { ...profile.value, [field]: value }, valid: false });
      }
    }
    parity(profile, cases);
  }
});

test('nested selections remain explicit and reject wrong custody, defaults, secrets and owner fields', () => {
  const profile = profiles.find(item => item.name === 'member-execution-http-model-create')!;
  const cases: Case[] = [];
  const variants = [selection, { ...selection, credentialCustody: 'local_keychain', billingSource: 'user_byok' },
    { ...selection, credentialCustody: 'platform_vault', engineLocation: 'platform', billingSource: 'user_byok' }];
  for (const variant of variants) {
    cases.push({ name: `valid selection ${variant.credentialCustody}`, value: { connectionId: id, selection: variant }, valid: true });
    for (const field of Object.keys(variant)) {
      const incomplete = { ...variant } as Record<string, unknown>; delete incomplete[field];
      cases.push({ name: `missing ${variant.credentialCustody}.${field}`, value: { connectionId: id, selection: incomplete }, valid: false });
    }
    for (const field of ['owner', 'ownerPrincipalId', 'scopeId', 'actor', 'modelReady', 'operational_authority', 'inferenceRef',
      'fallback', 'secretRef', 'apiKey', 'authEvidence', 'localHandle', 'providerEndpoint']) {
      cases.push({ name: `nested unknown ${variant.credentialCustody}.${field}`, value: { connectionId: id,
        selection: { ...variant, [field]: false } }, valid: false });
    }
    for (const engineLocation of ['runtime_local', 'platform']) for (const billingSource of ['user_cli', 'user_byok', 'platform_system']) {
      const valid = variant.credentialCustody === 'official_cli' ? engineLocation === 'runtime_local' && billingSource === 'user_cli'
        : variant.credentialCustody === 'local_keychain' ? engineLocation === 'runtime_local' && billingSource === 'user_byok'
          : engineLocation === 'platform' && billingSource === 'user_byok';
      cases.push({ name: `binding ${variant.credentialCustody}/${engineLocation}/${billingSource}`,
        value: { connectionId: id, selection: { ...variant, engineLocation, billingSource } }, valid });
    }
  }
  for (const field of ['providerRef', 'modelRef', 'processingLocation']) {
    for (const value of ['', 'x'.repeat(97), 'x\n', 'https://synthetic.invalid', 'x y', null]) {
      cases.push({ name: `invalid label ${field}: ${JSON.stringify(value)}`,
        value: { connectionId: id, selection: { ...selection, [field]: value } }, valid: false });
    }
  }
  parity(profile, cases);
});

test('Grant consent stays literal true and Run metadata admits only closed record states', () => {
  const grant = profiles.find(item => item.name === 'member-execution-http-grant-create')!;
  parity(grant, [false, 'true', 1, {}, null].map(value => ({ name: `invalid consent ${JSON.stringify(value)}`,
    value: { ...grant.value, consent: value }, valid: false })));
  const run = profiles.find(item => item.name === 'member-execution-http-run-metadata')!;
  parity(run, [
    ...['created', 'paused', 'cancelled'].map(state => ({ name: `closed state ${state}`, value: { ...run.value, state }, valid: true })),
    ...['ready', 'preflighting', 'running', 'completed', 'reconciling', 'failed'].map(state => ({ name: `operational state ${state}`,
      value: { ...run.value, state }, valid: false })),
    ...['currentAttemptId', 'lease', 'grantId', 'inferenceBindingId', 'privateContent', 'sessionHash'].map(field => ({
      name: `expanded Run ${field}`, value: { ...run.value, [field]: 'synthetic' }, valid: false })),
  ]);
});

test('HTTP configuration confines plaintext to explicit local loopback and rejects Hono HEAD before DB access', async () => {
  let queries = 0;
  const forbiddenPool = { query() { queries++; throw new Error('Unexpected database access.'); },
    connect() { queries++; throw new Error('Unexpected database access.'); } } as unknown as Pool;
  for (const environment of ['next', 'staging-next', 'local'] as const) {
    await assert.rejects(createMemberExecutionHttpTransport(forbiddenPool, {
      origin: 'http://synthetic.invalid', environment, clientId: 'synthetic-client',
    }), /invalid_member_execution_http_configuration/);
    if (environment !== 'local') {
      await assert.rejects(createMemberExecutionHttpTransport(forbiddenPool, {
        origin: 'http://127.0.0.1:4311', environment, clientId: 'synthetic-client',
      }), /invalid_member_execution_http_configuration/);
    }
  }
  for (const origin of ['http://localhost.evil.invalid', 'http://127.0.0.2', 'http://[::ffff:7f00:1]']) {
    await assert.rejects(createMemberExecutionHttpTransport(forbiddenPool, {
      origin, environment: 'local', clientId: 'synthetic-client',
    }), /invalid_member_execution_http_configuration/);
  }
  for (const origin of ['http://localhost:4311', 'http://127.0.0.1:4311', 'http://[::1]:4311', 'https://synthetic.invalid']) {
    const app = await createMemberExecutionHttpTransport(forbiddenPool, { origin, environment: 'local', clientId: 'synthetic-client' });
    for (const method of ['HEAD', 'OPTIONS', 'PUT']) {
      const response = await app.fetch(new Request(`${origin}/api/v1/me/execution-runs/${id}`, { method }));
      assert.equal(response.status, 405);
      assert.equal(response.headers.get('Allow'), 'GET');
      assert.equal(response.headers.get('Cache-Control'), 'private, no-store');
      assert.equal(response.headers.get('ETag'), null);
      if (method === 'HEAD') assert.equal(await response.text(), '');
    }
  }
  assert.equal(queries, 0, 'HEAD and unsupported methods must not reach charge/auth/record queries.');
});

test('shared HTTP reader preserves decoded-key, Unicode, byte, chunk and depth rejection boundaries', async () => {
  const request = (body: string | Uint8Array<ArrayBuffer>) => new Request('https://synthetic.invalid', {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body,
  });
  for (const body of ['{"connectionId":"x","\\u0063onnectionId":"y"}', '{"selection":{"x":1,"\\u0078":2}}',
    '{"\\u005f_proto__":1}', '{"constructor":1}', '{"prototype":1}', '{"x":"\\ud800"}', '{"x":1e0}',
    '{"x":-0}', '{"x":9007199254740992}', '\ufeff{}', '['.repeat(26) + ']'.repeat(26)]) {
    await assert.rejects(readBoundedHttpJson(request(body)), (error: unknown) => (error as {code?: string}).code === 'invalid_json');
  }
  for (const bytes of [new Uint8Array([0xc0, 0xaf]), new Uint8Array([0xed, 0xa0, 0x80]), new Uint8Array([0xf4, 0x90, 0x80, 0x80])]) {
    await assert.rejects(readBoundedHttpJson(request(bytes)), (error: unknown) => (error as {code?: string}).code === 'invalid_json');
  }
  assert.equal((await readBoundedHttpJson(request('{"x":"\\ud83d\\ude00"}')) as {x: string}).x, '😀');
  const streamed = (chunks: Uint8Array[]) => new Request('https://synthetic.invalid', {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: new ReadableStream<Uint8Array>({ start(controller) { for (const chunk of chunks) controller.enqueue(chunk); controller.close(); } }),
    duplex: 'half',
  } as RequestInit & {duplex: 'half'});
  const encoded = new TextEncoder().encode('{"x":"😀"}');
  assert.equal((await readBoundedHttpJson(streamed([...encoded].map(value => new Uint8Array([value])))) as {x: string}).x, '😀');
  const chunks = [new TextEncoder().encode('{'), ...Array.from({ length: 126 }, () => new Uint8Array()), new TextEncoder().encode('}')];
  assert.deepEqual(Object.keys(await readBoundedHttpJson(streamed(chunks)) as object), []);
  await assert.rejects(readBoundedHttpJson(streamed([...chunks, new Uint8Array()])),
    (error: unknown) => (error as {code?: string}).code === 'body_too_large');
});
