import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {Pool} from 'pg';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrate} from '../../scripts/database.js';
import {backfillLegacyScopeBatch} from '../../packages/resource-scopes/index.js';
import {createOperatorMediaBackfill,planOperatorBackfill,OperatorBackfillError} from '../../packages/media-migration/operator-backfill.js';
import {runMediaBackfill} from '../../scripts/media-backfill.js';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import type {ObjectStore} from '../../packages/asset-storage/index.js';
import {publicEventBanner} from '../../modules/community/events.js';
import {publicSocialThumbnail} from '../../modules/community/social-posts.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw Error('Explicit synthetic TEST_DATABASE_URL required');
const schema=`fp_operator_images_${process.pid}_${Date.now()}`,role=`fp_media_migrator_${process.pid}_${Date.now()}`,ownerRole=schema+'_owner',password=randomBytes(24).toString('hex'),admin=new Pool({connectionString:url}),owner=new Pool({connectionString:url,options:`-c role=${ownerRole} -c search_path=${schema}`});
let migrator:Pool,mf:Miniflare,store:ObjectStore,bytes:Buffer;
type Purpose='community.event-banner'|'community.social-thumbnail';
const purposes:Purpose[]=['community.event-banner','community.social-thumbnail'];
const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex'),safe=(e:unknown)=>e instanceof OperatorBackfillError&&e.message==='operator media backfill is unavailable';
const profile=(purpose:Purpose)=>purpose==='community.event-banner'?{source:'community_event_banners',domain:'community_events',id:'event_id',version:'aggregate_version',pointer:'community_event_banner_asset_targets'}:{source:'community_social_post_thumbnails',domain:'community_social_posts',id:'post_id',version:'media_version',pointer:'community_social_thumbnail_asset_targets'};
const plan=(purpose:Purpose)=>({target:{environment:'local' as const,database:new URL(url).pathname.slice(1),schema,role,releaseSha:'9'.repeat(40)},jobId:randomUUID(),logicalStore:'MEDIA' as const,storeBindingId:'synthetic-images-r2',migrationId:'synthetic-images-v1',purpose,maxRows:1,maxBytes:8388608,leaseSeconds:30});
before(async()=>{await admin.query(`CREATE ROLE ${ownerRole} NOLOGIN NOSUPERUSER NOBYPASSRLS; CREATE SCHEMA ${schema} AUTHORIZATION ${ownerRole}`);assert.equal((await owner.query("SELECT rolsuper FROM pg_roles WHERE rolname=current_user")).rows[0].rolsuper,false);await migrate(owner);await admin.query(`CREATE ROLE ${role} LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD '${password}'`);const sql=(await readFile(new URL('../../deploy/cloudflare/sql/40-media-backfill-operator-grants.psql',import.meta.url),'utf8')).split('-- BEGIN CLOSED OPERATOR GRANTS')[1].split('-- END CLOSED OPERATOR GRANTS')[0];await owner.query('BEGIN');try{await owner.query("SELECT set_config('freedom.operator_role',$1,true),set_config('freedom.operator_schema',$2,true)",[role,schema]);await owner.query(sql);await owner.query('COMMIT');}catch(e){await owner.query('ROLLBACK');throw e;}const connection=new URL(url);connection.username=role;connection.password=password;migrator=new Pool({connectionString:connection.toString()});mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'operator-images-r2',modules:true,script:'export default {fetch(){return new Response("synthetic");}}',compatibilityDate:'2026-09-21',r2Buckets:['MEDIA']}]}));await mf.ready;store=createR2ObjectStore(await mf.getR2Bucket('MEDIA') as unknown as AssetR2Binding);const image=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).webp().toBuffer();bytes=Buffer.alloc(524288);image.copy(bytes);bytes.write('JUNK',image.length,'ascii');bytes.writeUInt32LE(bytes.length-image.length-8,image.length+4);bytes.writeUInt32LE(bytes.length-8,4);assert.equal((await sharp(bytes).metadata()).format,'webp');await owner.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-images-v1',persistence_allowed=true,retained_byte_limit=16777216 WHERE purpose=ANY($1::text[])",[purposes]);});
after(async()=>{await mf?.dispose();await migrator?.end();await owner.end();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.query(`DROP ROLE IF EXISTS ${role},${ownerRole}`);await admin.end();});
async function approval(raw:ReturnType<typeof plan>){const p=planOperatorBackfill(raw),t=p.target;await owner.query("INSERT INTO media_backfill_operator_policy(role_name,environment,database_name,schema_name,release_sha,logical_store,store_binding_id,migration_id,purpose,approved_plan_sha256,allowed,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,clock_timestamp()+interval '1 hour')",[t.role,t.environment,t.database,t.schema,t.releaseSha,p.logicalStore,p.storeBindingId,p.migrationId,p.purpose,p.planSha256]);return p;}
async function source(purpose:Purpose,options:{mapping?:boolean;state?:string;size?:number;source?:'youtube'|'page'|'upload';reset?:boolean;identity?:{user:string;community:string}}={}){if(options.reset!==false)await owner.query('TRUNCATE communities CASCADE');const community=options.identity?.community??randomUUID(),user=options.identity?.user??randomUUID(),id=randomUUID();if(!options.identity){await owner.query("INSERT INTO communities VALUES($1,'Synthetic operator images')",[community]);await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,'Synthetic','not-a-password',$4)",[user,community,user+'@images.local.test',randomUUID()]);}if(purpose==='community.event-banner'){await owner.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic ended','Synthetic',clock_timestamp()-interval '2 days',clock_timestamp()-interval '1 day','online','Synthetic',$4,'open','other')",[id,community,user,options.state??'published']);await owner.query("INSERT INTO community_event_banners(event_id,image_bytes,orientation) VALUES($1,$2,'portrait')",[id,bytes.subarray(0,options.size??bytes.length)]);}else{await owner.query("INSERT INTO community_social_posts(post_id,community_id,author_user_id,url,platform,title,note,state) VALUES($1,$2,$3,$5,'youtube','Synthetic|title','Synthetic|note',$4)",[id,community,user,options.state??'active','https://www.youtube.com/watch?v='+id]);await owner.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,$3)",[id,bytes.subarray(0,options.size??bytes.length),options.source??'youtube']);}if(options.mapping!==false){await backfillLegacyScopeBatch(owner,500);await backfillLegacyScopeBatch(owner,500);}return {id,user,community};}
const host=(io=store)=>createOperatorMediaBackfill(migrator,{store:io,logicalStore:'MEDIA',storeBindingId:'synthetic-images-r2'});
async function preserved(purpose:Purpose,id:string){const f=profile(purpose);return (await owner.query(`SELECT * FROM ${f.source} WHERE ${f.id}=$1`,[id])).rows[0];}
for(const purpose of purposes){
 test(`${purpose}: restricted operator preserves exact512KiB bytes, original URL/read ACL and truthful partial cursor`,async()=>{const s=await source(purpose),second=await source(purpose,{reset:false,identity:s});const ordered=[s.id,second.id].sort(),p=await approval(plan(purpose));const first=await host().run(p);assert.equal(first.linked,1);assert.equal(first.status,'partial');assert.equal(first.allSourcesMigrated,false);assert.equal(first.remainingLegacy,true);assert.equal(first.contentReadUpperBound,bytes.length*6);const next=await host().run(p);assert.equal(next.linked,1);const done=await host().run(p);assert.equal(done.allSourcesMigrated,true);const f=profile(purpose);assert.equal((await owner.query(`SELECT ${purpose==='community.event-banner'?'after_banner_event_id':'after_post_id'} AS cursor FROM media_backfill_jobs WHERE job_id=$1`,[p.jobId])).rows[0].cursor,ordered[1]);for(const id of ordered){const row=await preserved(purpose,id);assert.equal(row.storage_source,'asset');assert.deepEqual(row.image_bytes,bytes);assert.equal(row[purpose==='community.event-banner'?'orientation':'source'],purpose==='community.event-banner'?'portrait':'youtube');const read=purpose==='community.event-banner'?await publicEventBanner(owner,id,store):await publicSocialThumbnail(owner,id,store);assert.equal(hash(read),hash(bytes));}assert.equal((await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n,0);assert.equal((await owner.query('SELECT bool_and(write_effect_coverage) AS covered FROM assets')).rows[0].covered,true);assert.deepEqual((await owner.query('SELECT DISTINCT state FROM asset_object_write_effects')).rows.map(r=>r.state),['fulfilled']);if(purpose==='community.social-thumbnail'){await owner.query("UPDATE community_social_posts SET state='hidden' WHERE post_id=$1",[s.id]);await assert.rejects(publicSocialThumbnail(owner,s.id,store));}else{await owner.query("UPDATE community_events SET state='cancelled' WHERE event_id=$1",[s.id]);await assert.rejects(publicEventBanner(owner,s.id,store));}assert.ok(f.pointer);});
 test(`${purpose}: fresh source fingerprint rejects provenance/orientation edit without any version increment`,async()=>{const s=await source(purpose),p=await approval(plan(purpose)),f=profile(purpose),version=(await owner.query(`SELECT ${f.version} AS v FROM ${f.domain} WHERE ${f.id}=$1`,[s.id])).rows[0].v;const io:ObjectStore={...store,async putImmutable(k,v){const result=await store.putImmutable(k,v);if(purpose==='community.event-banner')await owner.query("UPDATE community_event_banners SET orientation='landscape' WHERE event_id=$1",[s.id]);else await owner.query("UPDATE community_social_posts SET url='https://example.test/changed',title='new|title',note=NULL WHERE post_id=$1",[s.id]);return result;}};const result=await host(io).run(p);assert.equal(result.linked,0);assert.equal(result.stale,1);assert.equal(result.allSourcesMigrated,false);assert.equal((await owner.query(`SELECT ${f.version} AS v FROM ${f.domain} WHERE ${f.id}=$1`,[s.id])).rows[0].v,version);assert.equal((await preserved(purpose,s.id)).storage_source,'legacy');assert.equal((await owner.query('SELECT state FROM assets')).rows[0].state,'pending');});
 test(`${purpose}: disabled author, missing mapping and malformed legacy header classify blocked without fabricated authority`,async()=>{for(const reason of ['disabled','mapping','header']){const s=await source(purpose,{mapping:reason!=='mapping',size:reason==='header'?8:undefined});if(reason==='disabled')await owner.query('UPDATE users SET active=false WHERE user_id=$1',[s.user]);const result=await host().run(await approval(plan(purpose)));assert.equal(result.blocked,1);assert.equal(result.allSourcesMigrated,false);assert.equal(result.remainingLegacy,true);assert.equal(result.linked,0);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);assert.equal((await preserved(purpose,s.id)).storage_source,'legacy');}});
 test(`${purpose}: unknown committed native PUT resumes same common identities but remains unknown in GC effect history`,async()=>{const s=await source(purpose),p=await approval(plan(purpose)),io:ObjectStore={...store,async putImmutable(k,v){await store.putImmutable(k,v);throw Error('PRIVATE_PUT');},async get(){throw Error('PRIVATE_GET');}};await assert.rejects(host(io).run(p),safe);const item=(await owner.query('SELECT * FROM media_backfill_items WHERE job_id=$1',[p.jobId])).rows[0];assert.equal((await owner.query('SELECT state FROM asset_object_write_effects')).rows[0].state,'unknown');await owner.query('UPDATE media_backfill_jobs SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE job_id=$1',[p.jobId]);await owner.query('UPDATE asset_upload_intents SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE intent_id=$1',[item.intent_id]);assert.equal((await host().run(p)).linked,1);const after=(await owner.query('SELECT * FROM media_backfill_items WHERE job_id=$1',[p.jobId])).rows[0];assert.equal(after.intent_id,item.intent_id);assert.equal(after.asset_id,item.asset_id);assert.deepEqual((await owner.query('SELECT state FROM asset_object_write_effects ORDER BY begun_at')).rows.map(r=>r.state),['unknown','fulfilled']);assert.deepEqual((await preserved(purpose,s.id)).image_bytes,bytes);});
 test(`${purpose}: canonical consent revoked after PUT cannot publish despite approved plan`,async()=>{const s=await source(purpose),p=await approval(plan(purpose)),io:ObjectStore={...store,async putImmutable(k,v){const r=await store.putImmutable(k,v);await owner.query('UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose=$1',[purpose]);return r;}};try{await assert.rejects(host(io).run(p),safe);assert.equal((await preserved(purpose,s.id)).storage_source,'legacy');assert.equal((await owner.query('SELECT count(*)::int n FROM asset_objects')).rows[0].n,0);}finally{await owner.query('UPDATE domain_media_storage_policy SET persistence_allowed=true WHERE purpose=$1',[purpose]);}});
 test(`${purpose}: actual dedicated operator cannot write original bytes, provenance, owner, state or storage source`,async()=>{const s=await source(purpose),f=profile(purpose);for(const sql of [`UPDATE ${f.source} SET image_bytes=image_bytes`,`UPDATE ${f.source} SET storage_source=storage_source`,`UPDATE ${f.domain} SET ${purpose==='community.event-banner'?'organizer_ref':'author_user_id'}=${purpose==='community.event-banner'?'organizer_ref':'author_user_id'}`,`UPDATE ${f.domain} SET state=state`,purpose==='community.event-banner'?`UPDATE ${f.source} SET orientation=orientation`:`UPDATE ${f.source} SET source=source`])await assert.rejects(migrator.query(`SET search_path=${schema}; ${sql}`),(e:any)=>e.code==='42501');await assert.rejects(migrator.query(`INSERT INTO ${schema}.${f.source}(${f.id},image_bytes${purpose==='community.social-thumbnail'?',source':''}) VALUES($1,$2${purpose==='community.social-thumbnail'?",'page'":''})`,[s.id,bytes]),(e:any)=>e.code==='42501');assert.equal((await migrator.query(`SELECT ${schema}.lock_media_backfill_${purpose==='community.event-banner'?'banner_organizer':'social_author'}($1,$2)`,['0'.repeat(64),s.id])).rowCount,0);});
}
test('social hidden/deleted originals remain blocked; historical cancelled banner migrates under organizer read while staying nonpublic',async()=>{for(const state of ['hidden','deleted']){await source('community.social-thumbnail',{state});const result=await host().run(await approval(plan('community.social-thumbnail')));assert.equal(result.blocked,1);assert.equal(result.allSourcesMigrated,false);}const s=await source('community.event-banner',{state:'cancelled'});assert.equal((await host().run(await approval(plan('community.event-banner')))).linked,1);await assert.rejects(publicEventBanner(owner,s.id,store));});
test('both closed CLI purposes dry-run without environment reads; execute requires an installed trusted host',async()=>{const env=new Proxy({},{get(){throw Error('PRIVATE_ENV');}});for(const purpose of purposes){const p=plan(purpose),args=['--environment','local','--expected-database',p.target.database,'--schema',schema,'--expected-role',role,'--release-sha',p.target.releaseSha,'--job-id',p.jobId,'--store-binding-id',p.storeBindingId,'--migration-id',p.migrationId,'--max-rows','1','--max-bytes','8388608','--lease-seconds','30','--purpose',purpose];const dry=await runMediaBackfill(args,env);assert.equal(dry.exitCode,0);assert.equal((dry.report as any).plan.purpose,purpose);assert.equal((dry.report as any).execution,'not_run');const absent=await runMediaBackfill([...args,'--execute'],env);assert.equal((absent.report as any).code,'trusted_backfill_host_not_installed');assert.ok(!JSON.stringify(absent).includes('PRIVATE_ENV'));}assert.throws(()=>planOperatorBackfill({...plan(purposes[0]),purpose:'work.private-draft'}),safe);});

test('all six new SQL-standard authority ports have managed non-super ownership and no PUBLIC execution',async()=>{const rows=(await owner.query("SELECT p.proname,p.prosecdef,r.rolsuper,r.rolbypassrls,r.rolname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname=$1 AND p.proname=ANY($2::text[])",[schema,['lock_media_backfill_banner_organizer','lock_media_backfill_banner_consent','publish_media_backfill_banner','lock_media_backfill_social_author','lock_media_backfill_social_consent','publish_media_backfill_social']])).rows;assert.equal(rows.length,6);for(const row of rows){assert.equal(row.prosecdef,true);assert.equal(row.rolname,ownerRole);assert.equal(row.rolsuper,false);assert.equal(row.rolbypassrls,false);}assert.equal((await owner.query("SELECT count(*)::int n FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) acl WHERE n.nspname=$1 AND p.proname=ANY($2::text[]) AND acl.grantee=0 AND acl.privilege_type='EXECUTE'",[schema,rows.map(r=>r.proname)])).rows[0].n,0);});

test('social page and manual-upload source enum remains exact rather than inferred from URL/platform',async()=>{for(const sourceKind of ['page','upload'] as const){const s=await source('community.social-thumbnail',{source:sourceKind}),before=(await owner.query('SELECT url,platform,title,note FROM community_social_posts WHERE post_id=$1',[s.id])).rows[0];assert.equal((await host().run(await approval(plan('community.social-thumbnail')))).linked,1);assert.equal((await preserved('community.social-thumbnail',s.id)).source,sourceKind);assert.deepEqual((await owner.query('SELECT url,platform,title,note FROM community_social_posts WHERE post_id=$1',[s.id])).rows[0],before);assert.equal(hash(await publicSocialThumbnail(owner,s.id,store)),hash(bytes));}});
