import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {Pool} from 'pg';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrate} from '../../scripts/database.js';
import {backfillLegacyScopeBatch} from '../../packages/resource-scopes/index.js';
import {createOperatorMediaBackfill,planOperatorBackfill,OperatorBackfillError} from '../../packages/media-migration/operator-backfill.js';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import type {ObjectStore} from '../../packages/asset-storage/index.js';
import {tokenHash,type Actor} from '../../modules/identity-membership/service.js';
import {readSkillImage} from '../../modules/assets/skill-image.js';
import {readOwnIllustration,readSubmission} from '../../modules/skill-submissions/service.js';
import {highlightImageBytes,removeHighlight,readHighlightEvent} from '../../modules/community/event-highlights.js';
import {runMediaBackfill} from '../../scripts/media-backfill.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw Error('Explicit synthetic TEST_DATABASE_URL required');
const schema=`fp_operator_pairs_${process.pid}_${Date.now()}`,role=`fp_media_migrator_${process.pid}_${Date.now()}`,ownerRole=schema+'_owner',password=randomBytes(24).toString('hex'),admin=new Pool({connectionString:url}),owner=new Pool({connectionString:url,options:`-c role=${ownerRole} -c search_path=${schema}`});
let migrator:Pool,mf:Miniflare,store:ObjectStore,image:Buffer,thumb:Buffer,skill:Buffer;
type Purpose='skill.submission-image'|'community.event-highlight';
const hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),safe=(e:unknown)=>e instanceof OperatorBackfillError&&e.message==='operator media backfill is unavailable';
const plan=(purpose:Purpose)=>({target:{environment:'local' as const,database:new URL(url).pathname.slice(1),schema,role,releaseSha:'1'.repeat(40)},jobId:randomUUID(),logicalStore:'MEDIA' as const,storeBindingId:'synthetic-pairs-r2',migrationId:'synthetic-pairs-v1',purpose,maxRows:1,maxBytes:8388608,leaseSeconds:30});
before(async()=>{await admin.query(`CREATE ROLE ${ownerRole} NOLOGIN NOSUPERUSER NOBYPASSRLS;CREATE SCHEMA ${schema} AUTHORIZATION ${ownerRole}`);await migrate(owner);await admin.query(`CREATE ROLE ${role} LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD '${password}'`);const sql=(await readFile(new URL('../../deploy/cloudflare/sql/40-media-backfill-operator-grants.psql',import.meta.url),'utf8')).split('-- BEGIN CLOSED OPERATOR GRANTS')[1].split('-- END CLOSED OPERATOR GRANTS')[0];await owner.query('BEGIN');try{await owner.query("SELECT set_config('freedom.operator_role',$1,true),set_config('freedom.operator_schema',$2,true)",[role,schema]);await owner.query(sql);await owner.query('COMMIT');}catch(e){await owner.query('ROLLBACK');throw e;}const connection=new URL(url);connection.username=role;connection.password=password;migrator=new Pool({connectionString:connection.toString()});mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'operator-pairs-r2',modules:true,script:'export default {fetch(){return new Response("synthetic");}}',compatibilityDate:'2026-09-21',r2Buckets:['MEDIA']}]}));await mf.ready;store=createR2ObjectStore(await mf.getR2Bucket('MEDIA') as unknown as AssetR2Binding);const base=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).webp().toBuffer();const pad=(size:number)=>{const b=Buffer.alloc(size);base.copy(b);b.write('JUNK',base.length,'ascii');b.writeUInt32LE(size-base.length-8,base.length+4);b.writeUInt32LE(size-8,4);return b;};image=pad(1048576);thumb=pad(204800);skill=pad(524288);await owner.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-pairs-v1',persistence_allowed=true,retained_byte_limit=33554432 WHERE purpose=ANY($1::text[])",[['skill.submission-image','community.event-highlight']]);});
after(async()=>{await mf?.dispose();await migrator?.end();await owner.end();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE;DROP ROLE IF EXISTS ${role},${ownerRole}`);await admin.end();});
async function approval(raw:ReturnType<typeof plan>){const p=planOperatorBackfill(raw),t=p.target;await owner.query("INSERT INTO media_backfill_operator_policy(role_name,environment,database_name,schema_name,release_sha,logical_store,store_binding_id,migration_id,purpose,approved_plan_sha256,allowed,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,clock_timestamp()+interval '1 hour')",[t.role,t.environment,t.database,t.schema,t.releaseSha,p.logicalStore,p.storeBindingId,p.migrationId,p.purpose,p.planSha256]);return p;}
const host=(io=store)=>createOperatorMediaBackfill(migrator,{store:io,logicalStore:'MEDIA',storeBindingId:'synthetic-pairs-r2'});
async function member(community:string){const id=randomUUID(),session=tokenHash(randomBytes(32).toString('base64url'));const row=(await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref,onboarding_required) VALUES($1,$2,$3,'Synthetic owner','not-a-password',$4,false) RETURNING *",[id,community,id+'@operator-pair.local.test',randomUUID()])).rows[0];await owner.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[session,id]);return {...row,session_hash:session,csrf_token:'synthetic'} as Actor;}
async function base(){await owner.query('TRUNCATE communities CASCADE');const community=randomUUID();await owner.query("INSERT INTO communities VALUES($1,'Synthetic pairs')",[community]);const user=await member(community);return {community,user};}
async function mappings(){await backfillLegacyScopeBatch(owner,500);await backfillLegacyScopeBatch(owner,500);}
async function skillSource(status:'ready_for_review'|'published'|'revoked'='ready_for_review',withBytes=true){const b=await base(),id=randomUUID(),project=randomUUID(),version=randomUUID();if(status==='published'){await owner.query("INSERT INTO oss_projects(project_id,community_id,owner_ref,title,description,use_notes,repository_id,repository_full_name,repository_url,relationship) VALUES($1,$2,$3,'Synthetic','Synthetic','Synthetic','123','synthetic/source','https://github.com/synthetic/source','curator')",[project,b.community,b.user.user_id]);await owner.query("INSERT INTO oss_project_versions(version_id,project_id,repository_id,commit_sha,default_branch,repository_full_name,repository_url,readme_url,license_spdx,is_fork,archived,source_snapshot,source_sha256,facts_sha256,inspected_at) VALUES($1,$2,'123',$3,'main','synthetic/source','https://github.com/synthetic/source','https://github.com/synthetic/source/blob/main/README.md','MIT',false,false,'{}',$4,$4,clock_timestamp())",[version,project,'a'.repeat(40),'b'.repeat(64)]);}await owner.query("INSERT INTO skill_submissions(submission_id,community_id,owner_ref,status,payload,payload_sha256,image_bytes,grant_consumed_at,consent_to_share,project_id,project_version_id,published_at,revoked_at) VALUES($1,$2,$3,$4,'{\"title\":\"Synthetic\"}',$5,$6,clock_timestamp(),$7,$8,$9,CASE WHEN $7 THEN clock_timestamp() END,CASE WHEN $4='revoked' THEN clock_timestamp() END)",[id,b.community,b.user.user_id,status,hash('synthetic'),withBytes?skill:null,status==='published',status==='published'?project:null,status==='published'?version:null]);await mappings();return {...b,id};}
async function highlightSource(options:{missing?:boolean;thumbSize?:number;removed?:boolean;future?:boolean;mapping?:boolean}={}){const b=await base(),organizer=await member(b.community),event=randomUUID(),id=randomUUID();await owner.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic ended','Synthetic',clock_timestamp()-interval '2 days',clock_timestamp()+$4::interval,'online','Synthetic','published','open','other')",[event,b.community,organizer.user_id,options.future?'1 day':'-1 day']);await owner.query("INSERT INTO community_event_highlights(media_id,event_id,community_id,uploader_user_id,kind,title,orientation,byte_size,state,removed_at,removed_by_user_id) VALUES($1,$2,$3,$4,'photo','Synthetic|photo','landscape',$5,$6,CASE WHEN $6='removed' THEN clock_timestamp() END,CASE WHEN $6='removed' THEN $4::uuid END)",[id,event,b.community,b.user.user_id,image.length,options.removed?'removed':'active']);await owner.query("INSERT INTO community_event_highlight_images(media_id,variant,bytes) VALUES($1,'image',$2)",[id,image]);if(!options.missing)await owner.query("INSERT INTO community_event_highlight_images(media_id,variant,bytes) VALUES($1,'thumb',$2)",[id,options.thumbSize?Buffer.concat([thumb,Buffer.alloc(options.thumbSize-thumb.length)]):thumb]);if(options.mapping!==false)await mappings();return {...b,organizer,event,id};}
async function expire(job:string){await owner.query('UPDATE media_backfill_jobs SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE job_id=$1',[job]);await owner.query('UPDATE asset_upload_intents SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE intent_id IN (SELECT intent_id FROM media_backfill_items WHERE job_id=$1)',[job]);}
async function unpublished(id:string){assert.equal((await owner.query('SELECT storage_source FROM community_event_highlights WHERE media_id=$1',[id])).rows[0].storage_source,'legacy');assert.ok((await owner.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));assert.equal((await owner.query('SELECT count(*)::int n FROM asset_objects')).rows[0].n,0);const target=(await owner.query('SELECT * FROM community_event_highlight_asset_targets WHERE media_id=$1',[id])).rows[0];assert.equal(target.image_asset_id,null);assert.equal(target.thumb_asset_id,null);}

test('skill owner-private historical illustration preserves512KiB, URL, status and grant absence without public visibility',async()=>{const s=await skillSource(),before=await readSubmission(owner,s.user,s.id),sessions=(await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n;assert.deepEqual(await readOwnIllustration(owner,s.user,s.id),skill);const p=await approval(plan('skill.submission-image'));assert.equal((await host().run(p)).linked,1);const after=await readSubmission(owner,s.user,s.id);assert.equal(after.illustration_url,before.illustration_url);assert.equal(after.status,'ready_for_review');assert.deepEqual(await readOwnIllustration(owner,s.user,s.id,store),skill);assert.equal(await readSkillImage(owner,s.id,store),null);assert.equal((await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n,sessions);assert.equal((await owner.query('SELECT grant_hash,origin_key_id,storage_source,image_bytes FROM skill_submissions')).rows[0].grant_hash,null);assert.equal((await owner.query('SELECT state FROM asset_object_write_effects')).rows[0].state,'fulfilled');let puts=0;const io:ObjectStore={...store,async putImmutable(k,v){puts++;return store.putImmutable(k,v);}};await host(io).run(p);assert.equal(puts,0);});
test('skill original published shelf predicate and revoked owner attachment remain truthful after migration',async()=>{for(const status of ['published','revoked'] as const){const s=await skillSource(status);assert.equal(Boolean(await readSkillImage(owner,s.id,undefined)),status==='published');assert.equal((await host().run(await approval(plan('skill.submission-image')))).linked,1);assert.equal(Boolean(await readSkillImage(owner,s.id,store)),status==='published');assert.deepEqual(await readOwnIllustration(owner,s.user,s.id,store),skill);const pointer=(await owner.query('SELECT asset_id FROM skill_submission_image_asset_targets')).rows[0];assert.ok(pointer.asset_id);assert.equal((await owner.query('SELECT status FROM skill_submissions')).rows[0].status,status);}});
test('skill equal-size legacy byte change without version advance is stale; canonical owner/private scope cannot be fabricated',async()=>{const s=await skillSource(),p=await approval(plan('skill.submission-image')),io:ObjectStore={...store,async putImmutable(k,v){const r=await store.putImmutable(k,v);const changed=Buffer.from(skill);changed[changed.length-1]^=1;await owner.query('UPDATE skill_submissions SET image_bytes=$2 WHERE submission_id=$1',[s.id,changed]);return r;}};const result=await host(io).run(p);assert.equal(result.linked,0);assert.equal(result.stale,1);assert.equal((await owner.query('SELECT aggregate_version,storage_source FROM skill_submissions')).rows[0].aggregate_version,'1');assert.equal((await owner.query('SELECT storage_source FROM skill_submissions')).rows[0].storage_source,'legacy');});
test('skill nullable legacy image is absence rather than fabricated object or upload grant',async()=>{await skillSource('ready_for_review',false);const result=await host().run(await approval(plan('skill.submission-image')));assert.equal(result.linked,0);assert.equal(result.remainingLegacy,false);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);});
test('skill disabled owner or current principal blocks source without changing visibility or state',async()=>{for(const field of ['user','principal']){const s=await skillSource('revoked');await owner.query(field==='user'?'UPDATE users SET active=false WHERE user_id=$1':"UPDATE principals SET status='disabled' WHERE user_ref=$1",[s.user.user_id]);const r=await host().run(await approval(plan('skill.submission-image')));assert.equal(r.blocked,1);assert.equal(r.allSourcesMigrated,false);assert.equal((await owner.query('SELECT storage_source,status FROM skill_submissions')).rows[0].storage_source,'legacy');}});
test('highlight exact1MiB image +200KiB thumb uses two common intents and one atomic pair/version publication',async()=>{const s=await highlightSource(),before=await readHighlightEvent(owner,{communityId:null,viewerId:null,eventId:s.event}),p=await approval(plan('community.event-highlight'));assert.equal((await host().run(p)).linked,1);assert.deepEqual(await highlightImageBytes(owner,s.id,'image',store),image);assert.deepEqual(await highlightImageBytes(owner,s.id,'thumb',store),thumb);const after=await readHighlightEvent(owner,{communityId:null,viewerId:null,eventId:s.event});assert.deepEqual(after.items.map(i=>({image_url:'image_url' in i?i.image_url:null,thumb_url:'thumb_url' in i?i.thumb_url:null})),before.items.map(i=>({image_url:'image_url' in i?i.image_url:null,thumb_url:'thumb_url' in i?i.thumb_url:null})));assert.equal((await owner.query('SELECT aggregate_version FROM community_events')).rows[0].aggregate_version,'2');assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,2);assert.equal((await owner.query('SELECT count(*)::int n FROM asset_upload_intents')).rows[0].n,2);assert.deepEqual((await owner.query('SELECT variant FROM media_backfill_items ORDER BY variant')).rows.map(r=>r.variant),['image','thumb']);assert.equal((await owner.query('SELECT bool_and(write_effect_coverage) covered FROM assets')).rows[0].covered,true);let puts=0;await host({...store,async putImmutable(k,v){puts++;return store.putImmutable(k,v);}}).run(p);assert.equal(puts,0);assert.equal((await owner.query('SELECT aggregate_version FROM community_events')).rows[0].aggregate_version,'2');});
for(const failure of ['second-rejected','second-unknown','second-tampered'] as const)test(`highlight ${failure} leaves no half Asset publication and resumes original identities`,async()=>{const s=await highlightSource(),p=await approval(plan('community.event-highlight'));let puts=0;const io:ObjectStore={...store,async putImmutable(k,v){puts++;if(puts===2&&failure==='second-rejected')throw Error('PRIVATE_PUT');const r=await store.putImmutable(k,v);if(puts===2&&failure==='second-unknown')throw Error('PRIVATE_ACK');return r;},async get(k,range){if(puts===2&&failure==='second-unknown')throw Error('PRIVATE_GET');const object=await store.get(k,range);if(!object||puts!==2||failure!=='second-tampered')return object;await object.body.cancel();const bad=Buffer.from(thumb);bad[bad.length-1]^=1;return {...object,body:new ReadableStream({start(c){c.enqueue(bad);c.close();}})};}};await assert.rejects(host(io).run(p),safe);await unpublished(s.id);assert.deepEqual(await highlightImageBytes(owner,s.id,'thumb'),thumb);const identities=(await owner.query('SELECT variant,intent_id,asset_id FROM media_backfill_items ORDER BY variant')).rows;await expire(p.jobId);assert.equal((await host().run(p)).linked,1);assert.deepEqual((await owner.query('SELECT variant,intent_id,asset_id FROM media_backfill_items ORDER BY variant')).rows,identities);assert.equal((await owner.query('SELECT aggregate_version FROM community_events')).rows[0].aggregate_version,'2');if(failure==='second-unknown')assert.ok((await owner.query('SELECT state FROM asset_object_write_effects')).rows.some(r=>r.state==='unknown'));});
for(const edit of ['thumb-bytes','parent-orientation','event-version'])test(`highlight fresh ${edit} change makes BOTH common items stale and never publishes`,async()=>{const s=await highlightSource(),p=await approval(plan('community.event-highlight'));let calls=0;const io:ObjectStore={...store,async putImmutable(k,v){const r=await store.putImmutable(k,v);if(++calls===2){if(edit==='thumb-bytes'){const b=Buffer.from(thumb);b[b.length-1]^=1;await owner.query("UPDATE community_event_highlight_images SET bytes=$2 WHERE media_id=$1 AND variant='thumb'",[s.id,b]);}else if(edit==='parent-orientation')await owner.query("UPDATE community_event_highlights SET orientation='portrait' WHERE media_id=$1",[s.id]);else await owner.query('UPDATE community_events SET aggregate_version=aggregate_version+1 WHERE event_id=$1',[s.event]);}return r;}};const r=await host(io).run(p);assert.equal(r.linked,0);assert.equal(r.stale,1);assert.ok((await owner.query('SELECT outcome FROM media_backfill_items')).rows.every(row=>row.outcome==='stale'));await unpublished(s.id);const next=await host().run(await approval(plan('community.event-highlight')));assert.equal(next.blocked,1);assert.equal(next.allSourcesMigrated,false);});
test('highlight missing variant, historical oversize thumb, removed parent, future event and missing mappings are blocked, not silently complete',async()=>{for(const options of [{missing:true},{thumbSize:204802},{removed:true},{future:true},{mapping:false}]){await highlightSource(options);const r=await host().run(await approval(plan('community.event-highlight')));assert.equal(r.blocked,1);assert.equal(r.allSourcesMigrated,false);assert.equal(r.remainingLegacy,true);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);}});
test('highlight canonical prohibition after second PUT rolls back BOTH source attachments',async()=>{const s=await highlightSource(),p=await approval(plan('community.event-highlight'));let calls=0;const io:ObjectStore={...store,async putImmutable(k,v){const r=await store.putImmutable(k,v);if(++calls===2)await owner.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.event-highlight'");return r;}};try{await assert.rejects(host(io).run(p),safe);await unpublished(s.id);assert.equal((await owner.query('SELECT aggregate_version FROM community_events')).rows[0].aggregate_version,'1');}finally{await owner.query("UPDATE domain_media_storage_policy SET persistence_allowed=true WHERE purpose='community.event-highlight'");}});
test('original uploader/organizer/verified-admin removal survives migration; ordinary peer cannot delete pairs',async()=>{for(const authority of ['uploader','organizer','admin'] as const){const s=await highlightSource();await host().run(await approval(plan('community.event-highlight')));const peer=await member(s.community),command=(actor:Actor)=>({actor,operation:`POST /api/v1/event-highlights/media/${s.id}/remove`,key:randomUUID(),body:{}});await assert.rejects(removeHighlight(owner,command(peer),s.id),(e:any)=>e.code==='highlight_remove_forbidden');if(authority==='admin'){await owner.query('UPDATE users SET email_verified_at=clock_timestamp() WHERE user_id=$1',[peer.user_id]);await owner.query("INSERT INTO platform_admins(admin_id,community_id,email,display_name,active) VALUES($1,$2,$3,'Synthetic admin',true)",[randomUUID(),s.community,peer.email]);}await removeHighlight(owner,command(authority==='uploader'?s.user:authority==='organizer'?s.organizer:peer),s.id);assert.ok((await owner.query('SELECT state FROM assets')).rows.every(row=>row.state==='retired'));await assert.rejects(highlightImageBytes(owner,s.id,'image',store));}});
test('restricted operator cannot write skill grant/status/consent or original highlight bytes and metadata; all seven ports are managed/noPUBLIC',async()=>{for(const sql of ['UPDATE skill_submissions SET image_bytes=image_bytes','UPDATE skill_submissions SET status=status','UPDATE skill_submissions SET grant_hash=grant_hash','UPDATE skill_submissions SET consent_to_share=consent_to_share','UPDATE community_event_highlight_images SET bytes=bytes','UPDATE community_event_highlights SET title=title','UPDATE community_event_highlights SET storage_source=storage_source'])await assert.rejects(migrator.query(`SET search_path=${schema};${sql}`),(e:any)=>e.code==='42501');const names=['lock_media_backfill_skill_owner','lock_media_backfill_skill_consent','publish_media_backfill_skill','lock_media_backfill_highlight_uploader','lock_media_backfill_highlight_consent','lock_media_backfill_highlight_bytes','publish_media_backfill_highlight'];const rows=(await owner.query("SELECT p.proname,p.prosecdef,r.rolsuper,r.rolbypassrls,r.rolname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname=$1 AND p.proname=ANY($2::text[])",[schema,names])).rows;assert.equal(rows.length,7);for(const r of rows){assert.equal(r.prosecdef,true);assert.equal(r.rolsuper,false);assert.equal(r.rolbypassrls,false);assert.equal(r.rolname,ownerRole);}assert.equal((await owner.query("SELECT count(*)::int n FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) acl WHERE n.nspname=$1 AND p.proname=ANY($2::text[]) AND acl.grantee=0 AND acl.privilege_type='EXECUTE'",[schema,names])).rows[0].n,0);});
test('closed skill/highlight CLI plans need no environment or implicit host, and paired budget cannot be guessed',async()=>{const env=new Proxy({},{get(){throw Error('PRIVATE_ENV');}});for(const purpose of ['skill.submission-image','community.event-highlight'] as const){const p=plan(purpose),args=['--environment','local','--expected-database',p.target.database,'--schema',schema,'--expected-role',role,'--release-sha',p.target.releaseSha,'--job-id',p.jobId,'--store-binding-id',p.storeBindingId,'--migration-id',p.migrationId,'--max-rows','1','--max-bytes','8388608','--lease-seconds','30','--purpose',purpose];assert.equal((await runMediaBackfill(args,env)).exitCode,0);assert.equal(((await runMediaBackfill([...args,'--execute'],env)).report as any).code,'trusted_backfill_host_not_installed');}assert.throws(()=>planOperatorBackfill({...plan('community.event-highlight'),maxBytes:3145728}),safe);});

test('synthetically corrupted third highlight variant is blocked by complete bounded pair validation',async()=>{await highlightSource();await owner.query('ALTER TABLE community_event_highlight_images DROP CONSTRAINT community_event_highlight_images_variant_check');try{await owner.query("INSERT INTO community_event_highlight_images(media_id,variant,bytes) SELECT media_id,'unknown',bytes FROM community_event_highlight_images WHERE variant='thumb'");const r=await host().run(await approval(plan('community.event-highlight')));assert.equal(r.blocked,1);assert.equal(r.remainingLegacy,true);assert.equal(r.allSourcesMigrated,false);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);}finally{await owner.query("DELETE FROM community_event_highlight_images WHERE variant='unknown'");await owner.query("ALTER TABLE community_event_highlight_images ADD CONSTRAINT community_event_highlight_images_variant_check CHECK(variant IN ('image','thumb'))");}});
