import { test,before,after } from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { serve } from '@hono/node-server';
import { createPool,LOCAL_DATABASE_URL } from '../../packages/db/index.js';
import { createApp } from '../../apps/platform-api/src/app.js';
import { migrate } from '../../scripts/database.js';
import { seedLocal } from '../../packages/testing/seed.js';
import { PlatformClient } from '../../packages/sdk/client.mjs';
import metadata from '../../contracts/preview/v1/metadata.json' with {type:'json'};
const url=process.env.TEST_DATABASE_URL??LOCAL_DATABASE_URL;
const schema=`fp_protocol_${process.pid}_${Date.now()}`,admin=createPool(url),pool=new Pool({connectionString:url,options:`-c search_path=${schema}`});
let app:ReturnType<typeof createApp>,baseUrl:string;
const server=serve({fetch:req=>app.fetch(req),hostname:'127.0.0.1',port:0});
const key=()=>({idempotencyKey:randomUUID()});
before(async()=>{if(!server.listening)await once(server,'listening');const address=server.address();assert(address&&typeof address!=='string');const origin=`http://127.0.0.1:${address.port}`;baseUrl=origin+'/api/v1';await admin.query(`CREATE SCHEMA ${schema}`);await migrate(pool);await seedLocal(pool);app=createApp(pool,origin);});
after(async()=>{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
test('published preview SDK negotiates exact protocol and drives real HTTP/PG across member, supply and marketing',async()=>{
 const maker=await PlatformClient.loginDemo({baseUrl,email:'maker@local.test',password:'freedom-local-demo'});
 const seller=await PlatformClient.loginDemo({baseUrl,email:'client@local.test',password:'freedom-local-demo'});
 assert.equal((await maker.assertCompatible()).protocol_sha256,metadata.protocol_sha256);
 assert.equal((await maker.call('getHealth')).status,'ok');assert.equal((await maker.call('getSession')).user.email,'maker@local.test');
 assert.equal((await maker.call('listCareerTracks')).items.length,31);assert.equal((await maker.call('listGuilds')).items.length,15);
 const profile=await maker.call('savePositioning',{...key(),body:{real_world_occupations:['示範'],background:'',strengths:['規格整理'],goals:'供貨測試',weekly_minutes:30,desired_roles:['supplier'],selected_tracks:['food_supplier'],confirmed:true}});
 assert.equal((await maker.call('getPositioning')).profile?.profile_id,profile.profile_id);
 const membership=await maker.call('joinGuild',{...key(),params:{key:'guild_product_quality_supply'},body:{}});
 assert.equal((await maker.call('leaveGuild',{...key(),params:{key:'guild_product_quality_supply'},body:{},version:membership.aggregate_version})).state,'left');
 const productBody={title:'協定測試茶葉',specifications:'150g',net_price_minor:30000,currency:'TWD' as const,availability:'manual_confirmation' as const,stock:null,shipping_terms:'測試出貨',return_terms:'測試退貨'};
 const retry=key();const product=await maker.call('createSupplierProduct',{...retry,body:productBody});
 assert.equal((await maker.call('createSupplierProduct',{...retry,body:productBody})).product_id,product.product_id);
 await assert.rejects(maker.call('createSupplierProduct',{...retry,body:{...productBody,title:'changed'}}),{code:'idempotency_conflict',status:409});
 assert.equal((await maker.call('listSupplierProducts')).items.length,1);assert.equal((await seller.call('listCatalog')).items[0].product_id,product.product_id);
 const store=await seller.call('createStore',{...key(),body:{name:'協定測試店',description:'internal preview',support_contact:'test contact'}});
 assert.equal((await seller.call('listStores')).items[0].store_id,store.store_id);
 const listing=await seller.call('createListing',{...key(),body:{store_id:store.store_id,offer_version_id:product.current_offer.offer_version_id,retail_price_minor:55000,sale_terms:'test only'}});
 await seller.call('requestSupply',{...key(),params:{id:listing.listing_id},version:listing.aggregate_version,body:{snapshot_sha256:listing.snapshot_sha256}});
 const request=(await maker.call('listSupplyRequests')).items[0];
 await assert.rejects(seller.call('decideSupplyRequest',{...key(),params:{id:request.acceptance_id},version:request.aggregate_version,body:{decision:'accepted',note:'not owner',snapshot_sha256:request.snapshot_sha256,acknowledge_internal_preview:true}}),{status:404});
 await maker.call('decideSupplyRequest',{...key(),params:{id:request.acceptance_id},version:request.aggregate_version,body:{decision:'accepted',note:'preview only',snapshot_sha256:request.snapshot_sha256,acknowledge_internal_preview:true}});
 assert.equal((await seller.call('listListings')).items[0].state,'accepted');
 const campaign=await maker.call('createCampaign',{...key(),body:{title:'供貨草稿',audience:'test',goal:'read',draft_text:'test text',source_supplier_product_id:product.product_id}});
 await maker.call('createSupplierOffer',{...key(),params:{id:product.product_id},version:product.aggregate_version,body:{...productBody, title:undefined,specifications:undefined} as any}).then(()=>assert.fail('unknown keys must fail'),()=>{});
 const {title:_,specifications:__,...offer}=productBody;
 await maker.call('createSupplierOffer',{...key(),params:{id:product.product_id},version:product.aggregate_version,body:{...offer,net_price_minor:32000}});
 const updated=await maker.call('reviseCampaign',{...key(),params:{id:campaign.campaign_id},version:campaign.aggregate_version,body:{title:'供貨草稿',audience:'test',goal:'read',draft_text:'updated text'}});
 assert.deepEqual(updated.source_snapshot,campaign.source_snapshot);
 await assert.rejects(maker.call('reviseCampaign',{...key(),params:{id:campaign.campaign_id},version:campaign.aggregate_version,body:{title:'供貨草稿',audience:'test',goal:'read',draft_text:'stale'}}),{status:412});
 const shared=await maker.call('recordShare',{...key(),params:{id:campaign.campaign_id},version:updated.aggregate_version,body:{channel:'test',share_url:'https://github.com/FreeTWAI-AI/freedom-platform',note:'synthetic'}});
 assert.equal((shared.shares as any[])[0].verification_status,'self_reported');
 assert.equal((await seller.call('listCampaigns')).items.length,0);assert.equal((await maker.call('listCampaigns')).items.length,1);
 assert.equal((await maker.call('listProjects')).items.length,0);assert(Array.isArray((await maker.call('listWorks')).items));await maker.call('getDashboard');
 await maker.call('logout',{body:{}});await assert.rejects(maker.call('getSession'),{status:401});await seller.call('logout',{body:{}});
});
test('SDK refuses protocol skew, redirected credentials, unsafe identifiers and implicit retries',async()=>{
 let calls=0;
 const skew=new PlatformClient({baseUrl,csrfToken:'test',fetcher:async()=>{calls++;return Response.json({...metadata,protocol_sha256:'0'.repeat(64)});}});
 await assert.rejects(skew.call('createStore',{...key(),body:{name:'a',description:'b',support_contact:'c'}}),/differs from the pinned contract/);assert.equal(calls,1);
 const client=new PlatformClient({baseUrl,csrfToken:'test',fetcher:async(input,options)=>{calls++;assert.equal(options?.redirect,'error');if(String(input).endsWith('/protocol'))return Response.json(metadata);throw new Error('simulated uncertain network outcome');}});
 await client.assertCompatible();calls=0;
 await assert.rejects(client.call('reviseCampaign',{...key(),params:{id:'../../auth/logout'},version:1,body:{title:'a',audience:'b',goal:'c',draft_text:'d'}}),/identifier/);assert.equal(calls,0);
 for(const field of ['constructor','__proto__'])await assert.rejects(client.call('joinGuild',{...key(),params:{key:'guild_marketing'},body:JSON.parse('{"'+field+'":{"admin":true}}')}),/unknown field/);assert.equal(calls,0);
 await assert.rejects(client.call('createStore',{body:{name:'a',description:'b',support_contact:'c'}}),/Idempotency/);assert.equal(calls,0);
 await assert.rejects(client.call('createStore',{...key(),body:{name:'a',description:'b',support_contact:'c'}}),/uncertain network/);assert.equal(calls,1);
 await assert.rejects(PlatformClient.loginDemo({baseUrl:'https://staging.freetwai.com/api/v1',email:'maker@local.test',password:'freedom-local-demo'}),/loopback/);
 assert.throws(()=>new PlatformClient({baseUrl:'https://api.example/api/v1',appOrigin:'https://evil.example'}),/match/);
});
