import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import {migrate} from '../../scripts/database.js';
import {tokenHash,type Actor} from '../../modules/identity-membership/service.js';
import {createSocialThumbnailAssetService,resolveSocialThumbnailUploadPolicy} from '../../modules/assets/social-thumbnail.js';
import {saveSocialThumbnail,readSocialThumbnail,publicSocialThumbnail,deleteSocialPost,createSocialPost,listSocialPosts} from '../../modules/community/social-posts.js';
import {FakeObjectStore} from '../../packages/asset-storage/fake-store.js';
import {sha256,objectKey} from '../../packages/asset-storage/index.js';
import {createApp} from '../../apps/platform-api/src/app.js';
import {Problem} from '../../packages/shared/problem.js';
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('Explicit isolated TEST_DATABASE_URL required');
const schema=`fp_social_media_${process.pid}_${Date.now()}`,role=`${schema}_app`,admin=new Pool({connectionString:url}),fixture=new Pool({connectionString:url,options:`-c search_path=${schema} -c statement_timeout=10000`}),pool=new Pool({connectionString:url,options:`-c role=${role} -c search_path=${schema} -c statement_timeout=10000`});
const community=randomUUID();let png:Buffer,initialized=false,mf:Miniflare,bucket:AssetR2Binding;
before(async()=>{await admin.query(`CREATE ROLE ${role} NOLOGIN;CREATE SCHEMA ${schema};GRANT USAGE ON SCHEMA ${schema} TO ${role}`);initialized=true;await migrate(fixture);await fixture.query(`GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ${schema} TO ${role};GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA ${schema} TO ${role}`);const grants=await readFile(new URL('../../deploy/cloudflare/sql/20-runtime-grants.psql',import.meta.url),'utf8');for(const match of grants.matchAll(/-- BEGIN [A-Z ]+\n([\s\S]*?)\n\\gexec/g)){const sql=match[1].replaceAll(":'runtime'",`'${role}'`).replaceAll("n.nspname='public'",`n.nspname='${schema}'`);for(const row of (await fixture.query(sql)).rows)await fixture.query(Object.values(row)[0] as string);}png=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).png().toBuffer();mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'fp-social-domain-test',modules:true,script:'export default {fetch(){return new Response("synthetic");}}',compatibilityDate:'2026-09-21',r2Buckets:['MEDIA']}]}));await mf.ready;bucket=await mf.getR2Bucket('MEDIA') as unknown as AssetR2Binding;});
after(async()=>{await mf?.dispose();await pool.end();await fixture.end();if(initialized)await admin.query(`DROP SCHEMA ${schema} CASCADE;DROP ROLE ${role}`);await admin.end();});
beforeEach(async()=>{await fixture.query('TRUNCATE communities CASCADE');await fixture.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-social-policy',persistence_allowed=true,retained_byte_limit=10485760 WHERE purpose='community.social-thumbnail'");await fixture.query('INSERT INTO communities VALUES($1,$2)',[community,'Synthetic social']);});
async function member(communityId=community){const id=randomUUID(),token=randomBytes(32).toString('base64url'),hash=tokenHash(token);const row=(await fixture.query('INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,communityId,id+'@social.local.test','Synthetic owner','not-a-login-hash',randomUUID()])).rows[0];await fixture.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,'synthetic',clock_timestamp()+interval '1 hour')",[hash,id]);return {...row,session_hash:hash,csrf_token:'synthetic',synthetic_token:token} as Actor;}
async function setup(native=false){const owner=await member(),id=randomUUID();await fixture.query("INSERT INTO community_social_posts(post_id,community_id,author_user_id,url,platform,title,state) VALUES($1,$2,$3,'https://example.org/synthetic-post','other','Synthetic','active')",[id,community,owner.user_id]);const store=native?{...createR2ObjectStore(bucket)}:new FakeObjectStore(),api=createSocialThumbnailAssetService(pool,{store,resolvePolicy:resolveSocialThumbnailUploadPolicy});return {owner,id,store,api};}
async function upload(s:Awaited<ReturnType<typeof setup>>,version='1'){const prepared=await s.api.prepare(s.owner,{key:randomUUID(),targetPostId:s.id,expectedVersion:version,contentType:'image/png',byteSize:png.length,sha256:await sha256(png)});const claim=await s.api.claim(s.owner,{key:randomUUID(),intentId:prepared.intentId});const lease={intentId:claim.intentId,fence:claim.fence,leaseToken:claim.leaseToken};await s.api.write(s.owner,{key:randomUUID(),...lease},new ReadableStream({start(c){c.enqueue(png);c.close();}}));return {...prepared,lease};}
const code=(c:string)=>(e:unknown)=>e instanceof Problem&&e.code===c;
test('restricted app publishes genuine community asset and native R2 verifies original640x360 WebP',async()=>{const s=await setup(true),u=await upload(s);assert.equal((await pool.query('SELECT count(*)::int n FROM community_social_post_thumbnails')).rows[0].n,0);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});const row=(await pool.query('SELECT a.scope_kind,a.community_ref,r.owner_principal_id,o.profile_id FROM assets a JOIN resource_scopes r ON r.scope_id=a.scope_id JOIN asset_objects o USING(asset_id)')).rows[0];assert.equal(row.scope_kind,'community');assert.equal(row.community_ref,community);assert.equal(row.owner_principal_id,null);assert.equal(row.profile_id,'community.social-thumbnail');const bytes=await readSocialThumbnail(pool,s.owner,s.id,s.store),meta=await sharp(bytes).metadata();assert.equal(meta.format,'webp');assert.equal(meta.width,640);assert.equal(meta.height,360);assert.deepEqual(await publicSocialThumbnail(pool,s.id,s.store),bytes);assert.equal((await listSocialPosts(pool,s.owner,{})).items[0].thumbnail_url,`/api/v1/social-posts/${s.id}/thumbnail`);await assert.rejects(pool.query("UPDATE domain_media_storage_policy SET persistence_allowed=true"),(e:any)=>e.code==='42501');});
test('original HTTP PUT needs no new If-Match, preserves URL DTO CSRF and exact receipt without another PUT',async()=>{const s=await setup(),origin='http://127.0.0.1:4310',app=createApp(pool,origin,'local',{socialThumbnailAssets:s.api,socialThumbnailAssetStore:s.store}),headers={Origin:origin,Cookie:`freedom_local_session=${(s.owner as Actor&{synthetic_token:string}).synthetic_token}`,'X-CSRF-Token':'synthetic','Content-Type':'image/png','Idempotency-Key':randomUUID()},path=`/api/v1/social-posts/${s.id}/thumbnail`;let writes=0;const put=s.store.putImmutable.bind(s.store);s.store.putImmutable=async(...args)=>{writes++;return put(...args);};const send=()=>app.request(origin+path,{method:'PUT',headers,body:new Uint8Array(png)});const response=await send(),dto=await response.json() as any;assert.equal(response.status,200,JSON.stringify(dto));assert.equal(dto.thumbnail_url,path);assert.equal('media_version' in dto,false);assert.equal('asset_id' in dto,false);assert.deepEqual(await(await send()).json(),dto);assert.equal(writes,1);const read=await app.request(origin+path,{headers:{Cookie:headers.Cookie}});assert.equal(read.status,200);assert.equal(read.headers.get('cache-control'),'private, no-store');const publicRead=await app.request(origin+`/api/v1/public/social-posts/${s.id}/thumbnail`);assert.equal(publicRead.status,200);assert.equal(publicRead.headers.get('cache-control'),'public, max-age=300');const denied=await app.request(origin+path,{method:'PUT',headers:{...headers,'X-CSRF-Token':'wrong','Idempotency-Key':randomUUID()},body:new Uint8Array(png)});assert.equal(denied.status,403);assert.equal(writes,1);});
test('historical legacy previews remain byte-preserved and block R2-only cutover',async()=>{const s=await setup(),webp=await sharp(png).resize(640,360).webp().toBuffer();await fixture.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,'youtube')",[s.id,webp]);assert.deepEqual(await publicSocialThumbnail(pool,s.id),webp);const row=(await pool.query('SELECT source,storage_source FROM community_social_post_thumbnails')).rows[0];assert.deepEqual(row,{source:'youtube',storage_source:'legacy'});await assert.rejects(fixture.query("UPDATE domain_media_storage_policy SET mode='r2_only' WHERE purpose='community.social-thumbnail'"),(e:any)=>e.code==='23514');});
test('owner/current active post and internal stale source CAS remain authoritative',async()=>{const s=await setup(),peer=await member();await assert.rejects(s.api.prepare(peer,{key:randomUUID(),targetPostId:s.id,expectedVersion:'1',contentType:'image/png',byteSize:png.length,sha256:await sha256(png)}),code('author_required'));const u=await upload(s);const legacy=await sharp(png).webp().toBuffer();await fixture.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,'youtube')",[s.id,legacy]);await assert.rejects(s.api.finalize(s.owner,{key:randomUUID(),...u.lease}),code('version_conflict'));assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'pending');});
test('no installed transport cannot fall back to retained original bytes after Asset publication',async()=>{const s=await setup(),legacy=await sharp(png).webp().toBuffer();await fixture.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,'page')",[s.id,legacy]);const u=await upload(s,'2');await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});assert.deepEqual((await pool.query('SELECT image_bytes FROM community_social_post_thumbnails')).rows[0].image_bytes,legacy);await assert.rejects(readSocialThumbnail(pool,s.owner,s.id),code('media_unavailable'));await assert.rejects(publicSocialThumbnail(pool,s.id),code('media_unavailable'));await assert.rejects(pool.query('UPDATE community_social_thumbnail_asset_targets SET asset_id=NULL WHERE post_id=$1',[s.id]),(e:any)=>e.code==='23514');});
test('post deletion retires pointer, retains historical bytes, and old member/public URLs stop serving',async()=>{const s=await setup(),legacy=await sharp(png).webp().toBuffer();await fixture.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,'page')",[s.id,legacy]);const u=await upload(s,'2');await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});await deleteSocialPost(pool,{actor:s.owner,operation:`DELETE /api/v1/social-posts/${s.id}`,key:randomUUID(),body:{}},s.id);assert.equal((await pool.query('SELECT asset_id FROM community_social_thumbnail_asset_targets')).rows[0].asset_id,null);assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'retired');assert.deepEqual((await pool.query('SELECT image_bytes FROM community_social_post_thumbnails')).rows[0].image_bytes,legacy);await assert.rejects(publicSocialThumbnail(pool,s.id,s.store),code('not_found'));await assert.rejects(readSocialThumbnail(pool,s.owner,s.id,s.store),code('not_found'));});
test('public visibility change and member session revocation during object IO reject returned bytes',async()=>{const s=await setup(),u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});const get=s.store.get.bind(s.store);s.store.get=async(...args)=>{const value=await get(...args);await fixture.query('UPDATE sessions SET revoked_at=clock_timestamp() WHERE token_hash=$1',[s.owner.session_hash]);return value;};await assert.rejects(readSocialThumbnail(pool,s.owner,s.id,s.store),code('not_found'));s.store.get=async(...args)=>{const value=await get(...args);await fixture.query("UPDATE community_social_posts SET state='hidden' WHERE post_id=$1",[s.id]);return value;};await assert.rejects(publicSocialThumbnail(pool,s.id,s.store),code('not_found'));assert.equal((await pool.query('SELECT state FROM assets')).rows[0].state,'retired');});
test('canonical disabled policy and closed input reject before object effects; missing host port is503',async()=>{const s=await setup();await fixture.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.social-thumbnail'");await assert.rejects(upload(s),code('media_upload_unavailable'));await fixture.query("UPDATE domain_media_storage_policy SET persistence_allowed=true WHERE purpose='community.social-thumbnail'");await assert.rejects(s.api.prepare(s.owner,{key:randomUUID(),targetPostId:s.id,expectedVersion:'1',contentType:'image/png',byteSize:524289,sha256:await sha256(png)}));await assert.rejects(saveSocialThumbnail(pool,{actor:s.owner,operation:`PUT /api/v1/social-posts/${s.id}/thumbnail`,key:randomUUID(),body:null},s.id,{bytes:png,mime:'image/png'}),code('media_upload_unavailable'));assert.equal((await pool.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);});

test('replacement retires prior asset and native missing object cannot resurrect retained preview bytes',async()=>{const s=await setup(true),legacy=await sharp(png).webp().toBuffer();await fixture.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,'page')",[s.id,legacy]);const a=await upload(s,'2');await s.api.finalize(s.owner,{key:randomUUID(),...a.lease});const b=await upload(s,'3');await s.api.finalize(s.owner,{key:randomUUID(),...b.lease});assert.equal((await pool.query('SELECT state FROM assets WHERE asset_id=$1',[a.assetId])).rows[0].state,'retired');const row=(await pool.query('SELECT scope_id,representation_id FROM asset_objects WHERE asset_id=$1',[b.assetId])).rows[0];const key=objectKey({assetId:b.assetId,scopeId:row.scope_id,representationId:row.representation_id});await assert.rejects(s.store.delete(key));await bucket.delete(key);await assert.rejects(publicSocialThumbnail(pool,s.id,s.store),code('media_unavailable'));assert.deepEqual((await pool.query('SELECT image_bytes FROM community_social_post_thumbnails')).rows[0].image_bytes,legacy);});
test('member thumbnail scope remains community-specific while original active public thumbnail stays public',async()=>{const s=await setup(),u=await upload(s);await s.api.finalize(s.owner,{key:randomUUID(),...u.lease});const foreign=randomUUID();await fixture.query('INSERT INTO communities VALUES($1,$2)',[foreign,'Synthetic foreign']);const peer=await member(foreign);await assert.rejects(readSocialThumbnail(pool,peer,s.id,s.store),code('not_found'));await assert.rejects(readSocialThumbnail(pool,{...s.owner,session_hash:undefined} as unknown as Actor,s.id,s.store),code('not_found'));assert.ok((await publicSocialThumbnail(pool,s.id,s.store)).length);});
