import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import './AdminPermissions.css';
import './AdminLayout.css';
import {ADMIN_ACCESS_EXPIRED_MESSAGE,AdminClient,AdminRequestError} from './admin-client';
import {AdminGitHubSetup} from './AdminGitHubSetup';
import {AdminGuildWorkspace} from './GuildWorkspace';
import {AdminGuildManagement,type ManagedGuild} from './AdminGuildManagement';

type Admin = {admin_id:string;email:string;display_name:string;role:string;community_id:string};
type Bootstrap = {admin:Admin;csrf_token:string;available_skill_books:{id:string;title:string}[];pending_guild_appointments?:{guild_key:string;name:string;state:'pending'|'bound';bound_user_id:string|null}[];summary:{members:number;active_members:number;pending_guild_applications:number;guilds:number;admins:number}};
type AccessState='pending'|'ready'|'pending_removal'|'revoked';
type MemberAdmin={admin_id:string;active:boolean;aggregate_version:number;access_state:AccessState};
type Member = {platform_admin?:MemberAdmin|null;user_id:string;email:string;display_name:string;active:boolean;onboarding_required:boolean;onboarding_completed_at:string|null;aggregate_version:number;guilds:{guild_key:string;name:string}[]};
type GuildApplication = {application_id:string;name:string;profession:string;reason:string;state:string;applicant_name:string;applicant_email?:string;aggregate_version:number;review_reason?:string|null;reviewreason?:string|null;approved_guild_key?:string|null};
type Guild = ManagedGuild & {first_step:string;module_key:string};
type AdminNomination = {aggregate_version?:number;access_state?:AccessState;user_id?:string|null;admin_id?:string;email?:string|null;display_name?:string;role?:string;state?:string;status?:string;enabled?:boolean;active?:boolean;identity_binding?:'no_member_account'|'unverified_email_match'|'verified_email_match';member_account_present?:boolean;member_account_active?:boolean;member_email_verified?:boolean};
type Audit = {audit_id?:string;admin_name?:string;actor_email?:string;actor_name?:string;actor_display_name?:string;action:string;reason:string;target_ref?:string;target_id?:string;target_type?:string;created_at?:string;at?:string};
type AdminTab = 'members'|'guild-applications'|'guilds'|'admins'|'guild-workspace'|'github'|'audit';
const accessLabel=(state?:AccessState)=>state==='ready'?'可登入管理頁':state==='pending'?'登入權限同步中':state==='pending_removal'?'停用同步中':state==='revoked'?'登入權限已停用':'登入權限待確認';
const adminGroups:{label:string;items:[AdminTab,string][] }[]=[
  {label:'人員與權限',items:[['members','會員管理'],['admins','管理員名單']]},
  {label:'公會',items:[['guilds','公會管理'],['guild-applications','公會申請'],['guild-workspace','會長與維護者']]},
  {label:'系統',items:[['github','GitHub 連結'],['audit','操作紀錄']]},
];
const moduleOptions=[['guilds','公會交流'],['engagement','社群參與'],['positioning','定位與陪跑'],['supplier','供貨'],['retail','商店與銷售'],['opensource','開源作品'],['marketing','行銷'],['workbench','互助協作']];
export function AdminPanel(){
  const client=useRef(new AdminClient()).current;
  const [bootstrap,setBootstrap]=useState<Bootstrap|null>(null),[bootError,setBootError]=useState(''),[booting,setBooting]=useState(true),[tab,setTab]=useState<AdminTab>(window.location.pathname==='/admin/github/callback'?'github':'members');
  const [members,setMembers]=useState<Member[]>([]),[query,setQuery]=useState(''),[nextOffset,setNextOffset]=useState<number|null>(null),[applications,setApplications]=useState<GuildApplication[]>([]),[applicationOffset,setApplicationOffset]=useState<number|null>(null),[guilds,setGuilds]=useState<Guild[]>([]),[admins,setAdmins]=useState<AdminNomination[]>([]),[audit,setAudit]=useState<Audit[]>([]);
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[accessExpired,setAccessExpired]=useState(false);
  const [accessRefresh,setAccessRefresh]=useState(0);
  const lock=useRef(false),keys=useRef(new Map<string,string>()),loadSequence=useRef(0),appliedQuery=useRef(''),startSequence=useRef(0);
  const start=useCallback(async()=>{const sequence=++startSequence.current;setBooting(true);setBootError('');try{const value=await client.request<Bootstrap>('/bootstrap');if(sequence!==startSequence.current)return;client.csrf=value.csrf_token;setBootstrap(value);}catch(cause){if(sequence!==startSequence.current)return;setBootstrap(null);setBootError(cause instanceof Error?cause.message:'無法確認管理員身分。');}finally{if(sequence===startSequence.current)setBooting(false);}},[client]);
  const load=useCallback(async(offset=0)=>{const sequence=++loadSequence.current;setLoading(true);setError('');try{
    if(tab==='members'){const value=await client.request<{items:Member[];next_offset:number|null}>(`/members?limit=25&offset=${offset}&q=${encodeURIComponent(appliedQuery.current)}`);if(sequence===loadSequence.current){setMembers(current=>offset?[...current,...value.items]:value.items);setNextOffset(value.next_offset);}}
    if(tab==='guild-applications'){const value=await client.request<{items:GuildApplication[];next_offset:number|null}>(`/guild-applications?state=all&limit=25&offset=${offset}`);if(sequence===loadSequence.current){setApplications(current=>offset?[...current,...value.items]:value.items);setApplicationOffset(value.next_offset);}}
    if(tab==='guilds'){const value=await client.request<{items:Guild[]}>('/guilds');if(sequence===loadSequence.current)setGuilds(value.items);}
    if(tab==='admins'){const value=await client.request<{items:AdminNomination[]}>('/admins');if(sequence===loadSequence.current)setAdmins(value.items);}
    if(tab==='audit'){const value=await client.request<{items:Audit[]}>('/audit');if(sequence===loadSequence.current)setAudit(value.items);}
  }catch(cause){if(sequence===loadSequence.current)setError(cause instanceof Error?cause.message:'無法載入管理資料。');}finally{if(sequence===loadSequence.current)setLoading(false);}},[client,tab]);
  useEffect(()=>{client.onAccessExpired=()=>setAccessExpired(true);client.onAccessRecovered=()=>setAccessExpired(false);return()=>{client.onAccessExpired=null;client.onAccessRecovered=null;};},[client]);
  useEffect(()=>{void start();},[start]);
  useEffect(()=>{if(bootstrap)void load();return()=>{loadSequence.current+=1;};},[bootstrap?.admin.admin_id,tab]);
  const pendingAccess=admins.filter(admin=>admin.access_state==='pending'||admin.access_state==='pending_removal').map(admin=>`${admin.admin_id}:${admin.aggregate_version}`).sort().join(',');
  useEffect(()=>{
    if(!bootstrap||tab!=='admins'||!pendingAccess)return;
    let stopped=false,attempts=0,timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{
      if(stopped||attempts++>=12)return;
      if(document.visibilityState==='visible'&&!lock.current){
        const sequence=loadSequence.current;
        try{const value=await client.request<{items:AdminNomination[]}>('/admins');if(!stopped&&sequence===loadSequence.current)setAdmins(value.items);}
        catch(cause){if(!stopped){stopped=true;setError(cause instanceof Error?cause.message:'登入狀態暫時無法更新，請手動重新整理。');}}
      }
      if(!stopped&&attempts<12)timer=setTimeout(()=>void poll(),5000);
    };
    timer=setTimeout(()=>void poll(),5000);
    return()=>{stopped=true;clearTimeout(timer);};
  },[client,bootstrap?.admin.admin_id,tab,pendingAccess,accessRefresh]);
  async function mutate(path:string,body:unknown,version?:number|null){if(lock.current)return false;lock.current=true;setBusy(true);setError('');setNotice('');const request=JSON.stringify([path,body,version]),key=keys.current.get(request)??crypto.randomUUID();keys.current.set(request,key);try{await client.request(path,body,{key,version});keys.current.delete(request);await load();await start();setNotice('管理操作已保存，並留下操作紀錄。');return true;}catch(cause){if(cause instanceof AdminRequestError&&cause.status>0&&cause.status<500)keys.current.delete(request);setError(cause instanceof Error?cause.message:'操作未完成，請重新確認結果。');return false;}finally{lock.current=false;setBusy(false);}}
  async function memberSearch(event:FormEvent){event.preventDefault();appliedQuery.current=query.trim();await load();}

  const refreshSummary=()=>void start();
  return <main className="admin-layout admin-workspace"><header className="admin-header"><div className="brand"><span className="mark" aria-hidden="true"/><div><p className="eyebrow">FREEDOM WORKSHOP</p><h1>平台管理</h1></div></div><a className="btn btn-ghost" href="/">返回自由工坊</a></header>
    {booting&&<p role="status">正在確認管理員身分…</p>}
    {!booting&&!bootstrap&&<section className="card stack"><h2>需要管理員驗證</h2><p>這是獨立的管理入口，僅限已核准的管理員。請使用管理員的 Access 身分登入。</p>{bootError&&<p className="banner banner-error" role="alert">{bootError}</p>}{accessExpired?<button type="button" className="btn btn-primary" onClick={()=>window.location.reload()}>重新載入頁面</button>:<button className="btn btn-primary" onClick={()=>void start()}>重新確認管理身分</button>}</section>}
    {bootstrap&&<>
      <div className="admin-context-row">
        <details className="admin-account">
          <summary><strong>{bootstrap.admin.display_name}</strong><span>{bootstrap.admin.role==='super_admin'?'平台管理員':'管理員'}</span></summary>
          <div className="admin-account-details"><p>{bootstrap.admin.email}</p><button className="btn btn-ghost" onClick={refreshSummary} disabled={busy||booting}>重新確認管理身分</button></div>
        </details>
        <details className="admin-overview">
          <summary>平台概況{bootstrap.summary.pending_guild_applications>0&&<span className="badge">{bootstrap.summary.pending_guild_applications} 件公會申請</span>}</summary>
          <dl className="admin-summary" aria-label="平台管理概況">{[['會員',bootstrap.summary.members],['有效會員',bootstrap.summary.active_members],['待處理公會申請',bootstrap.summary.pending_guild_applications],['公會',bootstrap.summary.guilds],['管理員',bootstrap.summary.admins]].map(([name,value])=><div key={String(name)}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>
        </details>
      </div>
      {(bootstrap.pending_guild_appointments?.length??0)>0&&<section className="card stack admin-pending-appointments"><h2>我的公會長任命</h2><p>完成同信箱的會員定位後，確認連結公會長職務。</p><ul>{bootstrap.pending_guild_appointments?.map(appointment=><li key={appointment.guild_key}>{appointment.name} · {appointment.state==='bound'?'已連結會員並確認任命':'等待本人確認連結'}</li>)}</ul>{bootstrap.pending_guild_appointments?.some(appointment=>appointment.state==='pending')&&<div className="actions"><a className="btn btn-ghost" href="/" target="_blank" rel="noopener noreferrer">開啟會員登入與定位 ↗</a><button className="btn btn-primary" disabled={busy} onClick={()=>void mutate('/link-member',{})}>連結我的會員帳號並確認會長任命</button></div>}</section>}
      <nav className="admin-tabs" aria-label="平台管理選單">{adminGroups.map(group=><div className="admin-nav-group" key={group.label} role="group" aria-label={group.label}><span className="admin-nav-label">{group.label}</span><div className="admin-nav-items">{group.items.map(([key,label])=><button className={tab===key?'btn btn-primary':'btn btn-ghost'} aria-current={tab===key?'page':undefined} key={key} onClick={()=>{setTab(key);setNotice('');}}>{label}</button>)}</div></div>)}</nav>
      {accessExpired?<div className="banner banner-error" role="alert"><p>{ADMIN_ACCESS_EXPIRED_MESSAGE}</p><div className="actions"><button type="button" className="btn btn-primary" onClick={()=>window.location.reload()}>重新載入頁面</button></div></div>:error&&tab!=='guilds'&&<div className="banner banner-error" role="alert">{error}<div className="actions"><button className="btn btn-ghost" onClick={()=>void load()} disabled={busy}>重新載入資料</button>{!client.csrf&&<button className="btn btn-ghost" onClick={()=>void start()}>重新確認管理身分</button>}</div></div>}{notice&&<p className="banner status-note" role="status">{notice}</p>}{loading&&<p role="status">正在載入管理資料…</p>}
      {tab==='members'&&<section className="stack"><h2>會員管理</h2><form className="admin-search" onSubmit={memberSearch}><label className="field">搜尋會員<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="暱稱或 Email" maxLength={100}/></label><button className="btn btn-ghost" disabled={loading}>搜尋</button></form><div className="card-grid">{members.map(member=><article className="card stack" key={member.user_id}><div className="card-head"><h3>{member.display_name}</h3><span className="badge">{member.active?'啟用中':'已停用'}</span></div><p>{member.email}</p><p className="muted">{member.onboarding_completed_at?'已完成定位':member.onboarding_required?'定位進行中':'既有會員'}</p><div className="admin-member-permissions">{member.platform_admin?<><span className="badge">{member.platform_admin.active?'平台管理員':'管理權限已停用'}</span><p className="field-hint">{accessLabel(member.platform_admin.access_state)}</p><a href="#admin-list" onClick={event=>{event.preventDefault();setTab('admins');setNotice('');}}>前往管理員名單 ↗</a></>:<><AdminPermissionControl action="appoint" person={{display_name:member.display_name,email:member.email}} busy={busy} disabled={!member.active} onSubmit={reason=>mutate(`/members/${member.user_id}/admin`,{reason,confirmed:true},member.aggregate_version)}/>{!member.active&&<p className="field-hint">先重新啟用會員，再任命管理員。</p>}</>}</div><AdminReasonForm label={member.active?'停用這位會員':'重新啟用會員'} busy={busy} onSubmit={reason=>mutate(`/members/${member.user_id}/status`,{active:!member.active,reason},member.aggregate_version)}/></article>)}</div>{!loading&&!members.length&&!error&&<p className="muted">沒有符合條件的會員。</p>}{nextOffset!==null&&<button className="btn btn-ghost" onClick={()=>void load(nextOffset)} disabled={loading}>查看更多會員</button>}</section>}
      {tab==='guild-applications'&&<section className="stack"><h2>公會申請</h2>{applications.map(application=><GuildReview key={application.application_id} application={application} books={bootstrap.available_skill_books} busy={busy} onReview={(body)=>mutate(`/guild-applications/${application.application_id}/review`,body,application.aggregate_version)}/>)}{applicationOffset!==null&&<button className="btn btn-ghost" disabled={loading} onClick={()=>void load(applicationOffset)}>查看更多公會申請</button>}{!loading&&!applications.length&&!error&&<p className="muted">目前沒有公會申請。</p>}</section>}
      {tab==='guilds'&&<AdminGuildManagement client={client} guilds={guilds} busy={busy} loading={loading} error={accessExpired?'':error} onReload={()=>load()} onExpert={(guild,userId,active,reason,version)=>mutate(`/guilds/${encodeURIComponent(guild.guild_key)}/experts`,{user_id:userId,active,reason},version)} onSave={(guild,userId,reason)=>mutate(`/guilds/${encodeURIComponent(guild.guild_key)}/master`,{user_id:userId,reason},guild.officer_version)}/>}
      {tab==='admins'&&<section className="stack" id="admin-list"><div className="card-head"><h2>管理員名單</h2><button type="button" className="btn btn-ghost" disabled={busy||loading} onClick={()=>{setAccessRefresh(value=>value+1);void load();}}>更新登入狀態</button></div><p className="muted">管理員擁有平台全部管理權限。調整管理權限不會變更會員帳號狀態。</p><div className="card-grid">{admins.map((admin,index)=><article className="card stack admin-permission-card" key={admin.admin_id??index}><div className="card-head"><h3>{admin.display_name??'待確認人選'}</h3><span className="badge">{admin.active?'管理權限已啟用':'管理權限已停用'}</span></div><p>{admin.email??'登入身分待確認'}</p><p className="muted">超級管理員 · 平台全部管理權限</p><p className={`admin-access-state admin-access-${admin.access_state??'unknown'}`}>{accessLabel(admin.access_state)}</p>{admin.access_state==='pending_removal'&&<p className="field-hint">管理操作已停用，正在更新登入名單。</p>}<p className="field-hint">{admin.identity_binding==='verified_email_match'?'有已驗證的同信箱會員帳號':admin.identity_binding==='unverified_email_match'?'同信箱會員尚未驗證，不視為身分綁定':'尚未建立同信箱會員帳號'}。</p>{admin.admin_id===bootstrap.admin.admin_id?<p className="field-hint">目前登入的管理員</p>:admin.admin_id&&admin.aggregate_version&&<AdminPermissionControl key={`${admin.admin_id}-${admin.aggregate_version}`} action={admin.active?'deactivate':'activate'} person={{display_name:admin.display_name??'管理員',email:admin.email??''}} busy={busy} onSubmit={reason=>mutate(`/admins/${admin.admin_id}/status`,{active:!admin.active,reason,confirmed:true},admin.aggregate_version)}/>}</article>)}</div></section>}
      {tab==='github'&&<AdminGitHubSetup client={client}/>}
      {tab==='guild-workspace'&&<AdminGuildWorkspace client={client}/>}
      {tab==='audit'&&<section className="stack"><h2>操作紀錄</h2><p className="muted">最近的管理操作與填寫理由，方便回查。</p>{audit.map((entry,index)=><article className="card stack" key={entry.audit_id??index}><div className="card-head"><strong>{{member_status:'調整會員狀態',guild_application_review:'審核公會申請',appoint_guild_master:'任命公會長',appoint_guild_expert:'任命公會專家',remove_guild_expert:'移除公會專家',appoint_platform_admin:'任命平台管理員',platform_admin_status:'調整管理權限',link_verified_member:'確認會員身分',accept_nominated_guild_master:'確認公會長任命'}[entry.action]??entry.action}</strong>{(entry.created_at??entry.at)?<time dateTime={entry.created_at??entry.at}>{new Date(entry.created_at??entry.at??'').toLocaleString('zh-TW')}</time>:<span className="field-hint">時間未記錄</span>}</div><p>操作人：{entry.admin_name??entry.actor_display_name??entry.actor_name??entry.actor_email??'管理員'}</p><p>{entry.reason}</p>{(entry.target_ref??entry.target_id)&&<p className="field-hint">對象：{entry.target_type??''} {entry.target_ref??entry.target_id}</p>}</article>)}{!loading&&!audit.length&&!error&&<p className="muted">目前沒有管理操作紀錄。</p>}</section>}
    </>}
  </main>;
}
function AdminPermissionControl({action,person,busy,disabled=false,onSubmit}:{action:'appoint'|'activate'|'deactivate';person:{display_name:string;email:string};busy:boolean;disabled?:boolean;onSubmit:(reason:string)=>Promise<boolean>}){
  const [open,setOpen]=useState(false),[reason,setReason]=useState('');
  const label=action==='appoint'?'任命管理員':action==='activate'?'重新啟用管理權限':'停用管理權限';
  const confirm=action==='appoint'?'確認任命':action==='activate'?'確認重新啟用':'確認停用管理權限';
  return open?<form className="admin-permission-review stack" aria-label={label} onSubmit={async event=>{event.preventDefault();if(await onSubmit(reason.trim())){setOpen(false);setReason('');}}}>
    <div><h4>{label}</h4><p><strong>{person.display_name}</strong></p><p>{person.email}</p></div>
    <p>{action==='deactivate'?'停用後將無法再操作平台管理。':'任命為超級管理員，擁有平台全部管理權限，可管理會員、公會及其他管理員。'}</p>
    {action!=='appoint'&&<p className="field-hint">這項操作不變更會員帳號狀態。</p>}
    <label className="field">{action==='appoint'?'任命理由':'管理權限調整理由'}<textarea required minLength={3} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label>
    <div className="actions"><button className="btn btn-primary" disabled={busy||reason.trim().length<3}>{confirm}</button><button type="button" className="btn btn-ghost" disabled={busy} onClick={()=>setOpen(false)}>取消</button></div>
  </form>:<button type="button" className="btn btn-ghost" disabled={busy||disabled} onClick={()=>setOpen(true)}>{label}</button>;
}
function AdminReasonForm({label,busy,onSubmit}:{label:string;busy:boolean;onSubmit:(reason:string)=>Promise<boolean>}){
  const [open,setOpen]=useState(false),[reason,setReason]=useState('');
  return open?<form className="stack" onSubmit={async event=>{event.preventDefault();if(await onSubmit(reason)){setOpen(false);setReason('');}}}><label className="field">操作理由<textarea required minLength={3} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="actions"><button className="btn btn-primary" disabled={busy}>確認{label}</button><button type="button" className="btn btn-ghost" disabled={busy} onClick={()=>setOpen(false)}>取消</button></div></form>:<button className="btn btn-ghost" disabled={busy} onClick={()=>setOpen(true)}>{label}</button>;
}
function GuildReview({application:a,books,busy,onReview}:{application:GuildApplication;books:{id:string;title:string}[];busy:boolean;onReview:(body:unknown)=>Promise<boolean>}){
  const [decision,setDecision]=useState<'approve'|'reject'>('approve');
  const [selectedBooks,setSelectedBooks]=useState<string[]>([]);
  return <article className="card stack"><div className="card-head"><h3>{a.name}</h3><span className="badge">{a.state==='pending'?'待審核':a.state==='approved'?'已核准':a.state==='declined'?'未核准':a.state}</span></div><p>申請人：{a.applicant_name}{a.applicant_email?` · ${a.applicant_email}`:''}</p><p>專業領域：{a.profession}</p><p>{a.reason}</p>{a.state==='pending'?<form className="stack" onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);await onReview({decision,reason:data.get('review_reason'),...(decision==='approve'?{guild:{name:data.get('name'),purpose:data.get('purpose'),first_step:data.get('first_step'),module_key:data.get('module_key'),skill_book_ids:selectedBooks}}:{})});}}><label className="field">審核決定<select value={decision} onChange={event=>setDecision(event.target.value as 'approve'|'reject')}><option value="approve">核准並成立公會</option><option value="reject">這次不核准</option></select></label>{decision==='approve'&&<><label className="field">公會名稱<input name="name" required minLength={2} maxLength={100} defaultValue={a.name}/></label><label className="field">公會宗旨<textarea name="purpose" required minLength={5} maxLength={1000}/></label><label className="field">新成員的第一步<textarea name="first_step" required minLength={5} maxLength={1000}/></label><label className="field">主要參與方向<select name="module_key">{moduleOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><fieldset className="fieldset"><legend>公會技能庫的入門技能書（至少 1 本）</legend>{books.map(book=><label className="checkbox-row" key={book.id}><input type="checkbox" checked={selectedBooks.includes(book.id)} disabled={!selectedBooks.includes(book.id)&&selectedBooks.length>=20} onChange={()=>setSelectedBooks(selectedBooks.includes(book.id)?selectedBooks.filter(id=>id!==book.id):[...selectedBooks,book.id])}/>{book.title}</label>)}</fieldset>{!selectedBooks.length&&<p className="field-hint">請先選擇至少一本入門技能書，讓新成員加入後就能開始。</p>}</>}<label className="field">審核說明<textarea name="review_reason" required minLength={3} maxLength={1000}/></label><button className="btn btn-primary" disabled={busy||(decision==='approve'&&!selectedBooks.length)}>保存審核決定</button></form>:<p className="muted">審核說明：{a.review_reason??a.reviewreason??'已處理'}</p>}</article>;
}
