import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';

type Admin = {admin_id:string;email:string;display_name:string;role:string;community_id:string};
type Bootstrap = {admin:Admin;csrf_token:string;available_skill_books:{id:string;title:string}[];pending_guild_appointments?:{guild_key:string;name:string;state:'pending'|'bound';bound_user_id:string|null}[];summary:{members:number;active_members:number;pending_guild_applications:number;guilds:number;admins:number}};
type Member = {user_id:string;email:string;display_name:string;active:boolean;onboarding_required:boolean;onboarding_completed_at:string|null;aggregate_version:number;guilds:{guild_key:string;name:string}[]};
type GuildApplication = {application_id:string;name:string;profession:string;reason:string;state:string;applicant_name:string;applicant_email?:string;aggregate_version:number;review_reason?:string|null;reviewreason?:string|null;approved_guild_key?:string|null};
type Guild = {guild_key:string;name:string;purpose:string;first_step:string;module_key:string;guild_master:{user_id?:string;display_name:string}|null;officer_version:number|null};
type AdminNomination = {admin_id?:string;email?:string|null;display_name?:string;role?:string;state?:string;status?:string;enabled?:boolean;active?:boolean;identity_binding?:'no_member_account'|'unverified_email_match'|'verified_email_match';member_account_present?:boolean;member_account_active?:boolean;member_email_verified?:boolean};
type Audit = {audit_id?:string;admin_name?:string;actor_email?:string;actor_name?:string;actor_display_name?:string;action:string;reason:string;target_ref?:string;target_id?:string;target_type?:string;created_at?:string;at?:string};
type AdminTab = 'members'|'guild-applications'|'guilds'|'admins'|'audit';
const tabs:[AdminTab,string][]=[['members','會員管理'],['guild-applications','公會申請'],['guilds','公會管理'],['admins','管理員名單'],['audit','操作紀錄']];
const moduleOptions=[['guilds','公會交流'],['engagement','社群參與'],['positioning','定位與陪跑'],['supplier','供貨'],['retail','商店與銷售'],['opensource','開源作品'],['marketing','行銷'],['workbench','互助協作']];
class AdminRequestError extends Error { constructor(message:string,readonly status=0){super(message);} }
class AdminClient {
  csrf:string|null=null;
  async request<T>(path:string,body?:unknown,options:{key?:string;version?:number|null}={}):Promise<T>{
    const headers:Record<string,string>={Accept:'application/json'};
    if(body!==undefined){if(!this.csrf)throw new AdminRequestError('管理員驗證已過期，請重新確認管理身分。',403);headers['Content-Type']='application/json';headers['X-Admin-CSRF']=this.csrf;headers['Idempotency-Key']=options.key??crypto.randomUUID();if(options.version)headers['If-Match']=`"${options.version}"`;}
    let response:Response;
    try{response=await fetch(`/admin/api${path}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers,body:body===undefined?undefined:JSON.stringify(body)});}catch{throw new AdminRequestError('目前無法連線。操作不會自動重送，請重新載入確認結果。');}
    let value:any;try{value=await response.json();}catch{throw new AdminRequestError('管理入口沒有回傳完整資料，請重新確認管理身分。',response.status);}
    if(!response.ok){if(response.status===401||response.status===403)this.csrf=null;throw new AdminRequestError(typeof value?.detail==='string'?value.detail:'無法完成管理操作，請重新載入確認。',response.status);}
    return value as T;
  }
}
export function AdminPanel(){
  const client=useRef(new AdminClient()).current;
  const [bootstrap,setBootstrap]=useState<Bootstrap|null>(null),[bootError,setBootError]=useState(''),[booting,setBooting]=useState(true),[tab,setTab]=useState<AdminTab>('members');
  const [members,setMembers]=useState<Member[]>([]),[query,setQuery]=useState(''),[nextOffset,setNextOffset]=useState<number|null>(null),[applications,setApplications]=useState<GuildApplication[]>([]),[applicationOffset,setApplicationOffset]=useState<number|null>(null),[guilds,setGuilds]=useState<Guild[]>([]),[admins,setAdmins]=useState<AdminNomination[]>([]),[audit,setAudit]=useState<Audit[]>([]);
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const lock=useRef(false),keys=useRef(new Map<string,string>()),loadSequence=useRef(0);
  const start=useCallback(async()=>{setBooting(true);setBootError('');try{const value=await client.request<Bootstrap>('/bootstrap');client.csrf=value.csrf_token;setBootstrap(value);}catch(cause){setBootstrap(null);setBootError(cause instanceof Error?cause.message:'無法確認管理員身分。');}finally{setBooting(false);}},[client]);
  const load=useCallback(async(offset=0)=>{const sequence=++loadSequence.current;setLoading(true);setError('');try{
    if(tab==='members'){const value=await client.request<{items:Member[];next_offset:number|null}>(`/members?limit=25&offset=${offset}&q=${encodeURIComponent(query.trim())}`);if(sequence===loadSequence.current){setMembers(current=>offset?[...current,...value.items]:value.items);setNextOffset(value.next_offset);}}
    if(tab==='guild-applications'){const value=await client.request<{items:GuildApplication[];next_offset:number|null}>(`/guild-applications?state=all&limit=25&offset=${offset}`);if(sequence===loadSequence.current){setApplications(current=>offset?[...current,...value.items]:value.items);setApplicationOffset(value.next_offset);}}
    if(tab==='guilds'){const [value,people]=await Promise.all([client.request<{items:Guild[]}>('/guilds'),client.request<{items:Member[]}>('/members?limit=25&offset=0')]);if(sequence===loadSequence.current){setGuilds(value.items);setMembers(people.items);}}
    if(tab==='admins'){const value=await client.request<{items:AdminNomination[]}>('/admins');if(sequence===loadSequence.current)setAdmins(value.items);}
    if(tab==='audit'){const value=await client.request<{items:Audit[]}>('/audit');if(sequence===loadSequence.current)setAudit(value.items);}
  }catch(cause){if(sequence===loadSequence.current)setError(cause instanceof Error?cause.message:'無法載入管理資料。');}finally{if(sequence===loadSequence.current)setLoading(false);}},[client,query,tab]);
  useEffect(()=>{void start();},[start]);
  useEffect(()=>{if(bootstrap)void load();return()=>{loadSequence.current+=1;};},[bootstrap?.admin.admin_id,tab]);
  async function mutate(path:string,body:unknown,version?:number|null){if(lock.current)return false;lock.current=true;setBusy(true);setError('');setNotice('');const request=JSON.stringify([path,body,version]),key=keys.current.get(request)??crypto.randomUUID();keys.current.set(request,key);try{await client.request(path,body,{key,version});keys.current.delete(request);await load();await start();setNotice('管理操作已保存，並留下操作紀錄。');return true;}catch(cause){if(cause instanceof AdminRequestError&&cause.status>0&&cause.status<500)keys.current.delete(request);setError(cause instanceof Error?cause.message:'操作未完成，請重新確認結果。');return false;}finally{lock.current=false;setBusy(false);}}
  async function memberSearch(event:FormEvent){event.preventDefault();await load();}
  async function findGuildMembers(search:string){try{const result=await client.request<{items:Member[]}>(`/members?limit=25&offset=0&q=${encodeURIComponent(search.trim())}`);setMembers(result.items);}catch(cause){setError(cause instanceof Error?cause.message:'無法查詢會員。');}}
  const refreshSummary=()=>void start();
  return <main className="admin-layout"><header className="admin-header"><div className="brand"><span className="mark" aria-hidden="true"/><div><p className="eyebrow">FREEDOM WORKSHOP</p><h1>平台管理</h1></div></div><a className="btn btn-ghost" href="/">返回自由工坊</a></header>
    {booting&&<p role="status">正在確認管理員身分…</p>}
    {!booting&&!bootstrap&&<section className="card stack"><h2>需要管理員驗證</h2><p>這是獨立的管理入口，僅限已核准的管理員。請使用管理員的 Access 身分登入。</p>{bootError&&<p className="banner banner-error" role="alert">{bootError}</p>}<button className="btn btn-primary" onClick={()=>void start()}>重新確認管理身分</button></section>}
    {bootstrap&&<><section className="admin-identity"><div><strong>{bootstrap.admin.display_name}</strong><p className="muted">{bootstrap.admin.email} · {bootstrap.admin.role==='super_admin'?'平台管理員':'管理員'}</p></div><button className="btn btn-ghost" onClick={refreshSummary} disabled={busy||booting}>重新確認管理身分</button></section><section className="admin-summary" aria-label="平台管理概況">{[['會員',bootstrap.summary.members],['有效會員',bootstrap.summary.active_members],['待處理公會申請',bootstrap.summary.pending_guild_applications],['公會',bootstrap.summary.guilds],['管理員',bootstrap.summary.admins]].map(([name,value])=><div className="card" key={String(name)}><span>{name}</span><strong>{value}</strong></div>)}</section>{(bootstrap.pending_guild_appointments?.length??0)>0&&<section className="card stack"><h2>我的公會長任命</h2><p>先用與管理身分相同的 Email 建立會員帳號、登入並完成定位，再確認連結。平台管理本身不需要先完成定位。</p><ul>{bootstrap.pending_guild_appointments?.map(appointment=><li key={appointment.guild_key}>{appointment.name} · {appointment.state==='bound'?'已連結會員並確認任命':'等待本人確認連結'}</li>)}</ul>{bootstrap.pending_guild_appointments?.some(appointment=>appointment.state==='pending')&&<div className="actions"><a className="btn btn-ghost" href="/" target="_blank" rel="noopener noreferrer">開啟會員登入與定位 ↗</a><button className="btn btn-primary" disabled={busy} onClick={()=>void mutate('/link-member',{})}>連結我的會員帳號並確認會長任命</button></div>}</section>}<nav className="admin-tabs" aria-label="平台管理選單">{tabs.map(([key,label])=><button className={tab===key?'btn btn-primary':'btn btn-ghost'} aria-current={tab===key?'page':undefined} key={key} onClick={()=>{setTab(key);setNotice('');}}>{label}</button>)}</nav>
      {error&&<div className="banner banner-error" role="alert">{error}<div className="actions"><button className="btn btn-ghost" onClick={()=>void load()} disabled={busy}>重新載入資料</button>{!client.csrf&&<button className="btn btn-ghost" onClick={()=>void start()}>重新確認管理身分</button>}</div></div>}{notice&&<p className="banner status-note" role="status">{notice}</p>}{loading&&<p role="status">正在載入管理資料…</p>}
      {tab==='members'&&<section className="stack"><h2>會員管理</h2><form className="admin-search" onSubmit={memberSearch}><label className="field">搜尋會員<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="暱稱或 Email" maxLength={100}/></label><button className="btn btn-ghost" disabled={loading}>搜尋</button></form><div className="card-grid">{members.map(member=><article className="card stack" key={member.user_id}><div className="card-head"><h3>{member.display_name}</h3><span className="badge">{member.active?'啟用中':'已停用'}</span></div><p>{member.email}</p><p className="muted">{member.onboarding_completed_at?'已完成定位':member.onboarding_required?'定位進行中':'既有會員'}</p><AdminReasonForm label={member.active?'停用這位會員':'重新啟用會員'} busy={busy} onSubmit={reason=>mutate(`/members/${member.user_id}/status`,{active:!member.active,reason},member.aggregate_version)}/></article>)}</div>{!loading&&!members.length&&!error&&<p className="muted">沒有符合條件的會員。</p>}{nextOffset!==null&&<button className="btn btn-ghost" onClick={()=>void load(nextOffset)} disabled={loading}>查看更多會員</button>}</section>}
      {tab==='guild-applications'&&<section className="stack"><h2>公會申請</h2>{applications.map(application=><GuildReview key={application.application_id} application={application} books={bootstrap.available_skill_books} busy={busy} onReview={(body)=>mutate(`/guild-applications/${application.application_id}/review`,body,application.aggregate_version)}/>)}{applicationOffset!==null&&<button className="btn btn-ghost" disabled={loading} onClick={()=>void load(applicationOffset)}>查看更多公會申請</button>}{!loading&&!applications.length&&!error&&<p className="muted">目前沒有公會申請。</p>}</section>}
      {tab==='guilds'&&<section className="stack"><h2>公會管理</h2><p className="muted">公會長須先是該公會的有效會員。先搜尋會員，再於對應公會確認人選。</p><form className="admin-search" onSubmit={event=>{event.preventDefault();void findGuildMembers(String(new FormData(event.currentTarget).get('member_search')??''));}}><label className="field">搜尋公會長人選<input name="member_search" placeholder="暱稱或 Email" maxLength={100}/></label><button className="btn btn-ghost">查詢人選</button></form><div className="card-grid">{guilds.map(guild=><GuildMasterForm key={`${guild.guild_key}-${guild.officer_version}`} guild={guild} members={members.filter(member=>member.active&&member.guilds?.some(membership=>membership.guild_key===guild.guild_key))} busy={busy} onSave={(userId,reason)=>mutate(`/guilds/${encodeURIComponent(guild.guild_key)}/master`,{user_id:userId,reason},guild.officer_version)}/>)}</div></section>}
      {tab==='admins'&&<section className="stack"><h2>管理員名單</h2><p className="muted">管理權限來自已驗證的管理身分，與會員註冊分開。相同的 Email 文字不等於已綁定同一個人。</p><div className="card-grid">{admins.map((admin,index)=><article className="card stack" key={admin.admin_id??index}><h3>{admin.display_name??'待確認人選'}</h3><p>{admin.email??'登入身分待確認'}</p><p className="muted">{admin.active?'已啟用':'已停用'} · 平台管理員</p><p className="field-hint">{admin.identity_binding==='verified_email_match'?'有已驗證的同信箱會員帳號':admin.identity_binding==='unverified_email_match'?'同信箱會員尚未驗證，不視為身分綁定':'尚未建立同信箱會員帳號'}。管理權限不由會員帳號授予。</p></article>)}</div></section>}
      {tab==='audit'&&<section className="stack"><h2>操作紀錄</h2><p className="muted">最近的管理操作與填寫理由，方便回查。</p>{audit.map((entry,index)=><article className="card stack" key={entry.audit_id??index}><div className="card-head"><strong>{{member_status:'調整會員狀態',guild_application_review:'審核公會申請',appoint_guild_master:'任命公會長'}[entry.action]??entry.action}</strong><time>{new Date(entry.created_at??entry.at??'').toLocaleString('zh-TW')}</time></div><p>操作人：{entry.admin_name??entry.actor_display_name??entry.actor_name??entry.actor_email??'管理員'}</p><p>{entry.reason}</p>{(entry.target_ref??entry.target_id)&&<p className="field-hint">對象：{entry.target_type??''} {entry.target_ref??entry.target_id}</p>}</article>)}{!loading&&!audit.length&&!error&&<p className="muted">目前沒有管理操作紀錄。</p>}</section>}
    </>}
  </main>;
}
function AdminReasonForm({label,busy,onSubmit}:{label:string;busy:boolean;onSubmit:(reason:string)=>Promise<boolean>}){
  const [open,setOpen]=useState(false),[reason,setReason]=useState('');
  return open?<form className="stack" onSubmit={async event=>{event.preventDefault();if(await onSubmit(reason)){setOpen(false);setReason('');}}}><label className="field">操作理由<textarea required minLength={3} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="actions"><button className="btn btn-primary" disabled={busy}>確認{label}</button><button type="button" className="btn btn-ghost" disabled={busy} onClick={()=>setOpen(false)}>取消</button></div></form>:<button className="btn btn-ghost" disabled={busy} onClick={()=>setOpen(true)}>{label}</button>;
}
function GuildReview({application:a,books,busy,onReview}:{application:GuildApplication;books:{id:string;title:string}[];busy:boolean;onReview:(body:unknown)=>Promise<boolean>}){
  const [decision,setDecision]=useState<'approve'|'reject'>('approve');
  const [selectedBooks,setSelectedBooks]=useState<string[]>([]);
  return <article className="card stack"><div className="card-head"><h3>{a.name}</h3><span className="badge">{a.state==='pending'?'待審核':a.state==='approved'?'已核准':a.state==='declined'?'未核准':a.state}</span></div><p>申請人：{a.applicant_name}{a.applicant_email?` · ${a.applicant_email}`:''}</p><p>專業領域：{a.profession}</p><p>{a.reason}</p>{a.state==='pending'?<form className="stack" onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);await onReview({decision,reason:data.get('review_reason'),...(decision==='approve'?{guild:{name:data.get('name'),purpose:data.get('purpose'),first_step:data.get('first_step'),module_key:data.get('module_key'),skill_book_ids:selectedBooks}}:{})});}}><label className="field">審核決定<select value={decision} onChange={event=>setDecision(event.target.value as 'approve'|'reject')}><option value="approve">核准並成立公會</option><option value="reject">這次不核准</option></select></label>{decision==='approve'&&<><label className="field">公會名稱<input name="name" required minLength={2} maxLength={100} defaultValue={a.name}/></label><label className="field">公會宗旨<textarea name="purpose" required minLength={5} maxLength={1000}/></label><label className="field">新成員的第一步<textarea name="first_step" required minLength={5} maxLength={1000}/></label><label className="field">主要參與方向<select name="module_key">{moduleOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><fieldset className="fieldset"><legend>公會技能庫的入門技能書（至少 1 本）</legend>{books.map(book=><label className="checkbox-row" key={book.id}><input type="checkbox" checked={selectedBooks.includes(book.id)} disabled={!selectedBooks.includes(book.id)&&selectedBooks.length>=20} onChange={()=>setSelectedBooks(selectedBooks.includes(book.id)?selectedBooks.filter(id=>id!==book.id):[...selectedBooks,book.id])}/>{book.title}</label>)}</fieldset>{!selectedBooks.length&&<p className="field-hint">請先選擇至少一本入門技能書，讓新成員加入後就能開始。</p>}</>}<label className="field">審核說明<textarea name="review_reason" required minLength={3} maxLength={1000}/></label><button className="btn btn-primary" disabled={busy||(decision==='approve'&&!selectedBooks.length)}>保存審核決定</button></form>:<p className="muted">審核說明：{a.review_reason??a.reviewreason??'已處理'}</p>}</article>;
}
function GuildMasterForm({guild,members,busy,onSave}:{guild:Guild;members:Member[];busy:boolean;onSave:(userId:string,reason:string)=>Promise<boolean>}){
  const [expanded,setExpanded]=useState(false);
  return <article className="card stack"><h3>{guild.name}</h3><p>{guild.purpose}</p><p>公會長：{guild.guild_master?.display_name??'待任命'}</p>{expanded?<form className="stack" onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(await onSave(String(data.get('user_id')),String(data.get('reason'))))setExpanded(false);}}><label className="field">公會長人選<select aria-label="公會長人選" name="user_id" required defaultValue=""><option value="" disabled>從搜尋結果選擇會員</option>{members.map(member=><option value={member.user_id} key={member.user_id}>{member.display_name} · {member.email}</option>)}</select></label><label className="field">任命理由<textarea name="reason" required minLength={3} maxLength={1000}/></label><div className="actions"><button className="btn btn-primary" disabled={busy||!members.length}>確認任命</button><button className="btn btn-ghost" type="button" disabled={busy} onClick={()=>setExpanded(false)}>取消</button></div></form>:<button className="btn btn-ghost" onClick={()=>setExpanded(true)}>設定公會長</button>}</article>;
}
