import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import type {ModulePanelProps} from './shared';
import {useModuleMutation} from './shared';
import {formatMinor} from '../format';
import {SupplierPanel as LegacySupplierPanel,RetailPanel as LegacyRetailPanel} from './LegacyCommercePanels';
import './AgentShops.css';

type Item={item_id:string;mode:'test'|'live';title:string;description:string;photo_url:string|null;price_minor:string;shipping_minor:string;stock:number;reserved:number;shop_name:string;currency:string;shipping_terms:string;return_terms:string};
type Shop={shop_id:string;mode:'test'|'live';accepting_orders:boolean;kind:'internal'|'public';name:string;description:string;website_url:string;currency:string;product_count:number;selection_count:number;key_expires_at:string|null;key_revoked_at:string|null};
type Preview={manifest:{kind:'internal'|'public';mode:'test'|'live';name:string;website_url:string;currency:string;products?:{sku:string;title:string;price_minor:number;stock:number}[];selections?:{item_id:string;retail_price_minor:number}[]};count:number;sha256:string};
type Transfer={transfer_id:string;internal_shop_id:string;internal_shop_name:string;total_minor:string;payment_state:string;payment_url:string|null;shipment:{method:string;carrier:string;tracking_number:string;shipped_at:string;source:string}|null;delivery_ref:string;lines:{quantity:number;snapshot:{title:string}}[]};
type Order={order_id:string;buyer_payment:string;currency:string;total_minor?:string;expires_at:string;transfers:Transfer[]};
const paymentLabel:Record<string,string>={pending:'待付款',reported_paid:'商店後台回報已付款',reported_refunded:'商店後台回報已退款',cancelled:'已取消／逾期'};
function download(filename:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function ImportResult({kind,client,onImported}:{kind:Shop['kind'];client:ModulePanelProps['client'];onImported:()=>Promise<void>}){
 const [url,setUrl]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[reading,setReading]=useState(false),[readError,setReadError]=useState(''),[notice,setNotice]=useState('');
 const {mutate,busy,error}=useModuleMutation(client),request=useRef(0);
 async function inspect(body:{content:string}|{url:string}){
  const revision=++request.current;setReading(true);setPreview(null);setReadError('');setNotice('');
  try{const result=await client.post<Preview>('/commerce/preview',body,{idempotencyKey:crypto.randomUUID()});if(revision!==request.current)return;if(result.manifest.kind!==kind)throw Error(`這是${result.manifest.kind==='internal'?'內部':'公開'}商店成果，請到另一個開店入口匯入。`);setPreview(result);}
  catch(e){if(revision===request.current)setReadError(e instanceof Error?e.message:'無法讀取成果。');}finally{if(revision===request.current)setReading(false);}
 }
 return <section className="card stack" aria-labelledby={`${kind}-import`}><header><p className="eyebrow">帶回成果</p><h3 id={`${kind}-import`}>AI 做好了，把成果交回來</h3><p className="muted">上傳 AI 給你的商品／商店成果檔，先預覽，再確認。不用手填商品表格。</p></header>
 <label className="field">上傳成果檔<input type="file" accept=".json,.md,application/json,text/markdown" disabled={busy||reading} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>24000){++request.current;setPreview(null);setReadError('成果檔上限 24 KB，請讓 AI 精簡文字並以網址提供圖片。');return;}await inspect({content:await file.text()});}}/></label>
 <details><summary>我有成果檔網址</summary><form className="stack" onSubmit={e=>{e.preventDefault();void inspect({url});}}><label className="field">成果檔網址<input type="url" required value={url} maxLength={2000} placeholder="https://raw.githubusercontent.com/…/freedom-shop.json" onChange={e=>{setUrl(e.target.value);++request.current;setPreview(null);setReading(false);}}/></label><p className="field-hint">支援 GitHub 原始 JSON／MD 檔；其他平台可下載成果後直接上傳，不需要 GitHub 帳號。</p><button className="btn btn-ghost" disabled={busy||reading}>讀取成果</button></form></details>
 {(readError||error)&&<p role="alert" className="banner banner-error">{readError||error}</p>}{reading&&<p role="status">正在整理成果預覽…</p>}{notice&&<p role="status">{notice}</p>}
 {preview&&<div className="shop-import-preview stack"><h4>確認這次成果：{preview.manifest.name}</h4><p>{kind==='internal'?'內部商店 · 商品供登入會員挑選，商店網址不公開':'公開商店 · 確認後可透過公開商店資料取得網站網址'}</p><p>{preview.manifest.mode==='live'?'正式交易模式：請確認雙方金流與網站均已驗收':'測試模式：僅供測試金流串接，不代表已正式開店'}</p><p>共 {preview.count} 件商品 · {preview.manifest.currency}</p><p className="shop-url">網站：{preview.manifest.website_url}</p><ul>{preview.manifest.products?.map(p=><li key={p.sku}>{p.title} · {formatMinor(p.price_minor,preview.manifest.currency)} · 可供 {p.stock} 件</li>)}{preview.manifest.selections?.map(p=><li key={p.item_id}>商品 {p.item_id.slice(0,8)} · 預計售價 {formatMinor(p.retail_price_minor,preview.manifest.currency)}</li>)}</ul><p className="field-hint">{kind==='internal'?'請確認商品、價格與條件正確，並已同意會員依這些條件選品。外部內部商店的登入權限仍須由你的 AI 設好。':'請確認網站、售價及客服內容；這會登錄公開商店網址，不會替你部署網站或開通金流。'}</p><div className="actions"><button className="btn btn-primary" disabled={busy||reading} onClick={async()=>{const result=await mutate('/commerce/import',{manifest:preview.manifest,confirmed:true});if(result){setPreview(null);setNotice('成果已歸檔，可在我的商店查看。');await onImported();}}}>確認並歸檔</button><button className="btn btn-ghost" disabled={busy} onClick={()=>setPreview(null)}>取消</button></div></div>}
 </section>;
}
function ShipmentForm({transfer,client,onSaved}:{transfer:Transfer;client:ModulePanelProps['client'];onSaved:()=>Promise<void>}){
 const {mutate,busy,error}=useModuleMutation(client),[method,setMethod]=useState('carrier');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const result=await mutate(`/commerce/transfers/${transfer.transfer_id}/shipment`,{method,carrier:method==='carrier'?String(d.get('carrier')):'',tracking_number:method==='carrier'?String(d.get('tracking_number')):'',shipped_at:new Date(String(d.get('shipped_at'))).toISOString()});if(result)await onSaved();}
 return <details><summary>{transfer.shipment?'更正出貨登記':'登記出貨'}</summary><form className="stack" onSubmit={e=>void submit(e)}><label className="field">交付方式<select value={method} onChange={e=>setMethod(e.target.value)}><option value="carrier">物流寄送</option><option value="self_delivery">自行送達</option><option value="pickup">面交／自取</option></select></label>{method==='carrier'&&<><label className="field">物流公司<input name="carrier" required maxLength={80}/></label><label className="field">物流單號<input name="tracking_number" required maxLength={120}/></label></>}<label className="field">出貨日期與時間<input name="shipped_at" type="datetime-local" required/></label><p className="field-hint">只記錄你填寫的資訊，工坊不追蹤物流、不核實簽收。</p>{error&&<p role="alert">{error}</p>}<button className="btn btn-ghost" disabled={busy}>保存出貨登記</button></form></details>;
}
function ShopOrders({shop,client}:{shop:Shop;client:ModulePanelProps['client']}){
 const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setOrders((await client.get<{items:Order[]}>(`/commerce/shops/${shop.shop_id}/orders`)).items);}catch(e){setError(e instanceof Error?e.message:'無法讀取訂單。');}finally{setLoading(false);}},[client,shop.shop_id]);
 useEffect(()=>{void load();},[load]);
 return <div className="stack"><div className="actions"><button className="btn btn-ghost" onClick={()=>void load()} disabled={loading}>重新整理訂單</button></div><p className="field-hint">付款狀態來自各店後台回報，工坊未向銀行核實；成本付款與買家付款分開記錄。</p>{error&&<p role="alert">{error}</p>}{loading?<p role="status">載入訂單中…</p>:!orders.length&&!error?<p>目前沒有訂單。完成金流與商店連線後，交易會出現在這裡。</p>:orders.map(o=><article className="shop-order stack" key={o.order_id}><h4>訂單 {o.order_id.slice(0,8)}</h4><p>買家付款：{paymentLabel[o.buyer_payment]}</p>{o.buyer_payment==='pending'&&<p className="field-hint">保留至 {new Date(o.expires_at).toLocaleString('zh-TW')}；逾期不可回報成功付款。</p>}{o.transfers.map(t=><div className="stack" key={t.transfer_id}><strong>{t.internal_shop_name}</strong><p>{t.lines.map(l=>`${l.snapshot.title} × ${l.quantity}`).join('、')}</p><p>商品成本含運費：{formatMinor(t.total_minor,o.currency)}</p><p>成本付款：{paymentLabel[t.payment_state]}</p>{shop.kind==='public'&&t.payment_state==='pending'&&o.buyer_payment==='reported_paid'&&(t.payment_url?<a className="btn btn-ghost" href={t.payment_url} target="_blank" rel="noreferrer">支付商品成本</a>:<p className="field-hint">等待內部商店準備這筆訂單的付款入口。</p>)}{t.shipment?<p>出貨方已登記：{new Date(t.shipment.shipped_at).toLocaleString('zh-TW')} · {t.shipment.method==='carrier'?`${t.shipment.carrier} ${t.shipment.tracking_number}`:t.shipment.method==='pickup'?'面交／自取':'自行送達'}（未追蹤物流）</p>:<p className="muted">尚未登記出貨</p>}{shop.kind==='internal'&&o.buyer_payment==='reported_paid'&&t.payment_state==='reported_paid'&&<ShipmentForm transfer={t} client={client} onSaved={load}/>}</div>)}</article>)}</div>;
}
function ShopCard({shop,client,onChanged}:{shop:Shop;client:ModulePanelProps['client'];onChanged:()=>Promise<void>}){
 const [orders,setOrders]=useState(false),[token,setToken]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function keyAction(action:'key'|'revoke-key'){
  setBusy(true);setError('');setToken('');setNotice('');
  try{const r=await client.post<{token?:string}>(`/commerce/shops/${shop.shop_id}/${action}`,{},{idempotencyKey:crypto.randomUUID(),suppressConsole:true});setToken(r.token??'');setNotice(action==='key'?'新金鑰只顯示這一次，舊金鑰已失效。':'連線已撤銷。');await onChanged();}catch(e){setError(e instanceof Error?e.message:'設定失敗。');}finally{setBusy(false);}
 }
 return <article className="card stack"><div className="card-head"><h4>{shop.name}</h4><span className="pill">{shop.kind==='internal'?'內部商店':'公開商店'}</span></div><p>{shop.description}</p><p>{shop.mode==='test'?'測試模式':'正式模式'} · {shop.accepting_orders?'可建立新訂單':'已暫停接單'}</p><p className="muted">已歸檔 {shop.kind==='internal'?shop.product_count:shop.selection_count} 件商品</p><div className="actions"><a className="btn btn-ghost" href={shop.website_url} target="_blank" rel="noreferrer">{shop.kind==='internal'?'開啟我的內部商店':'開啟公開商店'}</a><button className="btn btn-ghost" onClick={()=>setOrders(v=>!v)}>{orders?'收起訂單':'查看訂單與付款'}</button><button className="btn btn-ghost" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await client.post(`/commerce/shops/${shop.shop_id}/accepting-orders`,{accepting:!shop.accepting_orders},{idempotencyKey:crypto.randomUUID()});await onChanged();}catch(e){setError(e instanceof Error?e.message:'設定失敗。');}finally{setBusy(false);}}}>{shop.accepting_orders?'暫停接單':'恢復接單'}</button></div>{orders&&<ShopOrders shop={shop} client={client}/>}
 <details onToggle={e=>{if(!e.currentTarget.open){setToken('');setNotice('');}}}><summary>連線設定（交給 AI 協助）</summary><div className="stack"><p className="field-hint">金鑰只放在你商店的私密後台，別貼到聊天、MD 或公開網頁。重建會讓舊連線失效；撤銷前請處理未完成訂單。</p><p>商店代號：<code className="shop-url">{shop.shop_id}</code></p><p>{shop.key_revoked_at?'連線已撤銷':shop.key_expires_at?`金鑰有效至 ${new Date(shop.key_expires_at).toLocaleString('zh-TW')}`:'尚未建立連線'}</p><div className="actions"><button className="btn btn-ghost" disabled={busy} onClick={()=>void keyAction('key')}>產生／重建連線金鑰</button>{shop.key_expires_at&&!shop.key_revoked_at&&<button className="btn btn-ghost" disabled={busy} onClick={()=>void keyAction('revoke-key')}>撤銷連線</button>}</div>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{token&&<label className="field">一次性顯示的連線金鑰<input type="password" readOnly value={token} autoComplete="off" onFocus={e=>e.target.select()}/><span className="field-hint">選取後複製到主機的秘密設定；收起此區就不再顯示。</span></label>}</div></details></article>;
}
function AgentShopPanel({kind,...props}:ModulePanelProps&{kind:Shop['kind']}){
 const {client}=props,[shops,setShops]=useState<Shop[]>([]),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[downloading,setDownloading]=useState(false),[notice,setNotice]=useState(''),[legacy,setLegacy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [s,c]=await Promise.all([client.get<{items:Shop[]}>('/commerce/shops'),client.get<{items:Item[]}>('/commerce/catalog')]);setShops(s.items.filter(s=>s.kind===kind));setItems(c.items);setSelected(ids=>ids.filter(id=>c.items.some(i=>i.item_id===id)));}catch(e){setError(e instanceof Error?e.message:'無法取得商店資料。');}finally{setLoading(false);}},[client,kind]);
 useEffect(()=>{void load();},[load]);
 async function kit(){setDownloading(true);setError('');setNotice('');try{const r=await client.post<{filename:string;markdown:string}>('/commerce/agent-kit',{kind,item_ids:kind==='public'?selected:[]},{idempotencyKey:crypto.randomUUID()});download(r.filename,r.markdown);setNotice('MD 開店包已下載，交給你原本使用的 AI；做好後回來上傳成果。');}catch(e){setError(e instanceof Error?e.message:'下載失敗。');}finally{setDownloading(false);}}
 const visible=items.filter(i=>[i.title,i.description,i.shop_name].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 return <section className="agent-shops stack" aria-label={kind==='internal'?'內部商店工作區':'公開商店工作區'}><header className="shop-intro"><p className="eyebrow">{kind==='internal'?'把商品交給 AI 整理':'用你的眼光，開自己的店'}</p><h2>{kind==='internal'?'有商品，就能開始。':'挑好商品，讓 AI 幫你開店。'}</h2><p>{kind==='internal'?'下載開店包，讓 AI 整理商品、製作不公開的商店，並帶你申請自己的金流。':'挑選自己的或別人的商品，下載開店包，讓 AI 製作公開商店與你的金流後台。'}</p><p className="muted">同一個人可以同時有兩種商店。各店自己收款；工坊只轉單、記錄付款與人工出貨登記。</p></header>
 <ol className="shop-steps"><li><span>01</span><strong>{kind==='internal'?'下載 MD 開店包':'挑商品，下載 MD'}</strong><p>把任務交給你原本使用的 AI。</p></li><li><span>02</span><strong>AI 整理與製作</strong><p>商品、網站、金流申請與串接一起準備。</p></li><li><span>03</span><strong>帶回成果</strong><p>上傳檔案，預覽確認後歸檔。</p></li></ol>
 {error&&<div role="alert" className="banner banner-error">{error}<button className="btn btn-ghost" onClick={()=>void load()} disabled={loading}>重新載入</button></div>}{notice&&<p role="status" className="banner banner-info">{notice}</p>}
 {kind==='public'&&<section className="stack" aria-labelledby="shop-catalog-heading"><div className="card-head"><h3 id="shop-catalog-heading">挑選這次想賣的商品</h3><span role="status">已選 {selected.length} 件</span></div><label className="field">搜尋商品<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="商品名稱、介紹或店名" maxLength={150}/></label>{loading?<p role="status">載入商品中…</p>:!items.length?<div className="card"><p>商品庫還沒有新模式的商品。你也可以先建立自己的內部商店。</p><button className="btn btn-ghost" onClick={()=>props.onNavigate?.('supplier')}>我有東西要賣</button></div>:!visible.length?<p>沒有符合條件的商品。</p>:<div className="shop-catalog">{visible.map(i=><article className={`card shop-product ${selected.includes(i.item_id)?'is-selected':''}`} key={i.item_id}>{i.photo_url&&<img src={i.photo_url} alt="" loading="lazy" referrerPolicy="no-referrer"/>}<div className="stack"><p className="eyebrow">{i.shop_name} · {i.mode==='test'?'測試商品':'正式商品'}</p><h4>{i.title}</h4><p>{i.description}</p><p>商品成本 <strong>{formatMinor(i.price_minor,i.currency)}</strong> · 每件運費 {formatMinor(i.shipping_minor,i.currency)}</p><p className="muted">可供 {i.stock-i.reserved} 件</p><details><summary>出貨與退換貨約定</summary><p>{i.shipping_terms}</p><p>{i.return_terms}</p></details><label className="checkbox-row"><input type="checkbox" checked={selected.includes(i.item_id)} disabled={!selected.includes(i.item_id)&&selected.length>=50} onChange={e=>setSelected(ids=>e.target.checked?[...ids,i.item_id]:ids.filter(id=>id!==i.item_id))}/><span>選入「{i.title}」</span></label></div></article>)}</div>}</section>}
 <div className="shop-download card"><div><h3>{kind==='internal'?'讓 AI 幫你整理商品與開店':'把挑好的商品交給 AI'}</h3><p className="muted">MD 內含商品格式、金流申請、交易串接與驗收步驟。你不用填一大堆表格。</p></div><button className="btn btn-primary" disabled={downloading||(kind==='public'&&(!selected.length||loading))} onClick={()=>void kit()}>{downloading?'正在準備…':kind==='internal'?'下載內部商店 MD':'下載公開商店 MD'}</button></div>
 <ImportResult key={kind} kind={kind} client={client} onImported={load}/>
 <section className="stack" aria-labelledby={`${kind}-shops`}><h3 id={`${kind}-shops`}>我的{kind==='internal'?'內部':'公開'}商店</h3>{loading&&shops.length===0?<p role="status">載入商店中…</p>:!shops.length?<p className="muted">成果確認歸檔後，你的商店會出現在這裡。</p>:shops.map(s=><ShopCard key={s.shop_id} shop={s} client={client} onChanged={load}/>)}</section>
 <details onToggle={e=>setLegacy(e.currentTarget.open)}><summary>查看舊版商品與合作資料</summary><p className="field-hint">舊資料保留供查閱與處理，不會自動變成已接通金流的新商店。</p>{legacy&&(kind==='internal'?<LegacySupplierPanel {...props}/>:<LegacyRetailPanel {...props}/>)}</details>
 </section>;
}
export function SupplierPanel(props:ModulePanelProps){return <AgentShopPanel key="internal" kind="internal" {...props}/>;}
export function RetailPanel(props:ModulePanelProps){return <AgentShopPanel key="public" kind="public" {...props}/>;}
