import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useModuleMutation, type ModulePanelProps } from './shared';
import type { PortalClient } from '../api';
import type { SkillBook } from './Onboarding';
import { SkillBooks } from './Onboarding';
import { ClientConnections } from './ClientConnections';

type Visibility='private'|'public'|'friends'|'squad'|'guild';
type Contact={value:string;visibility:Visibility;verified?:boolean};
type Account={user_id:string;nickname:string;login_email:string;email_verified:boolean;contacts:Record<'email'|'discord'|'github'|'line',Contact>;aggregate_version:number};
type GuildRef={guild_key:string;name:string};
export type MemberCardData={user_id:string;nickname:string;positioning_title:string|null;primary_guild:GuildRef|null;secondary_guilds:GuildRef[];capabilities:string[];equipment:string[];contacts:Partial<Record<'email'|'discord'|'github'|'line',string>>;is_self:boolean;friendship:{state:string;requester_ref?:string;aggregate_version?:number}};
const visibilityOptions: [Visibility,string][]=[['private','不公開'],['public','平台公開'],['friends','平台好友'],['squad','小隊夥伴'],['guild','公會夥伴']];
const contactLabels={email:'聯絡 E-mail',discord:'Discord 帳號',github:'GitHub 帳號',line:'LINE ID'} as const;
const fail=(e:unknown)=>e instanceof Error?e.message:'暫時無法讀取，請稍後再試。';
export function AccountPanel({client,session}:ModulePanelProps){
  const [account,setAccount]=useState<Account|null>(null),[nickname,setNickname]=useState(''),[contacts,setContacts]=useState<Account['contacts']|null>(null),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[member,setMember]=useState<MemberCardData|null>(null),[books,setBooks]=useState<SkillBook[]>([]),[labels,setLabels]=useState<Record<string,string>>({});
  const {mutate,busy,error}=useModuleMutation(client);
  const fill=(value:Account)=>{setAccount(value);setNickname(value.nickname);setContacts(value.contacts);};
  async function load(){setLoadError('');try{const [a,m,b]=await Promise.all([client.get<Account>('/me/account'),client.get<MemberCardData>(`/members/${session.user.user_id}`),client.get<{items:SkillBook[]}>('/me/skill-books')]);fill(a);setMember(m);setBooks(b.items);}catch(e){setLoadError(fail(e));}}
  useEffect(()=>{void load();void loadLabels(client).then(setLabels).catch(()=>{});},[client,session.user.user_id]);
  async function submit(event:FormEvent){event.preventDefault();if(!contacts||!account)return;setNotice('');const clean=Object.fromEntries(Object.entries(contacts).map(([key,c])=>[key,{value:c.value,visibility:c.visibility}]));const saved=await mutate<Account>('/me/account',{nickname,contacts:clean},account.aggregate_version);if(saved){fill(saved);setNotice('個人資料與每一項聯絡方式的可見範圍已保存。');window.dispatchEvent(new Event('freedom-profile-updated'));await load();}}
  return <section className="module-panel"><header className="section-heading"><p className="eyebrow">YOUR MEMBER CARD</p><h2>我的會員名片</h2><p>讓夥伴認識你的方向與能力，聯絡方式由你決定分享給誰。</p></header>{member&&<MemberCard member={member} labels={labels}/>}<Status error={loadError||error} notice={notice}/>{loadError&&<button className="btn" onClick={()=>void load()}>重新載入我的資料</button>}{!account&&!loadError&&<p role="status">載入會員資料…</p>}{account&&contacts&&<form className="card stack" onSubmit={submit}><h3>暱稱與聯絡方式</h3><label className="field">喜歡的暱稱<input required minLength={1} maxLength={60} value={nickname} onChange={e=>setNickname(e.target.value)}/></label><p className="muted">登入信箱：{account.login_email}。下方的聯絡 E-mail 可另外設定。</p><div className="contact-grid">{(Object.keys(contactLabels) as (keyof typeof contactLabels)[]).map(key=><div className="contact-row" key={key}><label className="field">{contactLabels[key]}<input type={key==='email'?'email':'text'} value={contacts[key].value} maxLength={key==='github'?39:key==='email'?200:100} autoComplete="off" onChange={e=>setContacts({...contacts,[key]:{...contacts[key],value:e.target.value}})} placeholder={key==='github'?'你的 GitHub username':key==='discord'?'你的 Discord username':undefined}/></label><label className="field">{contactLabels[key]}可見範圍<select aria-label={`${contactLabels[key]}可見範圍`} value={contacts[key].visibility} onChange={e=>setContacts({...contacts,[key]:{...contacts[key],visibility:e.target.value as Visibility}})}>{visibilityOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>)}</div><p className="field-hint">「平台公開」會分享給已登入的工坊會員。社群帳號是自行填寫的聯絡資料，不代表已驗證身分。「平台好友」須雙方接受；小隊與公會範圍依目前有效成員關係顯示。</p><button className="btn btn-primary" disabled={busy}>{busy?'保存中…':'保存個人資料與公開範圍'}</button></form>}<section className="stack"><h3>我的技能書架</h3>{books.length?<SkillBooks books={books}/>:<p className="muted">加入公會後，對應技能書會放在這裡。</p>}</section><ClientConnections client={client}/></section>;
}
export function MemberCard({member,children,labels={}}:{member:MemberCardData;children?:React.ReactNode;labels?:Record<string,string>}){
  return <article className="card member-card"><div className="member-card-heading"><div className="member-avatar" aria-hidden="true">{member.nickname.slice(0,1)}</div><div><p className="eyebrow">FREEDOM WORKSHOP MEMBER</p><h3>{member.nickname} <span className="positioning-title">{member.positioning_title??'探索自己的方向'}</span></h3><p>{member.primary_guild?`主要公會 · ${member.primary_guild.name}`:'尚未設定主要公會'}</p></div></div><div className="member-card-body"><div><h4>基本能力</h4><div className="tag-list">{member.capabilities.length?member.capabilities.map(c=><span key={c} className="pill">{labels[c]??c}</span>):<span className="muted">尚未填寫</span>}</div></div><div><h4>次要公會</h4><p className="muted">{member.secondary_guilds.map(g=>g.name).join('、')||'先專注在主要公會'}</p></div>{member.equipment.length>0&&<div><h4>裝備</h4><div className="tag-list">{member.equipment.map(c=><span className="pill" key={c}>{labels[c]??c}</span>)}</div></div>}{Object.keys(member.contacts).length>0&&<dl className="detail-list">{Object.entries(member.contacts).map(([key,value])=><div key={key}><dt>{contactLabels[key as keyof typeof contactLabels]}</dt><dd>{value}</dd></div>)}</dl>}</div>{children}</article>;
}
export function MembersPanel({client,session}:ModulePanelProps){
  const [members,setMembers]=useState<MemberCardData[]>([]),[nextOffset,setNextOffset]=useState<number|null>(null),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[labels,setLabels]=useState<Record<string,string>>({});
  const [friends,setFriends]=useState<{user_id:string;nickname:string;state:string;requester_ref:string;aggregate_version:number}[]>([]);
  const {mutate,busy,error}=useModuleMutation(client);
  async function load(offset=0){setLoadError('');setLoading(true);try{const [m,f]=await Promise.all([client.get<{items:MemberCardData[];next_offset:number|null}>(`/members?limit=20&offset=${offset}`),client.get<{items:typeof friends}>('/friends')]);setMembers(current=>offset?[...current,...m.items]:m.items);setNextOffset(m.next_offset);setFriends(f.items);}catch(e){setLoadError(fail(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();void loadLabels(client).then(setLabels).catch(()=>{});},[client]);
  async function act(userId:string,action:string,version?:number){const result=await mutate(`/friends/${userId}/${action}`,{},version);if(result){setNotice(action==='accept'?'已成為平台好友。':action==='remove'?'好友關係已移除。':'好友邀請已送出，等待對方接受。');await load();}}
  return <section className="module-panel"><header className="section-heading"><p className="eyebrow">FIND YOUR PEOPLE</p><h2>工坊夥伴</h2><p>找到同路人。每個人的聯絡方式，都依照本人設定的可見範圍顯示。</p></header><Status error={loadError||error} notice={notice}/>{friends.some(f=>f.state==='pending'&&f.requester_ref!==session.user.user_id)&&<section className="card stack"><h3>收到的好友邀請</h3>{friends.filter(f=>f.state==='pending'&&f.requester_ref!==session.user.user_id).map(f=><div className="member-request" key={f.user_id}><strong>{f.nickname}</strong><button className="btn btn-primary" disabled={busy} onClick={()=>void act(f.user_id,'accept',f.aggregate_version)}>接受邀請</button><button className="btn btn-ghost" disabled={busy} onClick={()=>void act(f.user_id,'remove',f.aggregate_version)}>婉拒</button></div>)}</section>}<div className="card-grid">{members.map(member=><MemberCard key={member.user_id} member={member} labels={labels}>{!member.is_self&&<div className="actions">{member.friendship.state==='accepted'?<><span className="badge">平台好友</span><button className="btn btn-ghost" disabled={busy} onClick={()=>void act(member.user_id,'remove',member.friendship.aggregate_version)}>移除好友</button></>:member.friendship.state==='pending'?<span className="muted">{member.friendship.requester_ref===session.user.user_id?'好友邀請已送出':'對方已邀請你，請從上方接受'}</span>:<button className="btn btn-ghost" disabled={busy} onClick={()=>void act(member.user_id,'request',member.friendship.aggregate_version)}>邀請成為好友</button>}</div>}</MemberCard>)}</div>{loading&&<p role="status">正在尋找工坊夥伴…</p>}{!loading&&!members.length&&!loadError&&<p className="muted">還沒有完成定位的會員。</p>}{nextOffset!==null&&<button className="btn btn-ghost" disabled={loading} onClick={()=>void load(nextOffset)}>查看更多夥伴</button>}{loadError&&<button className="btn" onClick={()=>void load()}>重新載入夥伴</button>}</section>;
}
export async function loadLabels(client:PortalClient){const definition=await client.get<{capability_categories:{options:{id:string;label:string}[]}[];equipment_categories:{options:{id:string;label:string}[]}[]}>('/assessment-definition');return Object.fromEntries([...definition.capability_categories,...definition.equipment_categories].flatMap(c=>c.options).map(o=>[o.id,o.label]));}
export function Status({error,notice}:{error?:string|null;notice?:string|null}){return <>{error&&<p role="alert" className="banner banner-error">{error}</p>}{notice&&<p role="status" className="banner status-note">{notice}</p>}</>;}
