import { useEffect, useState, type FormEvent } from 'react';
import type { PortalClient } from '../api';
import { useModuleMutation } from './shared';
import { BrandPoster, CommunityLinks } from './Community';

export type SkillBook = { book_id:string;title:string;repository_url:string;fork_url:string|null;description:string;guild_keys:string[];granted_at?:string };
export type GuildSummary = { guild_key:string;name:string;purpose:string;first_step:string;track_count:number;guild_master:{display_name:string}|null;is_primary:boolean;skill_books:SkillBook[];membership:{state:string;aggregate_version:number}|null };
export type OnboardingView = {required:boolean;completed:boolean;state:'new'|'draft'|'evaluated'|'completed';draft:null|{aggregate_version:number;assessment_version:string;assessment_sha256:string;answers:Record<string,string>;occupation:string;founding_interest:boolean;capabilities:string[];equipment:string[]};result:null|{recommendations:{guild_key:string;name:string;reason:string;title:string}[]};primary_guild_key:string|null;skill_books:SkillBook[]};
type Category = {id:string;label:string;options:{id:string;label:string}[]};
type Definition = {assessment_version:string;assessment_sha256:string;questions:{id:string;kind:'preference'|'ability';prompt:string;options:{id:string;label:string}[]}[];capability_categories:Category[];equipment_categories:Category[]};
export function SkillBooks({ books }: { books: SkillBook[] }) {
  return <div className="card-grid">{books.map(book => <article key={book.book_id} className="card skill-book"><p className="eyebrow">技能書 · REPOSITORY</p><h4>{book.title}</h4><p>{book.description}</p><div className="actions"><a className="btn btn-ghost" href={book.repository_url} target="_blank" rel="noopener noreferrer">閱讀技能書 ↗</a>{book.fork_url && <a className="btn btn-primary" href={book.fork_url} target="_blank" rel="noopener noreferrer">Fork 到我的 GitHub ↗</a>}</div></article>)}</div>;
}
export function Onboarding({ client, initial, onCompleted, onLogout, optional = false }: {client:PortalClient;initial:OnboardingView;onCompleted:()=>void;onLogout?:()=>void;optional?:boolean}) {
  const [view,setView]=useState(initial), [definition,setDefinition]=useState<Definition|null>(null), [guilds,setGuilds]=useState<GuildSummary[]>([]), [loadError,setLoadError]=useState('');
  const [step,setStep]=useState(initial.state==='evaluated'?4:0),[answers,setAnswers]=useState<Record<string,string>>(initial.draft?.answers??{}),[occupation,setOccupation]=useState(initial.draft?.occupation??''),[founding,setFounding]=useState(initial.draft?.founding_interest??false),[capabilities,setCapabilities]=useState<string[]>(initial.draft?.capabilities??[]),[equipment,setEquipment]=useState<string[]>(initial.draft?.equipment??[]),[selectedGuilds,setSelectedGuilds]=useState<string[]>([]),[primary,setPrimary]=useState(''),[finished,setFinished]=useState(false);
  const {mutate,busy,error,setError}=useModuleMutation(client);
  async function load(){setLoadError('');try{const [d,g]=await Promise.all([client.get<Definition>('/assessment-definition'),client.get<{items:GuildSummary[]}>('/guilds/directory')]);setDefinition(d);setGuilds(g.items);}catch(e){setLoadError(e instanceof Error?e.message:'定位資料暫時無法讀取。');}}
  useEffect(()=>{void load();},[client]);
  const toggle=(values:string[],id:string,set:(v:string[])=>void)=>set(values.includes(id)?values.filter(v=>v!==id):[...values,id]);
  async function save(){if(!definition)return;const next=await mutate<OnboardingView>('/me/onboarding/answers',{assessment_version:definition.assessment_version,assessment_sha256:definition.assessment_sha256,answers,occupation,founding_interest:founding,capabilities,equipment},view.draft?.aggregate_version);if(next)setView(next);return next;}
  async function next(event:FormEvent){event.preventDefault();const saved=await save();if(!saved)return;if(step===3){const evaluated=await mutate<OnboardingView>('/me/onboarding/evaluate',{},saved.draft?.aggregate_version);if(evaluated){setView(evaluated);setStep(4);}}else setStep(step+1);window.scrollTo({top:0,behavior:'instant'});}
  async function finish(){if(!primary||!selectedGuilds.includes(primary)){setError('請加入至少一個公會，並選擇你的主要公會。');return;}const result=await mutate<OnboardingView>('/me/onboarding/complete',{guild_keys:selectedGuilds,primary_guild_key:primary,confirmed:true},view.draft?.aggregate_version);if(result){setView(result);setFinished(true);window.scrollTo({top:0,behavior:'instant'});}}
  const steps=['認識自己','整理裝備','做事偏好','能力情境','選擇公會'];
  const chosenQuestions=definition?.questions.filter(q=>q.kind===(step===2?'preference':'ability'))??[];
  return <main className="onboarding-layout"><header className="onboarding-header"><div className="brand"><span className="mark" aria-hidden="true"/><div><strong>自由工坊</strong><p className="eyebrow">FIND YOUR PLACE</p></div></div>{onLogout&&<button className="btn btn-ghost" onClick={onLogout}>登出</button>}{optional&&<button className="btn btn-ghost" onClick={onCompleted}>返回我的定位</button>}</header>
    {!finished&&<><section className="onboarding-intro"><p className="eyebrow">YOUR FIRST QUEST</p><h1>每一種專長，都有自己的位置。</h1><p>先認識你的做事方式與能力，找到公會，領取第一本技能書。</p><p className="field-hint">{optional?'這次可以重新選擇方向，既有公會與成果都會保留。':'完成定位與加入公會後，就可以開始使用會員工作區。'} 進度會在每一步保存。</p></section><ol className="onboarding-progress" aria-label="定位進度">{steps.map((label,index)=><li key={label} aria-current={step===index?'step':undefined} className={step===index?'is-current':step>index?'is-done':''}><span>{step>index?'✓':index+1}</span>{label}</li>)}</ol></>}
    {loadError&&<div className="banner banner-error" role="alert">{loadError}<button className="btn btn-ghost" onClick={()=>void load()}>重新載入</button></div>}{error&&<p className="banner banner-error" role="alert">{error}</p>}
    {!definition&&!loadError&&<p role="status">正在準備你的定位旅程…</p>}
    {definition&&!finished&&step<4&&<form className="card onboarding-card stack" onSubmit={next}>
      {step===0&&<><p className="eyebrow">01 / ABOUT YOU</p><h2>你從哪裡來，帶著哪些能力？</h2><label className="field">你的職業／目前身分<input value={occupation} onChange={e=>setOccupation(e.target.value)} maxLength={160} placeholder="例如：護理師、餐飲業者、設計師、學生"/></label><label className="checkbox-row"><input type="checkbox" checked={founding} onChange={e=>setFounding(e.target.checked)}/>我有興趣為自己的職業成立專業公會</label><p className="muted">基本能力是你目前會做的事；剛起步也有自己的路。可複選。</p><CategoryChoices categories={definition.capability_categories} values={capabilities} onToggle={id=>toggle(capabilities,id,setCapabilities)}/></>}
      {step===1&&<><p className="eyebrow">02 / YOUR EQUIPMENT</p><h2>你的裝備庫</h2><p className="muted">勾選目前可使用的工具或訂閱。工具不等於能力，這裡不需要付款資訊、帳號密碼或 API 金鑰；沒有裝備也可以繼續。</p><CategoryChoices categories={definition.equipment_categories} values={equipment} onToggle={id=>toggle(equipment,id,setEquipment)}/></>}
      {(step===2||step===3)&&<><p className="eyebrow">{step===2?'03 / YOUR WORK STYLE':'04 / EVERYDAY PRACTICE'}</p><h2>{step===2?'你喜歡怎麼做事？':'遇到這些情境，你會怎麼做？'}</h2><p className="muted">{step===2?'選最接近你的答案，不必選看起來最厲害的。':'這些小情境幫你找到適合練習的方向；不是資格認證，也不是心理診斷。'}</p>{chosenQuestions.map((question,index)=><fieldset key={question.id} className="quiz-question"><legend><span>{String(index+1).padStart(2,'0')}</span>{question.prompt}</legend><div className="quiz-options">{question.options.map(option=><label className={`quiz-option${answers[question.id]===option.id?' selected':''}`} key={option.id}><input type="radio" name={question.id} value={option.id} required checked={answers[question.id]===option.id} onChange={()=>setAnswers({...answers,[question.id]:option.id})}/>{option.label}</label>)}</div></fieldset>)}</>}
      <div className="onboarding-actions">{step>0&&<button className="btn btn-ghost" type="button" disabled={busy} onClick={()=>setStep(step-1)}>上一步</button>}<button className="btn btn-primary" disabled={busy||(step===0&&!capabilities.length)}>{busy?'正在保存…':step===3?'看看適合我的公會':'保存，繼續下一步 →'}</button></div>{step===0&&!capabilities.length&&<p className="field-hint">請勾選至少一項能力；也可以選擇剛起步的選項。</p>}
    </form>}
    {!finished&&step===4&&<section className="stack"><header className="section-heading"><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>找到同路人，開始一起做事。</h2><p>這些公會適合你先試試。可以加入多個，再選一個作為主力。</p></header><div className="recommendation-grid">{view.result?.recommendations.map((r,index)=><article className={`card recommendation-card ${selectedGuilds.includes(r.guild_key)?'selected':''}`} key={r.guild_key}><p className="eyebrow">{index===0?'推薦你先加入':'你也可以加入'}</p><h3>{r.name}</h3><span className="positioning-title">{r.title}</span><p>{r.reason}</p><p className="muted">公會長：{guilds.find(g=>g.guild_key===r.guild_key)?.guild_master?.display_name??'待任命'}</p><label className="checkbox-row"><input type="checkbox" checked={selectedGuilds.includes(r.guild_key)} onChange={()=>{toggle(selectedGuilds,r.guild_key,setSelectedGuilds);if(primary===r.guild_key)setPrimary('');}}/>加入{r.name}</label>{selectedGuilds.includes(r.guild_key)&&<label className="checkbox-row"><input type="radio" name="primary-guild" checked={primary===r.guild_key} onChange={()=>setPrimary(r.guild_key)}/>設為主要公會</label>}</article>)}</div><details className="card"><summary>查看其他公會，自行選擇</summary><div className="stack">{guilds.filter(g=>!view.result?.recommendations.some(r=>r.guild_key===g.guild_key)).map(g=><div key={g.guild_key}><label className="checkbox-row"><input type="checkbox" checked={selectedGuilds.includes(g.guild_key)} onChange={()=>{toggle(selectedGuilds,g.guild_key,setSelectedGuilds);if(primary===g.guild_key)setPrimary('');}}/>{g.name}</label>{selectedGuilds.includes(g.guild_key)&&<label className="checkbox-row"><input type="radio" name="primary-guild" checked={primary===g.guild_key} onChange={()=>setPrimary(g.guild_key)}/>以{g.name}作為主要公會</label>}</div>)}</div></details><div className="card stack"><p>將加入 {selectedGuilds.length} 個公會。主要公會：<strong>{guilds.find(g=>g.guild_key===primary)?.name??'尚未選擇'}</strong></p><p className="muted">加入後，對應的技能書會立即放進你的書架。你仍可在之後調整主要公會。</p><div className="actions"><button className="btn btn-ghost" disabled={busy} onClick={()=>setStep(0)}>調整我的答案</button><button className="btn btn-primary" disabled={busy||!primary} onClick={()=>void finish()}>{busy?'正在加入…':'確認加入公會，領取技能書'}</button></div></div></section>}
    {finished&&<section className="stack"><BrandPoster compact/><header className="section-heading"><p className="eyebrow">WELCOME TO FREEDOM WORKSHOP</p><h1>你的第一段旅程，現在開始。</h1><p>已加入公會；主要公會是 <strong>{guilds.find(g=>g.guild_key===view.primary_guild_key)?.name}</strong>。以下技能書已加入你的書架。</p></header><SkillBooks books={view.skill_books}/><p className="field-hint">技能書連結到原始專案；Fork 會開啟 GitHub，由你登入並選擇保存的位置。</p><button className="btn btn-primary" onClick={onCompleted}>進入自由工坊 →</button></section>}
    <CommunityLinks/>
  </main>;
}
function CategoryChoices({categories,values,onToggle}:{categories:Category[];values:string[];onToggle:(id:string)=>void}){
  const [search,setSearch]=useState('');
  const filtered=categories.map(category=>({...category,options:category.options.filter(option=>`${category.label} ${option.label}`.toLowerCase().includes(search.toLowerCase()))})).filter(category=>category.options.length);
  return <div className="category-grid"><label className="field">搜尋能力或工具<input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="例如：設計、Python、PMP、Claude…"/></label><p className="field-hint">已勾選 {values.length} 項。展開分類，找到適合你的項目。</p>{filtered.map((category,index)=><details className="category-group" open={search||index===0?true:undefined} key={category.id}><summary>{category.label}<span>{category.options.filter(option=>values.includes(option.id)).length} / {category.options.length}</span></summary><div className="selection-chips">{category.options.map(option=><label key={option.id} className={values.includes(option.id)?'selection-chip selected':'selection-chip'}><input type="checkbox" checked={values.includes(option.id)} onChange={()=>onToggle(option.id)}/>{option.label}</label>)}</div></details>)}{!filtered.length&&<p className="muted">找不到符合的項目，試試其他關鍵字。</p>}</div>;
}
