import {useEffect,useState,type FormEvent} from 'react';
import {useModuleMutation,type ModulePanelProps} from './shared';
import {Status} from './Membership';
type Squad={squad_id:string;name:string;kind:'project'|'mutual_help';purpose:string;owner_ref:string;owner_name:string;member_count:number;membership:null|{state:string;aggregate_version:number}};
type SquadDetail=Squad&{members:{user_id:string;nickname:string;state:string;aggregate_version:number}[]};
const kindLabels={project:'專案小隊',mutual_help:'共同目標互助小隊'};
export function SquadsPanel({client,session}:ModulePanelProps){
  const [squads,setSquads]=useState<Squad[]>([]),[detail,setDetail]=useState<SquadDetail|null>(null),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[nextOffset,setNextOffset]=useState<number|null>(null);
  const {mutate,busy,error}=useModuleMutation(client);
  async function load(offset=0){setLoadError('');try{const data=await client.get<{items:Squad[];next_offset:number|null}>(`/squads?limit=20&offset=${offset}`);setSquads(current=>offset?[...current,...data.items]:data.items);setNextOffset(data.next_offset);}catch(e){setLoadError(e instanceof Error?e.message:'無法載入小隊。');}finally{setLoading(false);}}
  async function open(id:string){setLoadError('');try{const data=await client.get<SquadDetail>(`/squads/${id}`);const own=data.members.find(member=>member.user_id===session.user.user_id);setDetail({...data,membership:own?{state:own.state,aggregate_version:own.aggregate_version}:null});}catch(e){setLoadError(e instanceof Error?e.message:'無法載入小隊。');}}
  useEffect(()=>{void load();},[client]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,d=new FormData(form);const result=await mutate<Squad>('/squads',{name:d.get('name'),kind:d.get('kind'),purpose:d.get('purpose')});if(result){form.reset();setNotice('小隊已成立。夥伴可以提出加入申請。');await load();await open(result.squad_id);}}
  async function change(squad:Squad,action:string,version?:number){const result=await mutate(`/squads/${squad.squad_id}/${action}`,{},version);if(result){setNotice(action==='request'?'加入申請已送出，等待隊主接受。':'小隊資料已更新。');await load();if(detail?.squad_id===squad.squad_id)await open(squad.squad_id);}}
  return <section className="module-panel"><header className="section-heading"><p className="eyebrow">BUILD SOMETHING TOGETHER</p><h2>小隊集合</h2><p>公會陪你發展專業；小隊讓幾個人圍繞一件事一起行動。</p></header><Status error={loadError||error} notice={notice}/><div className="module-grid"><form className="card stack" onSubmit={create}><h3>成立一支小隊</h3><label className="field">小隊名稱<input name="name" required maxLength={80}/></label><label className="field">小隊類型<select name="kind"><option value="project">專案小隊</option><option value="mutual_help">共同目標互助小隊</option></select></label><p className="field-hint">目前先提供這兩種組隊方式；類型名稱會隨社群需求調整。</p><label className="field">我們想一起完成什麼<textarea name="purpose" required maxLength={800}/></label><button className="btn btn-primary" disabled={busy}>成立小隊</button></form><section className="card stack"><h3>一起做事的方式</h3><p><strong>專案小隊</strong>：集合不同專長，把一個作品或服務做出來。</p><p><strong>共同目標互助小隊</strong>：設定共同目標，一起練習、交流與互相支持。</p><p className="muted">加入需由隊主接受。接受前，申請者不會取得只分享給小隊夥伴的聯絡方式。</p></section></div><div className="card-grid">{squads.map(squad=><article className="card stack" key={squad.squad_id}><span className="eyebrow">{kindLabels[squad.kind]}</span><h3>{squad.name}</h3><p>{squad.purpose}</p><p className="muted">隊主：{squad.owner_name} · {squad.member_count} 位夥伴</p><div className="actions"><button className="btn btn-ghost" onClick={()=>void open(squad.squad_id)}>查看小隊</button>{squad.membership?.state==='active'?<span className="badge">已加入</span>:squad.membership?.state==='pending'?<span className="muted">等候隊主接受</span>:<button className="btn btn-primary" disabled={busy} onClick={()=>void change(squad,'request',squad.membership?.aggregate_version)}>申請加入</button>}</div></article>)}</div>{loading&&<p role="status">正在載入小隊…</p>}{!loading&&!squads.length&&<p className="muted">還沒有小隊，從你的第一個共同目標開始。</p>}{nextOffset!==null&&<button className="btn btn-ghost" onClick={()=>void load(nextOffset)}>查看更多小隊</button>}{detail&&<section className="card stack" aria-label="小隊詳情"><div className="card-head"><h3>{detail.name}的夥伴</h3><button className="btn btn-ghost" onClick={()=>setDetail(null)}>收起</button></div>{detail.members.map(member=><div className="member-request" key={member.user_id}><span>{member.nickname} · {member.state==='active'?'已加入':'申請中'}</span>{member.state==='pending'&&detail.owner_ref===session.user.user_id&&<button className="btn btn-primary" disabled={busy} onClick={async()=>{const result=await mutate(`/squads/${detail.squad_id}/members/${member.user_id}/accept`,{},member.aggregate_version);if(result){await load();await open(detail.squad_id);}}}>接受加入</button>}</div>)}{detail.membership?.state==='active'&&detail.owner_ref!==session.user.user_id&&<button className="btn btn-ghost" disabled={busy} onClick={()=>void change(detail,'leave',detail.membership?.aggregate_version)}>退出這支小隊</button>}</section>}</section>;
}
