import type {Pool} from 'pg';
import {readPublishedSquadOutcome} from './squad-outcomes.js';
import {listEventOutcomeBacklinks} from '../community/event-outcomes.js';
const escape=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export async function publicSquadOutcomeHtml(pool:Pool,id:string,origin:string,eventLinksEnabled:boolean){
 const row=await readPublishedSquadOutcome(pool,id,null);
 const backlinks=eventLinksEnabled?await listEventOutcomeBacklinks(pool,{kind:'squad_outcome',id},null):{items:[]};
 const description=[...row.summary.replace(/\s+/g,' ').trim()].slice(0,160).join(''),title=`${row.title}｜自由工坊小隊成果`,canonical=`${origin}/squad-outcomes/${row.outcome_id}`;
 return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><link rel="canonical" href="${escape(canonical)}"><meta name="description" content="${escape(description)}"><meta property="og:type" content="article"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(canonical)}"><meta property="og:image" content="${escape(origin)}/brand/freedom-workshop.webp"><link rel="stylesheet" href="/highlights.css"></head><body><header class="hl-top"><a href="/"><img class="hl-logo" src="/brand/freedom-workshop.webp" alt="自由工坊" width="1280" height="720"></a></header><main><article><h1>${escape(row.title)}</h1><p>小隊：${escape(row.squad_name)} · 作者：${escape(row.author.display_name)}</p><p>作者明確公開的小隊成果；不代表平台驗收、出席、職務或 XP。</p>${row.summary.split(/\n+/).map(line=>`<p>${escape(line)}</p>`).join('')}${row.artifact_url?`<p><a href="${escape(row.artifact_url)}" target="_blank" rel="noopener noreferrer">作者提供的成果來源 ↗</a></p>`:''}${backlinks.items.length?`<section><h2>來自哪場活動</h2><ul>${backlinks.items.map(item=>`<li><a href="${escape(item.path)}">${escape(item.event_title)} · ${escape(item.title)}</a></li>`).join('')}</ul></section>`:''}</article></main><footer class="hl-foot"><a href="/#squad-outcomes/${row.outcome_id}">登入後查看成果</a></footer></body></html>`;
}
