// Native local workerd + R2 + Hyperdrive; IMAGES uses Miniflare's local low-fidelity emulator.
import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {createServer,createConnection,type Socket} from 'node:net';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {Pool} from 'pg';
import sharp from 'sharp';
import {migrate} from '../../scripts/database.js';
import {tokenHash} from '../../modules/identity-membership/service.js';
const raw=process.env.TEST_DATABASE_URL;assert(raw,'Owned fp_* TEST_DATABASE_URL required');const adminUrl=new URL(raw);
assert.match(adminUrl.pathname,/^\/fp_[a-z0-9_]+$/);assert(['127.0.0.1','localhost','[::1]'].includes(adminUrl.hostname));const socket=adminUrl.searchParams.get('host');if(socket)assert(socket.startsWith('/'));
const database=`fp_worker_highlight_${process.pid}_${Date.now()}`,migrator=database+'_owner',runtimeRole=database+'_app',password=randomBytes(24).toString('hex');
function roleUrl(role:string){const url=new URL(raw!);url.pathname='/'+database;url.username=role;url.password=password;return url.href;}
const admin=new Pool({connectionString:raw}),owner=new Pool({connectionString:roleUrl(migrator)}),app=new Pool({connectionString:roleUrl(runtimeRole)});
const sockets=new Set<Socket>(),proxy=socket?createServer(client=>{const upstream=createConnection(join(socket,'.s.PGSQL.5432'));for(const channel of [client,upstream]){sockets.add(channel);channel.on('close',()=>sockets.delete(channel));channel.on('error',()=>{client.destroy();upstream.destroy();});}client.pipe(upstream).pipe(client);}):undefined;
const origin='http://127.0.0.1:8787',community=randomUUID(),instances:Miniflare[]=[];let directory:string,tcp:string,png:Buffer,created=false,outboundCalls=0;
before(async()=>{
  await admin.query(`CREATE ROLE ${migrator} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;CREATE ROLE ${runtimeRole} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT`);
  await admin.query(`CREATE DATABASE ${database} OWNER ${migrator}`);created=true;await migrate(owner);
  const source=(await readFile('deploy/cloudflare/sql/20-runtime-grants.psql','utf8')).replace(/^\\set .*$/mg,'').replaceAll(':"runtime"','"'+runtimeRole+'"').replaceAll(":'runtime'","'"+runtimeRole+"'");
  const q=await owner.connect();try{const parts=source.split('\\gexec');for(let index=0;index<parts.length;index++){const result=await q.query(parts[index]);if(index<parts.length-1){const last=Array.isArray(result)?result.at(-1)!:result;for(const row of last.rows)await q.query(Object.values(row)[0] as string);}}}catch(error){await q.query('ROLLBACK');throw error;}finally{q.release();}
  const connection=new URL(roleUrl(runtimeRole));if(proxy){await new Promise<void>(r=>proxy.listen(0,'127.0.0.1',r));const address=proxy.address();assert(address&&typeof address==='object');connection.hostname='127.0.0.1';connection.port=String(address.port);connection.searchParams.delete('host');}tcp=connection.href;
  await owner.query("INSERT INTO communities VALUES($1,'Synthetic native highlight community')",[community]);
  directory=await mkdtemp(resolve('.wrangler/native-highlight-'));await mkdir(join(directory,'assets'));await writeFile(join(directory,'assets/index.html'),'<!doctype html><title>Native highlight fixture</title>');
  png=await sharp({create:{width:40,height:30,channels:3,background:'#337788'}}).png().toBuffer();
});
after(async()=>{for(const instance of instances)await instance.dispose();for(const channel of sockets)channel.destroy();if(proxy?.listening)await new Promise<void>(r=>proxy.close(()=>r()));await Promise.all([owner.end(),app.end()]);try{if(created){await admin.query(`DROP DATABASE ${database} WITH (FORCE)`);await admin.query(`DROP ROLE ${migrator},${runtimeRole}`);}}finally{await admin.end();}if(directory)await rm(directory,{recursive:true,force:true});assert.equal(outboundCalls,0);});
async function worker(options:{enabled?:string;media?:boolean;images?:boolean;partialMedia?:boolean;readHook?:boolean;video?:boolean}={}){
  const instance=new Miniflare(convertV4MiniflareOptions({workers:[{name:'native-highlight-'+randomUUID(),...((options.partialMedia||options.readHook)?{modules:[{type:'ESModule' as const,path:'entry.js',contents:options.partialMedia?'import main from "./main.js";export default {fetch(request,env,ctx){const media=env.MEDIA;return main.fetch(request,{...env,MEDIA:{get:media.get.bind(media),put:media.put.bind(media)}},ctx)}};':"import main from \"./main.js\";export default {fetch(request,env,ctx){const media=env.MEDIA,id=request.headers.get(\"X-Synthetic-Remove-Media\"),fail=request.headers.get(\"X-Synthetic-Fail-Thumb-Put\");let done=false;const binding=id||fail?{async put(...args){if(fail&&args[2]?.customMetadata?.profile_id===\"community.event-highlight.thumbnail\")throw new Error(\"synthetic second PUT failure\");return media.put(...args);},head:media.head.bind(media),delete:media.delete.bind(media),async get(...args){const object=await media.get(...args);if(id&&!done){done=true;const url=new URL(request.url);url.pathname=\"/api/v1/event-highlights/media/\"+id+\"/remove\";url.search=\"\";const response=await main.fetch(new Request(url,{method:\"POST\",headers:{Origin:url.origin,Cookie:request.headers.get(\"Cookie\"),\"X-CSRF-Token\":request.headers.get(\"X-CSRF-Token\"),\"Content-Type\":\"application/json\",\"Idempotency-Key\":crypto.randomUUID()},body:\"{}\"}),env,ctx);if(response.status!==200)throw new Error(\"synthetic removal failed\");}return object;}}:media;return main.fetch(request,{...env,MEDIA:binding},ctx)}};"},{type:'ESModule' as const,path:'main.js',contents:await readFile(resolve(process.env.FREEDOM_WORKERD_BUNDLE_DIR??'.wrangler/dry-run/local','worker.js'),'utf8')}]}:{modules:true,scriptPath:resolve(process.env.FREEDOM_WORKERD_BUNDLE_DIR??'.wrangler/dry-run/local','worker.js')}),compatibilityDate:'2026-09-21',compatibilityFlags:['nodejs_compat'],bindings:{FREEDOM_ENV:'local',APP_ORIGIN:origin,FREEDOM_REGISTRATION_COMMUNITY_ID:community,...(options.video?{FREEDOM_EVENT_VIDEO_ENABLED:'true'}:{}),...(options.enabled===undefined?{}:{FREEDOM_EVENT_HIGHLIGHT_ENABLED:options.enabled})},hyperdrives:{HYPERDRIVE:tcp},...(options.media===false?{}:{r2Buckets:['MEDIA']}),...(options.images===false?{}:{images:{binding:'IMAGES'}}),assets:{directory:join(directory,'assets'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true},assetConfig:{not_found_handling:'none'}},outboundService:async()=>{outboundCalls++;return new Response(null,{status:503});}}]}));instances.push(instance);await instance.ready;return instance;
}
type Member={id:string;cookie:string;csrf:string};
async function member(){const id=randomUUID(),token=randomBytes(32).toString('base64url'),csrf=randomUUID();await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,'Synthetic highlight member','not-a-login',$4)",[id,community,id+'@native-highlight.test',randomUUID()]);await owner.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,$3,clock_timestamp()+interval '1 hour')",[tokenHash(token),id,csrf]);return {id,cookie:'freedom_local_session='+token,csrf};}
const call=(instance:Miniflare,path:string,init?:RequestInit)=>instance.dispatchFetch(origin+path,init as never) as unknown as Promise<Response>;
function headers(member:Member){return {Origin:origin,Cookie:member.cookie,'X-CSRF-Token':member.csrf};}
async function event(organizer:Member){const id=randomUUID();await owner.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic native highlight','Owned fixture',clock_timestamp()-interval '2 days',clock_timestamp()-interval '1 day','online','Synthetic','published','open','other')",[id,community,organizer.id]);return id;}
function upload(instance:Miniflare,human:Member,id:string,key=randomUUID(),kind='photos',extra:Record<string,string>={}){return call(instance,'/api/v1/event-highlights/'+id+'/'+kind,{method:'POST',headers:{...headers(human),'Content-Type':'image/png','Idempotency-Key':key,'X-Photo-Orientation':'landscape',...extra},body:new Uint8Array(png)});}
function remove(instance:Miniflare,human:Member,id:string){return call(instance,'/api/v1/event-highlights/media/'+id+'/remove',{method:'POST',headers:{...headers(human),'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:'{}'});}
async function unpublished(){assert.equal((await owner.query("SELECT count(*)::int n FROM assets WHERE state='ready'")).rows[0].n,0);assert.equal((await owner.query("SELECT count(*)::int n FROM community_event_highlights WHERE storage_source='asset'")).rows[0].n,0);}
test('canonical Worker installs atomic highlight image/thumb pair only with complete native bindings and community policy',async()=>{
 const installed=await worker({enabled:'true',readHook:true}),uninstalled=await worker(),organizer=await member(),human=await member(),stranger=await member(),adminMember=await member(),id=await event(organizer);
 const partial=await worker({enabled:'true',partialMedia:true});assert.equal((await upload(partial,human,id)).status,503);assert.equal((await owner.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0,'Partial get/put binding cannot fall back to legacy writer.');const partialVideo=await worker({enabled:'false',video:true,partialMedia:true});assert.equal((await upload(partialVideo,human,id)).status,503);assert.equal((await owner.query('SELECT count(*)::int n FROM community_event_highlights')).rows[0].n,0);
 const legacy=await upload(uninstalled,human,id);assert.equal(legacy.status,201,await legacy.clone().text());const legacyDto=await legacy.json() as {media_id:string};assert.equal((await owner.query('SELECT storage_source FROM community_event_highlights WHERE media_id=$1',[legacyDto.media_id])).rows[0].storage_source,'legacy');assert.equal((await remove(uninstalled,human,legacyDto.media_id)).status,200);await owner.query("UPDATE domain_media_storage_policy SET mode='bridge' WHERE purpose='community.event-highlight'");assert.equal((await upload(uninstalled,human,id)).status,503);assert.equal((await upload(installed,human,id)).status,503);await unpublished();await owner.query("UPDATE domain_media_storage_policy SET persistence_allowed=true,policy_revision='synthetic-native-highlight-v1',retained_byte_limit=10485760 WHERE purpose='community.event-highlight'");
 for(const options of [{enabled:'false'},{enabled:'malformed'},{enabled:'true',media:false},{enabled:'true',images:false},{enabled:'true',partialMedia:true}]){assert.equal((await upload(await worker(options),human,id)).status,503);await unpublished();assert.equal((await owner.query('SELECT count(*)::int n FROM asset_upload_intents')).rows[0].n,0);}
 assert.equal((await upload(installed,human,id,randomUUID(),'photos',{'X-CSRF-Token':'wrong'})).status,403);const key=randomUUID(),failed=await upload(installed,human,id,key,'photos',{'X-Synthetic-Fail-Thumb-Put':'true'});assert.equal(failed.status,503,await failed.clone().text());assert.equal((await owner.query("SELECT count(*)::int n FROM community_event_highlights WHERE storage_source='asset'")).rows[0].n,0);assert.equal((await owner.query("SELECT count(*)::int n FROM assets WHERE state='ready'")).rows[0].n,0);assert.equal((await (await installed.getR2Bucket('MEDIA')).list()).objects.length,1);const response=await upload(installed,human,id,key);assert.equal(response.status,201,await response.clone().text());const dto=await response.json() as {media_id:string;image_url:string;thumb_url:string;uploaded_by_organizer:boolean;uploader:{user_id:string}};assert.equal(dto.uploaded_by_organizer,false);assert.equal(dto.uploader.user_id,human.id);const base='/api/v1/public/event-highlights/media/'+dto.media_id;assert.equal(dto.image_url,base+'/image');assert.equal(dto.thumb_url,base+'/thumb');const replay=await upload(installed,human,id,key);assert.equal(replay.status,201);assert.deepEqual(await replay.json(),dto);
 const bucket=await installed.getR2Bucket('MEDIA');assert.equal((await bucket.list()).objects.length,2);const rows=(await owner.query("SELECT o.variant,o.content_sha256,a.state,i.bytes FROM asset_objects o JOIN assets a USING(asset_id) JOIN community_event_highlight_images i ON i.media_id=$1 AND i.variant=CASE o.variant WHEN 'image' THEN 'image' ELSE 'thumb' END WHERE a.purpose='community.event-highlight' ORDER BY o.variant",[dto.media_id])).rows;assert.equal(rows.length,2);assert(rows.every(r=>r.state==='ready'&&r.bytes===null));for(const [variant,width,height] of [['image',1600,1200],['thumb',480,360]] as const){const read=await call(installed,base+'/'+variant);assert.equal(read.status,200,await read.clone().text());assert.equal(read.headers.get('cache-control'),'public, max-age=300');const bytes=Buffer.from(await read.arrayBuffer()),metadata=await sharp(bytes).metadata();assert.equal(metadata.format,'webp');assert.equal(metadata.width,width);assert.equal(metadata.height,height);assert.equal(createHash('sha256').update(bytes).digest('hex'),rows.find(r=>r.variant===variant).content_sha256);assert.equal((await call(uninstalled,base+'/'+variant)).status,503);}
 await owner.query("UPDATE domain_media_storage_policy SET retained_byte_limit=1253376 WHERE purpose='community.event-highlight'");assert.equal((await upload(installed,human,id)).status,409);await owner.query("UPDATE domain_media_storage_policy SET retained_byte_limit=10485760 WHERE purpose='community.event-highlight'");assert.equal((await remove(installed,stranger,dto.media_id)).status,403);assert.equal((await remove(installed,organizer,dto.media_id)).status,200);assert.equal((await call(installed,dto.image_url)).status,404);assert.equal((await call(installed,dto.thumb_url)).status,404);
 const owned=await upload(installed,human,id,randomUUID(),'posters');assert.equal(owned.status,201);const ownedDto=await owned.json() as {media_id:string};assert.equal((await remove(installed,human,ownedDto.media_id)).status,200);await owner.query('UPDATE users SET email_verified_at=clock_timestamp() WHERE user_id=$1',[adminMember.id]);await owner.query("INSERT INTO platform_admins(admin_id,community_id,email,display_name) SELECT gen_random_uuid(),community_id,email,'Synthetic highlight admin' FROM users WHERE user_id=$1",[adminMember.id]);const adminUpload=await upload(installed,human,id);assert.equal(adminUpload.status,201);assert.equal((await remove(installed,adminMember,(await adminUpload.json() as {media_id:string}).media_id)).status,200);const raced=await upload(installed,human,id);assert.equal(raced.status,201);const racedDto=await raced.json() as {media_id:string;image_url:string;thumb_url:string};const denied=await call(installed,racedDto.image_url,{headers:{...headers(human),'X-Synthetic-Remove-Media':racedDto.media_id}});assert.equal(denied.status,404,await denied.clone().text());assert.equal((await call(installed,racedDto.thumb_url)).status,404);assert.equal((await bucket.list()).objects.length,8);assert.equal((await owner.query("SELECT count(*)::int n FROM assets WHERE state='ready'")).rows[0].n,0);await assert.rejects(app.query("UPDATE domain_media_storage_policy SET persistence_allowed=false WHERE purpose='community.event-highlight'"),e=>(e as {code:string}).code==='42501');
});
