// Native local workerd + R2 + Hyperdrive; IMAGES uses Miniflare's local low-fidelity emulator.
import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {createServer,createConnection,type Socket} from 'node:net';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {Pool} from 'pg';
import sharp from 'sharp';
import {migrate} from '../../scripts/database.js';
import {tokenHash} from '../../modules/identity-membership/service.js';
const raw=process.env.TEST_DATABASE_URL;assert(raw,'Owned fp_* TEST_DATABASE_URL required');const adminUrl=new URL(raw);
assert.match(adminUrl.pathname,/^\/fp_[a-z0-9_]+$/);assert(['127.0.0.1','localhost','[::1]'].includes(adminUrl.hostname));const socket=adminUrl.searchParams.get('host');if(socket)assert(socket.startsWith('/'));
const database=`fp_worker_banner_${process.pid}_${Date.now()}`,migrator=database+'_owner',runtimeRole=database+'_app',password=randomBytes(24).toString('hex');
function roleUrl(role:string){const url=new URL(raw!);url.pathname='/'+database;url.username=role;url.password=password;return url.href;}
const admin=new Pool({connectionString:raw}),owner=new Pool({connectionString:roleUrl(migrator)}),app=new Pool({connectionString:roleUrl(runtimeRole)});
// Pool.end() resolves after removing clients, before their sockets necessarily close.
// Wait for actual client end events before DROP FORCE, so teardown cannot kill an idle closing client.
const closedClients:Promise<void>[]=[];
for(const pool of [owner,app])pool.on('connect',client=>closedClients.push(new Promise<void>(resolve=>client.once('end',resolve))));
const sockets=new Set<Socket>(),proxy=socket?createServer(client=>{const upstream=createConnection(join(socket,'.s.PGSQL.5432'));for(const channel of [client,upstream]){sockets.add(channel);channel.on('close',()=>sockets.delete(channel));channel.on('error',()=>{client.destroy();upstream.destroy();});}client.pipe(upstream).pipe(client);}):undefined;
const origin='http://127.0.0.1:8787',community=randomUUID(),instances:Miniflare[]=[];let directory:string,tcp:string,png:Buffer,created=false,outboundCalls=0;
before(async()=>{
  await admin.query(`CREATE ROLE ${migrator} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;CREATE ROLE ${runtimeRole} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT`);
  await admin.query(`CREATE DATABASE ${database} OWNER ${migrator}`);created=true;await migrate(owner);
  const source=(await readFile('deploy/cloudflare/sql/20-runtime-grants.psql','utf8')).replace(/^\\set .*$/mg,'').replaceAll(':"runtime"','"'+runtimeRole+'"').replaceAll(":'runtime'","'"+runtimeRole+"'");
  const q=await owner.connect();try{const parts=source.split('\\gexec');for(let index=0;index<parts.length;index++){const result=await q.query(parts[index]);if(index<parts.length-1){const last=Array.isArray(result)?result.at(-1)!:result;for(const row of last.rows)await q.query(Object.values(row)[0] as string);}}}catch(error){await q.query('ROLLBACK');throw error;}finally{q.release();}
  const connection=new URL(roleUrl(runtimeRole));if(proxy){await new Promise<void>(r=>proxy.listen(0,'127.0.0.1',r));const address=proxy.address();assert(address&&typeof address==='object');connection.hostname='127.0.0.1';connection.port=String(address.port);connection.searchParams.delete('host');}tcp=connection.href;
  await owner.query("INSERT INTO communities VALUES($1,'Synthetic native banner community')",[community]);
  await owner.query("UPDATE domain_media_storage_policy SET mode='bridge' WHERE purpose='community.event-banner'");
  directory=await mkdtemp(resolve('.wrangler/native-banner-'));await mkdir(join(directory,'assets'));await writeFile(join(directory,'assets/index.html'),'<!doctype html><title>Native banner fixture</title>');
  png=await sharp({create:{width:30,height:40,channels:3,background:'#337788'}}).png().toBuffer();
});
after(async()=>{for(const instance of instances)await instance.dispose();for(const channel of sockets)channel.destroy();if(proxy?.listening)await new Promise<void>(r=>proxy.close(()=>r()));await Promise.all([owner.end(),app.end()]);await Promise.all(closedClients);try{if(created){await admin.query(`DROP DATABASE ${database} WITH (FORCE)`);await admin.query(`DROP ROLE ${migrator},${runtimeRole}`);}}finally{await admin.end();}if(directory)await rm(directory,{recursive:true,force:true});assert.equal(outboundCalls,0);});
async function worker(options:{enabled?:string;media?:boolean;images?:boolean}={}){
  const instance=new Miniflare(convertV4MiniflareOptions({workers:[{name:'native-banner-'+randomUUID(),modules:true,scriptPath:resolve(process.env.FREEDOM_WORKERD_BUNDLE_DIR??'.wrangler/dry-run/local','worker.js'),compatibilityDate:'2026-09-21',compatibilityFlags:['nodejs_compat'],bindings:{FREEDOM_ENV:'local',APP_ORIGIN:origin,FREEDOM_REGISTRATION_COMMUNITY_ID:community,...(options.enabled===undefined?{}:{FREEDOM_EVENT_BANNER_ENABLED:options.enabled})},hyperdrives:{HYPERDRIVE:tcp},...(options.media===false?{}:{r2Buckets:['MEDIA']}),...(options.images===false?{}:{images:{binding:'IMAGES'}}),assets:{directory:join(directory,'assets'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true},assetConfig:{not_found_handling:'none'}},outboundService:async()=>{outboundCalls++;return new Response(null,{status:503});}}]}));instances.push(instance);await instance.ready;return instance;
}
type Member={id:string;cookie:string;csrf:string};
async function member(){const id=randomUUID(),token=randomBytes(32).toString('base64url'),csrf=randomUUID();await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,'Synthetic banner member','not-a-login',$4)",[id,community,id+'@native-banner.test',randomUUID()]);await owner.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,$3,clock_timestamp()+interval '1 hour')",[tokenHash(token),id,csrf]);return {id,cookie:'freedom_local_session='+token,csrf};}
const call=(instance:Miniflare,path:string,init?:RequestInit)=>instance.dispatchFetch(origin+path,init as never) as unknown as Promise<Response>;
function headers(member:Member){return {Origin:origin,Cookie:member.cookie,'X-CSRF-Token':member.csrf};}
async function event(instance:Miniflare,member:Member){const response=await call(instance,'/api/v1/events',{method:'POST',headers:{...headers(member),'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify({title:'Synthetic native banner event',description:'Owned fixture only',starts_at:new Date(Date.now()+86400000).toISOString(),ends_at:new Date(Date.now()+90000000).toISOString(),mode:'online',location:'Synthetic',online_url:'https://example.invalid/event',event_kind:'other',visibility:'open',capacity:null})});assert.equal(response.status,201,await response.clone().text());return (await response.json() as {event_id:string}).event_id;}
function upload(instance:Miniflare,member:Member,id:string,key=randomUUID(),version='1',extra:Record<string,string>={}){return call(instance,'/api/v1/events/'+id+'/banner',{method:'POST',headers:{...headers(member),'Content-Type':'image/png','Idempotency-Key':key,'If-Match':'"'+version+'"','X-Poster-Orientation':'portrait',...extra},body:new Uint8Array(png)});}
async function noPublishedBanner(){assert.equal((await owner.query("SELECT count(*)::int n FROM assets WHERE state='ready'")).rows[0].n,0);assert.equal((await owner.query('SELECT count(*)::int n FROM community_event_banners')).rows[0].n,0);}
test('canonical Worker banner installation requires explicit opt-in and community policy; organizer lifecycle uses native R2',async()=>{
 const uninstalled=await worker(),installed=await worker({enabled:'true'}),human=await member(),foreign=await member(),id=await event(uninstalled,human);
 assert.equal((await upload(uninstalled,human,id)).status,503);assert.equal((await upload(installed,human,id)).status,503);await noPublishedBanner();
 await owner.query("UPDATE domain_media_storage_policy SET policy_revision='synthetic-native-banner-v1',persistence_allowed=true,retained_byte_limit=10485760 WHERE purpose='community.event-banner'");
 for(const options of [{enabled:'false'},{enabled:'malformed'},{enabled:'true',media:false},{enabled:'true',images:false}]){const unavailable=await worker(options);assert.equal((await upload(unavailable,human,id)).status,503);if(options.enabled!=='false'){assert.equal((await call(unavailable,'/api/v1/events',{method:'POST',headers:{...headers(human),'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:'{}'})).status,503);assert.equal((await owner.query('SELECT count(*)::int n FROM community_events')).rows[0].n,1);}await noPublishedBanner();}
 assert.equal((await upload(installed,foreign,id)).status,403);assert.equal((await upload(installed,human,id,randomUUID(),'1',{'X-CSRF-Token':'wrong'})).status,403);
 const key=randomUUID(),response=await upload(installed,human,id,key);assert.equal(response.status,200,await response.clone().text());const dto=await response.json() as {banner_url:string;aggregate_version:number;banner_orientation:string};assert.equal(dto.aggregate_version,2);assert.equal(dto.banner_orientation,'portrait');assert.equal(dto.banner_url,'/api/v1/events/'+id+'/banner?v=2');assert.equal(response.headers.get('etag'),'"2"');
 const replay=await upload(installed,human,id,key);assert.equal(replay.status,200,await replay.clone().text());assert.deepEqual(await replay.json(),dto);
 await owner.query("UPDATE domain_media_storage_policy SET retained_byte_limit=524288 WHERE purpose='community.event-banner'");assert.equal((await upload(installed,human,id,randomUUID(),'2')).status,409);await owner.query("UPDATE domain_media_storage_policy SET retained_byte_limit=10485760 WHERE purpose='community.event-banner'");
 const bucket=await installed.getR2Bucket('MEDIA');assert.equal((await bucket.list()).objects.length,1);
 const row=(await owner.query("SELECT b.storage_source,octet_length(b.image_bytes) legacy_bytes,o.content_sha256 FROM community_event_banners b JOIN community_event_banner_asset_targets t USING(event_id) JOIN asset_objects o ON o.asset_id=t.asset_id WHERE b.event_id=$1",[id])).rows[0];assert.equal(row.storage_source,'asset');assert.equal(row.legacy_bytes,null);
 const path='/api/v1/events/'+id+'/banner',publicPath='/api/v1/public/events/'+id+'/banner';const read=await call(installed,path,{headers:headers(human)});assert.equal(read.status,200);assert.equal(read.headers.get('cache-control'),'private, no-store');const bytes=Buffer.from(await read.arrayBuffer());const metadata=await sharp(bytes).metadata();assert.equal(metadata.format,'webp');assert.equal(metadata.width,900);assert.equal(metadata.height,1200);assert.equal(createHash('sha256').update(bytes).digest('hex'),row.content_sha256);assert.equal((await call(installed,path,{headers:headers(foreign)})).status,404);assert.equal((await call(installed,publicPath)).status,404);
 await owner.query("UPDATE community_events SET state='published' WHERE event_id=$1",[id]);const publicRead=await call(installed,publicPath);assert.equal(publicRead.status,200);assert.deepEqual(Buffer.from(await publicRead.arrayBuffer()),bytes);assert.equal((await call(installed,path,{headers:headers(foreign)})).status,200);assert.equal((await upload(installed,human,id,randomUUID(),'2')).status,409);
 await owner.query("UPDATE community_events SET state='pending' WHERE event_id=$1",[id]);const removed=await call(installed,path+'/remove',{method:'POST',headers:{...headers(human),'Content-Type':'application/json','Idempotency-Key':randomUUID(),'If-Match':'"2"'},body:'{}'});assert.equal(removed.status,200,await removed.clone().text());assert.equal((await call(installed,path,{headers:headers(human)})).status,404);assert.equal((await bucket.list()).objects.length,1,'Removal does not authorize object GC.');
 await assert.rejects(app.query("UPDATE domain_media_storage_policy SET persistence_allowed=true WHERE purpose='community.event-banner'"),error=>(error as {code:string}).code==='42501');
});
