import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {createServer,createConnection,type Socket} from 'node:net';
import {mkdir,mkdtemp,readFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {Pool} from 'pg';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrate} from '../../scripts/database.js';
import {backfillLegacyScopeBatch} from '../../packages/resource-scopes/index.js';
import {planOperatorBackfill} from '../../packages/media-migration/operator-backfill.js';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import {publicEventBanner} from '../../modules/community/events.js';
import {publicSocialThumbnail} from '../../modules/community/social-posts.js';
type Purpose='community.event-banner'|'community.social-thumbnail';
const purposes:Purpose[]=['community.event-banner','community.social-thumbnail'];
const hash=(v:Uint8Array)=>createHash('sha256').update(v).digest('hex');
const field=(purpose:Purpose)=>purpose==='community.event-banner'?{source:'community_event_banners',domain:'community_events',id:'event_id',version:'aggregate_version',pointer:'community_event_banner_asset_targets'}:{source:'community_social_post_thumbnails',domain:'community_social_posts',id:'post_id',version:'media_version',pointer:'community_social_thumbnail_asset_targets'};

test('private native operator RPC installs only four purposes; banner/social preserve original ACL/provenance and fence unknown ACK/stale IO',{timeout:60000},async()=>{
 const raw=process.env.TEST_DATABASE_URL;if(!raw)throw Error('Explicit owned TEST_DATABASE_URL required');
 const parsed=new URL(raw),socket=parsed.searchParams.get('host');if(!/^\/fp_[a-z0-9_]+$/.test(parsed.pathname)||(!socket&&!['127.0.0.1','localhost','[::1]'].includes(parsed.hostname)))throw Error('Owned fp_* loopback/socket database required');
 const suffix=process.pid+'_'+Date.now(),schema='fp_operator_rpc_images_'+suffix,ownerRole=schema+'_o',role='fp_media_migrator_'+suffix,password=randomBytes(24).toString('hex');
 const admin=new Pool({connectionString:raw}),owner=new Pool({connectionString:raw,options:`-c role=${ownerRole} -c search_path=${schema}`});
 const sockets=new Set<Socket>(),proxy=socket?createServer(client=>{const upstream=createConnection(join(socket,'.s.PGSQL.5432'));for(const s of [client,upstream]){sockets.add(s);s.on('close',()=>sockets.delete(s));s.on('error',()=>{client.destroy();upstream.destroy();});}client.pipe(upstream).pipe(client);}):undefined;
 let mf:Miniflare|undefined,directory:string|undefined,created=false,hook:undefined|(()=>Promise<void>);
 try{
  await admin.query(`CREATE ROLE ${ownerRole} NOLOGIN NOSUPERUSER NOBYPASSRLS;CREATE SCHEMA ${schema} AUTHORIZATION ${ownerRole}`);created=true;await migrate(owner);
  assert.equal((await owner.query('SELECT rolsuper FROM pg_roles WHERE rolname=current_user')).rows[0].rolsuper,false);
  await admin.query(`CREATE ROLE ${role} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT PASSWORD '${password}'`);
  const grants=(await readFile(new URL('../../deploy/cloudflare/sql/40-media-backfill-operator-grants.psql',import.meta.url),'utf8')).split('-- BEGIN CLOSED OPERATOR GRANTS')[1].split('-- END CLOSED OPERATOR GRANTS')[0];
  const q=await owner.connect();try{await q.query('BEGIN');await q.query("SELECT set_config('freedom.operator_role',$1,true),set_config('freedom.operator_schema',$2,true)",[role,schema]);await q.query(grants);await q.query('COMMIT');}catch(e){await q.query('ROLLBACK');throw e;}finally{q.release();}
  let port:string|undefined;if(proxy){await new Promise<void>(r=>proxy.listen(0,'127.0.0.1',r));const a=proxy.address();assert(a&&typeof a==='object');port=String(a.port);}
  const connection=new URL(raw);connection.username=role;connection.password=password;if(proxy){connection.hostname='127.0.0.1';connection.port=port!;connection.searchParams.delete('host');}
  const target={environment:'local' as const,database:parsed.pathname.slice(1),schema,role,releaseSha:'9'.repeat(40)},binding='synthetic-native-images-r2';
  const profile={target,logicalStore:'MEDIA',storeBindingId:binding,purposes:['member.service-cover','community.event-video',...purposes]};
  const bindings={FREEDOM_MEDIA_OPERATOR_ENABLED:'true',FREEDOM_MEDIA_OPERATOR_ENVIRONMENT:'local',FREEDOM_MEDIA_OPERATOR_RELEASE_SHA:target.releaseSha,FREEDOM_MEDIA_OPERATOR_STORE_BINDING_ID:binding,FREEDOM_MEDIA_OPERATOR_PROFILE:JSON.stringify(profile)};
  await mkdir(resolve('.wrangler'),{recursive:true});directory=await mkdtemp(resolve('.wrangler/media-operator-images-rpc-'));
  await promisify(execFile)(process.execPath,['node_modules/wrangler/bin/wrangler.js','deploy','--dry-run','--config','wrangler.media-operator.example.jsonc','--env','staging-next','--outdir',directory],{maxBuffer:1024*1024});
  const native={name:'operator',modules:true,scriptPath:join(directory,'worker.js'),compatibilityDate:'2026-09-21',compatibilityFlags:['nodejs_compat'],bindings,hyperdrives:{OPERATOR_HYPERDRIVE:connection.href},r2Buckets:{MEDIA:'synthetic-operator-images-assets'},outboundService:'no-external'};
  const bundle=await readFile(join(directory,'worker.js'),'utf8');
  const fault=`import {MediaOperator as Base} from './main.js';export class MediaOperator extends Base {constructor(ctx,env){const b=env.MEDIA;super(ctx,{...env,MEDIA:{put:async(...a)=>{await b.put(...a);throw Error('synthetic unknown ACK');},get:async()=>{throw Error('synthetic unavailable readback');},head:(...a)=>b.head(...a),delete:(...a)=>b.delete(...a)}});}}export {default} from './main.js';`;
  const mutate=`import {MediaOperator as Base} from './main.js';export class MediaOperator extends Base {constructor(ctx,env){const b=env.MEDIA;super(ctx,{...env,MEDIA:{put:async(...a)=>{const result=await b.put(...a);const response=await env.AFTER_PUT.fetch('https://synthetic-io-hook.internal/');if(!response.ok)throw Error('synthetic hook failure');return result;},get:(...a)=>b.get(...a),head:(...a)=>b.head(...a),delete:(...a)=>b.delete(...a)}});}}export {default} from './main.js';`;
  const names=['operator','unknown-ack','mutate','cover-only','foreign-profile'];
  mf=new Miniflare(convertV4MiniflareOptions({workers:[native,
   {...native,name:'cover-only',bindings:{...bindings,FREEDOM_MEDIA_OPERATOR_PROFILE:JSON.stringify({...profile,purposes:['member.service-cover']})}},
   {...native,name:'foreign-profile',bindings:{...bindings,FREEDOM_MEDIA_OPERATOR_PROFILE:JSON.stringify({...profile,purposes:['skill.submission-image']})}},
   {...native,name:'unknown-ack',scriptPath:undefined,modules:[{type:'ESModule',path:'entry.js',contents:fault},{type:'ESModule',path:'main.js',contents:bundle}]},
   {...native,name:'mutate',scriptPath:undefined,modules:[{type:'ESModule',path:'entry.js',contents:mutate},{type:'ESModule',path:'main.js',contents:bundle}],serviceBindings:{AFTER_PUT:async()=>{await hook?.();return new Response(null,{status:204});}}},
   {name:'no-external',modules:true,script:"let calls=0;export default {fetch(r){if(new URL(r.url).pathname==='/counts')return Response.json({calls});calls++;return new Response(null,{status:503});}}",compatibilityDate:'2026-09-21'},
   {name:'caller',modules:true,script:"export default {async fetch(r,e){try{return Response.json(await e[new URL(r.url).pathname.slice(1)].execute(await r.json()));}catch(error){return Response.json({code:error.message},{status:503});}}};",compatibilityDate:'2026-09-21',serviceBindings:Object.fromEntries(names.map(n=>[n,{name:n,entrypoint:'MediaOperator'}]))}]}));await mf.ready;
  const client=await mf.getWorker('caller'),rpc=async(name:string,p:unknown)=>client.fetch('https://synthetic-private-rpc.internal/'+name,{method:'POST',body:JSON.stringify(p)});
  const plan=(purpose:Purpose)=>planOperatorBackfill({target,jobId:randomUUID(),logicalStore:'MEDIA',storeBindingId:binding,migrationId:'synthetic-native-images-v1',purpose,maxRows:1,maxBytes:8388608,leaseSeconds:30});
  const approve=async(p:ReturnType<typeof plan>)=>{await owner.query("INSERT INTO media_backfill_operator_policy(role_name,environment,database_name,schema_name,release_sha,logical_store,store_binding_id,migration_id,purpose,approved_plan_sha256,allowed,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,clock_timestamp()+interval '1 hour')",[target.role,target.environment,target.database,target.schema,target.releaseSha,p.logicalStore,p.storeBindingId,p.migrationId,p.purpose,p.planSha256]);return p;};
  const image=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).webp().toBuffer(),bytes=Buffer.alloc(524288);image.copy(bytes);bytes.write('JUNK',image.length,'ascii');bytes.writeUInt32LE(bytes.length-image.length-8,image.length+4);bytes.writeUInt32LE(bytes.length-8,4);assert.equal((await sharp(bytes).metadata()).format,'webp');
  await owner.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-native-images-v1',persistence_allowed=true,retained_byte_limit=16777216 WHERE purpose=ANY($1::text[])",[purposes]);
  const bucket=await mf.getR2Bucket('MEDIA','operator'),store=createR2ObjectStore(bucket as unknown as AssetR2Binding);
  async function source(purpose:Purpose){await owner.query('TRUNCATE communities CASCADE');const community=randomUUID(),user=randomUUID(),id=randomUUID();await owner.query("INSERT INTO communities VALUES($1,'Synthetic native image operator')",[community]);await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,'Synthetic','not-a-password',$4)",[user,community,user+'@native-images.invalid',randomUUID()]);if(purpose==='community.event-banner'){await owner.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic ended','Synthetic',clock_timestamp()-interval '2 days',clock_timestamp()-interval '1 day','online','Synthetic','published','open','other')",[id,community,user]);await owner.query("INSERT INTO community_event_banners(event_id,image_bytes,orientation) VALUES($1,$2,'portrait')",[id,bytes]);}else{await owner.query("INSERT INTO community_social_posts(post_id,community_id,author_user_id,url,platform,title,note,state) VALUES($1,$2,$3,$4,'youtube','Original|title','Original|note','active')",[id,community,user,'https://www.youtube.com/watch?v='+id]);await owner.query("INSERT INTO community_social_post_thumbnails(post_id,image_bytes,source) VALUES($1,$2,'page')",[id,bytes]);}await backfillLegacyScopeBatch(owner,500);await backfillLegacyScopeBatch(owner,500);return {id,user,community};}
  const originalRead=(purpose:Purpose,id:string)=>purpose==='community.event-banner'?publicEventBanner(owner,id,store):publicSocialThumbnail(owner,id,store);
  for(const purpose of purposes){
   const f=field(purpose),s=await source(purpose),p=await approve(plan(purpose));
   for(const name of ['cover-only','foreign-profile']){const denied=await rpc(name,p);assert.equal(denied.status,503);assert.deepEqual(await denied.json(),{code:'operator_media_unavailable'});}
   for(const foreign of ['member.avatar','skill.submission-image','community.event-highlight'])assert.equal((await rpc('operator',{...p,purpose:foreign})).status,503);
   assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);
   const before=(await owner.query(`SELECT * FROM ${f.source} WHERE ${f.id}=$1`,[s.id])).rows[0],domain=(await owner.query(`SELECT * FROM ${f.domain} WHERE ${f.id}=$1`,[s.id])).rows[0];
   const response=await rpc('operator',p);assert.equal(response.status,200,await response.clone().text());assert.equal((await response.json() as any).linked,1);
   const after=(await owner.query(`SELECT * FROM ${f.source} WHERE ${f.id}=$1`,[s.id])).rows[0];assert.deepEqual(after.image_bytes,bytes);assert.equal(after.storage_source,'asset');assert.equal(after[purpose==='community.event-banner'?'orientation':'source'],before[purpose==='community.event-banner'?'orientation':'source']);
   const row=(await owner.query(`SELECT a.scope_kind,a.community_ref,o.content_sha256,o.profile_id FROM ${f.pointer} t JOIN assets a USING(asset_id) JOIN asset_objects o USING(asset_id) WHERE ${f.id}=$1`,[s.id])).rows[0];assert.equal(row.scope_kind,'community');assert.equal(row.community_ref,s.community);assert.equal(row.content_sha256,hash(bytes));assert.equal(row.profile_id,purpose);assert.equal(hash(await originalRead(purpose,s.id)),hash(bytes));
   const updated=(await owner.query(`SELECT * FROM ${f.domain} WHERE ${f.id}=$1`,[s.id])).rows[0];assert.equal(BigInt(updated[f.version]),BigInt(domain[f.version])+1n);if(purpose==='community.social-thumbnail')for(const key of ['url','platform','title','note'])assert.equal(updated[key],domain[key]);
   assert.equal((await (await rpc('operator',p)).json() as any).allSourcesMigrated,true);
   await owner.query(`UPDATE ${f.domain} SET state=$2 WHERE ${f.id}=$1`,[s.id,purpose==='community.event-banner'?'cancelled':'hidden']);await assert.rejects(originalRead(purpose,s.id),'original public ACL is rechecked');
   const stale=await source(purpose),sp=await approve(plan(purpose)),staleVersion=(await owner.query(`SELECT ${f.version} AS v FROM ${f.domain} WHERE ${f.id}=$1`,[stale.id])).rows[0].v;hook=async()=>{if(purpose==='community.event-banner')await owner.query("UPDATE community_event_banners SET orientation='landscape' WHERE event_id=$1",[stale.id]);else await owner.query("UPDATE community_social_posts SET url='https://example.invalid/changed',title='Changed|title',note=NULL WHERE post_id=$1",[stale.id]);};
   const staleResponse=await rpc('mutate',sp);hook=undefined;assert.equal(staleResponse.status,200,await staleResponse.clone().text());const staleReport=await staleResponse.json() as any;assert.equal(staleReport.stale,1);assert.equal(staleReport.linked,0);assert.equal((await owner.query(`SELECT ${f.version} AS v FROM ${f.domain} WHERE ${f.id}=$1`,[stale.id])).rows[0].v,staleVersion);assert.equal((await owner.query(`SELECT storage_source FROM ${f.source} WHERE ${f.id}=$1`,[stale.id])).rows[0].storage_source,'legacy');
   const inactive=await source(purpose);await owner.query('UPDATE users SET active=false WHERE user_id=$1',[inactive.user]);const blocked=await rpc('operator',await approve(plan(purpose)));assert.equal(blocked.status,200);assert.equal((await blocked.json() as any).blocked,1);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);
   const revoked=await source(purpose),rp=await approve(plan(purpose));hook=async()=>{await owner.query('UPDATE users SET active=false WHERE user_id=$1',[revoked.user]);};const revokeResponse=await rpc('mutate',rp);hook=undefined;assert.equal(revokeResponse.status,200,await revokeResponse.clone().text());assert.equal((await revokeResponse.json() as any).stale,1);assert.equal((await owner.query(`SELECT storage_source FROM ${f.source} WHERE ${f.id}=$1`,[revoked.id])).rows[0].storage_source,'legacy');
   const uncertain=await source(purpose),up=await approve(plan(purpose)),unknown=await rpc('unknown-ack',up);assert.equal(unknown.status,503);assert.deepEqual(await unknown.json(),{code:'operator_media_unavailable'});
   const item=(await owner.query('SELECT intent_id,asset_id FROM media_backfill_items WHERE job_id=$1',[up.jobId])).rows[0];assert.ok(item);assert.deepEqual((await owner.query('SELECT state FROM asset_object_write_effects WHERE asset_id=$1',[item.asset_id])).rows,[{state:'unknown'}]);assert.equal((await owner.query(`SELECT storage_source FROM ${f.source} WHERE ${f.id}=$1`,[uncertain.id])).rows[0].storage_source,'legacy');
   await owner.query('UPDATE media_backfill_jobs SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE job_id=$1',[up.jobId]);await owner.query('UPDATE asset_upload_intents SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE intent_id=$1',[item.intent_id]);
   const resume=await rpc('operator',up);assert.equal(resume.status,200,await resume.clone().text());assert.equal((await resume.json() as any).linked,1);assert.equal((await owner.query('SELECT fence FROM asset_upload_intents WHERE intent_id=$1',[item.intent_id])).rows[0].fence,'2');assert.equal((await owner.query('SELECT asset_id FROM media_backfill_items WHERE job_id=$1',[up.jobId])).rows[0].asset_id,item.asset_id);assert.deepEqual((await owner.query('SELECT state FROM asset_object_write_effects WHERE asset_id=$1 ORDER BY state',[item.asset_id])).rows,[{state:'fulfilled'},{state:'unknown'}]);assert.equal(hash(await originalRead(purpose,uncertain.id)),hash(bytes));
   const restricted=new Pool({connectionString:connection.href});try{for(const sql of [`UPDATE ${f.source} SET image_bytes=image_bytes`,`UPDATE ${f.source} SET ${purpose==='community.event-banner'?'orientation':'source'}=${purpose==='community.event-banner'?'orientation':'source'}`,`UPDATE ${f.domain} SET state=state`])await assert.rejects(restricted.query('SET search_path TO '+schema+';'+sql),(e:any)=>e.code==='42501');}finally{await restricted.end();}
  }
  assert.equal((await (await (await mf.getWorker('no-external')).fetch('https://synthetic-no-external.internal/counts')).json() as any).calls,0);assert.equal((await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n,0);assert.equal((await admin.query('SELECT count(*)::int n FROM pg_stat_activity WHERE usename=$1',[role])).rows[0].n,0);
 }finally{
  await mf?.dispose();for(const s of sockets)s.destroy();if(proxy?.listening)await new Promise<void>((r,j)=>proxy.close(e=>e?j(e):r()));await owner.end();if(created)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.query(`DROP ROLE IF EXISTS ${role};DROP ROLE IF EXISTS ${ownerRole}`);await admin.end();if(directory)await rm(directory,{recursive:true,force:true});
 }
});
