import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {createServer,createConnection,type Socket} from 'node:net';
import {mkdir,mkdtemp,readFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {Pool} from 'pg';
import sharp from 'sharp';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrate} from '../../scripts/database.js';
import {backfillLegacyScopeBatch} from '../../packages/resource-scopes/index.js';
import {planOperatorBackfill} from '../../packages/media-migration/operator-backfill.js';
import {objectKey} from '../../packages/asset-storage/index.js';
import {createAssetMaintenance} from '../../modules/assets/maintenance.js';
import {createR2ObjectStore,type AssetR2Binding} from '../../packages/asset-storage/r2.js';
import {hashPasswordAsync,login,authenticate} from '../../modules/identity-membership/service.js';
import {readSkillImage} from '../../modules/assets/skill-image.js';
import {readOwnIllustration,readSubmission} from '../../modules/skill-submissions/service.js';
import {highlightImageBytes,readHighlightEvent} from '../../modules/community/event-highlights.js';
import {readAvatar,avatarMetadata} from '../../modules/identity-membership/avatars.js';
import {publicMemberAvatar} from '../../modules/identity-membership/member-sharing.js';
type Purpose='skill.submission-image'|'community.event-highlight';
const purposes:Purpose[]=['skill.submission-image','community.event-highlight'];
const hash=(v:Uint8Array)=>createHash('sha256').update(v).digest('hex');

test('private native operator RPC installs seven-profile RPC avatar/skill/highlight actual bytes/current ACL; atomic pair and unknown/stale IO',{timeout:60000},async()=>{
 const raw=process.env.TEST_DATABASE_URL;if(!raw)throw Error('Explicit owned TEST_DATABASE_URL required');
 const parsed=new URL(raw),socket=parsed.searchParams.get('host');if(!/^\/fp_[a-z0-9_]+$/.test(parsed.pathname)||(!socket&&!['127.0.0.1','localhost','[::1]'].includes(parsed.hostname)))throw Error('Owned fp_* loopback/socket database required');
 const suffix=process.pid+'_'+Date.now(),schema='fp_operator_rpc_private_'+suffix,ownerRole=schema+'_o',role='fp_media_migrator_'+suffix,password=randomBytes(24).toString('hex');
 const admin=new Pool({connectionString:raw}),owner=new Pool({connectionString:raw,options:`-c role=${ownerRole} -c search_path=${schema}`});
 const sockets=new Set<Socket>(),proxy=socket?createServer(client=>{const upstream=createConnection(join(socket,'.s.PGSQL.5432'));for(const s of [client,upstream]){sockets.add(s);s.on('close',()=>sockets.delete(s));s.on('error',()=>{client.destroy();upstream.destroy();});}client.pipe(upstream).pipe(client);}):undefined;
 let mf:Miniflare|undefined,directory:string|undefined,created=false,hook:undefined|(()=>Promise<void>);
 try{
  await admin.query(`CREATE ROLE ${ownerRole} NOLOGIN NOSUPERUSER NOBYPASSRLS;CREATE SCHEMA ${schema} AUTHORIZATION ${ownerRole}`);created=true;await migrate(owner);
  assert.equal((await owner.query('SELECT rolsuper FROM pg_roles WHERE rolname=current_user')).rows[0].rolsuper,false);
  await admin.query(`CREATE ROLE ${role} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT PASSWORD '${password}'`);
  const grants=(await readFile(new URL('../../deploy/cloudflare/sql/40-media-backfill-operator-grants.psql',import.meta.url),'utf8')).split('-- BEGIN CLOSED OPERATOR GRANTS')[1].split('-- END CLOSED OPERATOR GRANTS')[0];
  const q=await owner.connect();try{await q.query('BEGIN');await q.query("SELECT set_config('freedom.operator_role',$1,true),set_config('freedom.operator_schema',$2,true)",[role,schema]);await q.query(grants);await q.query('COMMIT');}catch(e){await q.query('ROLLBACK');throw e;}finally{q.release();}
  let port:string|undefined;if(proxy){await new Promise<void>(r=>proxy.listen(0,'127.0.0.1',r));const a=proxy.address();assert(a&&typeof a==='object');port=String(a.port);}
  const connection=new URL(raw);connection.username=role;connection.password=password;if(proxy){connection.hostname='127.0.0.1';connection.port=port!;connection.searchParams.delete('host');}
  const target={environment:'local' as const,database:parsed.pathname.slice(1),schema,role,releaseSha:'9'.repeat(40)},binding='synthetic-native-private-r2';
  const profile={target,logicalStore:'MEDIA',storeBindingId:binding,purposes:['member.service-cover','community.event-video','community.event-banner','community.social-thumbnail',...purposes,'member.avatar']};
  const bindings={FREEDOM_MEDIA_OPERATOR_ENABLED:'true',FREEDOM_MEDIA_OPERATOR_ENVIRONMENT:'local',FREEDOM_MEDIA_OPERATOR_RELEASE_SHA:target.releaseSha,FREEDOM_MEDIA_OPERATOR_STORE_BINDING_ID:binding,FREEDOM_MEDIA_OPERATOR_PROFILE:JSON.stringify(profile)};
  await mkdir(resolve('.wrangler'),{recursive:true});directory=await mkdtemp(resolve('.wrangler/media-operator-private-rpc-'));
  await promisify(execFile)(process.execPath,['node_modules/wrangler/bin/wrangler.js','deploy','--dry-run','--config','wrangler.media-operator.example.jsonc','--env','staging-next','--outdir',directory],{maxBuffer:1024*1024});
  const native={name:'operator',modules:true,scriptPath:join(directory,'worker.js'),compatibilityDate:'2026-09-21',compatibilityFlags:['nodejs_compat'],bindings,hyperdrives:{OPERATOR_HYPERDRIVE:connection.href},r2Buckets:{MEDIA:'synthetic-operator-private-assets'},outboundService:'no-external'};
  const bundle=await readFile(join(directory,'worker.js'),'utf8');
  const fault=`import {MediaOperator as Base} from './main.js';export class MediaOperator extends Base {constructor(ctx,env){const b=env.MEDIA;let puts=0,lost=false;super(ctx,{...env,MEDIA:{put:async(...a)=>{const result=await b.put(...a);puts++;if(env.FAULT_SECOND!=='true'||puts===2){lost=true;throw Error('synthetic unknown ACK');}return result;},get:async(...a)=>{if(lost)throw Error('synthetic unavailable readback');return b.get(...a);},head:(...a)=>b.head(...a),delete:(...a)=>b.delete(...a)}});}}export {default} from './main.js';`;
  const mutate=`import {MediaOperator as Base} from './main.js';export class MediaOperator extends Base {constructor(ctx,env){const b=env.MEDIA;super(ctx,{...env,MEDIA:{put:async(...a)=>{const result=await b.put(...a);const response=await env.AFTER_PUT.fetch('https://synthetic-io-hook.internal/');if(!response.ok)throw Error('synthetic hook failure');return result;},get:(...a)=>b.get(...a),head:(...a)=>b.head(...a),delete:(...a)=>b.delete(...a)}});}}export {default} from './main.js';`;
  const names=['operator','unknown-ack','second-unknown','mutate','cover-only','foreign-profile'];
  mf=new Miniflare(convertV4MiniflareOptions({workers:[native,
   {...native,name:'cover-only',bindings:{...bindings,FREEDOM_MEDIA_OPERATOR_PROFILE:JSON.stringify({...profile,purposes:['member.service-cover']})}},
   {...native,name:'foreign-profile',bindings:{...bindings,FREEDOM_MEDIA_OPERATOR_PROFILE:JSON.stringify({...profile,purposes:['work.private-draft']})}},
   {...native,name:'unknown-ack',scriptPath:undefined,modules:[{type:'ESModule',path:'entry.js',contents:fault},{type:'ESModule',path:'main.js',contents:bundle}]},
   {...native,name:'second-unknown',bindings:{...bindings,FAULT_SECOND:'true'},scriptPath:undefined,modules:[{type:'ESModule',path:'entry.js',contents:fault},{type:'ESModule',path:'main.js',contents:bundle}]},
   {...native,name:'mutate',scriptPath:undefined,modules:[{type:'ESModule',path:'entry.js',contents:mutate},{type:'ESModule',path:'main.js',contents:bundle}],serviceBindings:{AFTER_PUT:async()=>{await hook?.();return new Response(null,{status:204});}}},
   {name:'no-external',modules:true,script:"let calls=0;export default {fetch(r){if(new URL(r.url).pathname==='/counts')return Response.json({calls});calls++;return new Response(null,{status:503});}}",compatibilityDate:'2026-09-21'},
   {name:'caller',modules:true,script:"export default {async fetch(r,e){try{return Response.json(await e[new URL(r.url).pathname.slice(1)].execute(await r.json()));}catch(error){return Response.json({code:error.message},{status:503});}}};",compatibilityDate:'2026-09-21',serviceBindings:Object.fromEntries(names.map(n=>[n,{name:n,entrypoint:'MediaOperator'}]))}]}));await mf.ready;
  const client=await mf.getWorker('caller'),rpc=async(name:string,p:unknown)=>client.fetch('https://synthetic-private-rpc.internal/'+name,{method:'POST',body:JSON.stringify(p)});
  const plan=(purpose:Purpose|'member.avatar')=>planOperatorBackfill({target,jobId:randomUUID(),logicalStore:'MEDIA',storeBindingId:binding,migrationId:'synthetic-native-images-v1',purpose,maxRows:1,maxBytes:8388608,leaseSeconds:30});
  const approve=async(p:ReturnType<typeof plan>)=>{await owner.query("INSERT INTO media_backfill_operator_policy(role_name,environment,database_name,schema_name,release_sha,logical_store,store_binding_id,migration_id,purpose,approved_plan_sha256,allowed,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,clock_timestamp()+interval '1 hour')",[target.role,target.environment,target.database,target.schema,target.releaseSha,p.logicalStore,p.storeBindingId,p.migrationId,p.purpose,p.planSha256]);return p;};
  const baseImage=await sharp({create:{width:40,height:20,channels:3,background:'green'}}).webp().toBuffer();
  const pad=(size:number)=>{const b=Buffer.alloc(size);baseImage.copy(b);b.write('JUNK',baseImage.length,'ascii');b.writeUInt32LE(size-baseImage.length-8,baseImage.length+4);b.writeUInt32LE(size-8,4);return b;};
  const skill=pad(524288),image=pad(1048576),thumb=pad(204800),avatar=pad(131072),memberPassword='synthetic-original-session-only',savedPassword=await hashPasswordAsync(memberPassword);
  await owner.query("UPDATE domain_media_storage_policy SET mode='bridge',policy_revision='synthetic-native-private-v1',persistence_allowed=true,retained_byte_limit=33554432 WHERE purpose=ANY($1::text[])",[purposes]);
  const bucket=await mf.getR2Bucket('MEDIA','operator'),store=createR2ObjectStore(bucket as unknown as AssetR2Binding);
  async function member(community:string){const user=randomUUID(),email=user+'@native-private.invalid';await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref,onboarding_required) VALUES($1,$2,$3,'Synthetic current member',$4,$5,false)",[user,community,email,savedPassword,randomUUID()]);const session=await login(owner,email,memberPassword),actor=await authenticate(owner,session.token);return actor;}
  async function source(purpose:Purpose,published=false){
   await owner.query('TRUNCATE communities CASCADE');const community=randomUUID();await owner.query("INSERT INTO communities VALUES($1,'Synthetic original private media')",[community]);const actor=await member(community),id=randomUUID();let event:string|undefined;
   if(purpose==='skill.submission-image'){
    const project=randomUUID(),version=randomUUID();if(published){await owner.query("INSERT INTO oss_projects(project_id,community_id,owner_ref,title,description,use_notes,repository_id,repository_full_name,repository_url,relationship) VALUES($1,$2,$3,'Synthetic','Synthetic','Synthetic','123','synthetic/source','https://github.com/synthetic/source','curator')",[project,community,actor.user_id]);await owner.query("INSERT INTO oss_project_versions(version_id,project_id,repository_id,commit_sha,default_branch,repository_full_name,repository_url,readme_url,license_spdx,is_fork,archived,source_snapshot,source_sha256,facts_sha256,inspected_at) VALUES($1,$2,'123',$3,'main','synthetic/source','https://github.com/synthetic/source','https://github.com/synthetic/source/blob/main/README.md','MIT',false,false,'{}',$4,$4,clock_timestamp())",[version,project,'a'.repeat(40),'b'.repeat(64)]);}
    await owner.query("INSERT INTO skill_submissions(submission_id,community_id,owner_ref,status,payload,payload_sha256,image_bytes,grant_consumed_at,consent_to_share,project_id,project_version_id,published_at) VALUES($1,$2,$3,$4,'{\"title\":\"Synthetic original skill\"}',$5,$6,clock_timestamp(),$7,$8,$9,CASE WHEN $7 THEN clock_timestamp() END)",[id,community,actor.user_id,published?'published':'ready_for_review',hash(Buffer.from('synthetic')),skill,published,published?project:null,published?version:null]);
   }else{
    const organizer=await member(community);event=randomUUID();await owner.query("INSERT INTO community_events(event_id,community_id,organizer_ref,title,description,starts_at,ends_at,mode,location,state,visibility,event_kind) VALUES($1,$2,$3,'Synthetic ended','Synthetic',clock_timestamp()-interval '2 days',clock_timestamp()-interval '1 day','online','Synthetic','published','open','other')",[event,community,organizer.user_id]);await owner.query("INSERT INTO community_event_highlights(media_id,event_id,community_id,uploader_user_id,kind,title,orientation,byte_size,state) VALUES($1,$2,$3,$4,'photo','Synthetic|photo','landscape',$5,'active')",[id,event,community,actor.user_id,image.length]);await owner.query("INSERT INTO community_event_highlight_images(media_id,variant,bytes) VALUES($1,'image',$2),($1,'thumb',$3)",[id,image,thumb]);
   }
   await backfillLegacyScopeBatch(owner,500);await backfillLegacyScopeBatch(owner,500);return {id,community,actor,event};
  }
  async function expire(job:string){await owner.query('UPDATE media_backfill_jobs SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE job_id=$1',[job]);await owner.query('UPDATE asset_upload_intents SET lease_expires_at=LEAST(lease_expires_at,clock_timestamp()) WHERE intent_id IN(SELECT intent_id FROM media_backfill_items WHERE job_id=$1)',[job]);}
  async function unpublished(purpose:Purpose,id:string){if(purpose==='skill.submission-image'){assert.equal((await owner.query('SELECT storage_source FROM skill_submissions WHERE submission_id=$1',[id])).rows[0].storage_source,'legacy');assert.equal((await owner.query('SELECT asset_id FROM skill_submission_image_asset_targets WHERE submission_id=$1',[id])).rows[0].asset_id,null);}else{assert.equal((await owner.query('SELECT storage_source FROM community_event_highlights WHERE media_id=$1',[id])).rows[0].storage_source,'legacy');const row=(await owner.query('SELECT image_asset_id,thumb_asset_id FROM community_event_highlight_asset_targets WHERE media_id=$1',[id])).rows[0];assert.deepEqual(row,{image_asset_id:null,thumb_asset_id:null});}assert.ok((await owner.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));assert.equal((await owner.query('SELECT count(*)::int n FROM asset_objects')).rows[0].n,0);}
  for(const purpose of purposes){
   const s=await source(purpose),p=await approve(plan(purpose)),sessions=(await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n;
   for(const name of ['cover-only','foreign-profile']){const denied=await rpc(name,p);assert.equal(denied.status,503);assert.deepEqual(await denied.json(),{code:'operator_media_unavailable'});}
   const before=purpose==='skill.submission-image'?await readSubmission(owner,s.actor,s.id):await readHighlightEvent(owner,{communityId:null,viewerId:null,eventId:s.event!});
   const response=await rpc('operator',p);assert.equal(response.status,200,await response.clone().text());assert.equal((await response.json() as any).linked,1);
   if(purpose==='skill.submission-image'){
    assert.deepEqual(await readOwnIllustration(owner,s.actor,s.id,store),skill);assert.equal(await readSkillImage(owner,s.id,store),null);const after=await readSubmission(owner,s.actor,s.id);assert.equal(after.illustration_url,(before as Awaited<ReturnType<typeof readSubmission>>).illustration_url);assert.equal(after.status,'ready_for_review');const row=(await owner.query('SELECT image_bytes,grant_hash,origin_key_id,storage_source FROM skill_submissions WHERE submission_id=$1',[s.id])).rows[0];assert.deepEqual(row.image_bytes,skill);assert.equal(row.grant_hash,null);assert.equal(row.origin_key_id,null);assert.equal(row.storage_source,'asset');const peer=await member(s.community);await assert.rejects(readOwnIllustration(owner,peer,s.id,store));
   }else{
    assert.deepEqual(await highlightImageBytes(owner,s.id,'image',store),image);assert.deepEqual(await highlightImageBytes(owner,s.id,'thumb',store),thumb);const after=await readHighlightEvent(owner,{communityId:null,viewerId:null,eventId:s.event!});const urls=(detail:Awaited<ReturnType<typeof readHighlightEvent>>)=>detail.items.map(i=>({image:'image_url' in i?i.image_url:null,thumb:'thumb_url' in i?i.thumb_url:null}));assert.deepEqual(urls(after),urls(before as Awaited<ReturnType<typeof readHighlightEvent>>));assert.equal((await owner.query('SELECT aggregate_version FROM community_events WHERE event_id=$1',[s.event])).rows[0].aggregate_version,'2');assert.deepEqual((await owner.query('SELECT variant,bytes FROM community_event_highlight_images WHERE media_id=$1 ORDER BY variant',[s.id])).rows,[{variant:'image',bytes:image},{variant:'thumb',bytes:thumb}]);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,2);
   }
   const metadata=(await owner.query('SELECT profile_id,transform_version,content_sha256 FROM asset_objects ORDER BY variant')).rows;for(const o of metadata){assert.ok(o.profile_id===purpose||o.profile_id==='community.event-highlight.thumbnail');assert.ok(o.transform_version.endsWith('.legacy-bytes.v1'));assert.ok([hash(skill),hash(image),hash(thumb)].includes(o.content_sha256));}
   const afterReads=(await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n;assert.equal(afterReads,sessions+(purpose==='skill.submission-image'?1:0),'only original test login creates peer session');assert.equal((await (await rpc('operator',p)).json() as any).allSourcesMigrated,true);
   if(purpose==='skill.submission-image'){await owner.query('UPDATE sessions SET revoked_at=clock_timestamp() WHERE token_hash=$1',[s.actor.session_hash]);await assert.rejects(readOwnIllustration(owner,s.actor,s.id,store));}else{await owner.query("UPDATE community_event_highlights SET state='removed',removed_at=clock_timestamp(),removed_by_user_id=uploader_user_id WHERE media_id=$1",[s.id]);await assert.rejects(highlightImageBytes(owner,s.id,'image',store));await assert.rejects(highlightImageBytes(owner,s.id,'thumb',store));}
   const stale=await source(purpose),sp=await approve(plan(purpose));let calls=0;hook=async()=>{if(++calls!==(purpose==='community.event-highlight'?2:1))return;if(purpose==='skill.submission-image')await owner.query("UPDATE skill_submissions SET payload=' {\"title\":\"Changed source\"}'::jsonb,payload_sha256=$2 WHERE submission_id=$1",[stale.id,hash(Buffer.from('changed source'))]);else await owner.query("UPDATE community_event_highlights SET orientation='portrait' WHERE media_id=$1",[stale.id]);};const staleResponse=await rpc('mutate',sp);hook=undefined;assert.equal(staleResponse.status,200,await staleResponse.clone().text());assert.equal((await staleResponse.json() as any).stale,1);await unpublished(purpose,stale.id);
   const uncertain=await source(purpose),up=await approve(plan(purpose));const failed=await rpc(purpose==='community.event-highlight'?'second-unknown':'unknown-ack',up);assert.equal(failed.status,503);assert.deepEqual(await failed.json(),{code:'operator_media_unavailable'});await unpublished(purpose,uncertain.id);if(purpose==='community.event-highlight'){assert.deepEqual(await highlightImageBytes(owner,uncertain.id,'image'),image);assert.deepEqual(await highlightImageBytes(owner,uncertain.id,'thumb'),thumb);}else assert.deepEqual(await readOwnIllustration(owner,uncertain.actor,uncertain.id),skill);
   const identities=(await owner.query('SELECT variant,intent_id,asset_id FROM media_backfill_items WHERE job_id=$1 ORDER BY variant',[up.jobId])).rows;assert.equal(identities.length,purpose==='community.event-highlight'?2:1);assert.ok((await owner.query('SELECT state FROM asset_object_write_effects')).rows.some(r=>r.state==='unknown'));await expire(up.jobId);
   const resume=await rpc('operator',up);assert.equal(resume.status,200,await resume.clone().text());assert.equal((await resume.json() as any).linked,1);assert.deepEqual((await owner.query('SELECT variant,intent_id,asset_id FROM media_backfill_items WHERE job_id=$1 ORDER BY variant',[up.jobId])).rows,identities);assert.ok((await owner.query('SELECT fence FROM asset_upload_intents')).rows.every(r=>r.fence==='2'));assert.ok((await owner.query('SELECT state FROM asset_object_write_effects')).rows.some(r=>r.state==='unknown'),'unknown history remains a GC veto');
   if(purpose==='community.event-highlight'){assert.deepEqual(await highlightImageBytes(owner,uncertain.id,'image',store),image);assert.deepEqual(await highlightImageBytes(owner,uncertain.id,'thumb',store),thumb);assert.equal((await owner.query('SELECT aggregate_version FROM community_events')).rows[0].aggregate_version,'2');}else assert.deepEqual(await readOwnIllustration(owner,uncertain.actor,uncertain.id,store),skill);
  }
  const published=await source('skill.submission-image',true),publishedPlan=await approve(plan('skill.submission-image'));assert.equal((await rpc('operator',publishedPlan)).status,200);assert.deepEqual(await readSkillImage(owner,published.id,store),skill);await owner.query("UPDATE skill_submissions SET status='revoked',revoked_at=clock_timestamp(),consent_to_share=false WHERE submission_id=$1",[published.id]);assert.equal(await readSkillImage(owner,published.id,store),null);assert.deepEqual(await readOwnIllustration(owner,published.actor,published.id,store),skill);
  async function avatarSource(){await owner.query('TRUNCATE communities CASCADE');await owner.query("UPDATE avatar_storage_policy SET mode='bridge',policy_revision='synthetic-native-avatar-v1',persistence_allowed=true,retained_byte_limit=4194304");const community=randomUUID();await owner.query("INSERT INTO communities VALUES($1,'Synthetic historical avatar')",[community]);const actor=await member(community);await owner.query('INSERT INTO member_avatars(user_id,community_id,image_bytes) VALUES($1,$2,$3)',[actor.user_id,community,avatar]);await backfillLegacyScopeBatch(owner,500);await backfillLegacyScopeBatch(owner,500);return {actor,community};}
  const av=await avatarSource(),ap=await approve(plan('member.avatar')),beforeAvatar=await avatarMetadata(owner,av.actor),avatarSessions=(await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n;
  const avatarResult=await rpc('operator',ap);assert.equal(avatarResult.status,200,await avatarResult.clone().text());assert.equal((await avatarResult.json() as any).linked,1);const afterAvatar=await avatarMetadata(owner,av.actor);assert.equal(afterAvatar.aggregate_version,'2');assert.equal(afterAvatar.avatar_url,`/api/v1/members/${av.actor.user_id}/avatar?v=2`);assert.equal(beforeAvatar.aggregate_version,'1');assert.deepEqual((await readAvatar(owner,av.actor,av.actor.user_id,'2',store)).image_bytes,avatar);assert.deepEqual((await owner.query('SELECT image_bytes FROM member_avatars WHERE user_id=$1',[av.actor.user_id])).rows[0].image_bytes,avatar);assert.deepEqual((await owner.query('SELECT profile_id,transform_version,content_sha256 FROM asset_objects')).rows,[{profile_id:'member.avatar',transform_version:'member.avatar.legacy-bytes.v1',content_sha256:hash(avatar)}]);assert.equal((await owner.query('SELECT count(*)::int n FROM sessions')).rows[0].n,avatarSessions);
  const share=randomBytes(32).toString('base64url');await owner.query('INSERT INTO member_card_shares(user_id,community_id,share_token,enabled,include_avatar) VALUES($1,$2,$3,true,true)',[av.actor.user_id,av.community,share]);assert.deepEqual(await publicMemberAvatar(owner,share,store),avatar);await owner.query('UPDATE member_card_shares SET enabled=false WHERE user_id=$1',[av.actor.user_id]);await assert.rejects(publicMemberAvatar(owner,share,store));await owner.query('UPDATE sessions SET revoked_at=clock_timestamp() WHERE token_hash=$1',[av.actor.session_hash]);await assert.rejects(readAvatar(owner,av.actor,av.actor.user_id,'2',store));assert.equal((await (await rpc('operator',ap)).json() as any).allSourcesMigrated,true);
  const covered=(await owner.query('SELECT asset_id,scope_id,representation_id FROM assets')).rows[0],gc=await owner.connect();try{await gc.query('BEGIN');await gc.query('UPDATE member_avatars SET aggregate_version=aggregate_version+1,image_bytes=NULL WHERE user_id=$1',[av.actor.user_id]);await gc.query('UPDATE member_avatar_asset_targets SET asset_id=NULL,linked_at_version=NULL WHERE user_id=$1',[av.actor.user_id]);await gc.query("UPDATE assets SET state='retired',retired_at=clock_timestamp()-interval '2 seconds' WHERE asset_id=$1",[covered.asset_id]);await gc.query('COMMIT');}catch(e){await gc.query('ROLLBACK');throw e;}finally{gc.release();}await owner.query("UPDATE asset_maintenance_policy SET enabled=true,revision='synthetic-maintenance',orphan_retention_seconds=1,retired_retention_seconds=1,delete_lease_seconds=30,capture_seconds=30,pin_seconds=30,max_capture_objects=100");await assert.rejects(createAssetMaintenance(owner,{store,enabled:true}).claimDelete(covered.asset_id),(e:any)=>e.code==='23514'&&e.message==='Operator avatar garbage collection is not installed');assert.equal((await owner.query('SELECT count(*)::int n FROM asset_deletion_tombstones')).rows[0].n,0);assert.ok(await store.head(objectKey({assetId:covered.asset_id,scopeId:covered.scope_id,representationId:covered.representation_id})));
  const staleAvatar=await avatarSource(),as=await approve(plan('member.avatar'));hook=async()=>{const changed=Buffer.from(avatar);changed[changed.length-1]^=1;await owner.query('UPDATE member_avatars SET image_bytes=$2 WHERE user_id=$1',[staleAvatar.actor.user_id,changed]);};const staleAvatarResult=await rpc('mutate',as);hook=undefined;assert.equal(staleAvatarResult.status,200,await staleAvatarResult.clone().text());assert.equal((await staleAvatarResult.json() as any).stale,1);assert.equal((await owner.query('SELECT storage_source FROM member_avatars')).rows[0].storage_source,'legacy');assert.ok((await owner.query('SELECT state FROM assets')).rows.every(r=>r.state==='pending'));assert.equal((await owner.query('SELECT count(*)::int n FROM asset_objects')).rows[0].n,0);
  const ambiguousAvatar=await avatarSource(),au=await approve(plan('member.avatar'));assert.equal((await rpc('unknown-ack',au)).status,503);const aid=(await owner.query('SELECT intent_id,asset_id FROM media_backfill_items WHERE job_id=$1',[au.jobId])).rows[0];assert.equal((await owner.query('SELECT storage_source FROM member_avatars')).rows[0].storage_source,'legacy');assert.deepEqual((await readAvatar(owner,ambiguousAvatar.actor,ambiguousAvatar.actor.user_id,'1')).image_bytes,avatar);await expire(au.jobId);const avatarResume=await rpc('operator',au);assert.equal(avatarResume.status,200,await avatarResume.clone().text());assert.equal((await avatarResume.json() as any).linked,1);assert.deepEqual((await owner.query('SELECT intent_id,asset_id FROM media_backfill_items WHERE job_id=$1',[au.jobId])).rows,[aid]);assert.equal((await owner.query('SELECT fence FROM asset_upload_intents')).rows[0].fence,'2');assert.ok((await owner.query('SELECT state FROM asset_object_write_effects')).rows.some(r=>r.state==='unknown'));assert.deepEqual((await readAvatar(owner,ambiguousAvatar.actor,ambiguousAvatar.actor.user_id,'2',store)).image_bytes,avatar);assert.deepEqual((await owner.query('SELECT image_bytes FROM member_avatars')).rows[0].image_bytes,avatar);
  const dangerous=await avatarSource(),dp=await approve(plan('member.avatar'));await owner.query(`GRANT UPDATE(persistence_allowed) ON avatar_storage_policy TO ${role}`);try{assert.equal((await rpc('operator',dp)).status,503,'live avatar consent write capability refuses before host');assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);}finally{await owner.query(`REVOKE UPDATE(persistence_allowed) ON avatar_storage_policy FROM ${role}`);}await owner.query('UPDATE users SET active=false WHERE user_id=$1',[dangerous.actor.user_id]);const disabledAvatar=await rpc('operator',dp);assert.equal(disabledAvatar.status,200);assert.equal((await disabledAvatar.json() as any).blocked,1);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);
  assert.equal((await (await (await mf.getWorker('no-external')).fetch('https://synthetic-no-external.internal/counts')).json() as any).calls,0);assert.equal((await admin.query('SELECT count(*)::int n FROM pg_stat_activity WHERE usename=$1',[role])).rows[0].n,0);
 }finally{
  await mf?.dispose();for(const s of sockets)s.destroy();if(proxy?.listening)await new Promise<void>((r,j)=>proxy.close(e=>e?j(e):r()));await owner.end();if(created)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.query(`DROP ROLE IF EXISTS ${role};DROP ROLE IF EXISTS ${ownerRole}`);await admin.end();if(directory)await rm(directory,{recursive:true,force:true});
 }
});
