import {FakeObjectStore} from '../../packages/asset-storage/fake-store.js';
import {createSkillImageAssetService,readSkillImage} from '../../modules/assets/skill-image.js';
import {authenticate} from '../../modules/identity-membership/service.js';
import {objectKey,type ObjectMetadata} from '../../packages/asset-storage/index.js';
import {digest} from '../../packages/db/index.js';
// Native local workerd + R2 + Hyperdrive; IMAGES uses Miniflare's local low-fidelity emulator.
import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {createServer,createConnection,type Socket} from 'node:net';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {Pool} from 'pg';
import sharp from 'sharp';
import {migrate} from '../../scripts/database.js';
import {tokenHash} from '../../modules/identity-membership/service.js';
const raw=process.env.TEST_DATABASE_URL;assert(raw,'Owned fp_* TEST_DATABASE_URL required');const adminUrl=new URL(raw);
assert.match(adminUrl.pathname,/^\/fp_[a-z0-9_]+$/);assert(['127.0.0.1','localhost','[::1]'].includes(adminUrl.hostname));const socket=adminUrl.searchParams.get('host');if(socket)assert(socket.startsWith('/'));
const database=`fp_worker_skill_${process.pid}_${Date.now()}`,migrator=database+'_owner',runtimeRole=database+'_app',password=randomBytes(24).toString('hex');
function roleUrl(role:string){const url=new URL(raw!);url.pathname='/'+database;url.username=role;url.password=password;return url.href;}
const admin=new Pool({connectionString:raw}),owner=new Pool({connectionString:roleUrl(migrator)}),app=new Pool({connectionString:roleUrl(runtimeRole)});
// Pool.end() resolves after removing clients, before their sockets necessarily close.
// Wait for actual client end events before DROP FORCE, so teardown cannot kill an idle closing client.
const closedClients:Promise<void>[]=[];
for(const pool of [owner,app])pool.on('connect',client=>closedClients.push(new Promise<void>(resolve=>client.once('end',resolve))));
const sockets=new Set<Socket>(),proxy=socket?createServer(client=>{const upstream=createConnection(join(socket,'.s.PGSQL.5432'));for(const channel of [client,upstream]){sockets.add(channel);channel.on('close',()=>sockets.delete(channel));channel.on('error',()=>{client.destroy();upstream.destroy();});}client.pipe(upstream).pipe(client);}):undefined;
const origin='http://127.0.0.1:8787',community=randomUUID(),instances:Miniflare[]=[];let directory:string,tcp:string,png:Buffer,created=false,outboundCalls=0;
before(async()=>{
  await admin.query(`CREATE ROLE ${migrator} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;CREATE ROLE ${runtimeRole} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT`);
  await admin.query(`CREATE DATABASE ${database} OWNER ${migrator}`);created=true;await migrate(owner);
  const source=(await readFile('deploy/cloudflare/sql/20-runtime-grants.psql','utf8')).replace(/^\\set .*$/mg,'').replaceAll(':"runtime"','"'+runtimeRole+'"').replaceAll(":'runtime'","'"+runtimeRole+"'");
  const q=await owner.connect();try{const parts=source.split('\\gexec');for(let index=0;index<parts.length;index++){const result=await q.query(parts[index]);if(index<parts.length-1){const last=Array.isArray(result)?result.at(-1)!:result;for(const row of last.rows)await q.query(Object.values(row)[0] as string);}}}catch(error){await q.query('ROLLBACK');throw error;}finally{q.release();}
  const connection=new URL(roleUrl(runtimeRole));if(proxy){await new Promise<void>(r=>proxy.listen(0,'127.0.0.1',r));const address=proxy.address();assert(address&&typeof address==='object');connection.hostname='127.0.0.1';connection.port=String(address.port);connection.searchParams.delete('host');}tcp=connection.href;
  await owner.query("INSERT INTO communities VALUES($1,'Synthetic native skill community')",[community]);
  await owner.query("UPDATE domain_media_storage_policy SET mode='bridge' WHERE purpose='skill.submission-image'");
  directory=await mkdtemp(resolve('.wrangler/native-skill-'));await mkdir(join(directory,'assets'));await writeFile(join(directory,'assets/index.html'),'<!doctype html><title>Native skill fixture</title>');
  png=await sharp({create:{width:40,height:21,channels:3,background:'#337788'}}).png().toBuffer();
});
after(async()=>{for(const instance of instances)await instance.dispose();for(const channel of sockets)channel.destroy();if(proxy?.listening)await new Promise<void>(r=>proxy.close(()=>r()));await Promise.all([owner.end(),app.end()]);await Promise.all(closedClients);try{if(created){await admin.query(`DROP DATABASE ${database} WITH (FORCE)`);await admin.query(`DROP ROLE ${migrator},${runtimeRole}`);}}finally{await admin.end();}if(directory)await rm(directory,{recursive:true,force:true});assert.equal(outboundCalls,0);});
async function worker(options:{enabled?:string;media?:boolean;images?:boolean}={}){
  const instance=new Miniflare(convertV4MiniflareOptions({workers:[{name:'native-skill-'+randomUUID(),modules:true,scriptPath:resolve(process.env.FREEDOM_WORKERD_BUNDLE_DIR??'.wrangler/dry-run/local','worker.js'),compatibilityDate:'2026-09-21',compatibilityFlags:['nodejs_compat'],bindings:{FREEDOM_ENV:'local',APP_ORIGIN:origin,FREEDOM_REGISTRATION_COMMUNITY_ID:community,...(options.enabled===undefined?{}:{FREEDOM_SKILL_IMAGE_ENABLED:options.enabled})},hyperdrives:{HYPERDRIVE:tcp},...(options.media===false?{}:{r2Buckets:['MEDIA']}),...(options.images===false?{}:{images:{binding:'IMAGES'}}),assets:{directory:join(directory,'assets'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true},assetConfig:{not_found_handling:'none'}},outboundService:async()=>{outboundCalls++;return new Response(null,{status:503});}}]}));instances.push(instance);await instance.ready;return instance;
}
type Member={id:string;cookie:string;csrf:string};
async function member(){const id=randomUUID(),token=randomBytes(32).toString('base64url'),csrf=randomUUID();await owner.query("INSERT INTO users(user_id,community_id,email,display_name,password_hash,profession_membership_ref) VALUES($1,$2,$3,'Synthetic skill member','not-a-login',$4)",[id,community,id+'@native-skill.test',randomUUID()]);await owner.query("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at) VALUES($1,$2,$3,clock_timestamp()+interval '1 hour')",[tokenHash(token),id,csrf]);return {id,cookie:'freedom_local_session='+token,csrf};}
const call=(instance:Miniflare,path:string,init?:RequestInit)=>instance.dispatchFetch(origin+path,init as never) as unknown as Promise<Response>;
function headers(member:Member){return {Origin:origin,Cookie:member.cookie,'X-CSRF-Token':member.csrf};}
const payload=()=>({repository_url:'https://github.com/example/project',title:'Synthetic skill',description:'Owned fixture only.',use_notes:'Read the README first.',demo_url:null,relationship:'author',share_introductions:Array.from({length:100},(_,i)=>`Synthetic skill introduction number ${i+1}`),cover_image:{mime_type:'image/png',data_base64:png.toString('base64')}});
async function issue(instance:Miniflare,human:Member){const response=await call(instance,'/api/v1/me/skill-submissions',{method:'POST',headers:{...headers(human),'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:'{}'});assert.equal(response.status,201,await response.clone().text());return await response.json() as {submission:{submission_id:string};upload_grant:{token:string}};}
const send=(instance:Miniflare,id:string,token:string,body:unknown=payload())=>call(instance,'/agent-api/v1/skill-submissions/'+id,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});
test('native Worker original browser and agent grant images publish finite assets with original replay and private ACL',async()=>{
 const installed=await worker({enabled:'true'}),uninstalled=await worker(),human=await member(),foreign=await member(),draft=await issue(installed,human),id=draft.submission.submission_id,token=draft.upload_grant.token;
 assert.equal((await send(installed,id,token)).status,503);assert.equal((await owner.query('SELECT count(*)::int n FROM assets')).rows[0].n,0);await owner.query("UPDATE domain_media_storage_policy SET persistence_allowed=true,policy_revision='synthetic-native-skill-v1',retained_byte_limit=4194304 WHERE purpose='skill.submission-image'");assert.equal((await send(uninstalled,id,token)).status,503);
 for(const options of [{enabled:'false'},{enabled:'malformed'},{enabled:'true',media:false},{enabled:'true',images:false}]){assert.equal((await send(await worker(options),id,token)).status,503);assert.equal((await owner.query('SELECT count(*)::int n FROM asset_upload_intents')).rows[0].n,0);}
 const response=await send(installed,id,token);assert.equal(response.status,200,await response.clone().text());const ack=await response.json();assert.deepEqual(Object.keys(ack as object).sort(),['grant_consumed_at','review_url','status','submission_id']);assert.deepEqual(await (await send(installed,id,token)).json(),ack);assert.equal((await send(installed,id,token,{...payload(),title:'Changed skill'})).status,409);
 const bucket=await installed.getR2Bucket('MEDIA');assert.equal((await bucket.list()).objects.length,1);const row=(await owner.query("SELECT s.storage_source,s.image_bytes,s.aggregate_version,o.content_sha256 FROM skill_submissions s JOIN skill_submission_image_asset_targets t USING(submission_id) JOIN asset_objects o ON o.asset_id=t.asset_id WHERE s.submission_id=$1",[id])).rows[0];assert.equal(row.storage_source,'asset');assert.equal(row.image_bytes,null);assert.equal(row.aggregate_version,'2');const path='/api/v1/me/skill-submissions/'+id+'/illustration';const read=await call(installed,path,{headers:headers(human)});assert.equal(read.status,200,await read.clone().text());const bytes=Buffer.from(await read.arrayBuffer());assert.equal(createHash('sha256').update(bytes).digest('hex'),row.content_sha256);const imageMetadata=await sharp(bytes).metadata();assert.equal(imageMetadata.format,'webp');assert.equal(imageMetadata.width,1200);assert.equal(imageMetadata.height,630);assert.equal((await call(installed,path,{headers:headers(foreign)})).status,404);assert.equal((await call(installed,'/api/v1/skill-submissions/'+id+'/illustration')).status,404);const view=await call(installed,'/api/v1/me/skill-submissions/'+id,{headers:headers(human)});assert.equal((await view.json() as {illustration_url:string}).illustration_url,path);
 const keyResponse=await call(installed,'/api/v1/me/skill-upload-keys',{method:'POST',headers:{...headers(human),'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify({label:'Synthetic skill key'})});assert.equal(keyResponse.status,201);const key=await keyResponse.json() as {token:string;key:{key_id:string}};const agentCreate=await call(installed,'/agent-api/v1/skill-submissions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key.token,'Idempotency-Key':randomUUID()},body:'{}'});assert.equal(agentCreate.status,201,await agentCreate.clone().text());const agentDraft=await agentCreate.json() as typeof draft;const agentUpload=await send(installed,agentDraft.submission.submission_id,agentDraft.upload_grant.token);assert.equal(agentUpload.status,200,await agentUpload.clone().text());assert.equal((await bucket.list()).objects.length,2);const revoke=await call(installed,'/api/v1/me/skill-upload-keys/'+key.key.key_id+'/revoke',{method:'POST',headers:{...headers(human),'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:'{}'});assert.equal(revoke.status,200,await revoke.clone().text());assert.equal((await send(installed,agentDraft.submission.submission_id,agentDraft.upload_grant.token)).status,401);assert.equal((await bucket.list()).objects.length,2);
 const project=randomUUID(),version=randomUUID();await owner.query("INSERT INTO oss_projects(project_id,community_id,owner_ref,title,description,use_notes,repository_id,repository_full_name,repository_url,relationship) VALUES($1,$2,$3,'Synthetic skill','Owned fixture','Read README','123456','example/project','https://github.com/example/project','author')",[project,community,human.id]);await owner.query("INSERT INTO oss_project_versions(version_id,project_id,repository_id,commit_sha,default_branch,repository_full_name,repository_url,readme_url,license_spdx,is_fork,archived,source_snapshot,source_sha256,facts_sha256,inspected_at) VALUES($1,$2,'123456',repeat('a',40),'main','example/project','https://github.com/example/project','https://example.invalid/README','MIT',false,false,'{}',repeat('b',64),repeat('c',64),clock_timestamp())",[version,project]);await owner.query("UPDATE skill_submissions SET status='published',consent_to_share=true,project_id=$2,project_version_id=$3,published_at=clock_timestamp(),aggregate_version=aggregate_version+1 WHERE submission_id=$1",[id,project,version]);const publicPath='/api/v1/skill-submissions/'+id+'/illustration',publicRead=await call(installed,publicPath);assert.equal(publicRead.status,200,await publicRead.clone().text());assert.deepEqual(Buffer.from(await publicRead.arrayBuffer()),bytes);await owner.query('UPDATE users SET active=false WHERE user_id=$1',[human.id]);assert.equal((await call(installed,publicPath)).status,404);assert.equal((await send(installed,id,token)).status,401);assert.equal((await bucket.list()).objects.length,2);await owner.query('UPDATE users SET active=true WHERE user_id=$1',[human.id]);
 // Original authenticated owner context is resolved from the genuine session.
 // Mutations occur after verified-object GET, before the second SQL ACL snapshot.
 const actor=await authenticate(app,human.cookie.slice('freedom_local_session='.length)),imageObject=(await owner.query('SELECT o.*,t.scope_id FROM asset_objects o JOIN skill_submission_image_asset_targets t USING(asset_id) WHERE t.submission_id=$1',[id])).rows[0],imageKey=objectKey({scopeId:imageObject.scope_id,assetId:imageObject.asset_id,representationId:imageObject.representation_id}),imageStore=new FakeObjectStore(),imageObjectMetadata:ObjectMetadata={profileId:imageObject.profile_id,contentType:imageObject.content_type,byteSize:imageObject.byte_size,sha256:imageObject.content_sha256,transformVersion:imageObject.transform_version,policyRevision:imageObject.policy_revision};await imageStore.putImmutable(imageKey,{bytes,metadata:imageObjectMetadata});
 for(const branch of ['owner-session','owner-principal','owner-scope','public-principal','public-scope']){let pulled=0;const mutation=async()=>{pulled++;if(branch==='owner-session')await owner.query('UPDATE sessions SET revoked_at=clock_timestamp() WHERE token_hash=$1',[actor.session_hash]);else if(branch.endsWith('principal'))await owner.query("UPDATE principals SET status='disabled' WHERE user_ref=$1",[human.id]);else await owner.query("UPDATE resource_scopes SET status='disabled' WHERE scope_id=$1",[imageObject.scope_id]);};const blockedStore={head:key=>imageStore.head(key),putImmutable:(key,value)=>imageStore.putImmutable(key,value),delete:key=>imageStore.delete(key),async get(key,range){const object=await imageStore.get(key,range);await mutation();return object;}} satisfies import('../../packages/asset-storage/index.js').ObjectStore;let denied=false;try{denied=await readSkillImage(app,id,blockedStore,branch.startsWith('owner')?actor:undefined)===null;}catch(error){denied=['session_expired','principal_disabled','scope_disabled','illustration_not_found'].includes((error as {code:string}).code);}assert.equal(denied,true,branch+' must not return bytes after authority changes');assert.equal(pulled,1);await owner.query('UPDATE sessions SET revoked_at=NULL WHERE token_hash=$1',[actor.session_hash]);await owner.query("UPDATE principals SET status='active' WHERE user_ref=$1",[human.id]);await owner.query("UPDATE resource_scopes SET status='active' WHERE scope_id=$1",[imageObject.scope_id]);}
 const fenced=await issue(installed,human),fencedId=fenced.submission.submission_id,fencedToken=fenced.upload_grant.token;await owner.query("UPDATE domain_media_storage_policy SET retained_byte_limit=524288 WHERE purpose='skill.submission-image'");assert.equal((await send(installed,fencedId,fencedToken)).status,409);assert.equal((await bucket.list()).objects.length,2);await owner.query("UPDATE domain_media_storage_policy SET retained_byte_limit=4194304 WHERE purpose='skill.submission-image'");
 // A separate restricted-role SQL test interrupts immutable I/O after the
 // original grant expires. Native R2 acceptance above is independent of this fake.
 const backing=new FakeObjectStore();let writes=0;const interrupted=createSkillImageAssetService(app,{store:{delete:key=>backing.delete(key),head:key=>backing.head(key),get:(key,range)=>backing.get(key,range),async putImmutable(key,value){writes++;const result=await backing.putImmutable(key,value);await owner.query("UPDATE skill_submissions SET grant_expires_at=clock_timestamp()-interval '1 second' WHERE submission_id=$1",[fencedId]);return result;}}});const rawPayload=payload(),{cover_image:_,...content}=rawPayload;const normalized={payload:content as import('../../modules/skill-submissions/payload.js').NormalizedSubmission['payload'],payload_sha256:digest({payload:content,image:'synthetic expiry hook'}),image:bytes};await assert.rejects(interrupted.stage({user_id:human.id,community_id:community,submission_id:fencedId,grant_hash:tokenHash(fencedToken)},normalized),e=>(e as {code:string}).code==='upload_grant_invalid');assert.equal(writes,1);const unchanged=(await owner.query('SELECT status,grant_consumed_at,image_bytes FROM skill_submissions WHERE submission_id=$1',[fencedId])).rows[0];assert.equal(unchanged.status,'awaiting_upload');assert.equal(unchanged.grant_consumed_at,null);assert.equal(unchanged.image_bytes,null);assert.equal((await owner.query("SELECT count(*)::int n FROM assets WHERE state='ready'")).rows[0].n,2);assert.equal((await owner.query('SELECT count(*)::int n FROM scoped_command_receipts')).rows[0].n,0,'No fabricated member-session grant receipts.');
 await assert.rejects(app.query("UPDATE domain_media_storage_policy SET persistence_allowed=true WHERE purpose='skill.submission-image'"),e=>(e as {code:string}).code==='42501');await assert.rejects(app.query("UPDATE skill_submissions SET image_bytes=$2 WHERE submission_id=$1",[id,png]),e=>(e as {code:string}).code==='23514');await assert.rejects(app.query('UPDATE skill_submission_image_asset_targets SET owner_user_id=$2 WHERE submission_id=$1',[id,foreign.id]),e=>(e as {code:string}).code==='23514');
});
