import {createHash} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {MEDIA_SOURCES,inventoryMedia,validateInventoryTarget,type InventoryTarget,type MediaInventoryReport,type MediaSourceSpec,type MediaProfileId} from './inventory.js';
import {objectKey,readVerifiedObject,type ObjectStore,type ObjectMetadata} from '../asset-storage/index.js';
const MAX=20971520,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export class MediaVerifyError extends Error {readonly code='media_verify_unavailable';constructor(){super('media content verification is unavailable');this.name='MediaVerifyError';}}
const fail=()=>new MediaVerifyError(),hash=(value:Uint8Array|string)=>createHash('sha256').update(value).digest('hex');
const registryHash=hash(JSON.stringify(MEDIA_SOURCES));
export interface VerifyCursor {readonly format:'freedom.media-verify-cursor/v1';readonly targetHash:string;readonly registryHash:string;readonly inventoryHash:string;readonly sourceIndex:number;readonly afterKey:readonly string[]|null;}
export interface VerifiedMediaRecord {readonly profileId:MediaProfileId;readonly key:readonly string[];readonly source:'legacy'|'asset';readonly byteSize:number|null;readonly sha256:string|null;readonly objectSha256:string|null;readonly objectByteSize:number|null;readonly bindingSha256:string;readonly status:string;readonly anomalies:readonly string[];readonly delta:'new'|'unchanged'|'changed'|'not_compared';readonly provenance:'actual_source_sha256'|'actual_object_full_sha256'|'not_content_verified';}
export interface MediaVerifyOptions {readonly target:InventoryTarget;readonly limits?:{readonly maxRows?:number;readonly maxBytes?:number;readonly statementTimeoutMs?:number;readonly maxDurationMs?:number};readonly cursor?:VerifyCursor;readonly baselineInventory?:MediaInventoryReport;readonly baselineRecords?:readonly Pick<VerifiedMediaRecord,'profileId'|'key'|'source'|'byteSize'|'sha256'|'objectSha256'|'bindingSha256'>[];}
const pointers:Partial<Record<MediaProfileId,{table:string;key:string;variant:string;domain:string;version:string}>>={
 'member.avatar':{table:'member_avatar_asset_targets',key:'user_id',variant:'avatar',domain:'member_avatars',version:'aggregate_version'},
 'member.service-cover':{table:'member_service_cover_asset_targets',key:'service_id',variant:'cover',domain:'member_services',version:'aggregate_version'},
 'community.event-banner':{table:'community_event_banner_asset_targets',key:'event_id',variant:'banner',domain:'community_events',version:'aggregate_version'},
 'community.social-thumbnail':{table:'community_social_thumbnail_asset_targets',key:'post_id',variant:'thumbnail',domain:'community_social_posts',version:'media_version'},
 'community.event-video':{table:'community_event_video_asset_targets',key:'event_id',variant:'video',domain:'community_events',version:'aggregate_version'},
};
const q=(v:string)=>{if(!/^[a-z_][a-z0-9_]{0,62}$/.test(v))throw fail();return '"'+v+'"';};
const table=(schema:string,name:string)=>q(schema)+'.'+q(name);
const inventoryHash=(r:MediaInventoryReport)=>hash(JSON.stringify(r.profiles));
const targetHash=(t:InventoryTarget)=>hash(JSON.stringify(t));
function keyValid(key:readonly string[],s:MediaSourceSpec){return key.length===s.keyColumns.length&&UUID.test(key[0]??'')&&(key.length===1||(typeof key[1]==='string'&&/^[a-zA-Z0-9_-]{1,64}$/.test(key[1])));}
function validate(raw:MediaVerifyOptions){
 if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!['target','limits','cursor','baselineInventory','baselineRecords'].includes(k)))throw fail();
 for(const key of ['limits','cursor','baselineInventory','baselineRecords'] as const)if(raw[key]===null)throw fail();
 const target=validateInventoryTarget(raw.target),limits=raw.limits??{};if(typeof limits!=='object'||Array.isArray(limits))throw fail();if(Object.keys(limits).some(k=>!['maxRows','maxBytes','statementTimeoutMs','maxDurationMs'].includes(k)))throw fail();
 const maxRows=limits.maxRows??16,maxBytes=limits.maxBytes??67108864,timeout=limits.statementTimeoutMs??10000,duration=limits.maxDurationMs??30000;
 if(!Number.isSafeInteger(maxRows)||maxRows<1||maxRows>128||!Number.isSafeInteger(maxBytes)||maxBytes<1||maxBytes>67108864||!Number.isSafeInteger(timeout)||timeout<1||timeout>30000||!Number.isSafeInteger(duration)||duration<1||duration>60000)throw fail();
 const cursor=raw.cursor;if(cursor&&(Object.keys(cursor).length!==6||cursor.format!=='freedom.media-verify-cursor/v1'||cursor.targetHash!==targetHash(target)||cursor.registryHash!==registryHash||!/^[0-9a-f]{64}$/.test(cursor.inventoryHash)||!Number.isInteger(cursor.sourceIndex)||cursor.sourceIndex<0||cursor.sourceIndex>=MEDIA_SOURCES.length||(cursor.afterKey!==null&&(!Array.isArray(cursor.afterKey)||!keyValid(cursor.afterKey,MEDIA_SOURCES[cursor.sourceIndex])))))throw fail();
 if(raw.baselineInventory&&(targetHash(validateInventoryTarget(raw.baselineInventory.target))!==targetHash(target)||raw.baselineInventory.format!=='freedom.media-inventory/v1'))throw fail();
 const baseline=raw.baselineRecords??[];if(!Array.isArray(baseline)||baseline.length>128)throw fail();const seen=new Set<string>();for(const r of baseline){const s=MEDIA_SOURCES.find(s=>s.profileId===r.profileId);if(!s||!Array.isArray(r.key)||!keyValid(r.key,s)||!['legacy','asset'].includes(r.source)||(r.byteSize!==null&&(!Number.isInteger(r.byteSize)||r.byteSize<0||r.byteSize>MAX))||(!/^[0-9a-f]{64}$/.test(r.bindingSha256))||[r.sha256,r.objectSha256].some(h=>h!==null&&(typeof h!=='string'||!/^[0-9a-f]{64}$/.test(h))))throw fail();const id=JSON.stringify([r.profileId,r.key]);if(seen.has(id))throw fail();seen.add(id);}
 return {target,maxRows,maxBytes,timeout,duration,cursor:cursor?Object.freeze({...cursor,afterKey:cursor.afterKey?Object.freeze([...cursor.afterKey]):null}):undefined,baseline:baseline.map(r=>Object.freeze({profileId:r.profileId,key:Object.freeze([...r.key]),source:r.source,byteSize:r.byteSize,sha256:r.sha256,objectSha256:r.objectSha256,bindingSha256:r.bindingSha256})),baselineInventoryHash:raw.baselineInventory?inventoryHash(raw.baselineInventory):undefined};
}
async function columns(c:PoolClient,schema:string,name:string,required:readonly string[]){const r=await c.query("SELECT a.attname::text AS name FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class t ON t.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=$1 AND t.relname=$2 AND t.relkind IN ('r','p') AND NOT t.relrowsecurity AND a.attnum>0 AND NOT a.attisdropped",[schema,name]);const set=new Set(r.rows.map(x=>x.name));return required.every(x=>set.has(x))?set:null;}
async function guard(c:PoolClient,t:InventoryTarget){const r=(await c.query("SELECT current_database() AS database,current_user AS role,rolsuper,rolbypassrls,current_setting('transaction_read_only') AS readonly FROM pg_catalog.pg_roles WHERE rolname=current_user")).rows[0];if(!r||r.database!==t.database||r.role!==t.role||r.rolsuper!==false||r.rolbypassrls!==false||r.readonly!=='on')throw fail();}
interface Shape {source:MediaSourceSpec;hasStorage:boolean;pointer:boolean;}
async function shape(c:PoolClient,t:InventoryTarget,s:MediaSourceSpec):Promise<Shape|null>{const cols=await columns(c,t.schema,s.table,[...s.keyColumns,s.byteColumn,...(s.mime.provenance==='mime_column'?[s.mime.column]:[])]);if(!cols)return null;
 if(s.parent&&!await columns(c,t.schema,s.parent.table,[s.parent.keyColumn,s.parent.kindColumn,s.parent.stateColumn]))return null;
 const p=pointers[s.profileId];let pointer=false;if(cols.has('storage_source')){if(!p||!await columns(c,t.schema,p.table,[p.key,'asset_id','scope_id','linked_at_version','purpose'])||!await columns(c,t.schema,p.domain,[p.key,p.version])||!await columns(c,t.schema,'assets',['asset_id','scope_id','purpose','state'])||!await columns(c,t.schema,'asset_objects',['asset_id','representation_id','content_type','byte_size','content_sha256','transform_version','policy_revision','profile_id','purpose','variant']))return null;pointer=true;}
 return {source:s,hasStorage:cols.has('storage_source'),pointer};}
function select(t:InventoryTarget,sh:Shape){const s=sh.source,keys=s.keyColumns.map(k=>k===s.variantColumn?`COALESCE(b.${q(k)}::text,'__null_variant__')`:`b.${q(k)}::text`),mime=s.mime.provenance==='mime_column'?`b.${q(s.mime.column)}::text`:"'image/webp'::text";let from=`${table(t.schema,s.table)} b`,extra='';
 if(s.parent){const p=s.parent;from+=` LEFT JOIN ${table(t.schema,p.table)} p ON p.${q(p.keyColumn)}=b.${q(p.keyColumn)}`;extra+=`,p.${q(p.keyColumn)}::text AS parent_id,p.${q(p.kindColumn)}::text AS parent_kind,p.${q(p.stateColumn)}::text AS parent_state,(SELECT count(*)::int FROM ${table(t.schema,s.table)} pairs WHERE pairs.${q(p.keyColumn)}=b.${q(p.keyColumn)} AND pairs.${q(s.variantColumn!)} IN ('image','thumb') AND octet_length(pairs.${q(s.byteColumn)})>0) AS pair_count`;}
 if(sh.pointer){const p=pointers[s.profileId]!;from+=` LEFT JOIN ${table(t.schema,p.table)} target ON target.${q(p.key)}=b.${q(p.key)} LEFT JOIN ${table(t.schema,p.domain)} domain ON domain.${q(p.key)}=b.${q(p.key)} LEFT JOIN ${table(t.schema,'assets')} a ON a.asset_id=target.asset_id AND a.scope_id=target.scope_id AND a.purpose=target.purpose AND a.purpose='${s.profileId}' AND a.state='ready' LEFT JOIN ${table(t.schema,'asset_objects')} o ON o.asset_id=a.asset_id AND o.purpose=a.purpose AND o.variant='${p.variant}'`;extra+=`,target.asset_id::text AS asset_id,target.scope_id::text AS scope_id,target.linked_at_version::text AS linked_version,domain.${q(p.version)}::text AS domain_version,o.representation_id::text AS representation_id,o.content_type,o.byte_size,o.content_sha256,o.transform_version,o.policy_revision,o.profile_id`;}
 return {keys,from,fields:`${keys.map((k,i)=>k+' AS key'+i).join(',')},octet_length(b.${q(s.byteColumn)}) AS byte_size_source,${mime} AS mime,${sh.hasStorage?'b.storage_source::text':"'legacy'::text"} AS source${extra}`};}
const rowKey=(r:any,s:MediaSourceSpec)=>s.keyColumns.map((_,i)=>r['key'+i]);
function identity(r:any){return JSON.stringify(r);}
async function metadata(c:PoolClient,t:InventoryTarget,sh:Shape,key:readonly string[]){const query=select(t,sh);return (await c.query(`SELECT ${query.fields} FROM ${query.from} WHERE ${query.keys.map((k,i)=>`${k}=$${i+1}`).join(' AND ')}`,[...key])).rows[0];}
async function bytes(c:PoolClient,t:InventoryTarget,s:MediaSourceSpec,key:readonly string[],cap:number){const r=(await c.query(`SELECT CASE WHEN octet_length(${q(s.byteColumn)}) BETWEEN 1 AND $${key.length+1} THEN ${q(s.byteColumn)} END AS content FROM ${table(t.schema,s.table)} WHERE ${s.keyColumns.map((k,i)=>`${q(k)}::text=$${i+1}`).join(' AND ')}`,[...key,cap])).rows[0];return r?.content as Buffer|null|undefined;}
function objectMetadata(r:any):ObjectMetadata {return {contentType:r.content_type,byteSize:Number(r.byte_size),sha256:r.content_sha256,transformVersion:r.transform_version,policyRevision:r.policy_revision,...(r.profile_id?{profileId:r.profile_id}:{})};}
/** Transaction queries use both a per-query cap and the remaining batch wall
 * clock. Proxy is local only; the caller's pooled client is never mutated. */
async function boundedConnect(pool:Pool,deadline:number,timeout:number):Promise<PoolClient>{
 let timer:ReturnType<typeof setTimeout>|undefined,expired=false;const pending=pool.connect().then(client=>{if(expired)client.release();return client;});let client:PoolClient;
 try{client=await Promise.race([pending,new Promise<never>((_,reject)=>{timer=setTimeout(()=>{expired=true;reject(fail());},Math.max(1,deadline-Date.now()));})]);}finally{if(timer)clearTimeout(timer);}
 return new Proxy(client,{get(target,property){if(property==='query')return async(sql:string,params?:unknown[])=>{if(typeof sql!=='string')throw fail();if(/^(COMMIT|ROLLBACK|BEGIN)/.test(sql))return target.query(sql,params);const remaining=deadline-Date.now();if(remaining<=0)throw fail();const cap=Math.max(1,Math.min(timeout,remaining));if(sql.startsWith('SET LOCAL statement_timeout'))return target.query(`SET LOCAL statement_timeout='${cap}'`);await target.query(`SET LOCAL statement_timeout='${cap}'`);return target.query(sql,params);};const value=Reflect.get(target,property,target);return typeof value==='function'?value.bind(target):value;}});
}
/** No writes exposed, late read bodies cancelled after a deadline. */
function readDeadlineStore(store:ObjectStore,deadline:number,onBytes:(length:number)=>void):ObjectStore {
 async function timed<T>(pending:Promise<T>,late?:(value:T)=>void):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined,expired=false;const task=pending.then(value=>{if(expired)late?.(value);return value;});try{return await Promise.race([task,new Promise<never>((_,reject)=>{timer=setTimeout(()=>{expired=true;reject(fail());},Math.max(1,deadline-Date.now()));})]);}finally{if(timer)clearTimeout(timer);}}
 return {putImmutable:async()=>{throw fail();},delete:async()=>{throw fail();},head:key=>timed(store.head(key)),async get(key,range){const value=await timed(store.get(key,range),value=>{value?.body.cancel().catch(()=>{});});if(!value)return null;const reader=value.body.getReader();let closed=false;const release=()=>{if(!closed){closed=true;reader.releaseLock();}};return {...value,body:new ReadableStream<Uint8Array>({async pull(controller){try{const next=await timed(reader.read());if(next.done){release();controller.close();}else {onBytes(next.value.length);controller.enqueue(next.value);}}catch{await reader.cancel().catch(()=>{});release();controller.error(fail());}},async cancel(reason){try{await reader.cancel(reason);}finally{release();}}},{highWaterMark:0})};}};
}
/** Bounded READ ONLY batches. Resume is a scan position, not an atomic snapshot
 * or authorization to migrate. IDs/digests are sensitive operator evidence. */
async function executeVerifyMedia(pool:Pool,raw:MediaVerifyOptions,store?:ObjectStore){const opts=validate(raw),{target}=opts,deadline=Date.now()+opts.duration;let current:MediaInventoryReport;try{current=await inventoryMedia({connect:()=>boundedConnect(pool,deadline,opts.timeout)} as Pool,target);}catch{throw fail();}const globalAnomaly=current.profiles.some(p=>p.status==='source_unavailable'||(p.counts&&p.counts.oversizeCount!=='0')||(p.unknownMimeCount!==null&&p.unknownMimeCount!=='0')||(p.highlightDetails&&[p.highlightDetails.unknownVariantCount,p.highlightDetails.orphanCount,p.highlightDetails.removedParentCount,p.highlightDetails.incompleteActivePairCount,p.highlightDetails.thumb.counts.oversizeCount].some(n=>n!=='0')));const invHash=inventoryHash(current),initialHash=opts.cursor?.inventoryHash??(opts.baselineInventoryHash??invHash),inventoryDrift=initialHash!==invHash;
 const records:VerifiedMediaRecord[]=[],unavailable:MediaProfileId[]=[],removedBaseline:{profileId:MediaProfileId;key:readonly string[]}[]=[];let consumed=0,limitReason:'row_limit'|'byte_limit'|'duration_limit'|null=null,index=opts.cursor?.sourceIndex??0,after:readonly string[]|null=opts.cursor?.afterKey??null,stop=false,scanComplete=false;
 let c:PoolClient;try{c=await boundedConnect(pool,deadline,opts.timeout);}catch{throw fail();}let destroy=false;
 try{await c.query('BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY');await c.query(`SET LOCAL statement_timeout='${opts.timeout}'`);await c.query("SET LOCAL lock_timeout='3000'");await guard(c,target);
 for(;index<MEDIA_SOURCES.length&&!stop;index++){
  if(Date.now()>=deadline){limitReason='duration_limit';stop=true;break;}
  const s=MEDIA_SOURCES[index],sh=await shape(c,target,s);if(!sh){unavailable.push(s.profileId);after=null;continue;}const query=select(target,sh),params:any[]=[];let where='';if(after){params.push(...after);where=`WHERE (${query.keys.join(',')}) > (${after.map((_,i)=>'$'+(i+1)).join(',')})`;}params.push(opts.maxRows-records.length+1);const rows=(await c.query(`SELECT ${query.fields} FROM ${query.from} ${where} ORDER BY ${query.keys.join(',')} LIMIT $${params.length}`,params)).rows;
  for(const row of rows){if(Date.now()>=deadline){limitReason='duration_limit';stop=true;break;}if(records.length>=opts.maxRows){limitReason='row_limit';stop=true;break;}const key=rowKey(row,s);if(!keyValid(key,s)||!['legacy','asset'].includes(row.source))throw fail();const anomalies:string[]=[],variant=s.variantColumn?key[1]:null,cap=s.variants.find(v=>v.name===variant)?.writerMaxBytes??s.maxBytes,size=row.byte_size_source as number|null;
   if(variant&&!s.variants.some(v=>v.name===variant))anomalies.push('invalid_variant');if(s.parent){if(!row.parent_id)anomalies.push('missing_parent');else if(row.parent_state===s.parent.removedState)anomalies.push('removed_parent');if(!s.parent.kinds.includes(row.parent_kind??''))anomalies.push('invalid_parent_kind');if(row.parent_state===s.parent.activeState&&s.parent.pairedKinds.includes(row.parent_kind)&&row.pair_count!==2)anomalies.push('incomplete_variant_pair');}
   if(size!==null&&(!Number.isInteger(size)||size<0))throw fail();if(size===0)anomalies.push('empty_source');if(size!==null&&size>cap)anomalies.push('oversize_source');if(s.mime.provenance==='mime_column'&&!s.mime.allowed.includes(row.mime))anomalies.push('invalid_mime');
   const canRead=size!==null&&size>0&&size<=cap&&!anomalies.includes('invalid_variant'),assetSize=row.source==='asset'&&row.byte_size?Number(row.byte_size):0;if(!Number.isSafeInteger(assetSize)||assetSize<0||assetSize>MAX)throw fail();const need=(canRead?size!*2:0)+(row.source==='asset'&&store?assetSize:0);if(consumed+need>opts.maxBytes){limitReason='byte_limit';stop=true;break;}
   let sha:string|null=null,objectSha:string|null=null,objectByteSize:number|null=null,status='legacy_verified',provenance:VerifiedMediaRecord['provenance']='not_content_verified';
   if(canRead){const source=await bytes(c,target,s,key,Math.min(size!,opts.maxBytes-consumed));if(source)consumed+=source.length;if(!source||source.length!==size){anomalies.push('source_drift');}else {sha=hash(source);provenance='actual_source_sha256';}}
   if(row.source==='legacy'){if(size===null)status=s.nullableBytes?'source_absent':'invalid_source';else if(anomalies.length)status='source_anomaly';}
   else {status='asset_verification_not_run';if(!row.asset_id||!row.scope_id||!row.representation_id||!row.domain_version||!row.linked_version||(s.profileId==='member.avatar'?row.linked_version!==row.domain_version:BigInt(row.linked_version)>BigInt(row.domain_version))){status='asset_pointer_invalid';anomalies.push('invalid_asset_pointer');}else if(store){try{const expected=objectMetadata(row);if((s.profileId==='member.avatar'?expected.profileId!==undefined:expected.profileId!==s.profileId)||expected.byteSize>cap||expected.contentType!==row.mime||expected.transformVersion!==(s.profileId==='member.avatar'?'avatar.webp.v1':s.profileId+'.legacy-bytes.v1'))throw fail();const full=await readVerifiedObject(readDeadlineStore(store,deadline,length=>{if(length>opts.maxBytes-consumed)throw fail();consumed+=length;}),objectKey({scopeId:row.scope_id,assetId:row.asset_id,representationId:row.representation_id}),expected);objectSha=hash(full.bytes);objectByteSize=full.bytes.length;provenance='actual_object_full_sha256';status='asset_verified';}catch{status='asset_object_unavailable_or_corrupt';anomalies.push('object_unverified');}}}
   const again=await metadata(c,target,sh,key);if(!again||identity(again)!==identity(row))anomalies.push('source_drift');if(canRead){const source=await bytes(c,target,s,key,Math.min(size!,opts.maxBytes-consumed));if(source)consumed+=source.length;if(!source||hash(source)!==sha)anomalies.push('source_drift');}
   if(anomalies.includes('source_drift'))status='source_drift';const prior=opts.baseline.find(r=>r.profileId===s.profileId&&JSON.stringify(r.key)===JSON.stringify(key));const delta=prior?prior.source===row.source&&prior.byteSize===size&&prior.sha256===sha&&prior.objectSha256===objectSha&&prior.bindingSha256===hash(identity(row))?'unchanged':'changed':opts.baseline.length?'new':'not_compared';records.push(Object.freeze({profileId:s.profileId,key:Object.freeze(key),source:row.source,byteSize:size,sha256:sha,objectSha256:objectSha,objectByteSize,bindingSha256:hash(identity(row)),status,anomalies:Object.freeze([...new Set(anomalies)]),delta,provenance}));after=key;
  }
  if(stop)break;after=null;
 }
 for(const prior of opts.baseline){const s=MEDIA_SOURCES.find(s=>s.profileId===prior.profileId)!,sh=await shape(c,target,s);if(sh&&!await metadata(c,target,sh,prior.key))removedBaseline.push({profileId:prior.profileId,key:prior.key});}
 scanComplete=index>=MEDIA_SOURCES.length;await c.query('COMMIT');
 }catch{try{await c.query('ROLLBACK');}catch{destroy=true;}throw fail();}finally{c.release(destroy);}
 const cursor:VerifyCursor|null=scanComplete?null:Object.freeze({format:'freedom.media-verify-cursor/v1',targetHash:targetHash(target),registryHash,inventoryHash:initialHash,sourceIndex:index,afterKey:after});
 return Object.freeze({format:'freedom.media-verify/v1',target,releaseBinding:'operator_declared_not_runtime_verified',readOnly:true,dataMoved:false,restore:'not_run',migrationReadiness:'not_evaluated',scanComplete,verificationCompleteness:globalAnomaly||unavailable.length||records.some(r=>r.anomalies.length>0||r.status!=='legacy_verified'&&r.status!=='asset_verified'&&r.status!=='source_absent')?'incomplete':'bounded_batch_verified',contentValidation:'not_run',mimeProvenance:'declared_by_stored_column_or_known_writer_not_decoded',pointInTimeSnapshot:false,contentVerificationScope:'bounded_batch_only',limitReason,progress:records.length>0,inventoryDrift,inventoryAnomalies:current.profiles.map(p=>({profileId:p.profileId,counts:p.counts,highlightDetails:p.highlightDetails})),sourceUnavailable:Object.freeze(unavailable),bytesRead:consumed,limits:{maxRows:opts.maxRows,maxBytes:opts.maxBytes,statementTimeoutMs:opts.timeout,maxDurationMs:opts.duration},records:Object.freeze(records),removedBaseline:Object.freeze(removedBaseline),cursor});
}

/** Errors never carry connection strings, content or upstream diagnostics. */
export async function verifyMedia(pool:Pool,options:MediaVerifyOptions,store?:ObjectStore){try{return await executeVerifyMedia(pool,options,store);}catch{throw fail();}}
/** Validates a plan without opening a connection or reading environment. */
export function planMediaVerify(options:MediaVerifyOptions){try{const o=validate(options);return Object.freeze({target:o.target,limits:{maxRows:o.maxRows,maxBytes:o.maxBytes,statementTimeoutMs:o.timeout,maxDurationMs:o.duration},cursor:o.cursor??null,baselineRecordsCount:o.baseline.length,baselineInventoryHash:o.baselineInventoryHash??null,registryHash,execution:'not_run',dataMoved:false});}catch{throw fail();}}
