import type {Actor} from '../identity-membership/service.js';
import {withMemberScope} from '../../packages/resource-scopes/index.js';
import {assertCurrentSessionClock} from '../../packages/db/member-session.js';
import {repositoryKey} from '../skill-submissions/repository-match.js';
import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {digest,transaction} from '../../packages/db/index.js';
import {Problem,requireCondition} from '../../packages/shared/problem.js';
import {objectKey,sha256,prepareLegacyMediaRepresentation,writeVerifiedObject,verifyObject,readVerifiedObject,type ObjectStore,type ObjectMetadata} from '../../packages/asset-storage/index.js';
import type {NormalizedSubmission} from '../skill-submissions/payload.js';
import {lockSkillUploadGrant,assertSkillUploadGrantClock,type SkillUploadGrant} from '../skill-submissions/upload-authority.js';
export async function skillImageStorageMode(q:Pick<PoolClient,'query'>){const row=(await q.query("SELECT mode FROM domain_media_storage_policy WHERE purpose='skill.submission-image' FOR SHARE")).rows[0];requireCondition(row,503,'media_upload_unavailable','內容上傳暫時無法使用。');return row.mode as 'legacy'|'bridge'|'r2_only';}
export async function resolveSkillImageUploadPolicy(q:PoolClient){const row=(await q.query("SELECT mode,policy_revision,persistence_allowed,retained_byte_limit::text quota FROM domain_media_storage_policy WHERE purpose='skill.submission-image' FOR SHARE")).rows[0];requireCondition(row&&row.mode!=='legacy'&&row.persistence_allowed===true&&typeof row.policy_revision==='string'&&typeof row.quota==='string'&&BigInt(row.quota)>=524288n,503,'media_upload_unavailable','內容上傳暫時無法使用。');return Object.freeze({revision:row.policy_revision as string,platformPersistenceAllowed:true,quota:row.quota as string});}
async function mapping(q:PoolClient,grant:SkillUploadGrant){
 await q.query('INSERT INTO principals(user_ref) VALUES($1) ON CONFLICT(user_ref) DO NOTHING',[grant.user_id]);const p=(await q.query("SELECT principal_id,status FROM principals WHERE user_ref=$1 FOR SHARE",[grant.user_id])).rows[0];requireCondition(p?.status==='active',403,'principal_disabled','這個身分目前無法使用。');
 await q.query("INSERT INTO resource_scopes(kind,owner_principal_id) VALUES('personal',$1) ON CONFLICT(owner_principal_id) DO NOTHING",[p.principal_id]);const s=(await q.query("SELECT scope_id,status FROM resource_scopes WHERE kind='personal' AND owner_principal_id=$1 FOR SHARE",[p.principal_id])).rows[0];requireCondition(s?.status==='active',403,'scope_disabled','這個資源範圍目前無法使用。');return {principal:p.principal_id as string,scope:s.scope_id as string};
}
async function requireSkillImageCapacity(q:PoolClient,grant:SkillUploadGrant,scope:string,quota:string,reserve:number){const used=(await q.query("SELECT COALESCE(sum(COALESCE(o.byte_size,i.reserved_bytes,524288)::bigint),0)::text n FROM assets a LEFT JOIN asset_objects o USING(asset_id) LEFT JOIN asset_upload_intents i USING(asset_id) WHERE a.scope_id=$1 AND a.purpose='skill.submission-image'",[scope])).rows[0];const legacy=(await q.query('SELECT COALESCE(sum(octet_length(image_bytes)),0)::text n FROM skill_submissions WHERE owner_ref=$1 AND community_id=$2',[grant.user_id,grant.community_id])).rows[0];requireCondition(BigInt(used.n)+BigInt(legacy.n)+BigInt(reserve)<=BigInt(quota),409,'asset_retained_quota','內容儲存容量已達上限。');}
async function assertSkillImageLeaseClock(q:PoolClient,intent:string){const row=(await q.query('SELECT expires_at>clock_timestamp() AND lease_expires_at>clock_timestamp() AS live FROM asset_upload_intents WHERE intent_id=$1',[intent])).rows[0];requireCondition(row?.live,409,'asset_lease_stale','上傳租約已失效。');}
interface Stage {readonly intent:string;readonly asset:string;readonly representation:string;readonly scope:string;readonly principal:string;readonly fence:string;readonly lease:string;readonly version:string;readonly policy:string;readonly digest:string;readonly metadata:ObjectMetadata;}
/** Finite upload-grant bridge: the original credential kernel supplies authority,
 * never a fabricated browser session or caller-selected scope. */
export function createSkillImageAssetService(pool:Pool,{store}:{readonly store:ObjectStore}){
 const stages=new WeakMap<object,Stage>();
 async function stage(grant:SkillUploadGrant,normalized:NormalizedSubmission):Promise<object|null>{
  grant=Object.freeze({...grant});if(!normalized.image)return null;const bytes=Buffer.from(normalized.image),sourceHash=await sha256(bytes),key=digest({purpose:'skill.submission-image',grant:grant.grant_hash,id:grant.submission_id,payload:normalized.payload_sha256});
  const snapshot=await transaction(pool,async q=>{
   const current=await lockSkillUploadGrant(q,grant);if(current.grant_consumed_at){requireCondition(current.payload_sha256===normalized.payload_sha256,409,'upload_grant_consumed','這份上傳授權已使用。');return null;}
   requireCondition(current.status==='awaiting_upload',409,'submission_not_awaiting_upload','這份草稿目前不能上傳。');if(current.seed)requireCondition(repositoryKey(current.seed.repository_url)===repositoryKey(normalized.payload.repository_url),422,'repository_mismatch','請上傳這份草稿的同一個儲存庫內容。');const mapped=await mapping(q,grant),policy=await resolveSkillImageUploadPolicy(q);
   await q.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['asset.quota/v1/'+mapped.scope+'/skill.submission-image']);
   await q.query('INSERT INTO skill_submission_image_asset_targets(submission_id,community_id,scope_id,owner_principal_id,owner_user_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[grant.submission_id,grant.community_id,mapped.scope,mapped.principal,grant.user_id]);
   let row=(await q.query('SELECT * FROM asset_upload_intents WHERE owner_principal_id=$1 AND scope_id=$2 AND prepare_key=$3 FOR UPDATE',[mapped.principal,mapped.scope,key])).rows[0];
   if(!row){const used=(await q.query("SELECT COALESCE(sum(COALESCE(o.byte_size,i.reserved_bytes,524288)::bigint),0)::text n FROM assets a LEFT JOIN asset_objects o USING(asset_id) LEFT JOIN asset_upload_intents i USING(asset_id) WHERE a.scope_id=$1 AND a.purpose='skill.submission-image'",[mapped.scope])).rows[0];const legacy=(await q.query('SELECT COALESCE(sum(octet_length(image_bytes)),0)::text n FROM skill_submissions WHERE owner_ref=$1 AND community_id=$2',[grant.user_id,grant.community_id])).rows[0];requireCondition(BigInt(used.n)+BigInt(legacy.n)+524288n<=BigInt(policy.quota),409,'asset_retained_quota','內容儲存容量已達上限。');const pending=(await q.query("SELECT count(*)::int n FROM asset_upload_intents WHERE scope_id=$1 AND purpose='skill.submission-image' AND state<>'finalized' AND expires_at>clock_timestamp()",[mapped.scope])).rows[0];requireCondition(pending.n<3,409,'asset_upload_quota','進行中的上傳已達上限。');
    const asset=randomUUID(),intent=randomUUID(),representation=randomUUID();await q.query("INSERT INTO assets(asset_id,scope_id,owner_principal_id,owner_user_id,policy_revision,representation_id,purpose,scope_kind) VALUES($1,$2,$3,$4,$5,$6,'skill.submission-image','personal')",[asset,mapped.scope,mapped.principal,grant.user_id,policy.revision,representation]);
    row=(await q.query("INSERT INTO asset_upload_intents(intent_id,asset_id,representation_id,scope_id,owner_principal_id,target_user_id,policy_revision,prepare_key,request_digest,source_content_type,source_byte_size,source_sha256,expected_version,expires_at,purpose,reserved_bytes,target_kind,target_submission_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'image/webp',$10,$11,$12,clock_timestamp()+interval '1 hour','skill.submission-image',524288,'skill.submission-image',$13) RETURNING *",[intent,asset,representation,mapped.scope,mapped.principal,grant.user_id,policy.revision,key,normalized.payload_sha256,bytes.length,sourceHash,current.aggregate_version,grant.submission_id])).rows[0];
   }
   requireCondition(row.request_digest===normalized.payload_sha256&&row.target_submission_id===grant.submission_id&&row.policy_revision===policy.revision&&row.source_byte_size===bytes.length&&row.source_sha256===sourceHash&&row.expected_version===current.aggregate_version,409,'asset_source_mismatch','上傳內容與準備紀錄不同。');
   const lease=randomUUID();const updated=(await q.query("UPDATE asset_upload_intents SET fence=fence+1,lease_token=$2,lease_expires_at=LEAST(expires_at,clock_timestamp()+interval '5 minutes'),state=CASE WHEN state='stored' THEN 'stored' ELSE 'processing' END WHERE intent_id=$1 AND state<>'finalized' AND expires_at>clock_timestamp() AND (lease_expires_at IS NULL OR lease_expires_at<=clock_timestamp()) RETURNING *",[row.intent_id,lease])).rows[0];requireCondition(updated,409,'asset_lease_active','目前仍有有效上傳租約。');await assertSkillUploadGrantClock(q,grant);
   return {...mapped,row:updated,policy};
  });if(!snapshot)return null;
  const representation=await prepareLegacyMediaRepresentation(new ReadableStream({start(c){c.enqueue(bytes);c.close();}}),'image/webp','skill.submission-image',snapshot.policy),row=snapshot.row,keyObject=objectKey({scopeId:snapshot.scope,assetId:row.asset_id,representationId:row.representation_id});
  try{await writeVerifiedObject(store,keyObject,representation,snapshot.policy);}catch{throw new Problem(503,'media_upload_unavailable','內容上傳暫時無法使用。');}
  await transaction(pool,async q=>{await lockSkillUploadGrant(q,grant);const policy=await resolveSkillImageUploadPolicy(q);await requireSkillImageCapacity(q,grant,snapshot.scope,policy.quota,0);requireCondition(policy.revision===snapshot.policy.revision,409,'asset_policy_changed','內容政策已更新。');const live=await q.query("SELECT 1 FROM asset_upload_intents WHERE intent_id=$1 AND fence=$2 AND lease_token=$3 AND lease_expires_at>clock_timestamp() AND state IN ('processing','stored') FOR UPDATE",[row.intent_id,row.fence,row.lease_token]);requireCondition(live.rowCount===1,409,'asset_lease_stale','上傳租約已失效。');const v=representation.metadata;await q.query("INSERT INTO asset_objects(asset_id,scope_id,representation_id,content_type,byte_size,content_sha256,transform_version,policy_revision,purpose,variant,profile_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'skill.submission-image','illustration','skill.submission-image') ON CONFLICT(asset_id) DO NOTHING",[row.asset_id,snapshot.scope,row.representation_id,v.contentType,v.byteSize,v.sha256,v.transformVersion,v.policyRevision]);await q.query("UPDATE asset_upload_intents SET state='stored' WHERE intent_id=$1",[row.intent_id]);await assertSkillImageLeaseClock(q,row.intent_id);await assertSkillUploadGrantClock(q,grant);});
  const opaque=Object.freeze({});stages.set(opaque,Object.freeze({intent:row.intent_id,asset:row.asset_id,representation:row.representation_id,scope:snapshot.scope,principal:snapshot.principal,fence:row.fence,lease:row.lease_token,version:row.expected_version,policy:snapshot.policy.revision,digest:normalized.payload_sha256,metadata:representation.metadata}));return opaque;
 }
 async function verify(stage:object){const value=stages.get(stage);requireCondition(value,503,'media_upload_unavailable','內容上傳暫時無法使用。');try{await verifyObject(store,objectKey({scopeId:value!.scope,assetId:value!.asset,representationId:value!.representation}),value!.metadata);}catch{throw new Problem(503,'media_upload_unavailable','內容上傳暫時無法使用。');}}
 async function publishOnOriginalTransaction(q:PoolClient,grant:SkillUploadGrant,normalized:NormalizedSubmission,opaque:object){const value=stages.get(opaque);requireCondition(value&&value.digest===normalized.payload_sha256,503,'media_upload_unavailable','內容上傳暫時無法使用。');const v=value!,current=await lockSkillUploadGrant(q,grant),mapped=await mapping(q,grant),policy=await resolveSkillImageUploadPolicy(q);requireCondition(mapped.scope===v.scope&&mapped.principal===v.principal&&policy.revision===v.policy&&current.aggregate_version===v.version,409,'asset_source_mismatch','上傳內容與準備紀錄不同。');await requireSkillImageCapacity(q,grant,mapped.scope,policy.quota,0);const row=(await q.query("SELECT * FROM asset_upload_intents WHERE intent_id=$1 AND fence=$2 AND lease_token=$3 AND target_submission_id=$4 AND request_digest=$5 AND state='stored' AND lease_expires_at>clock_timestamp() FOR UPDATE",[v.intent,v.fence,v.lease,grant.submission_id,v.digest])).rows[0];requireCondition(row,409,'asset_lease_stale','上傳租約已失效。');await assertSkillUploadGrantClock(q,grant);await q.query("UPDATE assets SET state='ready',ready_at=clock_timestamp() WHERE asset_id=$1 AND state='pending'",[v.asset]);await q.query('UPDATE skill_submission_image_asset_targets SET asset_id=$2,linked_at_version=$3 WHERE submission_id=$1 AND scope_id=$4 AND owner_principal_id=$5',[grant.submission_id,v.asset,BigInt(v.version)+1n,v.scope,v.principal]);await assertSkillImageLeaseClock(q,v.intent);await assertSkillUploadGrantClock(q,grant);await q.query("UPDATE asset_upload_intents SET state='finalized',finalized_at=clock_timestamp() WHERE intent_id=$1",[v.intent]);}
 return Object.freeze({stage,verify,publishOnOriginalTransaction});
}
export type SkillImageAssetService=ReturnType<typeof createSkillImageAssetService>;
/** Exact original owner or published-shelf projection, rechecked after object I/O. */
export async function readSkillImage(pool:Pool,id:string,store:ObjectStore|undefined,owner?:Actor):Promise<Buffer|null>{
 const published=`JOIN users u ON u.user_id=s.owner_ref AND u.community_id=s.community_id JOIN oss_projects p ON p.project_id=s.project_id AND p.owner_ref=s.owner_ref AND p.community_id=s.community_id JOIN oss_project_versions v ON v.version_id=s.project_version_id AND v.project_id=s.project_id`;
 const acl=owner?'s.owner_ref=$2 AND s.community_id=$3':"s.status='published' AND s.consent_to_share AND NOT p.official AND u.active AND (NOT u.onboarding_required OR u.onboarding_completed_at IS NOT NULL) AND NOT is_verification_test_account(u.user_id)";
 const snapshot=async(q:Pick<PoolClient,'query'>=pool)=>{const row=(await q.query(`SELECT s.storage_source,s.image_bytes,t.asset_id,t.scope_id,a.representation_id,a.policy_revision,a.state,a.deletion_fence,o.content_type,o.byte_size,o.content_sha256,o.transform_version,o.profile_id FROM skill_submissions s ${owner?'':published} LEFT JOIN skill_submission_image_asset_targets t ON t.submission_id=s.submission_id LEFT JOIN assets a ON a.asset_id=t.asset_id LEFT JOIN asset_objects o ON o.asset_id=t.asset_id WHERE s.submission_id=$1 AND ${acl} AND (s.image_bytes IS NOT NULL OR s.storage_source='asset') AND (s.storage_source='legacy' OR EXISTS(SELECT 1 FROM principals ip JOIN resource_scopes rs ON rs.owner_principal_id=ip.principal_id AND rs.kind='personal' WHERE ip.principal_id=t.owner_principal_id AND ip.user_ref=s.owner_ref AND ip.status='active' AND rs.scope_id=t.scope_id AND rs.status='active'))`,owner?[id,owner.user_id,owner.community_id]:[id])).rows[0];return row;};
 const initial=await snapshot();if(!initial)return null;if(initial.storage_source==='legacy')return initial.image_bytes as Buffer;
 const authorizedSnapshot=()=>owner?withMemberScope(pool,{actor:owner,scope:'personal'},async()=>{},async(q,context)=>{const row=await snapshot(q);if(row)requireCondition(row.scope_id===context.scope.scope_id&&context.subject_principal.principal_id===(await q.query('SELECT owner_principal_id FROM skill_submission_image_asset_targets WHERE submission_id=$1',[id])).rows[0]?.owner_principal_id,404,'illustration_not_found','這份投稿沒有示意圖。');await assertCurrentSessionClock(q,owner);return row;}):snapshot();
 const first=await authorizedSnapshot();if(!first)return null;
 requireCondition(store&&first.asset_id&&first.state==='ready'&&first.deletion_fence==='0'&&first.profile_id==='skill.submission-image',503,'media_upload_unavailable','內容上傳暫時無法使用。');
 const metadata:ObjectMetadata={contentType:first.content_type,byteSize:first.byte_size,sha256:first.content_sha256,transformVersion:first.transform_version,policyRevision:first.policy_revision,profileId:first.profile_id};let bytes:Uint8Array;
 try{bytes=(await readVerifiedObject(store!,objectKey({scopeId:first.scope_id,assetId:first.asset_id,representationId:first.representation_id}),metadata)).bytes;}catch{throw new Problem(503,'media_upload_unavailable','內容上傳暫時無法使用。');}
 const current=await authorizedSnapshot();if(!current)return null;requireCondition(current.storage_source==='asset'&&current.asset_id===first.asset_id&&current.representation_id===first.representation_id&&current.state==='ready'&&current.deletion_fence==='0'&&['scope_id','representation_id','policy_revision','content_type','byte_size','content_sha256','transform_version','profile_id'].every(field=>current[field]===first[field]),503,'media_upload_unavailable','內容上傳暫時無法使用。');return Buffer.from(bytes);
}
